### ISSUE TITLE
Error running nvim using docker container

### ISSUE THREAD

**Issue by ivano9** [ChristianChiarulli/LunarVim#100]
After run the docker container using the image (nvcode.Dockerfile) show this error:

![image](https://user-images.githubusercontent.com/43305758/103805468-664f6c00-5032-11eb-9df2-691b01d27d54.png)

**Comment by ChristianChiarulli** [comment]
I'm gonna assume it's an error with me moving to neovim 0.5. Although there could be other reasons. I haven't used this image in a while. If anyone finds a fix I'm open to a PR.
