### ISSUE TITLE
[Bug]: typescript file format not working with me

### ISSUE THREAD

**Issue by NurdinDev** [ChristianChiarulli/LunarVim#1010]
### Problem description

1- Go to any typescript file
2- Save file using `:w` 
3- You will see an error 
```
Error detected while processing BufWritePost Autocommands for "*":
E5108: Error executing lua /Users/nureddin/.config/nvim/lua/lsp/tsserver-ls.lua:14: attempt to get length of local 'extend_args' (a nil value)
```

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

0.4.8

### Neovim version (>= 0.5)

v0.6.0-dev+e5b75d41d

### Relevant log output

```shell
:LspStart typescript

lspconfig.lua:29: atempt to call field 'autostart' (a nil value)
```
```


### Screenshots

_No response_

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by williamgoulois** [comment]
Do you have a global prettier installation?

**Comment by NurdinDev** [comment]
I tried with and without prettier global installation, and the same.

**Comment by ChristianChiarulli** [comment]
If you're on rolling I should have a fix in, prettier seemed to work out of the box for me but I added a nil check just in case someone set that argument incorrectly.

**Comment by NurdinDev** [comment]
```
O.format_on_save = true
O.lint_on_save = true
O.completion.autocomplete = true
O.colorscheme = "tokyonight"
O.auto_close_tree = 0
O.default_options.wrap = true
O.default_options.timeoutlen = 100
  O.leader_key = " "

O.plugin.dashboard.active = true
O.plugin.terminal.active = true
O.plugin.terminal.direction = "horizontal"
O.plugin.zen.active = false
O.plugin.zen.window.height = 0.90

O.treesitter.ensure_installed = "maintained"
O.treesitter.ignore_install = { "haskell" }
O.treesitter.highlight.enabled = true

-- javascript
O.lang.tsserver.formatter = 'prettier'
O.lang.tsserver.linter = nil
O.lang.tsserver.autoformat = true

-- json
O.lang.json.autoformat = true

-- Additional Plugins
O.user_plugins = {
    {"folke/tokyonight.nvim"}
}

```

**Comment by benediktms** [comment]
Hi there, I have a similar issue. When saving a buffer with `O.format_on_save = true` I get the following error:
```
...ack/packer/start/formatter.nvim/lua/formatter/format.lua:80: attempt to concatenate upvalue 'name' (a nil value)
```
these are my settings in `lv-config` for tsserver:
```
O.lang.tsserver.formatter = 'prettier'
O.lang.tsserver.linter = 'eslint'
O.lang.tsserver.autoformat = true
```

**Comment by williamgoulois** [comment]
@benediktms I don't know your LunarVim version but with latest on rolling you should have
```lua
O.lang.tsserver.formatter.exe = 'prettier' --optional
O.lang.tsserver.linter = 'eslint'
```

Prettier is used by default we do not have others options implemented yet (prettierd will be added in the future)

I have `O.format_on_save` and `O.lint_on_save` to true in lv-config too

**Comment by benediktms** [comment]
@williamgoulois thanks for you response. I am on the latest rolling branch 

`O.lang.tsserver.formatter.exe = 'prettier'` does not work for me. I get the following error: 
```
Error detected while processing BufWritePost Autocommands for "lv-config.lua":
E5108: Error executing lua ...enedikt/.local/share/lunarvim/lvim/lua/lv-utils/init.lua:60: Vim(source):E5113: Error while calling lua chunk: /home/benedikt/.config/lvim/lv-config.lua:79: attempt to index field 'f
ormatter' (a string value)
```

I also tried the following:
```
O.lang.tsserver.formatter = {
  exe = "prettier",
  args = {"--stdin-filepath", vim.api.nvim_buf_get_name(0)},
  stdin = true
}
```
following an example from https://github.com/mhartington/formatter.nvim

This gets rid of the errors but does not format.

**Comment by rebuilt** [comment]
Can you try this

```
O.lang.tsserver.formatter = {
  exe = "prettier",
  args = {"--write"},
  stdin = false
}
```

**Comment by benediktms** [comment]
@rebuilt same result unfortunately :(

**Comment by rebuilt** [comment]
The is not a fix but here's a workaround
```
:!prettier --stdin-filepath %
:e!
```
You can bind these commands to keys.

**Comment by benediktms** [comment]
Seems that prettier is not found in general. I rememer running into this issue before a while back. I used coc-prettier which seemed to have solved the issue but switching to lsp seems to have brought this up again for me. Did you do any additional setup for prettier other than having a config file in the project root?

**Comment by rebuilt** [comment]
A config file should be all you need.  

Make sure you can run it from the command line.  If you can't, reinstall it.  https://prettier.io/docs/en/install.html

**Comment by benediktms** [comment]
Hmm strange, prettier is definitely installed (it works in VSCode) but neovim does not seem to recogize the executable. I tried both using only the local installation and global installation. I appreciate that this is probably not in the scope of this issue anymore, but I don't suppose you have any more suggestions?

**Comment by rebuilt** [comment]
What's the output of `which prettier`

**Comment by benediktms** [comment]
`/home/benedikt/.nvm/versions/node/v12.22.0/bin/prettier`

**Comment by benediktms** [comment]
I tried hardcoding that path into the [tsserver](https://github.com/ChristianChiarulli/LunarVim/blob/rolling/lua/lsp/tsserver-ls.lua#L5) file, but that also didn't work

**Comment by rebuilt** [comment]
It might have to do with nvm. https://github.com/jscheid/prettier.el/issues/70

**Comment by rebuilt** [comment]
Does formatting a file from the command line work?  `prettier --write file.js`  Does that give you any error messages?  Can you check the log files in .cache/nvim for any relevant error messages

**Comment by benediktms** [comment]
Yes running prettier from the command line works. I checked the logs also but there is noting in there that seems to be related to prettier. Basically just these lines:
```
[ START ] 2021-07-23T11:25:09+0100 ] LSP logging initiated                                                                                                                                                                               
[ ERROR ] 2021-07-23T11:25:18+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:402 ] '[tsserver] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPEN      DENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})\n\n'  
```

**Comment by benediktms** [comment]
I tried disabling the `stdin` field from `tsserver` again after having installed prettier which now works, however it only uses the default format settings not the ones defined in my project root.

**Comment by rebuilt** [comment]
> I tried disabling the `stdin` field from `tsserver` again after having installed prettier which now works, however it only uses the default format settings not the ones defined in my project root.

Make sure you don't have another configuration file that is getting sourced earlier.   https://prettier.io/docs/en/configuration.html

**Comment by benediktms** [comment]
Yes don't think there is anything conflicting. And as mentioned it used to work with coc-prettier before I switched. Really at the end of my rope. I will test this again later today in a VM on few different repos to double check

**Comment by ChristianChiarulli** [comment]
the new updates and #1095 should have fixed this

**Comment by benediktms** [comment]
FYI I discovered what the issue was (for me) and it was not a bug with this config at all. Our code base still has a tslint config file that we use for certain things including setting `"arrow-parens": false`. I explicitly added that option to the prettier config file as well which fixed the issue for me. Just mentioning this here so it's searchable in case anyone else comes across this niche case.
