### ISSUE TITLE
[Bug]: Nvimtree not working in dashboard

### ISSUE THREAD

**Issue by williamgoulois** [ChristianChiarulli/LunarVim#1018]
### Problem description

Steps to reproduce :
1- Open nvim with dashboard (on rolling)
2- Try to `<Space>e` to show nvimtree

The room for nvimtree is here and an empty buffer is created but nothing appears

With my testing i found out that reverting e264bfe06d53c8e1efe1ce95ebd86170abc5da24 from @abzcoding resolves the issue.

Looks like we will need to still use an old version of nvimtree and not master.
Are there new modifications in nvimtree repo that makes it not work with dashboard ?

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+14-gdf33f30e8

### Screenshots

This is what you will see after `<Space>e`
<img width="1788" alt="Screenshot_2021-07-19_at_00 51 49" src="https://user-images.githubusercontent.com/37271970/126084906-0a70c980-85ff-4f49-8a9a-c8f26c88893f.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
thank you for mentioning this, pinned the nvim-tree version again

**Comment by abzcoding** [comment]
@williamgoulois  apparently the issue only happens on **mac**, hence the fact nobody else on discord had the issue.
