### ISSUE TITLE
[Bug]: Cannot paste from a register into a telescope prompt as the which-key popup for registers closes telescope

### ISSUE THREAD

**Issue by mksud** [ChristianChiarulli/LunarVim#1022]
### Problem description

I am unable to paste from a register using `<c-r>` into a telescope prompt (filesearch, live grep etc). The which-key popup for registers closes telescope and the register content gets pasted into some open buffer.

For now i can workaround the issue with the following in `lv-config.lua`
`O.plugin.which_key.setup.plugins.registers = false`

I wish there was a better way than disabling the which-key registers feature altogether, it would be nice to disable this only when telescope is open. Please let me know if this issue should be filed against one of the plugins rather than LunarVim

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rafamadriz** [comment]
Yes, you should probably open this issue in those plugins repo, that's just how which-key behaves (both plugins use floating windows feature and I guess that one overwrites the other). Nothing that we can do to fix it.
