### ISSUE TITLE
I messed up while trying to update Lunarvim....please help!!!

### ISSUE THREAD

**Issue by meehirmanitrips** [ChristianChiarulli/LunarVim#1027]
I was trying to update lunarvim and somehow i messed it up and now it is not working at all.
Can someone tell me how do i uninstall lunarvim so that i can do fresh install after that.

**Comment by Tastyep** [comment]
https://github.com/ChristianChiarulli/LunarVim/wiki/Uninstalling-LunarVim

**Comment by meehirmanitrips** [comment]
I have successfully uninstalled lunar vim but on installing it again i am getting the following error:
```
E5113: Error while calling lua chunk: /home/meehir/.config/nvim/lua/settings.lua:25: attempt to index local 'opt' (a nil value)Press ENTER or type command to continue
```
What do i do next?

**Comment by rebuilt** [comment]
Compile and install the newest version of neovim
https://github.com/ChristianChiarulli/LunarVim/wiki/Installation

The latest commit is this one

```
commit bfb04812d520652ef24f95f227b74c6cc349ba38 (HEAD -> master, origin/master, origin/HEAD)
Merge: d9be6ba79 6f9e219f6
Author: James McCoy <jamessan@jamessan.com>
Date:   Sun Jul 18 13:39:20 2021 -0400

    Merge pull request #15073 from dundargoc/PVS/V751
    
    [RDY] chore(PVS/V751): tui.c, Parameter is not used
```

After installing the latest the output of nvim -v should include the sha for the commit

```
bfb04812
```

**Comment by meehirmanitrips** [comment]
Thank you so much its working now.
But there is still one small problem.........whenever i am opening any file it says filetype unknown in the bottom of the screen how do i get rid of that

**Comment by ChristianChiarulli** [comment]
@meehirmanitrips we're working on that bug currently. Still not sure what plugin/autocommand it causing it.

**Comment by abzcoding** [comment]
@meehirmanitrips can you try adding this to your `lv-config.lua` and check if the `filetype unknown` issue is fixed or not?
```lua
O.treesitter.highlight.additional_vim_regex_highlighting = false
```

**Comment by alechp** [comment]
@meehirmanitrips when you were starting up, was this the error you were seeing:

```
E5113: Error while calling lua chunk: /Users/me/.config/nvim/lua/settings.lua:25: attempt to index local 'opt' (a nil value)
```

?

**Comment by abzcoding** [comment]
> @meehirmanitrips when you were starting up, was this the error you were seeing:
> 
> ```
> E5113: Error while calling lua chunk: /Users/me/.config/nvim/lua/settings.lua:25: attempt to index local 'opt' (a nil value)
> ```
> 
> ?

it seems so as mentioned [here](https://github.com/ChristianChiarulli/LunarVim/issues/1027#issuecomment-882578402)

**Comment by alechp** [comment]
Oops, missed that. Thanks @abzcoding 

Ye I've had this same issue on both my laptop and iMac this week. Will try fresh installs for both

**Comment by abzcoding** [comment]
> Oops, missed that. Thanks @abzcoding
> 
> Ye I've had this same issue on both my laptop and iMac this week. Will try fresh installs for both

try [this](https://github.com/ChristianChiarulli/LunarVim/issues/1027#issuecomment-882593902)

**Comment by alechp** [comment]
Works! Thanks @abzcoding 

Had to wipe plugins and logs (https://github.com/ChristianChiarulli/LunarVim/wiki/Uninstalling-LunarVim), but all good now

---
### Context for others having install issues:

I was having a massive hang during install process

![Screen Shot 2021-07-19 at 5 55 16 PM](https://user-images.githubusercontent.com/3058939/126246167-a494b7c0-9462-4eff-8b11-69d23911a417.png)

Stopped process after 3 minutes. 

And this is what I saw after trying to use the partial-install or manually reverting (by using previous nvim config directory ie. `mv nvim-old nvim`):

![Screen Shot 2021-07-19 at 5 55 54 PM](https://user-images.githubusercontent.com/3058939/126246276-5dd9ce15-c9fb-42a7-98b6-c3783174383b.png)

**Comment by ChristianChiarulli** [comment]
luckily the new installer doesn't share the plugins directory with nvim anymore, and when you blow it away it cleans the plugins up as well.

**Comment by meehirmanitrips** [comment]
> @meehirmanitrips can you try adding this to your `lv-config.lua` and check if the `filetype unknown` issue is fixed or not?
> 
> ```lua
> O.treesitter.highlight.additional_vim_regex_highlighting = false
> ```

Yeah that problem has been solved now but unfortunately there is another problem........whenever i am trying to save the file it gives me the following error:

```
Error detected while processing BufWritePost Autocommands for "*":
E5108: Error executing lua /home/meehir/.config/nvim/ftplugin/c.lua:4: attempt to index field 'c' (a nil value)
```
How do i fix this........also there are two more things that i want to point out.

First is that whenever i try to see the hidden files on nvimtree by pressing i buttor or shift+i it gives me the following error:

```
E21: Cannot make changes, 'modifiable' is off
```
Second problem is that i cannot switch between the tabs.
The tab and shift+tab buttons do not work like they used to in the previous versions.
How do i get them to work?
Also thanks in advance :)

**Comment by abzcoding** [comment]
@meehirmanitrips 
- for switching between tabs use `shift+h` and `shift+l`
- also for `nvim-tree`
> H will toggle visibility of dotfiles (files/folders starting with a .)

for the first error , can you put your `~/.config/nvim/ftplugin/c.lua` file here

**Comment by meehirmanitrips** [comment]
This is my c.lua file:
```
O.formatters.filetype["c"] = {
  function()
    return {
      exe = O.lang.c.formatter.exe,
      args = O.lang.c.formatter.args,
      stdin = not (O.lang.c.formatter.stdin ~= nil),
    }
  end,
}
O.formatters.filetype["cpp"] = O.formatters.filetype["c"]

require("formatter.config").set_defaults {
  logging = false,
  filetype = O.formatters.filetype,
}

if require("lv-utils").check_lsp_client_active "clangd" then
  return
end

local clangd_flags = { "--background-index" }

if O.lang.clang.cross_file_rename then
  table.insert(clangd_flags, "--cross-file-rename")
end

table.insert(clangd_flags, "--header-insertion=" .. O.lang.clang.header_insertion)

require("lspconfig").clangd.setup {
  cmd = { DATA_PATH .. "/lspinstall/cpp/clangd/bin/clangd", unpack(clangd_flags) },
  on_attach = require("lsp").common_on_attach,
  handlers = {
    ["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
      virtual_text = O.lang.clang.diagnostics.virtual_text,
      signs = O.lang.clang.diagnostics.signs,
      underline = O.lang.clang.diagnostics.underline,
      update_in_insert = true,
    }),
  },
}
```
Also this problem seems to only be in c/c++ file types as the java file types are not having any such problems.

**Comment by phuongbk90** [comment]
> This is my c.lua file:
> 
> ```
> O.formatters.filetype["c"] = {
>   function()
>     return {
>       exe = O.lang.c.formatter.exe,
>       args = O.lang.c.formatter.args,
>       stdin = not (O.lang.c.formatter.stdin ~= nil),
>     }
>   end,
> }
> O.formatters.filetype["cpp"] = O.formatters.filetype["c"]
> 
> require("formatter.config").set_defaults {
>   logging = false,
>   filetype = O.formatters.filetype,
> }
> 
> if require("lv-utils").check_lsp_client_active "clangd" then
>   return
> end
> 
> local clangd_flags = { "--background-index" }
> 
> if O.lang.clang.cross_file_rename then
>   table.insert(clangd_flags, "--cross-file-rename")
> end
> 
> table.insert(clangd_flags, "--header-insertion=" .. O.lang.clang.header_insertion)
> 
> require("lspconfig").clangd.setup {
>   cmd = { DATA_PATH .. "/lspinstall/cpp/clangd/bin/clangd", unpack(clangd_flags) },
>   on_attach = require("lsp").common_on_attach,
>   handlers = {
>     ["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
>       virtual_text = O.lang.clang.diagnostics.virtual_text,
>       signs = O.lang.clang.diagnostics.signs,
>       underline = O.lang.clang.diagnostics.underline,
>       update_in_insert = true,
>     }),
>   },
> }
> ```
> 
> Also this problem seems to only be in c/c++ file types as the java file types are not having any such problems.

I have same issue when creating new file in nvim-tree and cannot save file.
![image](https://user-images.githubusercontent.com/8886054/126362715-58d58fc2-d0f2-4b64-93b0-1683994abf60.png)

**Comment by abzcoding** [comment]
this has turned into a forum discussion 😅 , feel free to file new issues if you have them after updating to the latest rolling branch
