### ISSUE TITLE
[Feature]: Solarized colors

### ISSUE THREAD

**Issue by Folaht** [ChristianChiarulli/LunarVim#1028]
### Feature motivation

I am always frustrated when I can's choose solarized-dark.

I made an attempt, but I can't figure out why the colors seems to be washed out.
And why some text types remain bold or standard despite changing it in the palette.

### Describe the expected solution

Expected solution:
![image](https://user-images.githubusercontent.com/9342090/126175942-f83f06db-f88a-42af-9d28-8d1af92961d3.png)

My attempt so far:
![image](https://user-images.githubusercontent.com/9342090/126175995-1c08dab7-7a8d-4c36-9e17-9ec5c5c93112.png)

### Describe the alternatives you've considered

None. I want solarized not spacegray.

**Comment by Uzaaft** [comment]
@Folaht Could you try another terminal? From experience I know that Alacritty does not render colors like other terminals. 
This is the standard LunarVim theme with konsole at the right and Alacritty at the left. 
![image](https://user-images.githubusercontent.com/48220549/126181417-262eed5f-7148-4ddf-a32a-3ae3fbbaacbb.png)

**Comment by Folaht** [comment]
It seems like Alacritty is responsible for the wash and removing italics.

![image](https://user-images.githubusercontent.com/9342090/126306455-1dab265a-5fe3-48ce-9a6d-22f691c363fa.png)

Thanks!
Looks like I still have some more color changing to do, but at least I can see what it's supposed to look like now.

**Comment by Uzaaft** [comment]
Nice! Seems like you can go ahead and close the issue: :)

**Comment by Folaht** [comment]
I'll reopen it once I've fixed the Alacritty issues and then come back for

- Satement, the bold text
- SignColumn, background color being overwritten by Normal
- ?info? row, same

**Comment by Uzaaft** [comment]
Just a heads up, if you are going to design the theme with the intention to merge it into LunarVim, I would advice you to use another terminal than alacritty while designing and coding it.

**Comment by Folaht** [comment]
How does one start lunarvim again without lsp?

**Comment by rebuilt** [comment]
> How does one inactivate lsp again without deinstalling it?

:LspStop  

https://github.com/ChristianChiarulli/LunarVim/wiki/Useful-command-for-troubleshooting
