### ISSUE TITLE
keymapping for terminal navigation in insert mode messed up

### ISSUE THREAD

**Issue by Soziopath** [ChristianChiarulli/LunarVim#1029]
### Problem description
keymapping for terminal navigation in insert mode/terminal mode is messed up.
just found out it was still working in commit a3f3f3b6.

Steps to reproduce:
1) open term `:new term://bash`
2) stay in insert mode in term window
3) previous working keymapping c-j, c-k, c-h, c-l are not switching from term window to other windows anymore

### LunarVim version

latest rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+c31bc6e

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
is there a reason to not use the terminal provided by LV? just asking :sweat_smile: 

by adding this to your `lv-config.lua` and using `<c-t>` to toggle it:
```lua
O.plugin.terminal.active = true
-- O.plugin.terminal.direction = "horizontal" -- to change from float to horizontal
-- O.plugin.terminal.size = 20 -- to change its size
```

**Comment by Soziopath** [comment]
im using rhysd/reply.vim to get a repl with keymappings to send my selection to the repl.
so the terminal provided by lv does not do the job :D

**Comment by Soziopath** [comment]
switching windows with `<c-j>,<c-k>,<c-h>,<c-l>` doesnt work with the lv terminal either.
just tested

**Comment by abzcoding** [comment]
> switching windows with `<c-j>,<c-k>,<c-h>,<c-l>` doesnt work with the lv terminal either.
> just tested

gonna fix it asap, thank you for bringing this to our attention

**Comment by abzcoding** [comment]
@Soziopath can you test using `<c-J>` `<c-K>` (basically ctrl+shift+k)
just want to make sure that I've found the issue

**Comment by Soziopath** [comment]
> 
> 
> @Soziopath can you test using `<c-J>` `<c-K>` (basically ctrl+shift+k)
> just want to make sure that I've found the issue

`<c-J>` and `<c-K>` are not working either
