### ISSUE TITLE
[Bug]: Unable to type capital K and J in the floating terminal

### ISSUE THREAD

**Issue by gikari** [ChristianChiarulli/LunarVim#1034]
### Problem description

Steps to reproduce:

0. Enable floating terminal
1. Open terminal with `<C-t>`
2. Try to type capital J or K

### LunarVim version

roliing

### Neovim version (>= 0.5)

NVIM v0.5.0

### Screenshots

This is printed instead:
![Screenshot_20210719_202950](https://user-images.githubusercontent.com/14205339/126201843-374a9a54-c9bc-43d8-86b2-78224361db8a.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
gotcha seems to be a keymap we have defined. Should be an easy fix.

**Comment by abzcoding** [comment]
@gikari can you pull the latest changes, I think this issue should be fixed now

**Comment by ChristianChiarulli** [comment]
It's fixed on rolling, thanks @abzcoding

**Comment by gikari** [comment]
Indeed, it was fixed. Thank you.
