### ISSUE TITLE
[Bug]: Error: attempt to concatenate nil value

### ISSUE THREAD

**Issue by kbrah** [ChristianChiarulli/LunarVim#1040]
### Problem description

After updating to the latest rolling branch commit I'm now getting an error 
`E5113: Error while calling lua chunk: C:\Users\dev\AppData\Local\nvim\lua\default-config.lua:1: attempt to concatenate a nil value`

The previous working version I had was also pretty recent (got it yesterday)

Any ideas how to fix? 
Tried to uninstall and install again. Also got the latest neovim version

### LunarVim version

latest rolling commit

### Neovim version (>= 0.5)

 NVIM v0.6.0-dev+59-g2475161de

### Relevant log output

```shell
E5113: Error while calling lua chunk: C:\Users\dev\AppData\Local\nvim\lua\default-config.lua:1: attempt to concatenate a nil
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kbrah** [comment]
It appears that the decoupling commit broke it. I assume that making that on Windows might take some tinkering so feel free to close this if you think this is not useful.

**Comment by rebuilt** [comment]
How are you launching it?  Are you using the 'nvim' command or 'lvim'?  Also, the lv-config.lua file now resides in ~/.config/lvim

**Comment by rebuilt** [comment]
This is what the lvim command is doing:

```
#!/bin/sh

nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim" "$@"

```

**Comment by rebuilt** [comment]
Updated the README. https://github.com/ChristianChiarulli/LunarVim#breaking-change-on-the-rolling-branch

**Comment by Uzaaft** [comment]
@rebuilt  Out of curiosity, what is the reasoning behind this change?

**Comment by rebuilt** [comment]
In the future, the goal is to be able to run 'apt install lunarvim', etc for the distro of your choice.  We need to decouple LunarVim from the nvim folder to achieve that.  Users can continue to run and use a neovim configuration if they wish and also easily install and use LunarVim.  

This change also separates out the user configuration files into their own folder.  This makes it easier to manage your configuration files.  I'm looking forward to throwing my configs into a git repo and pulling them down on all my machines.

**Comment by epileftro85** [comment]
I am still getting this error, even after running the command of the README

**Comment by rebuilt** [comment]
@epileftro85 Can you tell me how you installed and which steps you've tried?

Did you install by using the one-line-install command or by git pulling the latest updates?  

Did you install the master or rolling branch?  

If rolling, do the directories described here exist?
https://github.com/ChristianChiarulli/LunarVim#breaking-change-on-the-rolling-branch

What's the output of `which lvim`

**Comment by epileftro85** [comment]
Hi, i did install it both form

**Comment by epileftro85** [comment]
Hi, thanks for the reply
**_I've installed it one-line-install, manually, master and rolling_**

Output:
`/usr/local/bin/lvim`

Into debug mode I can see this

`E5113: Error while calling lua chunk: /home/andres/.config/nvim/init.lua:13: module 'default-config' not `found:``

I've already did this
https://github.com/ChristianChiarulli/LunarVim#breaking-change-on-the-rolling-branch

**Comment by Uzaaft** [comment]
Did you delete the files like it is written in the uninstall section of the wiki

**Comment by rebuilt** [comment]
Yeah, you'll need to uninstall what's in the nvim folder.  Those files take priority; they get sourced first

The error message shows it's trying to load this file.
`/home/andres/.config/nvim/init.lua`

The new location is 
`~/.local/share/lunarvim/lvim/init.lua`

**Comment by epileftro85** [comment]
@Uzaaft And @rebuilt i have:

1. uninstall lunarvim
2. move my nvim config folder to another place
3. rm nvim cache
4. re installing lunarvim with the one-line-install command 

I still seeing this

```
LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/rolling/utils/installer/install.sh)                                                        andres@andres-clavijo
Installing LunarVim
pip installed, moving on...
node installed, moving on...
pynvim installed, moving on...
Cloning into '/home/andres/.local/share/lunarvim/site/pack/packer/start/packer.nvim'...
remote: Enumerating objects: 2392, done.
remote: Counting objects: 100% (695/695), done.
remote: Compressing objects: 100% (205/205), done.
remote: Total 2392 (delta 545), reused 599 (delta 485), pack-reused 1697
Receiving objects: 100% (2392/2392), 750.89 KiB | 1.32 MiB/s, done.
Resolving deltas: 100% (1345/1345), done.
Cloning LunarVim configuration
Cloning into '/home/andres/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 8120, done.
remote: Counting objects: 100% (204/204), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 8120 (delta 115), reused 154 (delta 93), pack-reused 7916
Receiving objects: 100% (8120/8120), 10.41 MiB | 1.43 MiB/s, done.
Resolving deltas: 100% (4813/4813), done.
E5113: Error while calling lua chunk: /home/andres/.local/share/lunarvim/lvim/lua/settings.lua:29: attempt to index local 'opt' (a nil value)Press ENTER or type command to continue
```
Ubuntu 20.04

**Comment by Uzaaft** [comment]
@epileftro85  If you try and enter lvim, do you get a description of what section of the settings.lua file that causes the issue?

**Comment by epileftro85** [comment]
I see this error again and just nvim is starting

`E5113: Error while calling lua chunk: /home/andres/.local/share/lunarvim/lvim/lua/settings.lua:29: attempt to index local 'opt' (a nil value)Press ENTER or type command to continue`

**Comment by rebuilt** [comment]
Compile and install the newest version of neovim
https://github.com/ChristianChiarulli/LunarVim/wiki/Installation

The latest commit is this one

```
commit 2475161defb775b0104dbe8b504a5299044584a2 (HEAD -> master, origin/master, origin/HEAD)
Merge: 9358aa04c 823412eda
Author: Thomas Vigouroux <tomvig38@gmail.com>
Date:   Mon Jul 19 23:35:35 2021 +0200

    Merge pull request #15135 from neovim/marvim/api-doc-update/master
    
    docs: regenerate
```

After installing the latest the output of nvim -v should include the sha for the commit

```
2475161defb
```

**Comment by rebuilt** [comment]
https://github.com/ChristianChiarulli/LunarVim/issues/1027

**Comment by Uzaaft** [comment]
Ah, sorry, it is there in the post you provided. 
Seems likt it perhaps might be the:
```
opt.shortmess:append "c"
```
line. Not sure why. @rebuilt  I think we need a lua pro on this. xD

**Comment by epileftro85** [comment]
Installing nvim....

**Comment by epileftro85** [comment]
Done, maybe the `NVIM v0.5.0-dev+1357-g192f89ea1` has some bug or something, thank you for the responses, I will give it a try.

**Comment by Uzaaft** [comment]
You can go ahead and close the issue @epileftro85

**Comment by epileftro85** [comment]
@Uzaaft is not my thread, I was just participating, this belongs to @kbrah

**Comment by rebuilt** [comment]
Issue resolved

**Comment by Uzaaft** [comment]
> @Uzaaft is not my thread, I was just participating, this belongs to @kbrah

Ah my bad. Sorry about that
