### ISSUE TITLE
[Bug]: Cannot add keybindings in lv-config.lua

### ISSUE THREAD

**Issue by jambo6** [ChristianChiarulli/LunarVim#1047]
### Problem description

Install lunar vim and add a keybinding such as 
```
O.keys.normal_mode = {
    -- Page down/up
  {'[d', '<PageUp>'},
  {']d', '<PageDown>'},

  -- Navigate buffers
  {'<Tab>', ':bnext<CR>'},
  {'<S-Tab>', ':bprevious<CR>'},
}
```
as taken of the github readme

returns 
```
something is wrong with your lv-config
```

Keybindings do not work, remove the keybindings and there is no error. 

### LunarVim version

0.4.8

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ichigo-gyuunyuu** [comment]
Unable to reproduce on `rolling`, able to on `master`. The feature hasn't been added to `master` yet probably.

**Comment by jambo6** [comment]
Ah thanks, this works fine on rolling. I've now switched.
