### ISSUE TITLE
[Bug]: X close the buffer and not the character before

### ISSUE THREAD

**Issue by VDuchauffour** [ChristianChiarulli/LunarVim#1053]
### Problem description

It seems that X command close the current buffer. I set this keymap in `lv-config.lua` and sometime it does well, sometime it close the buffer.
`vim.api.nvim_set_keymap("n", "X", '"_X', { noremap = true })`
Same with
`vim.cmd [[nnoremap X "_X]]`
But `:nnoremap X "_X` works perfectly
Any ideas ? Thx

### LunarVim version

0.4.8

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
that keybinding is use inside LunarVim, that might cause the problem
``lua
vim.api.nvim_set_keymap("n", "<S-x>", ":BufferClose<CR>", { noremap = true, silent = true })
```

**Comment by VDuchauffour** [comment]
@abzcoding yes it seems work now. This keybinding aren't repetitive with leader+c ? Knowing that action is already indicated with the which-key plugin ?

**Comment by abzcoding** [comment]
@ChristianChiarulli  do we need both of them? (inside `lua/core/bufferline.lua`)
```lua
vim.api.nvim_set_keymap("n", "<S-x>", ":BufferClose<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>c", ":BufferClose<CR>", { noremap = true, silent = true })
```

**Comment by ChristianChiarulli** [comment]
I didn't even know s-x was a thing, which do you guys prefer?

**Comment by VDuchauffour** [comment]
@ChristianChiarulli I prefer <leader>c. <S-x> should remains in its standard vim behavior IMO

**Comment by kylo252** [comment]
> I didn't even know s-x was a thing, which do you guys prefer?

I think binding `<S-q>` to close buffer is a better choice. Plus, barely anyone uses or know about that mode 😄

**Comment by MichaelSasser** [comment]
> I didn't even know s-x was a thing, which do you guys prefer?

`<S-x>` shouldn't be remapped by lv.
