### ISSUE TITLE
[Bug]: vscode-which key setting interfere the `f` and `t`

### ISSUE THREAD

**Issue by albert-ying** [ChristianChiarulli/LunarVim#1055]
### Problem description

I mapped the vscode-which-key to `,` similar to your LunarVim/utils/lv-vscode/init.vim 

```
nnoremap <silent> , :call VSCodeNotify('whichkey.show')<CR>
xnoremap <silent> , :<C-u>call <SID>openWhichKeyInVisualMode()<CR>
```

The `<verb>t,` and `<verb>f,` works as usual (e.g., `dt,` and `df,`). However, the `f,` and `t,` do not work -- instead of move to the next `,` character, it opens whichkey menu immediately. I'm wondering how can I preserve the function of `f,` and `t,` while `,` is bound to whichkey in vscode?

Thank you!

### LunarVim version

current

### Neovim version (>= 0.5)

0.6

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by williamgoulois** [comment]
I don't know where did you see that we use `,` we actually use `<Space>` as leader :

https://github.com/ChristianChiarulli/LunarVim/blob/3ffee159af6bc619db7a3d14846d40a5ced6884c/utils/lv-vscode/init.vim#L72-L73

**Comment by williamgoulois** [comment]
I just tried to do `f<Space>`, `t<Space>` and it does work inside of VSCode. <Space> alone still triggers whichkey.

**Comment by williamgoulois** [comment]
Demo with KeyCastr and the same keybinding you did :
https://user-images.githubusercontent.com/37271970/126552824-99b2791f-49a7-4ac6-a8d8-e44627ab37de.mov

**Comment by albert-ying** [comment]
Thank you so much! So I checked again my config files, and noticed that somehow I have this in my keybinding during the whole time...

```
[
  {
    "key": ",",
    "command": "whichkey.show",
    "when": "editorTextFocus && neovim.mode == normal"
  }
]
```
Everything works fine after removing it.
