### ISSUE TITLE
[Bug]: Cant remap 'K'. 

### ISSUE THREAD

**Issue by jambo6** [ChristianChiarulli/LunarVim#1060]
### Problem description

I want to perform the following remapping
```
O.keys.normal_mode = {
    {"K", "5k"},
    {"J", "5j"},
}
```
however the `K` mapping does not work (`J` is fine). Other keymaps seem to work fine too. 

Also remapping K in insert mode works fine, just not normal mode.

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
To see what has been bound and where `:vebose nmap K`

imap for insert mode
vmap for selection

**Comment by jambo6** [comment]
Ok thank you, any idea what I do when it says
```
n    K     * :lua vim.lsp.buf.hover()<CR>
      Last set from anonymous :source
```
?

**Comment by rebuilt** [comment]
Great.  We've made progress.  Now if you search for that text by pressing Space+s+t.  You'll see the keybind is being set in `lua/lsp/init.lua`.   If you look at that file you'll also notice the whole block of keybinds is wrapped in `if O.lsp.default_keybinds`.  
So, you can either disable the default keybinds for lsp with
```
O.lsp.default_keybinds = false
```

And then define those lsp keybinds yourself

Or you can pick a different key that makes sense to you that doesn't overlap with the defaults

**Comment by rebuilt** [comment]
If it helps, these are my keybinds
```
O.lsp.default_keybinds = nil

vim.cmd("nnoremap <silent> gd <cmd>lua vim.lsp.buf.definition()<CR>")
vim.cmd("nnoremap <silent> gD <cmd>lua vim.lsp.buf.declaration()<CR>")
vim.cmd("nnoremap <silent> gr <cmd>lua vim.lsp.buf.references()<CR>")
vim.cmd("nnoremap <silent> gi <cmd>lua vim.lsp.buf.implementation()<CR>")
vim.api.nvim_set_keymap(
	"n",
	"gl",
	'<cmd>lua vim.lsp.diagnostic.show_line_diagnostics({ show_header = false, border = "single" })<CR>',
	{ noremap = true, silent = true }
)

vim.cmd("nnoremap <silent> gx <cmd>lua require'lsp'.PeekDefinition()<CR>")
vim.cmd("map <silent> gy :lua vim.lsp.buf.hover()<CR>")
vim.cmd("nnoremap <silent> [d :lua vim.lsp.diagnostic.goto_prev({popup_opts = {border = O.lsp.popup_border}})<CR>")
vim.cmd("nnoremap <silent> ]d :lua vim.lsp.diagnostic.goto_next({popup_opts = {border = O.lsp.popup_border}})<CR>")
-- scroll down hover doc or scroll in definition preview
-- scroll up hover doc
vim.cmd('command! -nargs=0 LspVirtualTextToggle lua require("lsp/virtual_text").toggle()')


```

**Comment by backtolife2021** [comment]
Cant remap 'L'

![image](https://user-images.githubusercontent.com/24669431/127113422-ab4bc87d-ed6f-48da-aa01-ee02085b202e.png)

**Comment by jambo6** [comment]
Thank you!!!!!!

**Comment by jambo6** [comment]
> Cant remap 'L'
> 
> ![image](https://user-images.githubusercontent.com/24669431/127113422-ab4bc87d-ed6f-48da-aa01-ee02085b202e.png)
> ![image](https://user-images.githubusercontent.com/24669431/127113594-d483a048-e7bc-4101-9b95-81061f69d007.png)

What colorscheme is that you have in the bufferline.lua file?

**Comment by backtolife2021** [comment]
> > Cant remap 'L'
> > ![image](https://user-images.githubusercontent.com/24669431/127113422-ab4bc87d-ed6f-48da-aa01-ee02085b202e.png)
> > ![image](https://user-images.githubusercontent.com/24669431/127113594-d483a048-e7bc-4101-9b95-81061f69d007.png)
> 
> What colorscheme is that you have in the bufferline.lua file?

(dracula.nvim)[https://github.com/Mofiqul/dracula.nvim]
