### ISSUE TITLE
[Feature]: Configurable override for root of the project

### ISSUE THREAD

**Issue by nathanielks** [ChristianChiarulli/LunarVim#1071]
### Feature motivation

Currently, the file explorer in the sidebar and the file fuzzy search defaults to setting the root as something near `.git`, as best I can tell. I often will `cd` into subdirectories to work on subpackages, but this isn't supported currently as lvim will try to find a directory up the chain containing a `.git` directory.

### Describe the expected solution

I'd like to either be able to change what files denote the root of a project, or be able to disable this behavior and use whatever directory I am in currently.

**Comment by rafamadriz** [comment]
LunarVim uses vim-rooter to trigger the root directory, you should look into this https://github.com/airblade/vim-rooter#configuration to configure it to your liking. vim-rooter uses global variables for configuration, placing `vim.g.rooter/patterns = <your-config>` anywhere in your config should do.

**Comment by nathanielks** [comment]
Oh, thank you so much 🙏
