### ISSUE TITLE
[Bug]: Telescope changes directory

### ISSUE THREAD

**Issue by eulertour** [ChristianChiarulli/LunarVim#1075]
### Problem description

1. Change directory
2. Open and close file search

Expected: Telescope searches under the current directory and the current directory is unchanged
Actual: Telescope searches under the directory from which lunarvim was started and the current directory is changed to the one from which lunarvim was started

### LunarVim version

0884dcd84670bc097c34253e983d2cde9c209dfa

### Neovim version (>= 0.5)

v0.6.0

### Screenshots

https://user-images.githubusercontent.com/43117506/126859396-4a87bafd-03d6-4c33-9ad6-e7f11fddf504.mp4

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
could be vim-rooter causing this

**Comment by eulertour** [comment]
I found I can stop it with `:RooterToggle`.
