### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jovanmaks** [ChristianChiarulli/LunarVim#1076]
### Problem description

When I work on python (or any else language) code everything works normally but when i try to save cpp file (I have installed LspInstall cpp) it seas:
Error detected while processing BufWritePost Autocommands for "*":
E5108: Error executing lua /home/demijan/.config/nvim/ftplugin/cpp.lua:4: attempt to index field 'c' (a nil value)

P.S. It saves on :wq! but wont on :w

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

0.4.8

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+64-g754ac5a83

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Can you try turning off autoformatting for cpp please.

**Comment by jovanmaks** [comment]
Works, thanks.
