### ISSUE TITLE
[Bug]: `vim.opt.cmdheight` not being respected on save

### ISSUE THREAD

**Issue by nwaywood** [ChristianChiarulli/LunarVim#1085]
### Problem description

To reproduce:
1. set cmdheight to anything that isn't 2 (e.g. `vim.opt.cmdheight = 1`)
2. reopen lvim (observe that the value you set is correct)
3. Save file (observe that the cmdheight changes back to 2 after saving)

### LunarVim version

Latest rolling commit `ceb018d45d0194bb0f8954aecffea4ac1549d906`

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+682247b52

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ichigo-gyuunyuu** [comment]
Similar bugs for various other options, like `vim.opt.wrap`. Seems like something is up with the order of resourcing `lv-config.lua` and other files
