### ISSUE TITLE
[Bug]: Formatting asks to use null-ls or tsserver everytime

### ISSUE THREAD

**Issue by Jacob87** [ChristianChiarulli/LunarVim#1087]
### Problem description

When I format on Javascript or Typescript files, I receive this following prompt every time :

![image](https://user-images.githubusercontent.com/86928797/126890436-e69b8c85-1c97-4019-a186-8c92f24aab9a.png)

I think this is because `tsserver_on_attach` from `lua/lsp/init.lua` is no longer attached anywhere.

This line: `client.resolved_capabilities.document_formatting = false` inside of this `tsserver_on_attach` should disable the (2) option.

It would be really good that if null-ls registers any formatter, then, and only then, we turn off the one from tsserver's lsp

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
#1095
