### ISSUE TITLE
[Bug]: Updates to setting in lv-config.lua are ignored

### ISSUE THREAD

**Issue by eulertour** [ChristianChiarulli/LunarVim#1088]
### Problem description

settings.lua is executed before lv-config.lua, so the options related to settings.lua such as lvim.line_wrap_cursor_movement have no effect.

https://github.com/ChristianChiarulli/LunarVim/blob/rolling/init.lua#L15-L16

### LunarVim version

98f8a77

### Neovim version (>= 0.5)

0.6.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ichigo-gyuunyuu** [comment]
Looks like a case of cyclic dependence 🥲

`settings.lua` needs to know certain options like the one this issue has raised. On the other hand, in order to be able to override vim defaults ( like through `vim.opt` ), `lv-config` needs to be required after `settings.lua`

**Comment by rebuilt** [comment]
Seems like the settings file needs to be split up.

**Comment by abzcoding** [comment]
should be fixed via #1097
