### ISSUE TITLE
how do you close terminal buffer...

### ISSUE THREAD

**Issue by Dulanjala007** [ChristianChiarulli/LunarVim#1099]
### Problem description

open terminal with :term
then close the buffer with shift+x

Error detected while processing function bufferline#bbye#delete:
E89: term:///mnt/wsl/react-hooks//9934:/bin/zsh will be killed (add ! to override)

doesn't close the buffer...
with :BufferClose! it closes...

is this a bug with buffer close or there're any other key mapping for it ?

### LunarVim version

latest master

### Neovim version (>= 0.5)

nvim 0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
That keybind was removed.  `<Space>c` should close the buffer.  You're also free to add the x binding back on your own.   

```
vim.api.nvim_set_keymap("n", "<S-x>", "<cmd>BufferClose!<CR>", { noremap = true, silent = true })

```

**Comment by rebuilt** [comment]
You can also define mappings like so
```
lvim.keys.normal_mode = {
--   Page down/up
   {'[d', '<PageUp>'},
   {']d', '<PageDown>'},

--   Navigate buffers
   {'<Tab>', ':bnext<CR>'},
   {'<S-Tab>', ':bprevious<CR>'},
}
```

**Comment by Dulanjala007** [comment]
ok.. thanks!
