### ISSUE TITLE
[Bug]: TAB doesn't work - Doesn't change buffers

### ISSUE THREAD

**Issue by w-r-z-k** [ChristianChiarulli/LunarVim#1102]
### Problem description

1. Run lvim 
2. Load two buffers
3. Hit TAB to switch between buffers (nothing happens except a message says `No signature help available`)
5. Type :bnext (works as expected)

I am looking into `~/.local/share/lunarvim/lvim/lua/keymappings.lua` to understand what keys are assigned to what functions.  And very few of these keys work.  I got used to the mapping of :bnext to TAB in previous versions of the config files from chris@machine.  But it doesn't seem to work.  

I see this code in the file:

```
  normal_mode = {
    -- Tab switch buffer
    -- { "<TAB>", ":bnext<CR>" },
    -- { "<S-TAB>", ":bprevious<CR>" },
  }
```

So I would expect it to work.  However, I also see this code:

```
if vim.fn.has "mac" == 1 then
  -- TODO: fix this
  default_keys.normal_mode[5][1] = "<A-Up>"
  default_keys.normal_mode[6][1] = "<A-Down>"
  default_keys.normal_mode[7][1] = "<A-Left>"
  default_keys.normal_mode[8][1] = "<A-Right>"
end
```

and the **TODO** tells me that perhaps none of these keys work for macos.  And certainly these option-arrow keys don't work.  I don't know how to interpret the `default_keys.normal_mode[][]` array since I don't know the guts of the lua configuration mechanism.

### LunarVim version

rolling version from 24JUL2021 (where do I find the lvim version?)

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+1476-g62d67de59

### Relevant log output

```shell
NVIM v0.6.0-dev+1476-g62d67de59
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-6177-3ju0xg/build/config -I/tmp/neovim-20210702-6177-3ju0xg/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-6177-3ju0xg/build/src/nvim/auto -I/tmp/neovim-20210702-6177-3ju0xg/build/include
Compiled by user@Users-iMac.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-62d67de/share/nvim"

Run :checkhealth for more info
```

### Screenshots

<img width="1468" alt="Screen Shot 2021-07-24 at 2 34 00 PM" src="https://user-images.githubusercontent.com/3805659/126917536-0fb2932a-9298-474a-a2ca-a04525f558b1.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
We really have to unmap tab. 
It's being set already as an lsp keybind 
```lvim.lsp.default_keybinds = nil```   And then you'll need to remap keybinds for lsp

**Comment by abzcoding** [comment]
@w-r-z-k this means they are commented, and shouldn't work
```lua
 normal_mode = {
    -- Tab switch buffer
    -- { "<TAB>", ":bnext<CR>" },
    -- { "<S-TAB>", ":bprevious<CR>" },
  }
```
use `shift-h` and `shift-l` to navigate between buffers

**Comment by w-r-z-k** [comment]
Uh! I didn't notice the -- marks.  I guess I could get used to shift H and L. Thanks.
