### ISSUE TITLE
[Bug]: If I don't have my formatter/linter in local, null-ls won't take the global one

### ISSUE THREAD

**Issue by Jacob87** [ChristianChiarulli/LunarVim#1103]
### Problem description

When I'm using typescript for example, null-ls won't take my linter (eslint) from global. It needs to have it in local (inside the project to work)

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### Screenshots

![image](https://user-images.githubusercontent.com/86928797/126917837-2681000d-15ec-4548-b7d6-f10c56c6470b.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
this seems to work fine for me on the latest rolling

**Comment by Jacob87** [comment]
@ChristianChiarulli  I pulled the latest rolling, and still have the same error. Did you remove your local eslint? `npm remove eslint` and make sure to use the global one from your computer with `npm i --global eslint` ? idk why I have this problem

**Comment by ChristianChiarulli** [comment]
really weird, I will try to prove it on stream tomorrow either way and we'll see.
