### ISSUE TITLE
[Bug]: Commenting is wrong for `.toml` files

### ISSUE THREAD

**Issue by nwaywood** [ChristianChiarulli/LunarVim#1106]
### Problem description

When commenting out (either via `gc` operators or via `<leader>/`) `.toml` files it comments out like this

`/* truncation_length = 10 */`

however the correct way to comment out in `.toml` files is

`# truncation_length = 10`

### LunarVim version

Rolling branch commit e6f4b20346f4257f065b18ffa3cf1ff34e0f0b56

### Neovim version (>= 0.5)

v0.6.0-dev+682247b52

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
https://github.com/ChristianChiarulli/LunarVim/issues/985

**Comment by nwaywood** [comment]
> #985

Ah sorry I missed that, I just searched issues for "toml". Feel free to close if you don't want a separate ticket to track `toml` 👍

**Comment by ChristianChiarulli** [comment]
I'll keep my eyes open for a new plugin for commenting for now I suggest putting an issue in upstream

**Comment by ChristianChiarulli** [comment]
https://github.com/terrortylor/nvim-comment/issues/29

**Comment by nwaywood** [comment]
The other option is switching to Kommentary? They seem to support more languages in general and are also more popular (which should mean better community support).

They have toml support https://github.com/b3nj5m1n/kommentary/blob/fe01018a490813a8d89c09947a7ca23fc0e9e728/lua/kommentary/config.lua#L62

**Comment by rebuilt** [comment]
We can also add the active property so users can chose the comment system that best supports their languages.

**Comment by nwaywood** [comment]
It looks like Kommentary is a superset of what nvim-comment supports so I don't think there would be any downside to switching (assuming its not buggy)

**Comment by ChristianChiarulli** [comment]
I will explore kommentary in the future, for now I have fixed the toml comment string.
