### ISSUE TITLE
[Bug]: Fresh install of lunarvim does not load the default colorscheme

### ISSUE THREAD

**Issue by colutti** [ChristianChiarulli/LunarVim#1109]
### Problem description

On a fresh Linux instance (tested on ubuntu and arch) opening Neovim does not load the default theme spacegrey. 
Activating it using Telescope works but it is not persisted (of course).

Tested on the main branch with the follow command:

`curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh| LVBRANCH=master bash -s -- --overwrite
`

### LunarVim version

Master

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+1501-g9c7e04eb3

### Screenshots

![image](https://user-images.githubusercontent.com/9368892/126957483-24594133-eb2e-4c73-b388-b061946a984a.png)

![image](https://user-images.githubusercontent.com/9368892/126957502-060ab719-af7a-4fc1-9640-a0372713441c.png)

![image](https://user-images.githubusercontent.com/9368892/126957527-020989c5-e731-4983-94b5-23b78af209de.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by nwaywood** [comment]
Did you spell it `spacegrey` or `spacegray` in your lv-config? Because you need the American spelling https://github.com/ChristianChiarulli/LunarVim/blob/3c9c081c28dd2bd9e69f46dce852dfb3e88842ff/lua/default-config.lua#L9

**Comment by colutti** [comment]
@nwaywood I changed nothing. I am using the default config file without any changes. It is set as it should be. 
BTW, this is not the only thing not working. LSPs arent as well (at least lua and terraform).

**Comment by ChristianChiarulli** [comment]
are you running lvim or nvim?

**Comment by rebuilt** [comment]
> @nwaywood I changed nothing. I am using the default config file without any changes. It is set as it should be.
> BTW, this is not the only thing not working. LSPs arent as well (at least lua and terraform).

Is this your first install or are you upgrading?  If you're upgrading, maybe your packer_compiled folder needs to get removed before installing
Please remove these directories and retry
```
rm -rf ~/.local/share/lunarvim
rm -rf ~/.cache/nvim
rm -rf ~/.config/lvim/plugin

#And if you haven't already done so, lunarvim no longer lives in ~/.config/nvim so if you have one formerly installed there, remove it.
rm -rf ~/.config/nvim
```

**Comment by rebuilt** [comment]
Oops, sorry.  I thought you were on rolling.  The advice I gave before applies to rolling.  I'll test a new install on master.

**Comment by rebuilt** [comment]
Can you please post the output of `:messages`.   
Check the error logs in `~/.cache/nvim` to see if there are any relevant error messages.
Can you post the full output of `nvim -v`.  I want to make sure your version of neovim  was compiled with LuaJit
Can you check `PackerStatus`.  At the top it should say 26 plugins were loaded.   If that number is different run `:PackerSync`

I wasn't able to reproduce the issues when I tested a new master install

**Comment by colutti** [comment]
![image](https://user-images.githubusercontent.com/9368892/127046895-2a7cc14d-dfb8-4ad5-9d10-35084f338650.png)

![image](https://user-images.githubusercontent.com/9368892/127047537-b300bb50-027c-4df5-a6b3-985415a18e6a.png)

![image](https://user-images.githubusercontent.com/9368892/127047573-642f5d29-c6e3-4abf-86c8-42796b8bec9e.png)

In this case, I am running lvim in a raspberry pi but I have the same issue with a docker image and a bare bone ubuntu installation.

**Comment by colutti** [comment]
> are you running lvim or nvim?

nvim, lunarvim from master, macbook pro (also tested on ubuntu, pi and arch)

**Comment by colutti** [comment]
I just created a Dockerfile to help you testing the bug.

`FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

ARG BUILD_APT_DEPS="ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip git python3 python3-pip nodejs npm git"
ARG TARGET=nightly

RUN apt update && apt upgrade -y && \
  apt-get -y install tzdata && \
  apt install -y ${BUILD_APT_DEPS} && \
  git clone https://github.com/neovim/neovim.git /tmp/neovim && \
  cd /tmp/neovim && \
	git checkout tags/${TARGET} && \
  make CMAKE_BUILD_TYPE=Release && \
  make CMAKE_INSTALL_PREFIX=/usr/local install && \
  cd ~ && \
  rm -rf /tmp/neovim && \
  git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim && \
  git clone --branch master https://github.com/ChristianChiarulli/lunarvim.git ~/.config/nvim && \
  cp $HOME/.config/nvim/utils/installer/lv-config.example-no-ts.lua $HOME/.config/nvim/lv-config.lua && \
  nvim --headless +'autocmd User PackerComplete sleep 100m | qall' +PackerInstall && \
  nvim --headless +'autocmd User PackerComplete sleep 100m | qall' +PackerSync && \
  rm $HOME/.config/nvim/lv-config.lua && \
  cp $HOME/.config/nvim/utils/installer/lv-config.example.lua $HOME/.config/nvim/lv-config.lua
`

Just save the file and run the container:

`docker build -t lunar_test ./
docker run -it lunar_test /bin/bash
`
Now, inside the container run

`nvim`

**Comment by colutti** [comment]
If you change the Lunar branch to rolling you can also use this docker image to test stuff.

**Comment by colutti** [comment]
The issue has been fixed with the latest main version
