### ISSUE TITLE
rust-tools don't work as Additional Plugin

### ISSUE THREAD

**Issue by bob3000** [ChristianChiarulli/LunarVim#1119]
The rust tools work only half ways when installed as an additional plugin in `lv-config.lua`. The virtual text shows up however the [commands](https://github.com/simrat39/rust-tools.nvim#commands) which come with the plugin are not available. 

This is how I added the plugin to the `lv-config.lua`:

```lua
-- Additional Plugins
local rust_tools_opts = {
	tools = { -- rust-tools options
		autoSetHints = true,
		hover_with_actions = true,
		runnables = {
			use_telescope = true,
		},
		inlay_hints = {},
		hover_actions = {
			border = {
				{ "╭", "FloatBorder" },
				{ "─", "FloatBorder" },
				{ "╮", "FloatBorder" },
				{ "│", "FloatBorder" },
				{ "╯", "FloatBorder" },
				{ "─", "FloatBorder" },
				{ "╰", "FloatBorder" },
				{ "│", "FloatBorder" },
			},
		},
	},
}

lvim.plugins = {
	{
		"simrat39/rust-tools.nvim",
		config = function()
			require("rust-tools").setup(rust_tools_opts)
		end,
	},
}
```

I think we had this issue once before but a lot has changed since then I can't figure out anymore how it was fixed. Help is highly appreciated :pray:

**Comment by ichigo-gyuunyuu** [comment]
rust-tools seems to setup rust-analyzer as well, which might be causing this issue. 

This is just a workaround but if you want lunarvim to not setup the lsp and leave everything to the plugin, add `lvim.lang.rust.lsp.provider = nil` in your lv-config. (pull in the latest commit). Also, the plugin requires you to have the rust-analyzer binary in your path by default.

**Comment by abzcoding** [comment]
@bob3000 check [my lvim](https://github.com/abzcoding/lvim/blob/main/lv-config.lua) for rust related config
I'm using `rust-tools.nvim` with no issues
I've added this
```lua
lvim.lsp.override = { "rust" }
-- the plugin installation
-- and a couple autocommands
-- and debugging stuff
```

**Comment by bob3000** [comment]
@abzcoding Thanks a lot. That did the trick :pray: 
@ichigo-gyuunyuu I had tried that before and it didn't work. However it does work now after this one commit was added https://github.com/ChristianChiarulli/LunarVim/commit/4d68c6eb78bc1376be5e7fb5c3303001eb425228 as you already mentioned. Thank you too :pray:

**Comment by sanevillain** [comment]
Can someone please share their config ? I tried everything written above to no avail. Even though the plugin is loaded none of the commands are actually available

**Comment by rebuilt** [comment]
> Can someone please share their config ? I tried everything written above to no avail. Even though the plugin is loaded none of the commands are actually available
https://github.com/abzcoding/lvim

**Comment by bob3000** [comment]
> Can someone please share their config ? I tried everything written above to no avail. Even though the plugin is loaded none of the commands are actually available

https://github.com/bob3000/dotfiles/blob/linux/conf/lv-config.lua#L162
