### ISSUE TITLE
[Bug]: Error when opening `fish` script

### ISSUE THREAD

**Issue by tiannaru** [ChristianChiarulli/LunarVim#1120]
### Problem description

Steps to reproduce:
1. Open fish file: `lvim test.fish`
Or, open any file and run `:set filetype=fish`
2. See an error that is related to `lsp`:
```
Error detected while processing /home/tiannaru/.local/share/lunarvim/lvim/ftplugin/fish.lua:
E5113: Error while calling lua chunk: /home/tiannaru/.local/share/lunarvim/lvim/lua/lsp/init.lua:302: attempt to index a nil value
Error detected while processing FileType Autocommands for "*":
Error while processing file: /home/tiannaru/.local/share/lunarvim/lvim/ftplugin/fish.lua
/home/tiannaru/.local/share/lunarvim/lvim/lua/lsp/init.lua:302: attempt to index a nil value
```
Pressing `<esc>` clears the error and lunarvim works as expected after that (as in, no LSP active for fish)

### LunarVim version

e5bd25b1f3d44395e522b2455c058b15f2bbe76f

### Neovim version (>= 0.5)

v0.6.0-dev+63-ga8c3d50fa

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
fixed on rolling
