### ISSUE TITLE
[Bug]: Can't properly insert tabs/spaces with the tab key in Markdown files

### ISSUE THREAD

**Issue by etienne-k** [ChristianChiarulli/LunarVim#1121]
### Problem description

**Steps to reproduce**
- Open a markdown file.
- Enter insert mode.
- Press the minus/dash key.
- Press the tab key.

**Expected behavior**
- Following the tab key press, a tab or spaces (depending on the indentation settings) is inserted.
- When an autocomplete suggestion list pops up though, cycling with the tab key should be possible.

**Actual behavior**

- Bad: An autocomplete suggestions list pops up.
- Bad: Nothing is inserted after the dash.
- Good: Cycling works with the tab key.

**Observations**
I noticed this is due to the hardcoded keybinds in lua/core/compe.lua:
```lua
vim.api.nvim_set_keymap("i", "<Tab>", "v:lua.tab_complete()", { expr = true })
vim.api.nvim_set_keymap("s", "<Tab>", "v:lua.tab_complete()", { expr = true })
vim.api.nvim_set_keymap("i", "<S-Tab>", "v:lua.s_tab_complete()", { expr = true })
vim.api.nvim_set_keymap("s", "<S-Tab>", "v:lua.s_tab_complete()", { expr = true })
```

Commenting out the two insert mode keybinds allows me to enter a tab/spaces, but it comes at a downside. It then no longer seems possible to cycle through the suggestions with the tab key. Cycling is still possible using the arrow keys.

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5.0 (stable)

### Screenshots

![image](https://user-images.githubusercontent.com/2804556/127040033-dc6b5342-100c-4bab-9e59-a09aae4fa752.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
Fixed Via #1130
