### ISSUE TITLE
[Bug]: Yaml autoindent is not as on-point as on vanilla neovim

### ISSUE THREAD

**Issue by tiannaru** [ChristianChiarulli/LunarVim#1125]
### Problem description

1. Open a new yaml file in a neovim with empty `init.vim`
2. Write yaml as usual. You will notice that auto-indentation is pretty good
3. Open new yaml file in a lunarvim instance with `lv-config.lua` taken from the Readme
4. Write yaml as usual. You will notice that on a new line the cursor is placed right at the start. 
Sometimes the de-dent on `:` and `-` will actually mess the file up.

It's quite hard to explain. I've attached a screencast to demonstrate.

It seems that this occurs regardless of whether `yamlls` is used, or if the `lv-config.lua` file is empty.

### LunarVim version

4d68c6eb78bc1376be5e7fb5c3303001eb425228

### Neovim version (>= 0.5)

v0.6.0-dev+63-ga8c3d50fa

### Screenshots

https://user-images.githubusercontent.com/31815875/127057659-bcc1f706-3bd0-4867-81e3-fd0a4c64f6e4.mp4

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
we could try disabling treesitter indents for yaml

**Comment by ChristianChiarulli** [comment]
disabling treesitter indent since it seems to work pretty well with vanilla indent. let me know if that solves your problem, or you'd like to see better support.

**Comment by tiannaru** [comment]
This is great! It's already better than in vscode 😈  Closing the issue.

**Comment by tiannaru** [comment]
forgot to mention, fixed in 66bf89c3d12ccc87f3f02e1b031771e6c9466fea
