### ISSUE TITLE
Telescope lvim keybinding for Next/Previous item in insert mode are wierd

### ISSUE THREAD

**Issue by vlcinsky** [ChristianChiarulli/LunarVim#1137]
### Problem description

Open any Telescope search, e.g. to search a file `<space>f`

See few items and try to select 3rd file from the bottom.

I am used in lists of items to pick from to use <Ctrl-P> and <Ctrl-N> for Previous/Next item movement in the list which is visible.

Current keybinding in LunarVim are surprising as they do not change position in visible list but swap search text to next/previous item from search history.

### LunarVim version

rolling branch commit 66bf89c

### Neovim version (>= 0.5)

v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
idk if it's a bug but it's something you could definitely change, what keybinds do you think should cycle history?

**Comment by vlcinsky** [comment]
I would swam keymapping for next/previous history item with next/previous found item.
So for history it would be Ctrl-j and Ctrl-k so at https://github.com/ChristianChiarulli/LunarVim/blob/rolling/lua/core/telescope.lua#L46 it would change from original:
```lua
      mappings = {
        i = {
          ["<C-n>"] = actions.cycle_history_next,
          ["<C-p>"] = actions.cycle_history_prev,
          ["<C-c>"] = actions.close,
          ["<C-j>"] = actions.move_selection_next,
          ["<C-k>"] = actions.move_selection_previous,
          ["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,
          ["<CR>"] = actions.select_default + actions.center,
```
to 
```lua
      mappings = {
        i = {
          ["<C-n>"] = actions.move_selection_next,
          ["<C-p>"] = actions.move_selection_previous,
          ["<C-c>"] = actions.close,
          ["<C-j>"] = actions.cycle_history_next,
          ["<C-k>"] = actions.cycle_history_prev,
          ["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,
          ["<CR>"] = actions.select_default + actions.center,
```

PS: "Bug" is result of the issue template which seemed to be the most relevant.

**Comment by vlcinsky** [comment]
[Default telescope.nvim mapping](https://github.com/nvim-telescope/telescope.nvim/blob/79644ab67731c7ba956c354bf0545282f34e10cc/lua/telescope/mappings.lua#L12) is also using
```lua
      ["<C-n>"] = actions.move_selection_next,
      ["<C-p>"] = actions.move_selection_previous,
```
