### ISSUE TITLE
[Bug]: No highlighting for visual mode

### ISSUE THREAD

**Issue by Oisov** [ChristianChiarulli/LunarVim#1143]
### Problem description

Using lunarvim I do not have any visual indication for visual mode. Meaning whenever I highlight something using `v` no visual change happens. I can still visual yank etc, but it is a bit hard when it does not actually highlight anything. I included a picture where I have visually highlighted the first line in the file, and as you can see (or not see), no visual indication is added.

I ran `:checkhealth` and no issues there. What sort of logs or otherwise do I need to include? Again this is on a clean install. I included my specs using neofetch.

### Things I have tried 

* Using a clean install of `lvim`, with a nightly build of `nvim`
* Normaly I use `st` but same issue persists with `alacritty`
* Using a transparent background by default, no changes when disabling `picom`
* Switching to a clean `nvim` build has no issues with highlighting.

### LunarVim version

Newest

### Neovim version (>= 0.5)

0.6.0

### Screenshots

![image](https://user-images.githubusercontent.com/29121774/127337508-65e01521-26fc-425e-b7d7-97b362c5fbde.png)

![image](https://user-images.githubusercontent.com/29121774/127336369-2ea639cf-3d77-4e50-8b33-bae6301674bc.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
I imagine it's a transparency thing.  Can you turn off transparency and check again?

**Comment by Oisov** [comment]
> I imagine it's a transparency thing. Can you turn off transparency and check again?

I have already tried this (as stated in my initial post). I have tried setting the transparency to 100 (no transparency) and disabling my compositor entirely (picom), neither makes a difference. Nvim keeps working fine while lunarvim refuses to offer highlighting for visual mode.

**Comment by rebuilt** [comment]
Oh.  Sorry, I assumed you were doing this in your `lv-config.lua`
```
lvim.transparent_window = true

```

I was asking you to turn that off to see if the it was a problem with these settings
```
    cmd "au ColorScheme * hi Normal ctermbg=none guibg=none"
    cmd "au ColorScheme * hi SignColumn ctermbg=none guibg=none"
    cmd "au ColorScheme * hi NormalNC ctermbg=none guibg=none"
    cmd "au ColorScheme * hi MsgArea ctermbg=none guibg=none"
    cmd "au ColorScheme * hi TelescopeBorder ctermbg=none guibg=none"
    cmd "au ColorScheme * hi NvimTreeNormal ctermbg=none guibg=none"
    cmd "let &fcs='eob: '"

```

**Comment by Dan-M** [comment]
I'm seeing the same issue in a `tmux` session with the `spacegrey` color scheme. 
Switching the color scheme resolves the issue.

If I run `lvim` outside of a `tmux` session, I can't replicate this problem even with the `spacegrey` color scheme.

Transparency doesn't seem to be the issue here. I'm using picom and alacritty as well.

![v-select-lvim](https://user-images.githubusercontent.com/859495/127484194-fd09788c-2425-4389-89c3-2958ca7f6216.png)

The screenshot shows 
tmux - lvim with slate color scheme on top
lvim with spacegrey color scheme in the middle and
tmux - lvim with spacegrey color scheme at the bottom

**Comment by deryrahman** [comment]
@Oisov Have you tried to change `Visual` colorscheme highlight? Put this on `lv-config`
```
lvim.autocommands.custom_groups = {
    { "ColorScheme", "*", "hi Visual guibg=#ffffff" },
}
```
Seems like `alt_bg` is not so contrast enough to differentiate between visual highlight color and lvim background color

**Comment by Oisov** [comment]
@deryrahman Sorry for the late reply. This fixed my issue

Is this something to consider adding a PR to fix, or will this gets fixed when a new default
colorscheme is picked?

**Comment by abzcoding** [comment]
@Oisov this is the default theme palette, so there might not be enough contrast between bg and alt_bg
but have an issue open for choosing a default colorscheme
also, feel free to check out  [LunarVim colorschemes](https://github.com/LunarVim/Colorschemes)
![image](https://user-images.githubusercontent.com/10992695/128029945-fb7627bc-6eeb-4ca0-9133-bd4459690a2f.png)

I'm closing this till we find a better colorscheme, or a better way to expose colors
