### ISSUE TITLE
[Feature]: from wiki, changing galaxy line

### ISSUE THREAD

**Issue by eo1989** [ChristianChiarulli/LunarVim#1144]
### Feature motivation

The write up regarding changing the galaxyline config doesnt work.

**Comment by rebuilt** [comment]
Which galaxyline elements are you trying to remove and what do your `table.remove` functions look like.  Are you on the lastest rolling release?  Un-comment the line with the print statement `-- print(vim.inspect(gl))` and post the output here.

**Comment by eo1989** [comment]
I followed the wiki to the tee. I am on the latest rolling release.
<img width="1122" alt="Screen Shot 2021-07-28 at 11 37 19" src="https://user-images.githubusercontent.com/7108365/127352401-c3f7675b-55dd-4d95-a6e2-870e6bf25381.png">

**Comment by rebuilt** [comment]
That was an issue with an older version of LunarVim.  It should be fixed in rolling.
If you don't feel like upgrading you'll need to require galaxyline explicitly

`local gl = require("galaxyline")`

And also remove or rename 'gl' from the function arguments

**Comment by rebuilt** [comment]
Problem should be fixed in the latest version.  If it still doesn't work for you, feel free to reopen.

**Comment by rebuilt** [comment]
I've updated the readme with new instructions.

**Comment by abzcoding** [comment]
the problem should be fixed i'm doing [this](https://github.com/abzcoding/lvim/blob/4608f2e716ab31161aef2eff2faba01102bbb427/lua/user/galaxyline.lua#L3)
```lua
lvim.builtin.galaxyline.on_config_done = function(gl)
  require("user.galaxyline").config(gl)
end
```
which works perfectly
