### ISSUE TITLE
[Bug]: I cannot install efm

### ISSUE THREAD

**Issue by devrrior** [ChristianChiarulli/LunarVim#1145]
### Problem description

When I type ":LspInstall efm", it returns could not install language server for efm

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

Newest

### Neovim version (>= 0.5)

v0.5.0

### Relevant log output

```shell
:LspInstall efm
[nvim-lspinstall] Could not install language server for efm
```

### Screenshots

![image](https://user-images.githubusercontent.com/69869135/127345010-20ae4262-adee-462e-8db6-88e4fb09352e.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
There are two things to mention.  First, you need to install golang https://golang.org/doc/install.  The installer uses `go get` to install efm.   And the second is that LunarVim no longer uses efm for formatting.  We are still in the process of working out the bugs for efm.  You can still set up efm on your own if you wish but then you'll need to choose which formatter to run every time you save a file.

**Comment by devrrior** [comment]
ok, thanks so much.

**Comment by rebuilt** [comment]
PS.  Formatting is now provided by null-ls and the language server for your filetype.  For example, if you program in python `:LspInstall python` should be enough to get basic formatting.  For a specific formatter, set it with `lvim.lang.cpp.formatter.exe = "my-formatter"`

**Comment by rebuilt** [comment]
You'll also need to set the following in your lv-config
```
lvim.lint_on_save = true
lvim.format_on_save = true

```

**Comment by devrrior** [comment]
Thanks for the help, that works. I have another issue related to python LSP, I'm working on a Django project but doesn't work completion and doesn't show definition preview hover, must I open a new issue for that?

**Comment by rebuilt** [comment]
Yes please so it's searchable if others have the same problem.
