### ISSUE TITLE
[Bug]: File explorer stops showing hidden files

### ISSUE THREAD

**Issue by barlingo** [ChristianChiarulli/LunarVim#1151]
### Problem description

Reproduce the problem:
1. Open any file with lvim.
2. Open file explorer using <space><e>
3. Show hidden files on explorer using <H>
4. Change windows back to the original file.
5. Go back to explorer and try hiding .dotfiles using <H> again. It does not work

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
what seems to be the issue?
i'm doing this using `H`
![nvim-tree](https://user-images.githubusercontent.com/10992695/127444222-9e97d9fe-a52e-47c3-ac1f-3c81c5345e19.gif)

**Comment by not-rusty** [comment]
I was bitten by this silly confusion aswell. For anyone reading this, press `g?` to see all the available options.
