### ISSUE TITLE
[Bug]:  Extreme lag when open python ( *py) file 

### ISSUE THREAD

**Issue by lavixta** [ChristianChiarulli/LunarVim#1165]
### Problem description

Hi, i just update new lvim and i have a problem with working with python file. I try other file (lua, js,jsx,ts,.. ) are all normal but when i open py file ( even empty file ) it is extremely lag.  

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5.0 

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Tastyep** [comment]
I'm not experiencing this personally, is anyone having the same issue ?

**Comment by ChristianChiarulli** [comment]
how big is the project?

**Comment by Tastyep** [comment]
I gave a try on tensorflow, it took maybe 30 secondes to be able to `<space>f` or `<space>st`, but otherwise it was still working great.

**Comment by rebuilt** [comment]
![telescope](https://user-images.githubusercontent.com/16025007/127560186-4e0bd069-ff5a-43fd-962f-75fb8d7c88be.gif)

**Comment by rebuilt** [comment]
I'm using fzy native.

**Comment by rebuilt** [comment]
Put this in lv-config.lua

```
lvim.builtin.telescope.extensions = {
	fzy_native = {
		override_generic_sorter = false,
		override_file_sorter = true,
	},
}

lvim.builtin.telescope.on_config_done = function()
	require("telescope").load_extension("fzy_native")
end

```

And in plugins

```
	{
		"nvim-telescope/telescope-fzy-native.nvim",
		run = "make",
	},
```

**Comment by youdaniel** [comment]
Experiencing some lag too. Basic vim stuff like o, i, :q feel much slower in python files.

**Comment by tarkin88** [comment]
it's laggy for me too on python files

**Comment by rebuilt** [comment]
I tested the speed on my t430.  I can confirm the slowness.  But then I installed the language server and that seemed to speed things up.

Do you have the language server installed?

```
:LspInstall python
```

**Comment by rebuilt** [comment]
I'm also seeing this in the error logs

```
Error executing vim.schedule lua callback: ...packer/start/p
lenary.nvim/lua/plenary/async_lib/util.lua:170: Oneshot chan
nel can only send once
```

**Comment by numine777** [comment]
The issue you're experiencing is almost certainly due to pyright not being able to find the project root properly.  I am experiencing the same issue.  In the past, I've overcome this by configuring pyright to register BUILD.bazel files as root markers, however, it's less straightforward as to where to make this change with the 0.5.0 refactor.  Hence my enhancement request to expose the ability to set root markers.

**Comment by youdaniel** [comment]
Language server is installed. Can confirm that it's pyright unable to find project root, as I'm only experiencing slowness with standalone files.

**Comment by ChristianChiarulli** [comment]
interesting, do you think it might be worth upstreaming this? 

https://github.com/neovim/nvim-lspconfig

We could expose configuring your own root but tbh I'm pretty sure you already can do this (you just won't get autocomplete to see the root_dir option).

Another thing you could do is `NlspConfig pyright` and try toggling some fo the settings to see if they help. 

You could also, add `python` to `lvim.lsp.overrides = { "python" }` and implement it yourself to see if it helps.

**Comment by numine777** [comment]
```

local root_files = {
    'setup.py',
    'pyproject.toml',
    'setup.cfg',
    'requirements.txt',
    '.git',
    'BUILD.bazel',
}
local util = require 'lspconfig/util'
lvim.lang.python.lsp.setup.root_dir = function(filename)
      return util.root_pattern(unpack(root_files))(filename) or
              util.path.dirname(filename)
      end
```

This solution in the lv-config.lua works great for me!

**Comment by mjlbach** [comment]
I don't think we want to support bazel generally... The pyright python rules are pretty standard. We'll add user-overridable local root directories and remove the fallback to util.path.dirname soon-ish (this is usually the most common slowdown, user opens a python file in their home directory and pyright recursively starts indexing /home)

**Comment by numine777** [comment]
My suggestion wasn't specifically to support bazel, just to expose the ability to set the root directories from a list of filenames (root markers).

**Comment by lavixta** [comment]
Hey i have tried all above but seem like it is still laggy. Even when i code on empty file, i have followed lunavim for a while and the issue seem to happened with lately null-ls config. I will try to figure it out first, Any one who experience the same issue are you also use MacOS

**Comment by williamgoulois** [comment]
I'm on MacOS too on an old MacbookPro from late 2013
Performance was okay 30 commits ago but now look at this
<img width="1680" alt="Screenshot 2021-07-30 at 22 44 48" src="https://user-images.githubusercontent.com/37271970/127710015-95ced84e-ef38-4ee0-ba94-67fc35bc6673.png">

**Comment by williamgoulois** [comment]
Just did a test between 2 commits :

Latest on rolling so at the moment 6f4dd84
[onRolling.log](https://github.com/ChristianChiarulli/LunarVim/files/6909971/onRolling.log)

On an older commit 21971cb (30 commits old)
[onOldRolling.log](https://github.com/ChristianChiarulli/LunarVim/files/6909974/onOldRolling.log)

From 477ms to 846ms !

**Comment by ChristianChiarulli** [comment]
I wonder if it's null-ls?

**Comment by cstsunfu** [comment]
I use myself config, disable lspconfig and change to coc.nvim, everything goes well.

**Comment by lavixta** [comment]
> I wonder if it's null-ls?
> 
> Could someone confirm if this speeds things up: `vim.g.null_ls_disable = true`

i tried but it is still laggy ( only for python ) 
<img width="116" alt="Screen Shot 2021-07-31 at 9 17 53 AM" src="https://user-images.githubusercontent.com/36840462/127736211-56d71558-c1d9-42ea-943b-dd7dbbebe044.png">
![Uploading Screen Shot 2021-07-31 at 9.17.53 AM.png…]()

**Comment by kylo252** [comment]
> > I wonder if it's null-ls?
> > Could someone confirm if this speeds things up: `vim.g.null_ls_disable = true`
> 
> i tried but it is still laggy ( only for python )


That doesn't seem to have disabled it. Can you just comment-out your linters and formatters or set both to `nil` ? 
_Assuming you have pulled #1172_

**Comment by rebuilt** [comment]
@kylo252 how hard would it be to change to code to actually disable it?

**Comment by kylo252** [comment]
> @kylo252 how hard would it be to change to code to actually disable it?

It's off by default after #1078 except for `stylua`. _Unless they defined a linter/formatter._

But to answer your question, it's very simple and can be done in multiple ways:
```lua
lvim.lang.mylang.lsp.on_attach=nil
```
Or you can wrap it inside common_on_attach
```lua
function M.common_on_attach(client, bufnr)
  if lvim.lsp.on_attach_callback then
    lvim.lsp.on_attach_callback(client, bufnr)
  end
  lsp_highlight_document(client)
  require("lsp.keybinds").setup()
  if not lvim.lsp.disable_null_ls_or_something then
    require("lsp.null-ls").setup(vim.bo.filetype)
  end
end
```

**Comment by lavixta** [comment]
Ah, i  think just my computer has a problem with flake8. When i set O.lang.python.inters[1] = nil, it is not lag anymore . Thanks all for your help

**Comment by CSpencerND** [comment]
Mine lags no matter what file type I'm on. As soon as I turn off Lsp everything runs perfectly. This only started after I upgrade Lunar Vim a few days ago to the stable release.

**Comment by mjlbach** [comment]
I'm guessing it's null-ls

**Comment by ChristianChiarulli** [comment]
Yea, this seems like a null-ls issue, specifically with diagnostics, formatters seem fine.
