### ISSUE TITLE
[Feature]: Expose the ability to set root markers for the LSP

### ISSUE THREAD

**Issue by numine777** [ChristianChiarulli/LunarVim#1169]
### Feature motivation

I work in a monorepo for my day job that uses Bazel files to delineate packages and services.  I had worked around this in previous versions of LunarVim by modifying the lspconfigs to include a bespoke list of `root_files`, however, the latest move to lvim has changed a lot.  Nlsp-settings allegedly allows config files to be written in lua rather than json but I have yet to get that feature to produce usable results.

A simpler solution would be to allow users to set a list of root markers for all lsps to allow the file system root to be found more easily.

### Describe the expected solution

A single variable exposed to lv-config that will contain a list of root markers.

### Describe the alternatives you've considered

Alternatives are directly modifying the lvim config files themselves.

**Comment by ChristianChiarulli** [comment]
I'm pretty sure you can just `lvim.lang.python.lsp.setup.root_dir = blah` You just won't see autocomplete for it.

**Comment by numine777** [comment]
That does work!  Thank you very much for the fix!
