### ISSUE TITLE
Use install for new lvim script

### ISSUE THREAD

**Issue by sedlund** [ChristianChiarulli/LunarVim#1178]
https://github.com/ChristianChiarulli/LunarVim/blob/cb108adec4799dd592b9bf436247bf98ad56807a/utils/installer/install.sh#L115

I have my umask set to 007 so using sudo like this makes the zsh  issue `permission denied` after running `lvim`

use this instead

> sudo install --owner=root --group=root --mode=775 "$HOME/.local/share/lunarvim/lvim/utils/bin/lvim" "/usr/local/bin"

**Comment by abzcoding** [comment]
does this fix your issue? #1168

**Comment by sedlund** [comment]
Yes that would work as well.

**Comment by abzcoding** [comment]
Closed via #1168
