### ISSUE TITLE
[Bug]: NvimTree width setting is wrong positioned / [Feature]: NvimTree width should be editable

### ISSUE THREAD

**Issue by Artem-Schander** [ChristianChiarulli/LunarVim#1182]
### Feature motivation

NvimTree width is set to 30 (inside of `lvim.builtin.nvimtree.show_icons.tree_width`) and is kind of hard coded, since the `toggle_tree` function sets the offset of 31 without respecting the actual width.

### Describe the expected solution

It should be possible to change that value from within lv-config (it is .. kind of)

### Describe the alternatives you've considered

```lua
local M = {}
--
M.config = function()
  lvim.builtin.nvimtree = {
    -- ...
    width = 40,
    -- ...
  }
end
-- ...
M.toggle_tree = function()
  local view_status_ok, view = pcall(require, "nvim-tree.view")
  if not view_status_ok then
    return
  end
  if view.win_open() then
    require("nvim-tree").close()
    if package.loaded["bufferline.state"] then
      require("bufferline.state").set_offset(0)
    end
  else
    if package.loaded["bufferline.state"] and lvim.builtin.nvimtree.side == "left" then
      -- require'bufferline.state'.set_offset(31, 'File Explorer')
      require("bufferline.state").set_offset(lvim.builtin.nvimtree.width + 1, "")
    end
    require("nvim-tree").toggle()
  end
end
--
return M

```

### Additional context

Is this worth a PR? Or can someone just replace the lines, if this request gets accepted.
BTW. I appreciate your work. Here happens so much.

**Comment by Artem-Schander** [comment]
Besides that .. if I set `lvim.builtin.nvimtree.quit_on_open = 1` the tree gets closed on file open, but the barbar offset stays. Is there a way to reset the offset in this case?

**Comment by williamgoulois** [comment]
For the Feature part I exposed nvimtree width in my PR #1074 can someone review/merge it?

For the Bug I don't know if we can register a callback on close of the tree 🤔

**Comment by abzcoding** [comment]
#1074 is merged, it should be editable now
