### ISSUE TITLE
[Bug]: Open 2 buffers with colorizer plugin installed, only second buffer works with this plugin.

### ISSUE THREAD

**Issue by jimcornmell** [ChristianChiarulli/LunarVim#1188]
### Problem description

- Install colorizer plugin through `lvim.plugins` in `lv-config.lua`

```lua
lvim.plugins = {
  {
    "norcalli/nvim-colorizer.lua",
    event = "BufRead",
    config = function()
      require("lv-colorizer").config()
    end,
  }
}
```
- Open 2 or more buffers, colorizer works as expected in buffers 2...n, but  not in buffer 1.  I.e. first file not working with colorizer, does not depend on the file so `lvim a.txt b.txt` or `lvim b.txt a.txt` give colorizer working with second txt file (but not the first).

My FULL config is [here](https://github.com/jimcornmell/LunarVim)

I assume its related to event, but I've tried other options other than BufRead, with no difference.

### LunarVim version

rolling (2021-07-31)

### Neovim version (>= 0.5)

v0.6.0-dev+96-g5f01714b2

### Relevant log output

```shell
N/A
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
get rid of the event field and test again.

**Comment by jimcornmell** [comment]
No change, still first buffer not working.

**Comment by williamgoulois** [comment]
I cannot reproduce your bug (tested it without Event field) ?

https://user-images.githubusercontent.com/37271970/127748545-964760ae-0613-4d75-aefc-0c7c9eda73ad.mov

**Comment by jimcornmell** [comment]
I've been experimenting and I can toggle the behaviour on and off.  So when I load my `user.vim` in `config.lua` I get the following two results:

Result 1: If I load my user file by wrapping it in a on_config_done then colorizer does not load, yet my configuration of colours gets applied, see the yellow todo on line 16.  (I know protecting it with `lvim.builtin.which_key.on_config_done` is wrong/hacky but I'm not sure what to protect it with, and maybe that is the problem!)
```lua
lvim.builtin.which_key.on_config_done = function()
    vim.cmd('source ~/.config/lvim/user.vim')
end
```
![Screenshot_20210801_141843](https://user-images.githubusercontent.com/7923416/127772590-d0444c63-36be-4275-8a07-35bd5b7a09e5.png)

Result 2: If I just load my user.vim with no wrapper, then colorizer works (see line 15 in the image below), yet my colours do not get applied, the todo on line 16 is blue.

```lua
vim.cmd('source ~/.config/lvim/user.vim')
```
![Screenshot_20210801_141827](https://user-images.githubusercontent.com/7923416/127772598-013370c2-224e-4d69-b5a3-e63705c00471.png)

So its the loading of my personal user.vim which is causing the issues but in a weird way.  I'm guessing I need to wrap my `user.vim` load or place it somewhere else (its currently the last line in `config.lua`).

My latest [config.lua](https://github.com/jimcornmell/LunarVim/blob/master/config.lua) and [user.vim](https://github.com/jimcornmell/LunarVim/blob/master/user.vim)

**Comment by williamgoulois** [comment]
Ok i investigated the problem which is apparently linked to colorsheme.
We set colorscheme after we load `config.lua` (so after you set your custom colors) which means they are overrided with.

Problem is that we must call colorscheme after plugins are loaded or we break new LunarVim installs.

For reference we load your config here: https://github.com/ChristianChiarulli/LunarVim/blob/fbbf1b22a4ab48e19a33a5b10322253ebbca7b8f/init.lua#L37

and set colorsheme after here:
https://github.com/ChristianChiarulli/LunarVim/blob/fbbf1b22a4ab48e19a33a5b10322253ebbca7b8f/init.lua#L54

A solution for you might be to isolate colors in a file and call it in init.lua after the set of colorscheme. Can you try ?

**Comment by jimcornmell** [comment]
Hi @williamgoulois, many, many thanks, that works fine, see line 284 and 285 in this image, correct colours and colorizer working.

![Screenshot_20210802_082930](https://user-images.githubusercontent.com/7923416/127821229-2110d5d4-1120-47b5-98a7-b7c4de4d249f.png)

The snippet at the end of `config.lua` now is:

```lua
vim.cmd('source ~/.config/lvim/lua/user/galaxyline.lua')

lvim.builtin.galaxyline.on_config_done = function()
    vim.cmd('source ~/.config/lvim/user_colors.vim')
end

vim.cmd('source ~/.config/lvim/user.vim')
```

I'm still not happy with my wrapper on line 278, what is the correct method?

**Comment by williamgoulois** [comment]
For your situation (you forked LunarVim) i think the best solution is to move 
`vim.cmd('source ~/.config/lvim/user_colors.vim')` to the end of `init.lua`. This will allow you to remove wrapper.

A better solution might be to be able to expose configuration of colors in `config.lua` and then call it in init.lua. What do you think of this @abzcoding, @ChristianChiarulli ?
