### ISSUE TITLE
[Bug]: Can't insert tab/spaces with the tab key

### ISSUE THREAD

**Issue by etienne-k** [ChristianChiarulli/LunarVim#1195]
### Problem description

_This issue is related to #1121 and the solution merged with #1130._

I fear the PR leaves us with problems, and hope you don't mind me opening an issue for this.

**Problem 1: missing functionality**

When you open a source file that is not one of the following types, inserting a tab or spaces using the tab key is impossible:
`exclude_filetypes = { "md", "markdown", "mdown", "mkd", "mkdn", "mdwn", "text", "txt" }`

In fact, inserting a tab character using any keyboard key is completely impossible.

This behavior is unlike any other editor (VSCode, IntelliJ, Kate, Sublime, ... you name it) I could think of.

In #1130, a suggested workaround was to add filetypes to the exclude list. This is not a viable solution if we want to correct/change the behavior globally (i.e. if we want to insert tabs/spaces with the tab key, regardless of the file type).

**Problem 2: inconsistent navigation**

Once a file type is added to the exclude list, we can insert spaces/tabs again with the tab key.
However, it's no longer possible to navigate through the completion list using tab/shift+tab.

This seems like a regression, and it doesn't provide a consistent behavior.

**Proposed solution**
Allow configuring key bindings for the following actions:
- Force-trigger completion (this is *not* the same as cycling through the completion list!!)
- Navigate down in the auto-completion list
- Navigate up in the auto-completion list

Provide defaults like in most editors:
- Trigger -> CTRL+Space
- Navigate up/down -> <Up> or <Shift+Tab> and <Down> or <Tab>

**Conclusion**

While I'm aware that LunarVim may be a bit opinionated in its default behavior (which is absolutely fine!), there are certain expectations users coming from other editors / Vim configs may have.
I'm quite certain that "tab key inserts tab/spaces" belongs to these expectations. No matter which file type is loaded.

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5.0

### Screenshots

![test old](https://user-images.githubusercontent.com/2804556/127749700-a1ebc9e9-5c38-40cf-892f-e3ae92cd4471.gif)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
Could you test the new rolling, I think I have improved the behavior somewhat. Please let me know if it's missing anything.

**Comment by etienne-k** [comment]
You're right, with the latest rolling, I can insert tabs both in normal text files and in source files, and I can still cycle in the autocomplete list with tab! Perfect, thanks a lot!!
