### ISSUE TITLE
[Bug]:In insert Mode! When I press the tab key, it displays pumvisible()? ":" "

### ISSUE THREAD

**Issue by angryheng** [ChristianChiarulli/LunarVim#1216]
### Problem description

In insert Mode! When I press the tab key, `it displays pumvisible()? ":" "`

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6.0

### Screenshots

![tab](https://user-images.githubusercontent.com/28853495/127977429-6451fa6f-0b1c-42f8-8083-c2fcf60247c7.gif)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Can run this and paste the results here please `:enew | pu=execute('verbose imap <tab>')` 
The result should only contain the code below.  I want to see if you have more than one tab mapping.  Otherwise this new mapping we introduced recently needs to be fixed somehow.  

```vim
i  <Tab>       * pumvisible() ? "<C-N>" : "<Tab>"
	Last set from anonymous :source
```
