### ISSUE TITLE
[Bug] No lsp key bindings when language server is set up by plugin

### ISSUE THREAD

**Issue by bob3000** [ChristianChiarulli/LunarVim#1219]
I'm not sure if this is a bug or a feature but since this commit https://github.com/ChristianChiarulli/LunarVim/commit/77e283bd9c33166937756250918b12e349caf050 I lost my lsp key bindings for the rust_analyzer. I'm using the [rust-tools](https://github.com/simrat39/rust-tools.nvim) plugin which sets up the `rust_analyzer` on it's own. For it to work properly I have to include `lvim.lsp.override = { "rust" }` in my `config.lua` to avoid the plugin to conflict with the `lspconfig` plugin. Since the commit mentioned above the override takes away the keybindings (e.g. "gd", "gD", "K" etc.) which was not the case before. If this is a feature, what would be the best way to work around this issue?

**Comment by kylo252** [comment]
They live inside `common_on_attach()` now. can you not use it with your current setup?

**Comment by ChristianChiarulli** [comment]
pls link your config and I will send you and example using rust tools with an override at some point this week or next.

**Comment by abzcoding** [comment]
@bob3000 
you can set up rust_tools like [this](https://github.com/abzcoding/lvim/blob/main/lua/user/rust_tools.lua) to use the keybindings as well

**Comment by bob3000** [comment]
@kylo252 I saw that the keybindings are now set by this one function but I don't see how I could call the function with the necessary arguments if lspconfig is not involved. Any suggestions?

@ChristianChiarulli https://github.com/bob3000/dotfiles/blob/linux/conf/lv-config.lua :pray: 

@abzcoding I basically took your config as a blueprint when I set up the rust tools. It should be broken now just like my config. Please set your cursor on a function call inside a rust file and type "gd". Are you still getting to see the function's definition?

**Comment by abzcoding** [comment]
@bob3000 mine works just fine
![rust](https://user-images.githubusercontent.com/10992695/128147198-0b3a5532-95e0-4a2a-8326-2bae5d8e7720.gif)

**Comment by kylo252** [comment]
> @kylo252 I saw that the keybindings are now set by this one function but I don't see how I could call the function with the necessary arguments if lspconfig is not involved. Any suggestions?

We can expose `add_lsp_buffer_keybindings()` if you feel it's useful. The reason I moved these away from the default config is two folds: 

1- These won't do anything if LSP isn't working
2- If they only work when a language server is attached, then they are better set as a local buffer binding.

This is all according to the examples from [lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/README.md#keybindings-and-completion) btw.

**Comment by kylo252** [comment]
@bob3000, You're missing the `server` argument in your `lv-config.lua`

https://github.com/bob3000/dotfiles/blob/e4b3aaa20405af7cbcf23d08d90aa3ada8d934b5/conf/lv-config.lua#L70-L91

You need to add the extra config flags as @abzcoding has in his config

```lua
    -- all the opts to send to nvim-lspconfig
    -- these override the defaults set by rust-tools.nvim
    -- see https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#rust_analyzer
    server = {
      cmd = { DATA_PATH .. "/lspinstall/rust/rust-analyzer" },
      on_attach = require("lsp").common_on_attach,
    }, -- rust-analyser options
```

reference: https://github.com/simrat39/rust-tools.nvim

**Comment by bob3000** [comment]
@abzcoding It shouldn't work :thinking: Are you sure you are on the latest commit on the rolling branch? If so the function `add_lsp_buffer_keybindings` which now sets the key bindings should never be called since you have `lvim.lsp.override = { "rust", "java" }` in your config.

@kylo252 I tried setting the server block. It didn't do anything. As far as I understand the `server` setting, whatever you write there is being forwarded to the rust_analyzer. Does it work for you?

**Comment by kylo252** [comment]
> @kylo252 I tried setting the server block. It didn't do anything. As far as I understand the `server` setting, whatever you write there is being forwarded to the rust_analyzer. Does it work for you?

If it doesn't work then it's a rust_analyzer issue/bug. You can try to add some dummy test function with some syntax error. It should break LSP unless it's ignoring that block completely. I don't really use rust, but I'll take a look to see if can I set up a test project quickly enough.

**Comment by abzcoding** [comment]
> @abzcoding It shouldn't work 🤔 Are you sure you are on the latest commit on the rolling branch? If so the function `add_lsp_buffer_keybindings` which now sets the key bindings should never be called since you have `lvim.lsp.override = { "rust", "java" }` in your config.
> 
> @kylo252 I tried setting the server block. It didn't do anything. As far as I understand the `server` setting, whatever you write there is being forwarded to the rust_analyzer. Does it work for you?

i'm always on the latest rolling :)
i have this line in setting up rust_tools
```lua
      on_attach = require("lsp").common_on_attach,
```
so the keybindings work

**Comment by abzcoding** [comment]
> > @kylo252 I tried setting the server block. It didn't do anything. As far as I understand the `server` setting, whatever you write there is being forwarded to the rust_analyzer. Does it work for you?
> 
> If it doesn't work then it's a rust_analyzer issue/bug. You can try to add some dummy test function with some syntax error. It should break LSP unless it's ignoring that block completely. I don't really use rust, but I'll take a look to see if can I set up a test project quickly enough.

we don't need to change anything common_on_attach already provides everything
```lua
function M.common_on_attach(client, bufnr)
  if lvim.lsp.on_attach_callback then
    lvim.lsp.on_attach_callback(client, bufnr)
  end
  lsp_highlight_document(client)
  add_lsp_buffer_keybindings(bufnr)
  if lvim.lsp.smart_cwd then
    vim.api.nvim_set_current_dir(client.config.root_dir)
    require("core.nvimtree").change_tree_dir(client.config.root_dir)
  end
  require("lsp.null-ls").setup(vim.bo.filetype)
end
```

**Comment by bob3000** [comment]
@abzcoding I agree with you. The way you configured it should be the proper way to do it but it won't work for me. I even copy and pasted your rust-tools opts into my config file but still no luck.
I did the following to see if the funciton is ever called
```
	server = {
		-- on_attach = require("lsp").common_on_attach,
		on_attach = function()
			print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
		end,
	}, -- rust-analyser options
```
But I don't see any exclamation marks in the message area. So the function is not called or am I mistaken?

**Comment by abzcoding** [comment]
> @abzcoding I agree with you. The way you configured it should be the proper way to do it but it won't work for me. I even copy and pasted your rust-tools opts into my config file but still no luck.
> I did the following to see if the funciton is ever called
> 
> ```
> 	server = {
> 		-- on_attach = require("lsp").common_on_attach,
> 		on_attach = function()
> 			print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
> 		end,
> 	}, -- rust-analyser options
> ```
> 
> But I don't see any exclamation marks in the message area. So the function is not called or am I mistaken?
add `lvim.debug = true` to your config and do it like this

```lua
      on_attach = function()
        require("utils").lvim_log(string.format("[%s]", "!!!!!!!!!!!!!!!!!!!!!!!!!!!!"))
      end,
```
you should see the message
<img width="290" alt="Screen Shot 2021-08-04 at 4 46 10 PM" src="https://user-images.githubusercontent.com/10992695/128179094-80ac582e-31e1-4fe1-9e03-3938686913c8.png">

**Comment by abzcoding** [comment]
if you can't see the message even after doing this, then you can file an issue with `rust-tools`

**Comment by bob3000** [comment]
@abzcoding No message :disappointed: Looks like I've to somehow figure it out on my own if nobody can't reproduce it. Thank you guys anyways.

**Comment by abzcoding** [comment]
possible issue with `rust_format`

**Comment by bob3000** [comment]
I was finally able to figure out what's wrong. I'll add the solution here for others running into the same kind of trouble.

The solution is that the `opts` that are handed to `require("rust-tools").setup(opts)` must be defined inside the function attached to `config` in the packer block. Mine was defined outside of this function and the values defined there went somehow stale or something. A working configuration for the rust-tools inside `config.lua` looks basically like this.

```lua
lvim.plugins = {
	{
		"simrat39/rust-tools.nvim",
		config = function()
			local opts = {
				tools = {
                                      -- rust-tools options
				},
				server = {
					cmd = { DATA_PATH .. "/lspinstall/rust/rust-analyzer" },
					on_attach = require("lsp").common_on_attach,
				}, -- rust-analyser options
			}
			require("rust-tools").setup(opts)
		end,
		ft = { "rust", "rs" },
	},
}
```

**Comment by nhussein11** [comment]
Hi everyone!
I'm running into the exact same problem, and this thread was the most closely to solve my problem but it didn't work yet (I have to say that I'm newbie at nvim)

My lspconfig.lua file has the keymapping as follows:

```lua
local on_attach = function(client, bufnr)
	-- keybind options
	local opts = { noremap = true, silent = true, buffer = bufnr }

	-- set keybinds
	keymap.set("n", "gf", "<cmd>Lspsaga lsp_finder<CR>", opts) -- show definition, references
	keymap.set("n", "gD", "<Cmd>lua vim.lsp.buf.declaration()<CR>", opts) -- got to declaration
	keymap.set("n", "gd", "<cmd>Lspsaga peek_definition<CR>", opts) -- see definition and make edits in window
	keymap.set("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>", opts) -- go to implementation
	keymap.set("n", "<leader>ca", "<cmd>Lspsaga code_action<CR>", opts) -- see available code actions
	keymap.set("n", "<leader>rn", "<cmd>Lspsaga rename<CR>", opts) -- smart rename
	keymap.set("n", "<leader>D", "<cmd>Lspsaga show_line_diagnostics<CR>", opts) -- show  diagnostics for line
	keymap.set("n", "<leader>d", "<cmd>Lspsaga show_cursor_diagnostics<CR>", opts) -- show diagnostics for cursor
	keymap.set("n", "[d", "<cmd>Lspsaga diagnostic_jump_prev<CR>", opts) -- jump to previous diagnostic in buffer
	keymap.set("n", "]d", "<cmd>Lspsaga diagnostic_jump_next<CR>", opts) -- jump to next diagnostic in buffer
	keymap.set("n", "K", "<cmd>Lspsaga hover_doc<CR>", opts) -- show documentation for what is under cursor
	keymap.set("n", "<leader>o", "<cmd>LSoutlineToggle<CR>", opts) -- see outline on right hand side

	-- typescript specific keymaps (e.g. rename file and update imports)
	if client.name == "tsserver" then
		keymap.set("n", "<leader>rf", ":TypescriptRenameFile<CR>") -- rename file and update imports
		keymap.set("n", "<leader>oi", ":TypescriptOrganizeImports<CR>") -- organize imports (not in youtube nvim video)
		keymap.set("n", "<leader>ru", ":TypescriptRemoveUnused<CR>") -- remove unused variables (not in youtube nvim video)
	end
end
```

And then, I followed the rust-tools docs, doing the following in my rust-tools.lua file (called by init.lua):

```lua
local rt = require("rust-tools")

rt.setup({
	server = {
		on_attach = function(_, bufnr)
			-- Hover actions
			vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
			-- Code action groups
			vim.keymap.set("n", "<Leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })
			-- go to peek definition
		end,
	},
})
```

I wanna to be able to "import" (I'm not sure if import is the correct word) my key mapping already defined in my lspconfig file into the rust-tools. I just wanna to use this mapping into .rs files.

**Comment by kylo252** [comment]
> _Note_: copying and pasting the lspconfig lines into the rust-tools file the problem is solved, but I was wondering for a better way to do it

@nhussein11, call the original `on_attach` as well



```lua
local rt = require("rust-tools")

rt.setup({
	server = {
		on_attach = function(client, bufnr)
			-- Add common options
            require("lvim.lsp").common_on_attach(client, bufnr)
			-- Add rust-tools specific logic
			-- ...
		end,
	},
})
```
