### ISSUE TITLE
[Feature]: Where applicable, provide some default formatters and linters.

### ISSUE THREAD

**Issue by vlcinsky** [ChristianChiarulli/LunarVim#1225]
### Feature motivation

The LunarVim concept is to serve out of the box.

Current configuration is missing formatters and linters for most of languages.

### Describe the expected solution

Where applicable, configure some generally used formatters and linters for each language.

This way user can get well configured editor from very first moment while having options to configure different formatters and linters.

### Describe the alternatives you've considered

I have formatters and linters for python configured in my (lv-)config.lua.

**Comment by ChristianChiarulli** [comment]
Our strategy is currently to support all formatters and linters but not prescribe them. It is too much of a burden to keep up with 50+ linters and 50+ formatters. Also there will inevitably be conflicts between user preference for the default options.
