### ISSUE TITLE
I need a logo

### ISSUE THREAD

**Issue by ChristianChiarulli** [ChristianChiarulli/LunarVim#131]
If someone could make me a NVCode logo that would be great. I'll keep submissions open for at least 3 months.

**Comment by gauthierc** [comment]
Something like this?
![nvcode-logo](https://user-images.githubusercontent.com/3176890/111065309-4bc5c300-84b9-11eb-86bd-37a2b433f99f.png)

**Comment by ChristianChiarulli** [comment]
@gauthierc Yea that's awesome! Just needs a 'V'.

**Comment by Binx-Codes** [comment]
![Chris NVCode Logo](https://user-images.githubusercontent.com/68950943/111263776-da644c80-863f-11eb-90b3-7de525e1eb3d.PNG)

Is this fine? If you need any improvements to this logo feel free to comment.

**Comment by gauthierc** [comment]
I proposed yesterday a pullRequest with the source in svg format and the image in png format with the 'V'.
Personally I prefer without the 'V' which is already present in the 'N' of the transformed NeoVim logo.
I also proposed another version with more color.
![nvcode-logo-blue-text](https://user-images.githubusercontent.com/3176890/111266159-6bc8c400-862a-11eb-955a-675cf4430cfd.png)

The second proposal is more original, but from my point of view, we find less the relation with NeoVim.

**Comment by weiss-d** [comment]
How about this hybrid? 🤔
![image](https://user-images.githubusercontent.com/62437174/112865856-db768e80-90c1-11eb-9981-b4a8a7c8f02c.png)

**Comment by weiss-d** [comment]
Or with an eye on @gauthierc's variant we can stick with the original Neovim logo, but in VSCode colors.
 @ChristianChiarulli 

![image](https://user-images.githubusercontent.com/62437174/113430724-4b975400-93e3-11eb-8168-37afde08050a.png)

**Comment by lemontghe** [comment]
![ok](https://user-images.githubusercontent.com/21209054/114312629-7fbbf480-9b08-11eb-8bdf-49d5f2a1d7ac.png)
jk

**Comment by weiss-d** [comment]
![image](https://user-images.githubusercontent.com/62437174/114314879-3027f980-9b05-11eb-8366-e16103484f66.png)
C-[

**Comment by alechp** [comment]
Should logo be LunarVim now instead of NVCode?

**Comment by weiss-d** [comment]
Hi @ChristianChiarulli! I'm glad you liked the meme 😊
The creative process is hard to stop, so I made a logo for the new name as well. Let me know if you'll need a refined SVGs.

![image](https://user-images.githubusercontent.com/62437174/115991392-cf9ebf00-a5d0-11eb-9b08-dcd8e5282b52.png)

**Comment by ChristianChiarulli** [comment]
I didn't see these until just now, I actually really like them @weiss-d.

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/123904721-f4037880-d93e-11eb-9f0c-b7d8e45e7b86.png)

Looks cool with colors too

**Comment by ChristianChiarulli** [comment]
Could someone remove the background as well of the original?

**Comment by weiss-d** [comment]
@ChristianChiarulli here they are. Feel free to DM me on Reddit if you need some further edits.

[LunarVim_logo__weiss-d.tar.gz](https://github.com/ChristianChiarulli/LunarVim/files/6741310/LunarVim_logo__weiss-d.tar.gz)

**Comment by luxus** [comment]
This could be closed @ChristianChiarulli

**Comment by rebuilt** [comment]
Logo created
