### ISSUE TITLE
unable to start --> E5113: Error while calling lua chunk

### ISSUE THREAD

**Issue by christophedh** [ChristianChiarulli/LunarVim#137]
hi i have this issue after the installation

```
E5113: Error while calling lua chunk: /home/christophe/.config/nvcode/init.l
 found:
        no field package.preload['plugins']
        no file './plugins.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.
        no file '/usr/local/share/lua/5.1/plugins.lua'
        no file '/usr/local/share/lua/5.1/plugins/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/plu
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/plu
        no file './plugins.so'
        no file '/usr/local/lib/lua/5.1/plugins.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/plugi
        no file '/usr/local/lib/lua/5.1/loadall.so'
```
on  Ubuntu 20.04.2 LTS
NVIM v0.5.0-dev+1152-gf5daf55c1
Lua 5.3.3

thanks :)

**Comment by fanmih** [comment]
This is exactly the same as issue #136 if I am not mistaken.

**Comment by en1tan** [comment]
this is still an issue

**Comment by Gxinhu** [comment]
I meet the same problem.

**Comment by barrydevp** [comment]
same here, any one has fixed this issue?

**Comment by K7esavan** [comment]
I'm also facing this issue

**Comment by gallatin1988** [comment]
I have this issue as well starting nvim. So far I have encountered when initializing treesitter, galaxyline, and telescope.

**Comment by en1tan** [comment]
the issue with this is the way lua files are being imported, seems the init.lua doesn't recognise the lua files in the lua folder
I tried setting the `package.path = package.path..';'..'/home/user/.config/nvcode/lua/?.init.lua` and while this seems to work some ways, its not working for single lua files in the lua folder

**Comment by en1tan** [comment]
so this is what I did and so far as of this writing it is working. move your nvim folder to old `mv ~/.config/nvim ~/.config/nvim.old` then clone the repo to replace `gh repo clone ChristianChiarulli/nvcode ~/.config/nvim`
start `nv`, it may colorscheme show error, press enter and type `:PackerSync` then allow it install packages then reopen `:qa` `nv`, it will start compiling again, that's all you need

![2021-03-22_15-32](https://user-images.githubusercontent.com/16443589/112006438-fd04d280-8b23-11eb-8441-0f40ed80250b.png)

**Comment by K7esavan** [comment]
I renamed nvim to nvim.old and install nvcode, then I opened the plugins.lua file under ~/.config/nvcode/lua 
after that I use the command :PackerInstall then I renamed the nvim.old to nvim 
Now it is working fine
