### ISSUE TITLE
Auto Install script

### ISSUE THREAD

**Issue by ChristianChiarulli** [ChristianChiarulli/LunarVim#147]
If anyone wants to tackle doing this I would appreciate it!

**Comment by mohammedzeglam-pg** [comment]
local packer = nil
local function init()
  if packer == nil then
    packer = require('packer')
    packer.init({disable_commands = true})
  end

  local use = packer.use
  packer.reset()

  --Packer with optional plugin
  use {'wbthomason/packer.nvim', opt = true}

  --LSP
  use 'neovim/nvim-lspconfig'
  use 'glepnir/lspsaga.nvim'
  use 'onsails/lspkind-nvim'
  use 'kosayoda/nvim-lightbulb'
  --Icons
  use 'kyazdani42/nvim-web-devicons'
  use 'ryanoasis/vim-devicons'
  -- Treesitter
  use {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'}
  use 'nvim-treesitter/playground'
  use 'p00f/nvim-ts-rainbow'
  --Explorer
  use 'kyazdani42/nvim-tree.lua'

  -- General Plugins
  use 'windwp/nvim-autopairs'
  use 'akinsho/nvim-bufferline.lua'
  use '907th/vim-auto-save'
  -- Autocomplete
  use 'hrsh7th/nvim-compe'
  use 'hrsh7th/vim-vsnip'
  use 'hrsh7th/vim-vsnip-integ'
  use 'honza/vim-snippets'

  -- Telescope
  use 'nvim-lua/popup.nvim'
  use 'nvim-lua/plenary.nvim'
  use 'nvim-telescope/telescope.nvim'
  use 'nvim-telescope/telescope-media-files.nvim'
  --Formatter
  use 'sbdchd/neoformat'

  --Color
  use 'chriskempson/base16-vim'
  -- Status Line and Bufferline
  use 'glepnir/galaxyline.nvim'
  -- use {'akinsho/nvim-bufferline.lua', requires = 'kyazdani42/nvim-web-devicons'}
--  use 'romgrk/barbar.nvim'
    -- Git
    use 'TimUntersberger/neogit'
    use {'lewis6991/gitsigns.nvim', requires = {'nvim-lua/plenary.nvim'}}
    use 'f-person/git-blame.nvim'
    use 'tpope/vim-fugitive'
    use 'tpope/vim-rhubarb'

    -- Easily Create Gists
    use 'mattn/vim-gist'
    use 'mattn/webapi-vim'

    -- General Plugins
    use 'windwp/nvim-autopairs'
    use 'kevinhwang91/nvim-bqf'
    use 'unblevable/quick-scope'
    use 'airblade/vim-rooter'
    use 'kevinhwang91/rnvimr'
    use 'mhinz/vim-startify'
    use 'metakirby5/codi.vim'
    use 'psliwka/vim-smoothie'
    use {'iamcco/markdown-preview.nvim', run = 'cd app && npm install'}
    use 'moll/vim-bbye'
    use 'turbio/bracey.vim'
    use 'AndrewRadev/tagalong.vim'
    use 'alvan/vim-closetag'
    use 'liuchengxu/vim-which-key'
    use 'voldikss/vim-floaterm'
    use 'liuchengxu/vista.vim'
    use 'terrortylor/nvim-comment'
    use 'bfredl/nvim-miniyank'
    use 'junegunn/goyo.vim'
    use 'andymass/vim-matchup'
    use 'phaazon/hop.nvim'
    use 'gennaro-tedesco/nvim-jqx'
    use 'Yggdroot/indentLine'
		use 'tpope/vim-sleuth'
end
local plugins = setmetatable({}, {
 __index = function(_, key)
    init()
    return packer[key]
  end
})

return plugins

**Comment by mohammedzeglam-pg** [comment]
> If anyone wants to tackle doing this I would appreciate it!

hi you can fix issue of packer with different approach like the approach of the packer maker it is in dotfiles in his repo

**Comment by ChristianChiarulli** [comment]
I'll check that out

**Comment by mohammedzeglam-pg** [comment]
> I'll check that out
local packer = nil
local function init()
  if packer == nil then
    packer = require('packer')
    packer.init({disable_commands = true})
  end

  local use = packer.use
  packer.reset()

  --Packer with optional plugin
  use {'wbthomason/packer.nvim', opt = true}

-- LSP
    use 'neovim/nvim-lspconfig'
    use 'glepnir/lspsaga.nvim'
    use 'onsails/lspkind-nvim'
    use 'kosayoda/nvim-lightbulb'
    use 'mfussenegger/nvim-jdtls'

    -- Debugging
    use 'mfussenegger/nvim-dap'

    -- Autocomplete
    use 'hrsh7th/nvim-compe'
    use 'hrsh7th/vim-vsnip'
    use 'hrsh7th/vim-vsnip-integ'
    use 'honza/vim-snippets'
    -- use 'epilande/vim-react-snippets'
    -- use 'xabikos/vscode-javascript'
    -- use 'cstrap/python-snippets'
    -- use 'ylcnfrht/vscode-python-snippet-pack'
    -- use 'golang/vscode-go'
    -- use 'rust-lang/vscode-rust'
    -- use 'SirVer/ultisnips'
    -- use 'norcalli/snippets.nvim'
    -- Treesitter

    use {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'}
    use 'nvim-treesitter/nvim-treesitter-refactor'
    use 'nvim-treesitter/playground'
    use 'p00f/nvim-ts-rainbow'

    -- Icons
    use 'kyazdani42/nvim-web-devicons'
    use 'ryanoasis/vim-devicons'

    -- Status Line and Bufferline
    use 'glepnir/galaxyline.nvim'
    -- use {'akinsho/nvim-bufferline.lua', requires = 'kyazdani42/nvim-web-devicons'}
    use 'romgrk/barbar.nvim'

    -- Telescope
    use 'nvim-lua/popup.nvim'
    use 'nvim-lua/plenary.nvim'
    use 'nvim-telescope/telescope.nvim'
    use 'nvim-telescope/telescope-media-files.nvim'

    -- Explorer
    use 'kyazdani42/nvim-tree.lua'

    -- Color
    use 'christianchiarulli/nvcode-color-schemes.vim'
    use 'norcalli/nvim-colorizer.lua'
    use {"chriskempson/base16-vim"}
    -- Git
    use 'TimUntersberger/neogit'
    use {'lewis6991/gitsigns.nvim', requires = {'nvim-lua/plenary.nvim'}}
    use 'f-person/git-blame.nvim'
    use 'tpope/vim-fugitive'
    use 'tpope/vim-rhubarb'

    -- Easily Create Gists
    use 'mattn/vim-gist'
    use 'mattn/webapi-vim'

    -- General Plugins
    use 'windwp/nvim-autopairs'
    use 'kevinhwang91/nvim-bqf'
    use 'unblevable/quick-scope'
    use 'airblade/vim-rooter'
    use 'kevinhwang91/rnvimr'
    use 'mhinz/vim-startify'
    use 'metakirby5/codi.vim'
    use 'psliwka/vim-smoothie'
    use {'iamcco/markdown-preview.nvim', run = 'cd app && npm install'}
    use 'moll/vim-bbye'
    use 'turbio/bracey.vim'
    use 'AndrewRadev/tagalong.vim'
    use 'alvan/vim-closetag'
    use 'liuchengxu/vim-which-key'
    use 'voldikss/vim-floaterm'
    use 'liuchengxu/vista.vim'
    use 'terrortylor/nvim-comment'
    use 'bfredl/nvim-miniyank'
    use 'junegunn/goyo.vim'
    use 'andymass/vim-matchup'
    use 'phaazon/hop.nvim'
    use 'gennaro-tedesco/nvim-jqx'
    use '907th/vim-auto-save'
	-- TODO put this back when stable for indent lines
-- 	use { 'lukas-reineke/indent-blankline.nvim', branch = 'lua'}
-- 	vim.g.indent_blankline_space_char = ' '
-- 	vim.g.indent_blankline_buftype_exclude = {'terminal'}
-- 	vim.g.indent_blankline_filetype_exclude = {'help', 'startify'}
-- 	vim.g.indent_blankline_char = '▏'
-- 	vim.g.indent_blankline_use_treesitter=true
    -- use 'RRethy/vim-illuminate'
    -- use 'b3nj5m1n/kommentary'
    use 'tpope/vim-sleuth'
end
local plugins = setmetatable({}, {
 __index = function(_, key)
    init()
    return packer[key]
  end
})

return plugins

**Comment by mohammedzeglam-pg** [comment]
vim.cmd [[command! PackerInstall packadd packer.nvim | lua require('plugins').install()]]
vim.cmd [[command! PackerUpdate packadd packer.nvim | lua require('plugins').update()]]
vim.cmd [[command! PackerSync packadd packer.nvim | lua require('plugins').sync()]]
vim.cmd [[command! PackerClean packadd packer.nvim | lua require('plugins').clean()]]
vim.cmd [[command! PackerCompile packadd packer.nvim | lua require('plugins').compile()]]

**Comment by mohammedzeglam-pg** [comment]
> I'll check that out

delete my comments if get that
