### ISSUE TITLE
Global markdownlint

### ISSUE THREAD

**Issue by dylantjb** [ChristianChiarulli/LunarVim#158]
You might be looking for markdownlint-cli or markdowncli-cli2. The latter is configuration based and supposedly faster.

https://github.com/igorshubovych/markdownlint-cli

https://github.com/DavidAnson/markdownlint-cli2

**Comment by jvaverka** [comment]
Hitting a snag on this issue. Seems like this functionality requires something heavy like [coc](https://github.com/fannheyward/coc-markdownlint), [efm](https://github.com/mattn/efm-langserver#supported-lint-tools), [ale](https://www.rockyourcode.com/lint-your-markdown-files-in-vim/), etc. which I am pretty sure we want to avoid.

Is there a simpler way to just attach markdownlint-cli to neovim's native tooling? Reading through neovim documentation, but the answer isn't obvious to me yet. Anyone have any thoughts?

**Comment by abzcoding** [comment]
you can now use `markdownlint` through `null-ls`

**Comment by abzcoding** [comment]
<img width="1664" alt="Screen Shot 2021-08-04 at 6 43 24 PM" src="https://user-images.githubusercontent.com/10992695/128196558-e2292ad3-1dcc-4f1e-9242-18551dd85c68.png">

**Comment by jvaverka** [comment]
@abzcoding - probably just my lack of null-ls knowledge, but how is this achieved?

I am investigating your config files, and I see that you set the linter in [ftplugin](https://github.com/abzcoding/lvim/blob/main/ftplugin/markdown.lua). Is there an additional step?

**Comment by abzcoding** [comment]
@jvaverka 
basically, you need a language server that supports `markdown` and after that, you can use it
you can do it like this ( you don't need the `ftplugin` part)
```lua
lvim.lang.markdown = {
  formatters = { { exe = "prettier" } },
  linters = { { exe = "markdownlint" } },
}
lvim.builtin.lspinstall.on_config_done = function()
  lvim.lang.tailwindcss.lsp.setup.filetypes = { "markdown" }
  lvim.lang.tailwindcss.lsp.active = true
  require("lsp").setup "tailwindcss"
end
```
also make sure that you are on `rolling`

**Comment by jvaverka** [comment]
This works beautifully. Thanks, @abzcoding!
