### ISSUE TITLE
user config shoud be load at last

### ISSUE THREAD

**Issue by wuhanhui** [ChristianChiarulli/LunarVim#184]
There is a user config file **nv-settings.lua**. This file should load at last in file **init.lua** to make sure we can overwrite some default config

**Comment by ChristianChiarulli** [comment]
Good point, I forget why I moved it up 🤔

**Comment by wuhanhui** [comment]
Maybe some of the options should load before some plugins? I am not sure about that.

**Comment by ChristianChiarulli** [comment]
right, are you experiencing issues with placement?

**Comment by wuhanhui** [comment]
Yes, for example, I want to replace some language server executable path.
I add some blew in the settings
``` lua
require'lspconfig'.clangd.setup {
    cmd = {"clangd-10"},
    on_attach = require'lsp'.common_on_attach
}
```
But it still uses the default path. Then I move nv-settings to last. It works. So maybe it is better to add an empty user-nvsettings.lua to the last to avoid change nv-settings.lua position.

**Comment by ChristianChiarulli** [comment]
I still feel like this should load first. I just need to expose options for this, so that you don't have to edit the lspconfig.

**Comment by wuhanhui** [comment]
In my opinion, user config should handle some customer things like below
1. user key bindings
2. some options for default plugins (like the executable path or configuration)
3. add new plugins or choose to install part of default plugins.

Nvcode is really a nice and awesome repo for beginners to use neovim. But you can not make a configuration that satisfy everyone. So make a user configuration method just like [space-vim](https://github.com/liuchengxu/space-vim) with layer and user configuration file in the future, this may save you lots of work to deal with kinds of new feature requests. Meanwhile, you can focus on maintaining the main function of nvcode.

**Comment by gauthierc** [comment]
Indeed, the layers implemented in space-vim allow to activate the support of the languages we use only.
I also think that using this approach is the best solution.
