### ISSUE TITLE
Hi, guys i got this error after installing... anyone please point me to a solution. thanks

### ISSUE THREAD

**Issue by vinnielazio** [ChristianChiarulli/LunarVim#185]
tree-sitter CLI not found: `tree-sitter` is not executable!
tree-sitter CLI is needed because `gdscript` is marked that it needs to be generated from the grammar definitions to be compatible with nvim!
tree-sitter CLI not found: `tree-sitter` is not executable!
tree-sitter CLI is needed because `devicetree` is marked that it needs to be generated from the grammar definitions to be compatible with nvim!
tree-sitter CLI not found: `tree-sitter` is not executable!
tree-sitter CLI is needed because `nix` is marked that it needs to be generated from the grammar definitions to be compatible with nvim!
tree-sitter CLI not found: `tree-sitter` is not executable!
tree-sitter CLI is needed because `erlang` is marked that it needs to be generated from the grammar definitions to be compatible with nvim!
tree-sitter CLI not found: `tree-sitter` is not executable!
tree-sitter CLI is needed because `ocamllex` is marked that it needs to be generated from the grammar definitions to be compatible with nvim!
tree-sitter CLI not found: `tree-sitter` is not executable!
tree-sitter CLI is needed because `ledger` is marked that it needs to be generated from the grammar definitions to be compatible with nvim!
tree-sitter CLI not found: `tree-sitter` is not executable!
tree-sitter CLI is needed because `supercollider` is marked that it needs to be generated from the grammar definitions to be compatible with nvim!
tree-sitter CLI not found: `tree-sitter` is not executable!
tree-sitter CLI is needed because `swift` is marked that it needs to be generated from the grammar definitions to be compatible with nvim!

**Comment by jameswalmsley** [comment]
You need to install tree-sitter cli:

```
npm install -g tree-sitter-cli
```
