### ISSUE TITLE
Add Deno LSP

### ISSUE THREAD

**Issue by hemedani** [ChristianChiarulli/LunarVim#193]
It's added to [LspInstall](https://github.com/kabouzeid/nvim-lspinstall) so it can easily installed.
add some configuration to avoid conflict with tsserver something like vim `coc-settings.json` or vscode `settings.json` file with these details :
```
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true
}
```
and maybe add some `which-key` for `DenolsCache`. [this is the denols configuration](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#denols)

**Comment by ChristianChiarulli** [comment]
Hopefully someone considers putting a PR in soon, I'll gladly accept it.

**Comment by eduardjbotha** [comment]
Hey @ChristianChiarulli, this is my first PR attempt on Github, so please bear with me.
From what I can gather, the steps are

1. clone the repo
2. create a new branch
3. make the change
4. push the branch
5. click "Create Pull Request" in the browser

I'm stuck at point 4 with a 403. Is this the correct approach?
If so, could you grant me the necessary rights, so that I can create the PR?

**Comment by abzcoding** [comment]
you can use `deno` through `null-ls`
```lua
lvim.lang.javascript.formatters = {
  {
   -- can be prettier or prettierd or eslint or eslint_d or 
    exe = "deno_fmt",
    args = {},
  },
}
```

**Comment by jackmac92** [comment]
@abzcoding is that full deno lsp or just the formatting?

**Comment by abzcoding** [comment]
> @abzcoding is that full deno lsp or just the formatting?

just formatting i assume, but you can use the deno ls as well, wait a bit ...

**Comment by abzcoding** [comment]
ok so you need sth like this in your `config.lua`
```lua
lvim.builtin.lspinstall.on_config_done = function()
  lvim.builtin.rooter.active = false
  lvim.lang.javascript.lsp = {
    provider = "denols",
    setup = {
      cmd = {
        DATA_PATH .. "/lspinstall/deno/bin/deno",
        "lsp",
      },
      filetypes = { "javascript", "javascriptreact", "javascript.jsx", "typescript", "typescriptreact", "typescript.tsx" },
      init_options = {
        enable = true,
        lint = false,
        unstable = false,
      },
      root_dir = require("lspconfig").util.root_pattern("package.json", "tsconfig.json", ".git"),
      on_attach = require("lsp").common_on_attach,
      on_init = require("lsp").common_on_init,
      capabilities = require("lsp").common_capabilities(),
    },
  }
  require("lsp").setup "javascript"
end
```

**Comment by terenced** [comment]
@abzcoding the snippet you provided does not see to work

**Comment by abzcoding** [comment]
> @abzcoding the snippet you provided does not see to work

that is from 29 days ago 😢, can you hop on discord or create a new issue for it?

**Comment by abzcoding** [comment]
@terenced you can test this instead
```lua
lvim.lang.javascript.lsp = {
  provider = "denols",
  setup = {
    cmd = {
      DATA_PATH .. "/lspinstall/deno/bin/deno",
      "lsp",
    },
    filetypes = { "javascript", "javascriptreact", "javascript.jsx", "typescript", "typescriptreact", "typescript.tsx" },
    init_options = {
      enable = true,
      lint = false,
      unstable = false,
    },
    root_dir = require("lspconfig").util.root_pattern("package.json", "tsconfig.json", ".git"),
  },
}
```

**Comment by terenced** [comment]
I managed to get it working with this config.

The trick we was to get `root_dir` to look for `mod.ts`. Deno projects do not have a `package.json`.

```
lvim.lang.javascript.lsp = {
  provider = "denols",
  setup = {
    cmd = {
      DATA_PATH .. "/lspinstall/deno/bin/deno",
      "lsp",
    },
    filetypes = { "typescript", "typescriptreact", "typescript.tsx" },
    init_options = {
      enable = true,
      lint = false,
      unstable = false,
    },
    root_dir = require("lspconfig").util.root_pattern("mod.ts", ".git"),
  },
}
```

**Comment by seanaye** [comment]
@terenced this still doesn't work for me, despite having both .git and mod.ts in my project and denols installed

**Comment by hemedani** [comment]
@seanaye use my configuration instead : [lesvim](https://github.com/MiaadTeam/lesvim)

**Comment by terenced** [comment]
@seanaye I switched mine to check for `import_map.json`
```
local isDeno = require("lspconfig/util").root_pattern("import_map.json")
if isDeno() then
  lvim.lang.typescript.lsp = {
    provider = "denols",
    setup = {
      cmd = {
        DATA_PATH .. "/lspinstall/deno/bin/deno",
        "lsp",
      },
      filetypes = { "javascript","javascriptreact", "typescript", "typescriptreact", "typescript.tsx" },
      init_options = {
        enable = true,
        lint = false,
        unstable = false,
        importMap = './import_map.json',
      },
      root_dir = require("lspconfig").util.root_pattern("mod.ts", ".git"),
    },
  }
end
```

**Comment by sigmaSd** [comment]
the above methods doesn't work any more since lvim.lang is no longer supported https://github.com/LunarVim/LunarVim/blob/3de829e76ed3d90b25250b1ab76f6425146af9d2/README.md#breaking-changes
