### ISSUE TITLE
Buffer tabs don't show up on :e and session restore

### ISSUE THREAD

**Issue by weiss-d** [ChristianChiarulli/LunarVim#195]
Buffer tabs on the top of the window (don't know how to call them properly) don't show up when I restore session with `SCP-S-l`
or when I open a file with `:e` from the dashboard. When I use `:e` after some files already have been opened with Explorer or Ranger, everything is Ok.

**Comment by fanmih** [comment]
Same issue here. Tabs do not show up when you open files or restore session from Dashboard. If one starts with a file loaded `> nvim myfile` and then restore the session then everything shows up in tabs as it should.

**Comment by VitFL** [comment]
Issue still remains ) If restore session via SessionLoad or "Load Last Session" from Dashboard - session is loaded, but there is no tabs... however it is possible to switch between buffers using "Tab" key.

Anyone found a solution?

**Comment by rebuilt** [comment]
I just looked in to this for you.  There's something weird going on with the dashboard screen.  I you load a session without the default dashboard home screen, the tabs show up correctly.  So if your goal is just to load the last session and you want tabs to show up:

```bash
nvim anonymousBuffer  #  The file name can be anything you want since it never gets saved and will be lost immediately when you load a session
```

This isn't a solution but I'll open an issue on the Dashboard project about it and see what they say.

**Comment by rebuilt** [comment]
https://github.com/glepnir/dashboard-nvim/issues/76
