### ISSUE TITLE
PackerInstall is not a editor command

### ISSUE THREAD

**Issue by jilvanx** [ChristianChiarulli/LunarVim#198]
I had a issue:
I ran the command:
`bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/nvim/master/utils/installer/install.sh)`

![2021-03-30_16-52](https://user-images.githubusercontent.com/5150533/113048478-f5bf7380-9178-11eb-82e3-c74d043f67fa.png)

After that I opened 'nvim' and I can't execute `:PackerInstall` 
![2021-03-30_16-53](https://user-images.githubusercontent.com/5150533/113048733-3c14d280-9179-11eb-82e1-1d563c32bf8e.png)

What's going on ?

**Comment by ChristianChiarulli** [comment]
Not sure, is the packer repo in your start directory?

**Comment by Khwarazmi** [comment]
I ran the script without any problems, how ever when i try packerinstall i'm getting the same error
Not an editor command: PackerInstall

**Comment by smikeblog** [comment]
IMO is better to remove function installpacker() from install script and install it from /lua/plugins.lua file to avoid surprises

**Comment by jilvanx** [comment]
> Not sure, is the packer repo in your start directory?

~/.local/share/nvim/site/pack/packer/start/packer.nvim

**Comment by jilvanx** [comment]
> I ran the script without any problems, how ever when i try packerinstall i'm getting the same error
> Not an editor command: PackerInstall

**Comment by weiss-d** [comment]
Had the same problem.
Have manually deleted `~/.cache/nvim` and `~/.local/share/nvim` folders which seemed to contain some stuff from previous config installation (SpaceVim). Then reinstalled Neovim and it worked. Cannot say that both steps are necessary, but I didn't check in between :]

**Comment by ChristianChiarulli** [comment]
This will hopefully be fixed when the new install script lands. Bear with me on this for a little while.

**Comment by smikeblog** [comment]
> This will hopefully be fixed when the new install script lands. Bear with me on this for a little while.

IMO not many users will agree to install smth using sudo command. Cn alternative maybt to use several scripts as in Arco Linux 001-installglobal-sudo-pkgs.sh; 002-compileNvimFromGit.sh; 003-installPacker&pkgs.sh ...

**Comment by jameswalmsley** [comment]
> > This will hopefully be fixed when the new install script lands. Bear with me on this for a little while.
> 
> IMO not many users will agree to install smth using sudo command. An alternative maybe to use several scripts as in Arco Linux install 001-installglobal-sudo-pkgs.sh; 002-compileNvimFromGit.sh; 003-installPacker&pkgs.sh ...
> And user can install from 2 or 3 or only config

Most software is installed using sudo if you want it to be globally installed for all users on the system.

For users who don't want to do that, we can support 2 options:

1. Installing everything into ~/.local (the same as a global install but for a single user).
2. The user can clone and use the nvcode configuration as their primary nvim configuration.

**Comment by Khwarazmi** [comment]
Error detected while processing /usr/local/share/nvcode/nvim/utils/init.lua: from james script

**Comment by ChristianChiarulli** [comment]
I don't think it requires sudo anymore... but we'll see where it goes,
could still be a little bit until this is fully implemented tho.

**Comment by jameswalmsley** [comment]
@Khwarazmi Can you post a screen-shot of the error you have:
(Move this to issue #180)

Then I can find out whats wrong and help you.

Also which system are you using? (Arch / Ubuntu etc)

**Comment by smikeblog** [comment]
> Most software is installed using sudo if you want it to be globally installed for all users on the system.

Agree but not configs and not in /usr/binI IMO. /opt is for Optional things.

**Comment by joaop-oliveira1** [comment]
Make sure you're running the latest version of Neovim from the [nightly release](https://github.com/neovim/neovim/releases).
if you are on linux download the .appimage, in my humble opinion is the best one, Packer commands seems to come built-in in neovim v0.5.0-dev.

Hope I helped in some way!

**Comment by realkelvinperez** [comment]
> Had the same problem.
> Have manually deleted `~/.cache/nvim` and `~/.local/share/nvim` folders which seemed to contain some stuff from previous config installation (SpaceVim). Then reinstalled Neovim and it worked. Cannot say that both steps are necessary, cause I didn't check in between :]

I can confirm that this worked for me on MacOs

**Comment by jjablonski-it** [comment]
I'm having the same issue and cleaning `cache` and `local` is not working for me.

**Comment by lgberro** [comment]
Had the same problem with macOS Big Sur. Solved uninstalling neovim and installing the development version
```
brew install --HEAD luajit
brew install --HEAD neovim
```
And cleaning up with https://github.com/ChristianChiarulli/nvcode/issues/198#issuecomment-811658134

After that I faced the `module 'galaxyline' not found` problem, solved with https://github.com/ChristianChiarulli/nvcode/issues/236#issuecomment-813410492

Finally the `:PackerInstall` run flawlessly :)

**Comment by GuilhermeVBeira** [comment]
For me works removing the old cache
`rm -rf ~/.local/share/lunarvim`
