### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fiduchi** [ChristianChiarulli/LunarVim#236]
E5113: Error while calling lua chunk: ...e/nvim/site/pack/packer/start/packer.nvim/l
ua/packer.lua:495: /home/sm/.config/nvim/lua/nv-galaxyline/init.lua:1: module 'galax
yline' not found:
        no field package.preload['galaxyline']
        no file './galaxyline.lua'
        no file '/usr/share/luajit-2.0.5/galaxyline.lua'
        no file '/usr/local/share/lua/5.1/galaxyline.lua'
        no file '/usr/local/share/lua/5.1/galaxyline/init.lua'
        no file '/usr/share/lua/5.1/galaxyline.lua'
        no file '/usr/share/lua/5.1/galaxyline/init.lua'
        no file './galaxyline.so'
        no file '/usr/local/lib/lua/5.1/galaxyline.so'
        no file '/usr/lib/lua/5.1/galaxyline.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
Нажмите ENTER или введите команду для продолжения

**Comment by rt3norio** [comment]
Same here

**Comment by fiduchi** [comment]
E5113: Error while calling lua chunk: ...im/site/pack/packer/start/gitsigns.nvim/lua
/gitsigns.lua:1: module 'plenary/async_lib/async' not found:
        no field package.preload['plenary/async_lib/async']
        no file './plenary/async_lib/async.lua'
        no file '/usr/share/luajit-2.0.5/plenary/async_lib/async.lua'
        no file '/usr/local/share/lua/5.1/plenary/async_lib/async.lua'
        no file '/usr/local/share/lua/5.1/plenary/async_lib/async/init.lua'
        no file '/usr/share/lua/5.1/plenary/async_lib/async.lua'
        no file '/usr/share/lua/5.1/plenary/async_lib/async/init.lua'
        no file './plenary/async_lib/async.so'
        no file '/usr/local/lib/lua/5.1/plenary/async_lib/async.so'
        no file '/usr/lib/lua/5.1/plenary/async_lib/async.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
Нажмите ENTER или введите команду для продолжения

**Comment by laughing-stock** [comment]
Cloning the repo of galaxyline into .local/share/nvim/site/pack/packer/start fixed the 'module not found' issue for me.
