### ISSUE TITLE
Formatting does not work in python

### ISSUE THREAD

**Issue by Alex-crypto-tech** [ChristianChiarulli/LunarVim#239]
I have installed both efm and python language-server. Still, the code formatting(automatic tabs and spaces) does not work.
Also, there is a weird error that comes every time I work with .py file.
" Error detected while processing BufWritePre Autocommands for "*.py":
Error5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp.lua: 1155: table index is null"

Kindly help!

**Comment by daniel-bray** [comment]
Does anything in this thread help you?

https://github.com/ChristianChiarulli/nvcode/issues/224

**Comment by Alex-crypto-tech** [comment]
> Does anything in this thread help you?
> 
> #224

Actually I wanted auto indentation and spaces while writing the python file.
I think neoformat beautifies the code but I don't think it does something like auto-indent/ automatic tabs.

**Comment by laughing-stock** [comment]
I guess your issue is with auto indent.
Check out #181

**Comment by weiss-d** [comment]
> I guess your issue is with auto indent.
> Check out #181

Yep, that's still the issue. Formatting totally doesn't work in newly created files, though sometimes it starts working in some random places in old files (I cannot find out the regularity so far).

**Comment by rebuilt** [comment]
Maybe you can try disabling polyglot?  As per this thread:  https://www.reddit.com/r/neovim/comments/mmm4fd/word_of_advice_if_using_neovim_treesitter_then/

**Comment by weiss-d** [comment]
> Maybe you can try disabling polyglot? As per this thread: https://www.reddit.com/r/neovim/comments/mmm4fd/word_of_advice_if_using_neovim_treesitter_then/

I've commented `use 'sheerun/vim-polyglot'` in `lua/plugins.lua` and run `:PackerUpdate` which have deleted the `polyglot`. This doesn't help.

**Comment by rebuilt** [comment]
The error ' " Error detected while processing BufWritePre Autocommands for "*.py":'  probably means efm is not attached to the current buffer.  

What is the output of :LspInfo  ?  Is efm attached?   Efm finds the root by looking for a top level .git folder.  Are you in a git repository?  If not 
```bash
git init
```

Python is set up to run linting. But the linting isn't done by the python language server. It's done by efm. And in this case efm isn't set up correctly. So every time you save a file efm tries and fails to lint it.

**Comment by rebuilt** [comment]
What's the output of :LspInfo?

**Comment by rebuilt** [comment]
Also check your efm configuration file.  
You should have something like this in there.

  local tsserver_args = {prettier, eslint}

**Comment by weiss-d** [comment]
My `:LspInfo` output:

![image](https://user-images.githubusercontent.com/62437174/115999795-e1df2400-a5f5-11eb-95c4-71360ffec8fd.png)

The `lsp.log` contains this after running Nvim with the empty Python file as an argument:
```
[ START ] 2021-04-25T18:43:07+0300 ] LSP logging initiated
[ WARN ] 2021-04-25T18:43:08+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ WARN ] 2021-04-25T18:43:08+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:412 ]	"stubPath /tmp/typings is not a valid directory."
[ ERROR ] 2021-04-25T18:43:08+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:410 ]	"Exception received when installing recursive file system watcher"
```

**Comment by rebuilt** [comment]
Efm is not getting attached to the current buffer.  Efm provides linting.  Efm is only configured to work inside a git repository.  You have to make sure 'identfied root' finds the top level .git folder.

**Comment by rebuilt** [comment]
Make sure you :PackerUpdate because new logic was added in lspconfig for root detection

**Comment by weiss-d** [comment]
> Make sure you :PackerUpdate because new logic was added in lspconfig for root detection

I've just pulled the recent changes, ran `:PackerUpdate`, opened a file from Git repository, neither of these helped :disappointed: 

![image](https://user-images.githubusercontent.com/62437174/116001100-90399800-a5fb-11eb-8c6b-909896360aaa.png)

The error in `lsp.log` is still the same.

**Comment by rebuilt** [comment]
You've made progress.  It's now identifying the root.  
What's the output of 
```bash
:LspStart efm
```

If the message is too long and get cut off read it with 
```bash
:messages
```

**Comment by weiss-d** [comment]
> You've made progress. It's now identifying the root.
> What's the output of
> 
> ```shell
> :LspStart efm
> ```

![image](https://user-images.githubusercontent.com/62437174/116003649-84ec6980-a607-11eb-95d0-81c946bb39b7.png)

**Comment by rebuilt** [comment]
Someone else reported they had to cd into a .git folder for efm to match a root directory.  Like literally 'cd .git' and try from there.

**Comment by weiss-d** [comment]
> Someone else reported they had to cd into a .git folder for efm to match a root directory. Like literally 'cd .git' and try from there.

Now `LspStart efm` goes without errors, but this doesn't help the auoformatting.

**Comment by rebuilt** [comment]
If all else fails and you still want formatting, try https://github.com/sbdchd/neoformat.  Maybe someone else will have other ideas to fix it but I'm tapped out.

**Comment by rebuilt** [comment]
The other user updated his neovim-git aur package today which seemed to fix the issue

**Comment by weiss-d** [comment]
Nothing has changed for me after this update. Tried on Hash (Arch) with `neovim-nighty-git` package as well as on Ubuntu compiling it manually.
It must be a severe bug or misconfig, because bare Vim has no problem with Python autoformatting out of the box, so this behaviour looks just weird.

**Comment by rebuilt** [comment]
There are a few configs that have to be in place for completion to work.  Check that this code exists in these places:

lv-settings.lua
```bash
O.python.formatter = 'yapf'
O.python.autoformat = true
```

lua/lv-autocommands/init.lua
```bash
local python_autoformat = {'BufWritePre', '*.py', 'lua vim.lsp.buf.formatting_sync(nil, 1000)'}
if O.python.autoformat then table.insert(auto_formatters, python_autoformat) end
```

Python must be in the list of filetypes and python_arguments must be set
lua/lsp/efm-general-ls.lua
```bash
require"lspconfig".efm.setup {
    -- init_options = {initializationOptions},
    cmd = {DATA_PATH .. "/lspinstall/efm/efm-langserver"},
    init_options = {documentFormatting = true, codeAction = false},
    filetypes = {"lua", "python", "javascriptreact", "javascript", "typescript", "sh", "html", "css", "json", "yaml", "markdown", "vue"},
    settings = {
        rootMarkers = {".git/"},
        languages = {
            python = python_arguments,
            lua = lua_arguments,
            sh = sh_arguments,
            javascript = tsserver_args,
            javascriptreact = tsserver_args,
			typescript = {eslint,prettier},
            html = {prettier},
            css = {prettier},
            json = {prettier},
            yaml = {prettier},
            markdown = {markdownPandocFormat}
            -- javascriptreact = {prettier, eslint},
            -- javascript = {prettier, eslint},
            -- markdown = {markdownPandocFormat, markdownlint},
        }
    }
}
```
