### ISSUE TITLE
GalaxyLine issue with global-install

### ISSUE THREAD

**Issue by jameswalmsley** [ChristianChiarulli/LunarVim#244]
Hi Chris

```
use { 'glepnir/galaxyline.nvim', config = my('nv-galaxyline') }
-- use { 'glepnir/galaxyline.nvim', config = function() require'nv-galaxyline' end } -- inline fn alternative
```

Why did you leave the inline fn alternative there? (Guessing you saw some issue?)
This works with my local config, by when testing the global install, I have to switch to the alternative or it doesn't work.

I can't understand why... it seems to be the same code to me.

Best

James

**Comment by jameswalmsley** [comment]
Seems this is the same issue also mentioned in #236

**Comment by Walkability** [comment]
@jameswalmsley Yes, I can only get packer to install galaxyline with the inline version.
