### ISSUE TITLE
Can you ad rust-tools.nvim in your config to enhance rust support? 

### ISSUE THREAD

**Issue by crucificados666** [ChristianChiarulli/LunarVim#251]

**Comment by en1tan** [comment]
it's already added
https://github.com/ChristianChiarulli/nvcode/blob/master/lua/lsp/rust-ls.lua

**Comment by crucificados666** [comment]
Yes I am in the know because of the standard rust-analyzer config. But I asked for adding the rust-tools.nvim plugin (https://github.com/simrat39/rust-tools.nvim) which adds extra functionality on top of rust-analyzer.

**Comment by en1tan** [comment]
oh alright then

**Comment by crucificados666** [comment]
top config anyhow!!!

**Comment by bob3000** [comment]
https://github.com/ChristianChiarulli/LunarVim/pull/448

**Comment by ChristianChiarulli** [comment]
we have this now
