### ISSUE TITLE
LSP Install

### ISSUE THREAD

**Issue by dagadbm** [ChristianChiarulli/LunarVim#254]
Hello!

Out of  all the lsp install plugins and so on  that exist your nvcode configuration  is actually  one of the best.

Have you considered creating a separate plugin to manage all of this crazy  world?
prettier/eslint/eslint_d and all other formatters/linters that I see you already implemented here?

I dont want to use nvcode (nothing personal). I just think the community really needs a centralized lsp install repo.
Is there  anyone thinking on doing this?

kabouz lspinstall wont add formatters/linters and some have tsserver integrated,  others dont have. Its all a huge mess.

**Comment by rafamadriz** [comment]
I agree with you, it's kinda of a mess, Not sure if he will do that, but it would be really awesome. I'd say that it is going to take around 1-2 years after 0.5 is released to have something like coc-nvim but using native lsp and written in lua. A tool that can install, configure and setup servers, linters and formatters is what I'm expecting the most. But it is going to take time to have something as complete as coc-nvim.
