### ISSUE TITLE
A few bugs with VScode integration

### ISSUE THREAD

**Issue by premell** [ChristianChiarulli/LunarVim#256]
1) when using the terminal in vscode the spacebar was still linked to whichkey, so that I had to use shift+spacebar even though the terminal had focus.
2) If you are in the explorer and use CTRL+H you open file searcher
3) I was unable to use the vim binding CTRL+F to page down, instead it opened the file searcher

**Comment by redmasters** [comment]
Same here. When in the terminal the spacebar trigger whichkey menu.

**Comment by filahf** [comment]
I have the same problem with whichkey triggering when it shouldn't. Have you been able to resolve this issue?

**Comment by rebuilt** [comment]
Chris replaced a vim version of whichkey with a lua version 8 hours ago.  Are you using this new version or the old?

**Comment by Wolowit** [comment]
edit this on keybindings.json work for me

>  "key": "space",
      "command": "whichkey.show",
      "when": "neovim.mode != 'insert' && !terminalFocus && !viewContainer.workbench.view.extensions.enabled"

**Comment by filahf** [comment]
Thanks to both of you. I'll try out the new lua version!

**Comment by premell** [comment]
Thank you Wolowit it worked! Had stopped using VScodium because of that problem. I feel like it should be the default behavior, maybe we should make a PR?

**Comment by rebuilt** [comment]
Yes.  Please make a pr.
