### ISSUE TITLE
Outdated AUR package in README

### ISSUE THREAD

**Issue by darioisthebest** [ChristianChiarulli/LunarVim#265]
In the README.md you have the instructions to install, but `neovim-nightly-git` is outdated, the latest update was on 2020-11-17 13:28, and the [neovim-nightly-git](https://aur.archlinux.org/packages/neovim-nightly-git/) will not work with nvim-treesitter, so please use `neovim-git`

Neovim git AUR: https://aur.archlinux.org/packages/neovim-git/

The last update of `neovim-git`was on 2021-03-06 10:42

**Comment by mozgwar** [comment]
neovim-nightly-git is a git package the version will be updated to the lastest nightly at build time

**Comment by darioisthebest** [comment]
yes, but I tried neovim-nightly and I can't get treesitter working and when I installed neovim-git treesitter works

**Comment by ChristianChiarulli** [comment]
hmm, I kind of always recommend building from source. Hopefully .5 will just release soon and we don't have to deal with all of the confusion.

**Comment by DanielPower** [comment]
From the pinned comment on `neovim-nightly-git`:

> The Neovim developers have been updating the nightly tag very inconsistently lately, so this package lags quite a bit behind HEAD. Currently, completion-nvim is broken due to it (https://github.com/nvim-lua/completion-nvim/issues/274).
> 
> If you experience any issues, you might want to switch to the better maintained and up-to-date neovim-git AUR package instead.

So perhaps it would be best to just update the README to recommend `neovim-git` instead.
