### ISSUE TITLE
Error detected while processing init.lua - WSL2

### ISSUE THREAD

**Issue by rsrini7** [ChristianChiarulli/LunarVim#268]
Is Lua issue or unicode issue ?

bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)
Installing LunarVim
pip installed, moving on...
node installed, moving on...
pynvim installed, moving on...
Cloning into '/home/rsrini/.local/share/nvim/site/pack/packer/start/packer.nvim'...
remote: Enumerating objects: 1925, done.
remote: Counting objects: 100% (225/225), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 1925 (delta 118), reused 195 (delta 100), pack-reused 1700
Receiving objects: 100% (1925/1925), 603.53 KiB | 3.57 MiB/s, done.

Error detected while processing /home/rsrini/.config/nvim/init.lua:
line    1:
E492: Not an editor command: require('plugins')
line    2:
E492: Not an editor command: require('lv-globals')
line    3:
E492: Not an editor command: require('lv-utils')
line    4:
E33: No previous substitute regular expression
line    5:
E492: Not an editor command: require('lv-autocommands')
line    6:
E492: Not an editor command: require('settings')
line    7:
E492: Not an editor command: require('keymappings')
line    8:
E492: Not an editor command: require('colorscheme')
line    9:
E492: Not an editor command: require('lv-galaxyline')
line   10:
E492: Not an editor command: require('lv-comment')
line   11:
E492: Not an editor command: require('lv-compe')
line   12:
E492: Not an editor command: require('lv-barbar')
line   13:
E492: Not an editor command: require('lv-dashboard')
line   14:
E492: Not an editor command: require('lv-telescope')
line   15:
E492: Not an editor command: require('lv-gitsigns')
line   16:
-- More --

**Comment by Cublibre** [comment]
I got this issue too, fixed it by building neovim from source then running the installer again.

**Comment by rsrini7** [comment]
Yes. Above issue is resolved when building from source . 

But, after :PackerInstall then :PackerStatus

Error executing vim.schedule lua callback: vim/shared.lua:396: t: expected table, got nil
stack traceback:
        vim/shared.lua:396: in function 'tbl_count'
        ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:273: in function 'cb'
        vim.lua:253: in function <vim.lua:253>

fine after :PackerClean :PackerCompile and then :PackerInstall , :PackerStatus   
Why few packers are not loaded by default ?

**Comment by boonkerz** [comment]
build from source does not help.

E5113: Error while calling lua chunk: /home/thomas/.config/nvim/lua/settings.lua:11: Vim:E492: Not an editor command:
Error detected while processing /usr/local/share/nvim/runtime/filetype.vim:
line    5:
E492: Not an editor command: ^M
line    7:
E15: Invalid expression: exists("did_load_filetypes")^M
line 2347:
E488: Trailing characters
line 2348:
E171: Missing :endif
Error detected while processing /usr/local/share/nvim/runtime/ftplugin.vim:
line    5:
E492: Not an editor command: ^M
line    6:
E15: Invalid expression: exists("did_load_ftplugin")^M
line   36:

**Comment by rebuilt** [comment]
@boonkerz Did you uninstall the old version of nvim?  Is it possible the system is still trying to use the old build?

**Comment by boonkerz** [comment]
yea is uninstalled.

➜  ~ nvim -v
NVIM v0.5.0-dev+1267-g7bf62ab02
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/thomas/neovim/build/config -I/home/thomas/neovim/src -I/home/thomas/neovim/.deps/usr/include -I/usr/include -I/home/thomas/neovim/build/src/nvim/auto -I/home/thomas/neovim/build/include
Compiled by thomas@DESKTOP-E17406D

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
➜  ~ whereis nvim
nvim: /usr/local/bin/nvim /usr/local/lib/nvim

**Comment by rebuilt** [comment]
@boonkerz  Are you also using WSL2?

**Comment by rebuilt** [comment]
#279

**Comment by borazan** [comment]
Solved by uninstalling neovim and neovim-runtime, then running:
cd ~
sudo rm -r neovim
git clone https://github.com/neovim/neovim
cd neovim
sudo make CMAKE_BUILD_TYPE=Release install
cd ~
sudo rm -r neovim
I then deleted the nvim file in .config and reinstalled lunarvim with the bash command, works perfectly

**Comment by wis** [comment]
Developers, I'd like to inform you that some versions  >= 0.5 do not parse init.lua files.
this was my neovim version: NVIM v0.5.0-771-g9280a69a6
and I got these errors that indicate to me neovim is trying to parse a vimL .vimrc file not a lua file:
some of the errors copied from the top:
```
Error detected while processing /home/x/.local/share/lunarvim/lvim/init.
lua:
line    1:
E492: Not an editor command: -- {{{ Bootstrap
line    2:
E492: Not an editor command: local home_dir = vim.loop.os_homedir()
"rtp:append(home_dir" [New]
Cannot open file "rtp:append(home_dir"
".." is a directory
""/.local/share/lunarvim/lvim")" [New DIRECTORY]
Cannot open file ""/.local/share/lunarvim/lvim")"
line    4:
E480: No match: opt
"rtp:remove(home_dir" [New]
Cannot open file "rtp:remove(home_dir"
".." is a directory
""/.local/share/nvim/site")" [New DIRECTORY]
Cannot open file ""/.local/share/nvim/site")"
line    6:
E480: No match: opt
"rtp:remove(home_dir" [New]
Cannot open file "rtp:remove(home_dir"
".." is a directory
""/.local/share/nvim/site/after")" [New DIRECTORY]
Cannot open file ""/.local/share/nvim/site/after")"
line    7:
E480: No match: opt
"rtp:prepend(home_dir" [New]
Cannot open file "rtp:prepend(home_dir"
".." is a directory
""/.local/share/lunarvim/site")" [New DIRECTORY]
Cannot open file ""/.local/share/lunarvim/site")"
line    8:
E480: No match: opt
"rtp:append(home_dir" [New]
Cannot open file "rtp:append(home_dir"
".." is a directory
""/.local/share/lunarvim/site/after")" [New DIRECTORY]
Cannot open file ""/.local/share/lunarvim/site/after")"
line    9:
```
I run Arch Linux, I installed this >= 0.5 version of neovim that according to Wiki should work and installed neovim-nightly version >= 0.6 and the same rolling release config installed with install.sh worked perfectly.
