### ISSUE TITLE
Not compatible with Neovide

### ISSUE THREAD

**Issue by vivichrist** [ChristianChiarulli/LunarVim#269]
> neivide
Ignored client type property: "methods"
Ignored client type property: "attributes"
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /(...)/build/pamac-build/neovide/src/neovide/CARGO/git/checkouts/skribo-3c422fce25a33836/a35c876/src/collection.rs:130:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: segmentation fault (core dumped)  neovide

**Comment by ChristianChiarulli** [comment]
hmm, I noticed the same thing, let me know if you find out what's causing the issue, I'll take a look too.

**Comment by vivichrist** [comment]
This could actually be an issue with Neovide. Each time I run `neovide` with the `RUST_BACKTRACE=full` environment variable there is a cycle of maybe 3-4 different errors.

**Comment by rebuilt** [comment]
I haven't had any trouble loading with neovide with either nvcode or lunarvim settings.  I've compiled both nvim and neovide(with yay installer).  Here are the versions: NVIM v0.5.0-dev+1263-ga129887c0  neovide-git 0.7.0.r3.ge1d8d40-1.  

@vivichrist  The error message you posted contains a suggested fix. 
```bash
sysctl dev.i915.perf_stream_paranoid=0
``` 
Run that command from terminal and see if anything changes.

**Comment by vivichrist** [comment]
I have the AUR packages for neovim-nightly-git and neovide-0.7.0-1
installed, so that is probably the reason.

**Comment by weiss-d** [comment]
I had something similar with neovim-nighty-git and neovide from AUR. Turned out that I needed to install a Vulkan driver for my graphic card.

**Comment by vivichrist** [comment]
I have hybrid graphics
