### ISSUE TITLE
Not working on POP_OS 20.04 

### ISSUE THREAD

**Issue by Burnsedia** [ChristianChiarulli/LunarVim#270]
I have tried to install LunarVim on PopOS 20.04, problem will not work on Ubuntu 20.04, PackerInstall and LSP not working for some reason.

**Comment by rebuilt** [comment]
It's hard to know where to start without some error messages.  

packer.nvim logs to stdpath(cache)/packer.nvim.log. Looking at this file is usually a good start if something isn't working as expected.  
The ex command :LspInfo will help you start debugging problems with LSP.
LSP server logs can be found at  ~/.cache/nvim/lsp.log
Are you on the lastest version of nvim?

**Comment by rebuilt** [comment]
Also, Chris released a video two hours ago showing how to install it.  https://youtu.be/Qm864kVxAss

**Comment by Burnsedia** [comment]
Thanks, for the information. I am very busy, sorry about the crap issue.

**Comment by Burnsedia** [comment]
rror detected while processing /home/overlord/.config/nvim/init.lua:
line    1:
E492: Not an editor command: require('plugins')
line    2:
E492: Not an editor command: require('lv-globals')
line    3:
E492: Not an editor command: require('lv-utils')
line    4:
E33: No previous substitute regular expression
line    5:
E492: Not an editor command: require('lv-autocommands')
line    6:
E492: Not an editor command: require('settings')
line    7:
E492: Not an editor command: require('keymappings')
line    8:
E492: Not an editor command: require('colorscheme')
line    9:
E492: Not an editor command: require('lv-galaxyline')
line   10:
E492: Not an editor command: require('lv-comment')
line   11:
E492: Not an editor command: require('lv-compe')
line   12:
E492: Not an editor command: require('lv-barbar')
line   13:
E492: Not an editor command: require('lv-dashboard')
line   14:
E492: Not an editor command: require('lv-telescope')
line   15:
E492: Not an editor command: require('lv-gitsigns')
line   16:
E492: Not an editor command: require('lv-nvimtree')
line   17:
E492: Not an editor command: require('lv-treesitter')
line   18:
E492: Not an editor command: require('lv-autopairs')
line   19:
E492: Not an editor command: require('lv-rnvimr')
line   21:
E492: Not an editor command: -- Which Key (Hope to replace with Lua plugin someday)
line   22:
E33: No previous substitute regular expression
line   23:
E33: No previous substitute regular expression
line   25:
E492: Not an editor command: -- LSP
line   26:
E492: Not an editor command: require('lsp')
line   27:
E492: Not an editor command: require('lsp.clangd')
line   28:
E492: Not an editor command: require('lsp.php-ls')
line   29:
E492: Not an editor command: require('lsp.dart-ls')
line   30:
E492: Not an editor command: require('lsp.lua-ls')
line   31:
E492: Not an editor command: require('lsp.bash-ls')
line   32:
E492: Not an editor command: require('lsp.go-ls')
line   33:
E492: Not an editor command: require('lsp.js-ts-ls')
line   34:
E492: Not an editor command: require('lsp.python-ls')
line   35:
E492: Not an editor command: require('lsp.rust-ls')
line   36:
E492: Not an editor command: require('lsp.json-ls')
line   37:
E492: Not an editor command: require('lsp.yaml-ls')
line   38:
E492: Not an editor command: require('lsp.terraform-ls')
line   39:
E492: Not an editor command: require('lsp.vim-ls')
line   40:
E492: Not an editor command: require('lsp.graphql-ls')
line   41:
E492: Not an editor command: require('lsp.docker-ls')
line   42:
E492: Not an editor command: require('lsp.html-ls')
line   43:
E492: Not an editor command: require('lsp.css-ls')
line   44:
E492: Not an editor command: require('lsp.emmet-ls')
line   45:
E492: Not an editor command: require('lsp.efm-general-ls')
line   46:
E492: Not an editor command: require('lsp.latex-ls')
line   47:
E492: Not an editor command: require('lsp.svelte-ls')
line   48:
E492: Not an editor command: require('lsp.tailwindcss-ls')
line   49:
E492: Not an editor command: require('lsp.ruby-ls')
line   50:
E492: Not an editor command: require('lsp.kotlin-ls')
Error detected while processing command line:
E492: Not an editor command: PackerInstall

**Comment by Burnsedia** [comment]
I can not find a deb packages for Packer neovim/vim plugin.

**Comment by rebuilt** [comment]
Packer is available [here](https://github.com/wbthomason/packer.nvim)

The way to install it is just to clone the git repository to your computer

```bash
git clone https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
```

Lsp requires version 0.5 of neovim.  
Make sure you go through the steps above to recompile a fresh version.  Anything packaged in the normal repositories will be version 0.4 and some users are reporting problems with the nightly builds of neovim.  

If something went wrong with the install it's probably a good idea to start fresh.
Remove the following directories

```bash
~/.config/nvim
~/.cache/nvim
~/.local/share/nvim
```

**Comment by rebuilt** [comment]
Back up any configurations you want to save from ~/.config/nvim before deleting it.

**Comment by Burnsedia** [comment]
I did, this is a fresh neovim install
on a fresh Linux install, but Unbuntu/PopOS is a pain, easy to install, hard to configure. 
I may just go back to arch or manjaro. sorry

**Comment by Burnsedia** [comment]
I still can not get it to work, I have the latest stable neovim 0.4.4 from the snap store, I can not get in to install from source, missing so many dependencies, is there a docker container for the build pipeline?

**Comment by rebuilt** [comment]
0.4 won't work.  You need neovim 0.5 to get the new features.  I've added sections to the readme.  Let me know if those new instructions work for you.  You're probably missing the build-essential package

**Comment by rebuilt** [comment]
Make sure to uninstall version 0.4

**Comment by Burnsedia** [comment]
I got it uninstalled, I got it working now, I think

**Comment by rebuilt** [comment]
Ok.  Cool.  Any problems or concerns when following the new documentation?

**Comment by CSpencerND** [comment]
I don't understand what's going on. I've been trying to get this to work all day. I follow all the instructions exactly. After running the installation script LunarVim opens. When I close it and run nvim it loads up normal nvim and Packer nor Lsp are found to be commands. The only way I can get LunarVim back is to redo the installation.

**Comment by rebuilt** [comment]
What's the output of these commands?

```bash
which nvim
nvim -v
```

**Comment by CSpencerND** [comment]
which nvim 
`/usr/local/bin/nvim`

nvim -v
```
NVIM v0.5.0-dev+1302-g8a93d1028
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/cspencer/Installed/neovim/build/config -I/home/cspencer/Installed/neovim/src -I/home/cspencer/Installed/neovim/.deps/usr/include -I/usr/include -I/home/cspencer/Installed/neovim/build/src/nvim/auto -I/home/cspencer/Installed/neovim/build/include
Compiled by root@tiamat

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by rebuilt** [comment]
It might be using the system vim config file.  You can start neovim by specifying a configuration file
```bash
nvim -u ~/.config/nvim/init.lua
```

Also double check that LunarVim files are in the ~/.config/nvim directory and not something else.  These should be the contents of that file.  

```bash
ftplugin  LICENSE  lv-settings.lua  README.md  vimscript
init.lua  lua      plugin           utils
```
Make sure your system is not starting with some other init configuration.  These are the rules for initialization
```bash
						*system-vimrc* *sysinit.vim*
     a. The system vimrc file is read for initializations.  If
	nvim/sysinit.vim file exists in one of $XDG_CONFIG_DIRS, it will be
	used.  Otherwise the system vimrc file is used. The path of this file
	is given by the |:version| command.  Usually it's "$VIM/sysinit.vim".

						*VIMINIT* *EXINIT* *$MYVIMRC*
     b. Locations searched for initializations, in order of preference:
	-  $VIMINIT environment variable (Ex command line).
	-  User |config|: $XDG_CONFIG_HOME/nvim/init.vim.
	-  Other config: {dir}/nvim/init.vim where {dir} is any directory
	   in $XDG_CONFIG_DIRS.
	-  $EXINIT environment variable (Ex command line).
	|$MYVIMRC| is set to the first valid location unless it was already
	set or when using $VIMINIT.

     c. If the 'exrc' option is on (which is NOT the default), the current
	directory is searched for two files.  The first that exists is used,
	the others are ignored.
	-  The file ".nvimrc"
	-  The file ".exrc"
```
You can read the yourself with this command ':h viminit'

**Comment by CSpencerND** [comment]
> "It might be using the system vim config file. You can start neovim by specifying a configuration file"
> `nvim -u ~/.config/nvim/init.lua`

Hoooooollllyyyy shit. That was it!!! xD it's always something so simple. Thank you so much!

**Comment by CSpencerND** [comment]
The solution was to put this is my .zshenv:
`export MYVIMRC=XDG_CONFIG_HOME/nvim/init.lua`
