### ISSUE TITLE
Not installing dependencies

### ISSUE THREAD

**Issue by Dunrar** [ChristianChiarulli/LunarVim#273]
I'm new to vim/neovim in general and was trying to install this config on WSL2. Using the all-in-one command, many dependencies are not being installed. Starting nvim and running :PackerInstall does seemingly nothing. An example would be Ranger, which is not being installed. After installing Ranger by hand no icons are visible. Even installing it by hand, I can not get ueberzug to work properly etc. It would be nice if I could get some pointers on how to set this up properly.

**Comment by rebuilt** [comment]
Do you have a 0.5 version of nvim?

**Comment by Dunrar** [comment]
Yes, just checked again.

**Comment by rebuilt** [comment]
I'll test on windows and get back to you

**Comment by Dunrar** [comment]
Thank you!

**Comment by rebuilt** [comment]
I got it working on wsl.  Here are the steps I followed:

Installed wsl with the help of this guide:  https://docs.microsoft.com/en-us/windows/wsl/install-win10
Installed Ubuntu as the wsl distribution

```bash
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip
git clone https://github.com/neovim/neovim
sudo make CMAKE_BUILD_TYPE=Release install
sudo apt install xsel
sudo apt install python3-pip npm
```

Now to confirm I have version 0.5
nvim -v 
NVIM v0.5.0-dev+1265-g66f9dd3c6

And I wanted to confirm there's no nvim folder already present so the script can create one of its own
ls ~/.config/nvim
ls: cannot access '.config/nvim': No such file or directory

Run the installation script
```bash
bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)
```

Launch nvim and run :PackerInstall as an ex command.  Then restart neovim
:PackerInstall


Install the lua language server.  Then restart neovim.  And confirm that next time neovim launches the galaxyline at the bottom contains the words sumneko_lua to let me know the name of the language server that is running for this file.  I can also call :LspInfo to confirm the same.  
:LspInstall lua

**Comment by rebuilt** [comment]
Others have reported problems with the nightly version of neovim so if you have that, even if it's 0.5, you should still remove the old nvim and compile from source.

**Comment by Dunrar** [comment]
I followed your steps and while compiling, I got this error:

```
Missing dependencies for penlight 1.5.4-1:
   luafilesystem (not installed)

penlight 1.5.4-1 depends on luafilesystem (not installed)
Installing https://luarocks.org/luafilesystem-1.8.0-1.src.rock

Error: Failed installing dependency: https://luarocks.org/luafilesystem-1.8.0-1.src.rock - Could not fetch rock file: Error fetching file: Failed downloading https://luarocks.org/luafilesystem-1.8.0-1.src.rock - luafilesystem-1.8.0-1.src.rock
make[3]: *** [CMakeFiles/penlight.dir/build.make:61: usr/lib/luarocks/rocks-5.1/penlight] Error 1
make[3]: Leaving directory '/home/schillmann/neovim/.deps'
make[2]: *** [CMakeFiles/Makefile2:501: CMakeFiles/penlight.dir/all] Error 2
make[2]: Leaving directory '/home/schillmann/neovim/.deps'
make[1]: *** [Makefile:84: all] Error 2
make[1]: Leaving directory '/home/schillmann/neovim/.deps'
make: *** [Makefile:105: deps] Error 2
```

**Comment by Dunrar** [comment]
Okay, neovim compiled and I have the right version. I ran the installation script, after which nvim started. I quit nvim, restarted, pressed `:` (ex command?) and typed `PackerInstall` and confirmed with Enter, but nothing seemed to happen. I restarted neovim and installed the lua server, which shows up when calling :LspInfo. 

When using `neovim .` , neovim opens with `/bin/bash: ranger: command not found`.

**Comment by rebuilt** [comment]
ranger is a separate program and not part of neovim.  Install it with 
```bash
sudo apt install ranger
```

You'll also need to install the other optional dependencies if you're interested in the functionality they provide: 
ueberzug
ripgrep
pynvim
neovim-remote

You'll have to search out how to install each of those on Ubuntu since some won't be in the Ubuntu repos.  Follow the install guides for each of those projects.  

:PackerInstall won't actually do anything the second time it's called.  It knows it's already installed the packages.

**Comment by rebuilt** [comment]
Do you see this when launching neovim?  

![lunarvim](https://user-images.githubusercontent.com/16025007/115302753-0e60ef00-a163-11eb-9810-3da3ae3b9126.png)

**Comment by Dunrar** [comment]
Thank you very much!

**Comment by rebuilt** [comment]
I was misinformed.  After reading through the install script, it does try to install the dependencies.  But I also noticed that the script won't work correctly in WSL because the 'uname' command in WSL spits out something unexpected.

**Comment by meicale** [comment]
I can not install ueberzug on wsl2. Have you ever solved that? Could you share it?

> ranger is a separate program and not part of neovim. Install it with
> 
> ```shell
> sudo apt install ranger
> ```
> 
> You'll also need to install the other optional dependencies if you're interested in the functionality they provide: ueberzug ripgrep pynvim neovim-remote
> 
> You'll have to search out how to install each of those on Ubuntu since some won't be in the Ubuntu repos. Follow the install guides for each of those projects.
> 
> :PackerInstall won't actually do anything the second time it's called. It knows it's already installed the packages.
