### ISSUE TITLE
installation Error: LunarVim

### ISSUE THREAD

**Issue by lakshyarao22** [ChristianChiarulli/LunarVim#276]
![image](https://user-images.githubusercontent.com/5268175/115344721-64697d00-a1cb-11eb-8113-78544f63e5fe.png)

**Comment by rebuilt** [comment]
Did you see any errors when running the installation script?

Do you have at least version 0.5 of neovim installed?
```bash
nvim -v
```

Did you run :PackerInstall from inside nvim?
```bash
:PackerInstall
```

Did you have a previous distribution of nvim installed?  Something like spacevim?

**Comment by rebuilt** [comment]
This seems similar to #268.  Are you also using wsl2?  Did you compile from source?

**Comment by rebuilt** [comment]
#279

**Comment by lakshyarao22** [comment]
I am using manjaro linux

**Comment by rebuilt** [comment]
Have you compiled neovim from source? Others have reported they needed to do that for everything to work.  First uninstall your current neovim.  Then run:

```bash
sudo pacman -S base-devel cmake unzip ninja tree-sitter
git clone https://github.com/neovim/neovim
cd neovim
sudo make CMAKE_BUILD_TYPE=Release install
```
The script tries to install these dependencies as well.  Just make sure they're installed

```bash
sudo pacman -S nodejs npm python-pip ripgrep fzf ranger
npm install -g tree-sitter-cli
pip3 install pynvim --user
pip3 install ueberzug neovim-remote
```

And then re-run the script to copy over all the LunarVim settings
```bash
bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)
```

**Comment by diego-rapoport** [comment]
I had the same problem. Compiling from source did the job, but then I tried to run neovim and it says it is not in /usr/bin/nvim, which is true. So I have to run /usr/local/bin/nvim to make it work.
Any suggestions on how to solve this? I do have /usr/local/bin inside $PATH so don't know how to proceed.

**Comment by V1ctorW1ll1an** [comment]
Thanks, it worked for me.

**Comment by rebuilt** [comment]
@ChristianChiarulli 
This can be closed
