### ISSUE TITLE
Saving a python file causes a crash

### ISSUE THREAD

**Issue by eulertour** [ChristianChiarulli/LunarVim#278]
Attempting to save a python file from a fresh install (as of e94d9e18c581945a16b090425995a2dd57321411) results in
```
Error detected while processing BufWritePre Autocommands for "*.py":
E5108: Error executing lua ...ount_nvim.aTA5Wts/usr/share/nvim/runtime/lua/vim/lsp.lua:1274: table index is nil
```

**Comment by rebuilt** [comment]
It might be the python auto-formatter trying to modify the file as its being written to disk.  Try setting the auto-format to false on line 25 of ./lua/lv-globals.lua.  If that fixes things, try adjusting the time delay for autoformatting.  ./lua/lv-autocommands/init.lua  Line 5  

Documentation for that function: 
```bash
 *vim.lsp.buf.formatting_sync()*
formatting_sync({options}, {timeout_ms})
                Performs |vim.lsp.buf.formatting()| synchronously.

                Useful for running on save, to make sure buffer is formatted
                prior to being saved. {timeout_ms} is passed on to
                |vim.lsp.buf_request_sync()|. Example:


    vim.api.nvim_command[[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()]]
 

                Parameters: 
                    {options}     Table with valid `FormattingOptions` entries
                    {timeout_ms}  (number) Request timeout
```

**Comment by rebuilt** [comment]
The documentation recommends making sure the buffer is formatted prior to being saved.  I'm not sure how to do that.  Maybe someone with more knowledge can figure that out?

**Comment by eulertour** [comment]
I don't know if it's the answer you were going for, but setting autoformat to false works because it disables autoformatting entirely. I tried adjusting the timeout with no success. Since buf_request_sync blocks while waiting for a result I don't think the problem is from writing the file to disk while formatting it.

**Comment by rebuilt** [comment]
Make sure you have go and efm installed.
On arch 
```bash
sudo pacman -S go
```

Then install the efm language server using :LspInstall

```bash
:LspInstall efm
```

This will probably mess up your auto-indenting.  Its a known bug.

**Comment by rebuilt** [comment]
If you do experience the auto-indenting thing, try disabling indenting for python as suggested here #181

**Comment by rebuilt** [comment]
Also make sure the file you're editing is in a git repository so that efm will load.

**Comment by eulertour** [comment]
It turns out I needed to LspInstall efm after all. I had the efm-langserver binary in my path and thought that was enough but I guess it wasn't. Thanks.
