### ISSUE TITLE
Install script will fail in WSL2

### ISSUE THREAD

**Issue by rebuilt** [ChristianChiarulli/LunarVim#279]
A lot of users are failing to install lunarvim in WSL2.   Reading through the installer script leads me to believe dependencies will not be installed.  
The script checks for the name of the OS and performs the correct action for that distribution
```bash
[ "$(uname)" == "Darwin" ] && installnodemac
	[ -n "$(uname -a | grep Ubuntu)" ] && installnodeubuntu
	[ -f "/etc/arch-release" ] && installnodearch
	[ -f "/etc/fedora-release" ] && installnodefedora
	[ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ] && echo "Windows not currently supported"
	sudo npm i -g neovim
```

However, uname in WSL hides the distibution
This is the output:  
```bash
uname -a
Linux DESKTOP-F94NIEJ 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Here is the output of /etc/lsb-release

```bash
cat lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

I'm not sure if lsb-release exists for other distros in WSL2

Additionally, in wsl2 a global install of tree-sitter-cli will fail 
This command has to be used:
```bash
sudo npm install -g tree-sitter-cli --unsafe-perm=true --allow-root
```

I'm not sure if you want to support WSL or not but I wanted to share what I've learned so far so you can make a decision.  At the very least print a message saying WSL is not supported.  

@Walkability @enkodr @ivano9 @ChristianChiarulli

**Comment by rebuilt** [comment]
That said, it is possible to install the dependencies manually.  Here are the steps to install. 

```bash
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip build-essential
git clone https://github.com/neovim/neovim
sudo make CMAKE_BUILD_TYPE=Release install
sudo apt install xsel python3-pip npm
sudo npm install -g tree-sitter-cli --unsafe-perm=true --allow-root
nvim
:PackerInstall
:LspInstall lua
```

**Comment by boonkerz** [comment]
it has not work either :(

**Comment by rebuilt** [comment]
@boonkerz What is the output of :checkhealth and :PackerStatus?

**Comment by rebuilt** [comment]
Also try deleting the directories ~/.cache/nvim and ~/.local/share/nvim.  Then rerun :PackerInstall

**Comment by najamsk** [comment]
## OS
  - OK: Name: Linux

## Ranger
  - ERROR: Ranger not Found

## Pynvim
  - OK: Version: 0.4.1

## Ueberzug (optional)
  - WARNING: Ueberzug is not found in Python Lib

## RPC
  - ERROR: RPC: timeout 3s
  - ERROR: Vim(call):E900: Invalid channel id

health#nvim_treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    function health#check[21]..health#nvim_treesitter#check, line 1
    Vim(lua):E5105: Error while calling lua chunk: ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:2:           module 'vim.treesitter.query' not found:
    no field package.preload['vim.treesitter.query']
    no file '/home/najam/.config/nvim/lua/vim/treesitter/query.lua'

**Comment by rebuilt** [comment]
@najamsk 
Try deleting 
```bash
~/.local/share/nvim
~/.cache/nvim
~/.config/nvim
```

Then retry the steps listed above to make sure you have all the dependences.  Then re-run the installation script.

**Comment by najamsk** [comment]
I made it work before sleeping atleast its launching. 


healthcheck revleas follwing i know i am missing many things maybe. like for sure git status is not working from lunarvim. Also cant figure out copy paste from neovim that is instlal inside wsl. tried the offical answer that yank thing added to host windows path.  still nothing.

**Comment by meicale** [comment]
hi
