### ISSUE TITLE
Problem installing efm-langserver

### ISSUE THREAD

**Issue by Lazk3r** [ChristianChiarulli/LunarVim#282]
When I run `:LspInstall efm` i get this error:

![error](https://user-images.githubusercontent.com/82919717/115486166-b4703000-a21b-11eb-9012-4774e88fca6d.png)

`:LspInfo`

![lspinfo](https://user-images.githubusercontent.com/82919717/115486280-fac58f00-a21b-11eb-960b-a699c4d53e4b.png)

**Comment by rebuilt** [comment]
Do you have 'go' installed? 
```bash
which go
```
If not.  Install go and try again with :LspInstall

If that doesn't work, you might try installing manually.

```bash
cd /home/lazk3r/.local/share/nvim/lspinstall/efm/
GOPATH=$(pwd) GOBIN=$(pwd) GO111MODULE=on go get -v github.com/mattn/efm-langserver
GOPATH=$(pwd) GO111MODULE=on go clean -modcache
```

**Comment by Lazk3r** [comment]
Thanks, I had to reinstall 'go' for it to work
