### ISSUE TITLE
Gopls doesn't work. 

### ISSUE THREAD

**Issue by shubham-cpp** [ChristianChiarulli/LunarVim#283]
I cloned your configs for trying out nvim-lsp but the gopls didn't seem to work. I have everything setup as mentioned on nvim-lsp config.md and I also checked gopls wiki for vim/nvim. After doing some research I found out that nvim-lsp defaults aren't setup properly, so here's the solution.

```lua
require'lspconfig'.gopls.setup{
    cmd = {DATA_PATH .. "/lspinstall/go/gopls","serve"},
    settings = {gopls = {analyses = {unusedparams = true}, staticcheck = true}},
    root_dir = lsp.util.root_pattern(".git","go.mod","."),
    init_options = {usePlaceholders = true, completeUnimported = true},
    on_attach = require'lsp'.common_on_attach
}
```
The **root_dir** variable was causing the problem, so we also added the current directory. Without that the gopls server will only start if current directory is a git directory or go.mod file exists

**Comment by ChristianChiarulli** [comment]
awesome consider a PR if you have time

**Comment by shubham-cpp** [comment]
Yup. My bad
