### ISSUE TITLE
Unable to install VIM Plugins

### ISSUE THREAD

**Issue by jonathan-raines** [ChristianChiarulli/LunarVim#285]
I have having trouble with installing https://github.com/vim-ruby/vim-ruby and https://github.com/tpope/vim-endwise.

I have a stock LunarVim setup that was installed today. 

<img width="591" alt="Screen Shot 2021-04-21 at 1 28 07 PM" src="https://user-images.githubusercontent.com/5840124/115603388-b5e63a80-a2a5-11eb-8639-afa22e0ff7c5.png">

I ran PackerInstall and restarted neovim afterwards. When running :PackerStatus, I can see both plugins but they are showing as "not loaded"

<img width="398" alt="Screen Shot 2021-04-21 at 1 31 31 PM" src="https://user-images.githubusercontent.com/5840124/115603546-e75f0600-a2a5-11eb-94b4-efa7dca40bd4.png">

I created a directory called "lv-endwise" and an init.lua file, following issue #277 

<img width="523" alt="Screen Shot 2021-04-21 at 1 33 46 PM" src="https://user-images.githubusercontent.com/5840124/115603805-36a53680-a2a6-11eb-9a96-edf244c6d9a8.png">

I have tried adding different variations of the require statement straight into the main init.lua file, but no matter how I format it or how many times I restart neovim I cannot get the endwise plugin to work at all.

Could someone please help me add this plugin to the config file so that I can continue to tweak it per my development needs?

Thanks!

Edit: Now I'm no so sure that it's not installing the plugin properly. I seem to have vim-rails running by just adding it to the plugins.lua file and running PackerInstall. Now I'm thinking there's something conflicting with Endwise so that it's not running (and making me think it's not installed properly).

**Comment by rebuilt** [comment]
I can confirm your theory.  Endwise is conflicting with treesitter.  If you comment out the treesitter section(lines 12-18) in lv-globals.lua you'll see that endwise works correctly.  I'm not sure what to do about it.  I have endwise and treesitter working in my own configuration which is not based on lunarvim.  So they CAN work together.  I'm not sure why they're not in this case.  

Here are the steps I took to confirm all this:  I ran nvim in verbose mode.  I confirmed that the endwise autocommand got loaded at start.  I defined a ruby method but didn't see the autocommand trigger.  Something else is overwriting the triggers (treesitter).  I commented out sections of init.lua until I found the spot that caused the error; the treesitter configuration.

**Comment by rebuilt** [comment]
You can confirm endwise is loaded with 
```bash
:lua print(vim.g.loaded_endwise)
```

This should output to the status line
```bash
1
```

**Comment by rebuilt** [comment]
Just for reference: https://github.com/neoclide/coc.nvim/issues/297

**Comment by rebuilt** [comment]
Enable additional_vim_regex_highlighting and vim-endwise will work.

```bash
require('nvim-treesitter.configs').setup {
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = true
  },
}
```

Solution found here: https://github.com/nvim-treesitter/nvim-treesitter/issues/703

**Comment by jonathan-raines** [comment]
Issue is a clashing of plugins treesitter and vim-endwise. Closing issue as I can install vim plugins

**Comment by rebuilt** [comment]
Did the regex highlighting thing help?  
Run a :PackerSync .  I think they've fixed it.

if that doesn't work, try changing the use definition to
```bash
    use "tpope/vim-endwise"
    require_plugin("vim-endwise")
```

**Comment by jonathan-raines** [comment]
I didn't try the additional regex highlighting. I did try running :PackerSync and the endwise plugin is still in conflict with treesitter. I tried your other suggestion of changing endwise from an optional plugin and that didn't seem to work either.

**Comment by jonathan-raines** [comment]
I would still love to get endwise working with treesitter.

**Comment by rebuilt** [comment]
Make sure you have timeoutlen set to something longer than 100 miliseconds.  It takes longer than that to type out a key combination.
This will also slow down how long it takes for whichkey to open.
lua/settings.lua
```lua
vim.o.timeoutlen = 100 -- By default timeoutlen is 1000 ms
```
