### ISSUE TITLE
Vue/vls LSP config file

### ISSUE THREAD

**Issue by divn** [ChristianChiarulli/LunarVim#294]
Anyone willing to help me setup the vue lsp?

**Comment by rebuilt** [comment]
Reference docs are [here](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#vuels).  
Put this in it own file in ./lua/lsp/vue-ls/init.lua

```bash
require'lspconfig'.vuels.setup{}
```

and then require it from the main init.lua file
```bash
require('lsp.vue-ls')
```
Make sure you install vuels
```bash
npm install -g vls
```

Confirm installation
```bash
which vls
```

And then to troubleshoot :LspInfo

**Comment by divn** [comment]
Done deal, TY.
I tried myself and was messing with root_dirs etc, inserted only what u said and it works.
Thank you again, have a nice day

**Comment by rebuilt** [comment]
If you leave it empty, it will use the defaults.  Check the defaults on the reference doc I listed above to see what its already doing for you.

**Comment by divn** [comment]
checked and played with those aswell, cant get prettier to work on .vue files like it works on .js files at the moment

**Comment by rebuilt** [comment]
Line 95 of lua/lsp/efm-general-ls.lua  Add vue to the filetypes

```bash
    filetypes = {"lua", "python", "javascriptreact", "javascript", "sh", "html", "css", "json", "yaml", "markdown", "vue"},
```
:wq

**Comment by divn** [comment]
how bout eslint :D then im done ! ur the best

**Comment by divn** [comment]
I got it !
