### ISSUE TITLE
Open termanal in directory

### ISSUE THREAD

**Issue by premell** [ChristianChiarulli/LunarVim#295]
It would be nice if whichkey would open the terminal in the current directory, its quite annoying to have to cd over to ones file everytime one wants to use the terminal

**Comment by alourie** [comment]
@premell @ChristianChiarulli it can be done with something like:

```vimscript
" t is for launching terminal
let g:which_key_map.t = {
      \ 'name' : '+terminal' ,
      \ 't' : [':term'                                          , 'open terminal'],
      \ 'T' : [':lcd %:p:h | :term'             , 'open terminal in this directory'],
      \}
```
I can open a PR if interested.

**Comment by premell** [comment]
Thank you! This is exactly what i want, however for some reason the terminal is opened in a  new tab instead of as a floating or toggleable terminal. Is there anyway to get this functionality but with the normal terminal layout?

**Comment by alourie** [comment]
@premell for that you need to update the command to do the right thing. The solution I suggested is using the built-in terminal in neovim; for other terminals, you'd need to look up their usage patterns. I'm not using the terminal often enough to know how to use other plugins, sorry :-)

**Comment by ChristianChiarulli** [comment]
I should probably implement better terminal support

**Comment by alourie** [comment]
@ChristianChiarulli  and then you should also define what "better" means in this context :-)

**Comment by ChristianChiarulli** [comment]
@alourie I'll know when I see it haha, for now I'm just adding it to the project to track this issue.

**Comment by abzcoding** [comment]
> @alourie I'll know when I see it haha, for now I'm just adding it to the project to track this issue.

I think [nvim-toggleterm](https://github.com/akinsho/nvim-toggleterm.lua) is the best candidate currently.

**Comment by abzcoding** [comment]
we have [nvim-toggleterm](https://github.com/akinsho/nvim-toggleterm.lua) now, you can enable it by adding this to your `lv-config.lua`:

```lua
O.plugin.terminal.active = true
```

also check out their documentation for setting your desired keybindings
