### ISSUE TITLE
tsserver does not work....?

### ISSUE THREAD

**Issue by arrase21** [ChristianChiarulli/LunarVim#297]
any about what it might be?
I already tried with LspInstall and npm install -g..... 
(in my other config if it works)
![D-shot-captura-pantalla-210424-1703-47](https://user-images.githubusercontent.com/68574161/115975436-58165480-a52a-11eb-842f-b067d8901f04.png)

**Comment by rebuilt** [comment]
You have to be inside a git repository for the language servers to identify the root directory.

**Comment by rebuilt** [comment]
Try :LspStart tsserver and then :messages to read any error messages.

**Comment by ianmubangizi** [comment]
## Problems
- The ts-server crashes on fresh install of this config, 
it occurs after writing code then saving, and it seems to not work at all. 
- elm give me this error:
```
Error detected while processing CursorHold Autocommands for "<buffer=13>":
RPC[Error] code_name = MethodNotFound, message = "method textDocument/documentHighlight is not supported by any of the servers registered for the current buffe
r"
```

- - Commenting out common_on_attach stops it from occurring:
```lua
 -- ~/.config/nvim/lua/lsp/init.lua
function lsp_config.tsserver_on_attach(client, bufnr)
    -- lsp_config.common_on_attach(client, bufnr)
    client.resolved_capabilities.document_formatting = false
end
```

**Comment by ianmubangizi** [comment]
##Another Error: 

![Screenshot_2021-05-06_12-41-00](https://user-images.githubusercontent.com/18429123/117282749-c41f8380-ae6d-11eb-880b-16ce9793e05b.png)

**Comment by rebuilt** [comment]
Which filetype are you editing?  "javascriptreact", "javascript", "typescript","typescriptreact"

**Comment by rebuilt** [comment]
Does :TSInstallInfo show a parser installed for your language?

**Comment by ianmubangizi** [comment]
> Which filetype are you editing? "javascriptreact", "javascript", "typescript","typescriptreact"
* javascriptreact

## These are the only error am getting for the health check:
![Screenshot_2021-05-06_17-26-21](https://user-images.githubusercontent.com/18429123/117315435-5df82800-ae90-11eb-8d07-99ae527587a7.png)


I really don't need all those servers, am planning one removing them, but I don't want to make changes until I understand why the ts-server is not working

**Comment by rebuilt** [comment]
This line in your lsp.log is interesting
```
"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55f2ca]\n\ngoroutine 
```
I've never seen this error before.  If I saw that error, I'd try reinstalling from scratch.  I don't think that's going to be solved by configuration.  

```
sudo rm -R ~/.local/share/nvim
nvim
:PackerSync
:PackerInstall
:LspInstall typescript
:LspInstall efm
:LspInfo
```

**Comment by rebuilt** [comment]
If that doesn't work, try recompiling neovim 0.5.

**Comment by ianmubangizi** [comment]
It seems to only work in small projects, the ts-server just crashes in my actual project.
![Screenshot_2021-05-06_21-28-39](https://user-images.githubusercontent.com/18429123/117347682-0a96d180-aeb2-11eb-8952-cdd7a8a4e279.png)

**Comment by rebuilt** [comment]
Maybe you can get by with only one server running.  Try turning off efm by removing the javascriptreact filetype from
```lua
    filetypes = {
        "ruby","lua", "python", "javascriptreact", "javascript", "typescript", "typescriptreact", "sh", "html", "css", "json",
        "yaml", "markdown", "vue"
    },
```

EFM wont start and then you may still be able to use LSP provided by the tsserver.

**Comment by rebuilt** [comment]
The file location is ~/.config/nvim/lua/lsp/efm-general-ls.lua

**Comment by chrisbirster** [comment]
I get the same error as well. It seems like tsserver only works for small projects.
