### ISSUE TITLE
Lsp error loading python

### ISSUE THREAD

**Issue by ElAouane** [ChristianChiarulli/LunarVim#300]
Hi, I installed yesterday LunarVim (BTW great work its amazing) and everything was working just fine. I run :LspInstall elm and :LspInstall python and everything was just great with autocompletion and indentation etc. Today when I opened lunar vim to keep working, nothing was working, if I open a py file and start coding, the indentation is not working. if I run :source % to refresh I get this error

```
Error detected while processing /Users/hamzaelaouane/Desktop/Dev/SocialMedia/tweets/views.py:
line    1:
E492: Not an editor command: from django.shortcuts import render
line    2:
E492: Not an editor command: from django.http import HttpResponse
line    3:
E488: Trailing characters: # Create your views here.
line    4:
E492: Not an editor command: def home_view(request, *args, **kwargs):
line    5:
```

I get those errors for each line of code in my file.

**Comment by rebuilt** [comment]
Are you in a git repo?  

Whats the output of 
```bash
:LspInfo
```

**Comment by ElAouane** [comment]
if I run :LspInfo I get this:

```
  1
~
~
~
~
~                  Configured servers: dartls, graphql, clangd, sumneko_lua, intelephense, kotlin_language_server, bashls, tsserver, tailwindls, solargraph, gopls,
~                  Neovim logs at: /Users/my-user/.cache/nvim/lsp.log
~
~                  0 client(s) attached to this buffer:
~
~                  0 active client(s):
~
~                  Clients that match the filetype python:
~
~                    Config: efm
~                      cmd:               /Users/my-user/.local/share/nvim/lspinstall/efm/efm-langserver
~                      cmd is executable: True
~                      identified root:   None
~                      custom handlers:
~
~                    Config: pyright
~                      cmd:               /Users/my-user/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
~                      cmd is executable: True
~                      identified root:   /Users/my-user
~                      custom handlers:   textDocument/publishDiagnostics
~
~
PYTHON python.py 
:LspInfo
                                                                                                                                                                    1,1           All
```

**Comment by rebuilt** [comment]
What's the output of 'ls -la'  from the root directory of your project?   The one you ran 'git init' from.

**Comment by rebuilt** [comment]
What are the contents of Users/my-user/.cache/nvim/lsp.log
Also try ':LspStart efm' and ':LspStart python'  then read :messages

**Comment by ElAouane** [comment]
if I run :LspStart efm I get this..

`Autostart for efm failed: Matching root directory not detected`

with :LspStart python:
`E5108: error executing Lia ....im/site/pack/packer/opt/nvim-lsconfig.lua:27: attempt to index a nil value`

**Comment by rebuilt** [comment]
What's the output of 'ls -la' from the root directory of your project? The one you ran 'git init' from.

**Comment by ElAouane** [comment]
Sorry I forgot to reply to that.

I don't have a git init in this project

**Comment by rebuilt** [comment]
Just make a folder called .git in that directory.  You don't actually have to initialize a real repository if you don't want to.  It's searching for that folder.

**Comment by ElAouane** [comment]
I have done that and as soon as I open nvim I get this error:
`Error executing vim.schedule Lua callback: ....te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/git.lua:64: attempt to concatenate local "cwd" (a nil value)`

**Comment by rebuilt** [comment]
What's :LspInfo now?

**Comment by ElAouane** [comment]
```
~
~                      Configured servers: emmet_ls, bashls, dockerls, texlab, html, dartls, svelte, cssls, efm, solargraph, clangd, yamlls, intelephense, vimls, jsonls, gopls, rust_analyzer, tsserver
~                      Neovim logs at: /Users/my-user/.cache/nvim/lsp.log
~
~                      0 client(s) attached to this buffer:
~
~                      0 active client(s):
~
~                      Clients that match the filetype python:
~
~                        Config: efm
~                          cmd:               /Users/my-user/.local/share/nvim/lspinstall/efm/efm-langserver
~                          cmd is executable: True
~                          identified root:   .
~                          custom handlers:
~
~                        Config: pyright
~                          cmd:               /Users/my-user/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
~                          cmd is executable: True
~                          identified root:   .
~                          custom handlers:   textDocument/publishDiagnostics
~
```

**Comment by rebuilt** [comment]
Also, whats the content of /lua/nvim-tree/git.lua?  I don't see that file as a part of the current lunarvim project.

**Comment by ElAouane** [comment]
under `/Users/my-user/.config/nvim/lua/lv-nvimtree/` I have only init.lua and not git.lua.

**Comment by rebuilt** [comment]
Try it again.  It looks like it's identifying a root now.  See if the :messages have changed
```bash
:LspStart efm
```

**Comment by ElAouane** [comment]
Same error from before. Could be a non compatibility with a MacBook M1?

**Comment by rebuilt** [comment]
A lot of people have been having trouble with packaged neovims.  Did you compile neovim on your machine?

**Comment by ElAouane** [comment]
Yes on my machine. But I am using MacBook M1 silicon. And until the day before yasterday it was working just fine, then suddenly it stopped working

**Comment by rebuilt** [comment]
Run :checkhealth to make sure everything is set up correctly.  Have you made any changes to your config lately?

**Comment by rebuilt** [comment]
Try reinstalling python lsp
```bash
:LspInstall python
```

**Comment by rebuilt** [comment]
I think you should start from scratch.  Something is failing and the error above makes me think something is wrong with your plugins 'pack/packer/start/nvim-tree.lua'

```bash
sudo rm -R ~/.local/share/nvim
:PackerCompile
:PackerInstall
:LspInstall python
:LspInstall efm
```
