### ISSUE TITLE
Colorizer installation?

### ISSUE THREAD

**Issue by etrigan63** [ChristianChiarulli/LunarVim#304]
The instructions you gave for `colorizer` in your blog post don't work with Lunarvim. Can you post updated instructions?

**Comment by rebuilt** [comment]
Do you have a link for that blog post?

**Comment by rebuilt** [comment]
~/.config/nvim/init.lua
```bash
require('lv-colorizer')
```

~/.config/nvim/lua/lv-colorizer/init.lua
```bash
require'colorizer'.setup()
```

~/.config/nvim/lua/plugins.lua
```bash
use {"norcalli/nvim-colorizer.lua", opt = true}
require_plugin("nvim-colorizer.lua")
```

```bash
:PackerCompile
:PackerInstall
```

![colorizer](https://user-images.githubusercontent.com/16025007/116136372-833ba800-a6d2-11eb-9adb-836cbf81ac1b.gif)

**Comment by etrigan63** [comment]
> Do you have a link for that blog post? Which colorizer exactly are you trying to install?

https://www.chrisatmachine.com/Neovim/10-adding-color/

**Comment by rebuilt** [comment]
Looks like that blog assumes an init.vim configuration file.  Lunarvim uses init.lua.  You could have still used those same instructions to set it up.
But you have to change any .vim syntax to lua syntax
```bash 
lua require'plug-colorizer'
```
Becomes
```bash
require'plug-colorizer'
```

Read this for more info:  https://github.com/nanotee/nvim-lua-guide

**Comment by etrigan63** [comment]
That requires actual knowledge of lua.

**Comment by alourie** [comment]
Well, the post specifically mentions using `init.vim` which is not present in lunarvim. That being said, maybe @ChristianChiarulli would consider redoing blog posts that are relevant for the new setup.

**Comment by arxra** [comment]
Looks like the instructions in the readme works just fine: https://github.com/ChristianChiarulli/LunarVim#an-example-installation-of-the-colorizer-plugin which are more project specific than the blogpost.

**Comment by rebuilt** [comment]
@arxra I added those instructions to address this issue

**Comment by rebuilt** [comment]
@ChristianChiarulli 
This can be closed
