### ISSUE TITLE
AutoPairs not working in latest pull of lunarvim

### ISSUE THREAD

**Issue by ferran9908** [ChristianChiarulli/LunarVim#313]
In the latest pull of LunarVim, autopairs don't seem to be working. It was working before I pulled the latest version.

I'm on a Mac, with the neovim --HEAD installed.

Looks like commit `102b46ca4a99522f` introduced this bug. Reverting the file to how it was earlier solves the problem, but the makes autocomplete experience obsolete.

**Comment by ChristianChiarulli** [comment]
hmm, I need to look into this

**Comment by ChristianChiarulli** [comment]
I think they should work now

**Comment by hlmeerichs** [comment]
Not sure if its the same issue (also on mac), but after a fresh install I get:

E5113: Error while calling lua chunk: /Users/admin/.config/nvim/lua/lv-autopairs
/init.lua:81: module 'nvim-autopairs.rule' not found:
        no field package.preload['nvim-autopairs.rule']
        no file './nvim-autopairs/rule.lua'
        no file '/opt/homebrew/Cellar/luajit-openresty/20201229_1/share/luajit-2
.1.0-beta3/nvim-autopairs/rule.lua'
        no file '/usr/local/share/lua/5.1/nvim-autopairs/rule.lua'
        no file '/usr/local/share/lua/5.1/nvim-autopairs/rule/init.lua'
        no file '/opt/homebrew/Cellar/luajit-openresty/20201229_1/share/lua/5.1/
nvim-autopairs/rule.lua'
        no file '/opt/homebrew/Cellar/luajit-openresty/20201229_1/share/lua/5.1/
nvim-autopairs/rule/init.lua'
        no file './nvim-autopairs/rule.so'
        no file '/usr/local/lib/lua/5.1/nvim-autopairs/rule.so'
        no file '/opt/homebrew/Cellar/luajit-openresty/20201229_1/lib/lua/5.1/nv
im-autopairs/rule.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './nvim-autopairs.so'
        no file '/usr/local/lib/lua/5.1/nvim-autopairs.so'
        no file '/opt/homebrew/Cellar/luajit-openresty/20201229_1/lib/lua/5.1/nv
im-autopairs.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by soerenmartius** [comment]
same here

<img width="918" alt="Screenshot 2021-04-29 at 09 59 20" src="https://user-images.githubusercontent.com/930643/116519268-98325a00-a8d1-11eb-9415-0231f192d26a.png">

**Comment by rebuilt** [comment]
This sometimes happens when you change versions. 
Let Packer reinstall your plugins.  

```bash
sudo rm -R ~/.local/share/nvim
:PackerCompile
:PackerInstall
```

**Comment by ferran9908** [comment]
Closing issue it works as expected now.
