### ISSUE TITLE
Lua which key implementation introduces lag on OSX

### ISSUE THREAD

**Issue by soerenmartius** [ChristianChiarulli/LunarVim#318]
On OSX, the new which-key integration takes 1-2 seconds after pressing until the window is showing up. Could you give me some advice on how to debug this so I can provide more information?

**Comment by rebuilt** [comment]
What's the output of 
```bash
:verb set timeoutlen?
```

You can manually set it with
```bash
:set timeoutlen=200
```
Check the lua/settings.lua file for where it's actually set.

**Comment by rebuilt** [comment]
Also check if timeout is enabled at all in OSX

```bash
:verb set timeout
```

**Comment by ChristianChiarulli** [comment]
timeoutlen is 500 right now, I could make it less.

**Comment by soerenmartius** [comment]
Thanks, that was helpful! setting `timeoutlen=50` feels most natural to me!
