### ISSUE TITLE
WhichKey error when trying the config?

### ISSUE THREAD

**Issue by thepenguinthatwants** [ChristianChiarulli/LunarVim#323]
Hi I get this error when I open nvim.
Not sure if it might be cause by neovim version as I updated to the latest.
`WhichKey: Your <leader> key for "n" mode in buf 0 is currently mapped to "". WhichKey automatically creates triggers, so please remove the mapping
`

**Comment by argapost** [comment]
See this https://github.com/folke/which-key.nvim/issues/19#issuecomment-829408262

I think @ChristianChiarulli  might remove this line as it is no longer needed with the new whichkey.

```lua
vim.api.nvim_set_keymap('n', '<Space>', '<NOP>', {noremap = true, silent = true})
```

**Comment by folke** [comment]
@thepenguinthatwants @argapost I just pushed a fix that allows overriding an existing keymap for `<leader>` if it's empty, like `<nop>`

If the mapping is anything else, it won't be overriden and the warning message will be shown instead.

**Comment by rebuilt** [comment]
@folke  Does this mean I can move the whichkey trigger to backslash and still have my leader key set to space?  And if whichkey is the only bind on backslash does that mean the rules for ttimeoutlen apply?

**Comment by folke** [comment]
@rebuilt triggers are automatically managed by WhichKey. For example, if you have a mapping for `<leader>gs` (something like git status), triggers will exist for:
* `<leader>`
* `<leader>g`

**Comment by folke** [comment]
@rebuilt I added an option to disable automatic adding of triggers so you can define your own triggers. See the `triggers` option in the config section for more info

**Comment by rebuilt** [comment]
Thank you! That's perfect.
