### ISSUE TITLE
How open a terminal bellow?

### ISSUE THREAD

**Issue by redmasters** [ChristianChiarulli/LunarVim#327]
In previous version the keys <space>+t showed the terminal below the code, how open terminal in this new LuaVim ?

**Comment by ferran9908** [comment]
I'm not sure if there are keybindings yet but the following command should help you.

`:sp|te`

**Comment by jordisantamaria** [comment]
This repository is now only for lsp configuration, you have to install your own plugins you need, the configuration you looking for is like this:

In plugins install this:
`use 'voldikss/vim-floaterm'`

Then in which key Include this:
```
    t = {
        name = "+Terminal",
        [";"] = {":FloatermNew --wintype=normal --height=8<CR>", "Terminal"},
        n = {":FloatermNew node<CR>", "Node"},
        f = {":FloatermNew python<CR>", "Python"},
        t = {":FloatermToggle<CR>", "Toogle"},
    },
```
