### ISSUE TITLE
Should there be a changelog?

### ISSUE THREAD

**Issue by thepenguinthatwants** [ChristianChiarulli/LunarVim#329]
Hi,
I noticed that there are huge changes compared to earlier releases like nvcode version.
Such as no more using hop.nvim or kristijanhusak/vim-dadbod-ui.

And settings themselves has changed a lot.
Are the plugins just bad or just because obsolete toward the ideal of this project?

**Comment by rebuilt** [comment]
He discussed his reasoning in this video.  https://youtu.be/WjncGIHyXFw.  Basically he wants a smaller version with fewer plugins.  

I like the idea of having a changelog.

**Comment by rebuilt** [comment]
You can see what's changed by reading the git log

```bash
git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
```

**Comment by thepenguinthatwants** [comment]
> You can see what's changed by reading the git log
> 
> ```shell
> git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
> ```


That is one beautiful way to check git logs. Thanks!
