### ISSUE TITLE
Installation failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by ittisafur** [ChristianChiarulli/LunarVim#335]
```
bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)
Installing LunarVim
pip installed, moving on...
node installed, moving on...
pynvim installed, moving on...
packer already installed
Cloning LunarVim configuration
Cloning into '/home/undefined/.config/nvim'...
remote: Enumerating objects: 4537, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 4537 (delta 49), reused 64 (delta 28), pack-reused 4432
Receiving objects: 100% (4537/4537), 9.60 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (2557/2557), done.
/proc/self/fd/11: line 85: nvim: command not found
```
So i had vim 8 previously and removed everything and tried shiftng.Removed .vim/ and .vimrc folder in "~" dir. Made sure that i don't have nvim folder in .config/
Donno why it fails.

**Comment by rebuilt** [comment]
The install utility doesn't install neovim.  Look at the instructions for compiling it.  
https://github.com/ChristianChiarulli/LunarVim#get-the-latest-version-of-neovim

**Comment by ittisafur** [comment]
Ahh my bad should have read the entire thing. Got it fixed but a confused and some guideline would really help. So i started learning vim on March. So, all i did was wrote my configs in .vimrc now i donno where to actually write them as due the new setup i had some of my own keybidings to do.

**Comment by ittisafur** [comment]
Ahh my bad should have read the entire thing. Got it fixed Thanks
