### ISSUE TITLE
Some default bindings won't work anymore

### ISSUE THREAD

**Issue by OuterHeavenCC** [ChristianChiarulli/LunarVim#336]
Some default bindings like "caw", "caW", "c0" won't work anymore, they just move the cursor without deleting and going into insert mode

**Comment by rebuilt** [comment]
The 'c' keybind is being overwritten by a keybind set by lunarvim.  ~/.config/nvim/lua/lv-which-key/init.lua   I just submitted a pull request to be able to toggle whichkey on/off.

**Comment by rebuilt** [comment]
In the meantime you can use 
'cf'  (change forward) 
'cF'  change backwords 
'cb' change backwords
'ct' change until
'cT' change backwards until

**Comment by folke** [comment]
With WhichKey, default bindings on c should work. Is there anything still not working related to this?

Might be I fixed that yesterday.

**Comment by rebuilt** [comment]
@folke Confirmed.  After :PackerSync these keybindings work as expected.

@OuterHeavenCC  You'll also have to remove the keybinding in ~/.config/nvim/lua/lsp/init.lua line 23. 'ca' is mapped to LspSaga code_action.

**Comment by rebuilt** [comment]
@OuterHeavenCC  In whichkey, a codeaction is mapped to 
```bash
<space>la
```
So that might be a good keybind to use

**Comment by OuterHeavenCC** [comment]
> @folke Confirmed. After :PackerSync these keybindings work as expected.
> 
> @OuterHeavenCC You'll also have to remove the keybinding in ~/.config/nvim/lua/lsp/init.lua line 23. 'ca' is mapped to LspSaga code_action.

Thanks, that worked!

**Comment by sakshambedi** [comment]
The new Lua based which key is buggy. It takes time compared the the vim based whichkey and doesn't work sometimes.

**Comment by folke** [comment]
@sakshambedi the time it takes before showing the popup is configured by `timeoutlen`. Please refer to the [documentation](https://github.com/folke/which-key.nvim#%EF%B8%8F-configuration) about this.

In what cases does it not work for you?

Would be great if you could submit a bug report.

Thanks!
