### ISSUE TITLE
"String required" on every start (OSX)

### ISSUE THREAD

**Issue by alechp** [ChristianChiarulli/LunarVim#338]
### Error
`E5113: Error while calling lua chunk: Vim:E928: String required`

![Screen Shot 2021-05-01 at 11 38 58 AM](https://user-images.githubusercontent.com/3058939/116791923-5d1b5c80-aa72-11eb-9bb8-524cd1368933.png)

### Attempts to resolve
1. Pulled latest LunarVim
2. Tried all of the `Packer` commands

### What I've noticed
1. Treesitter doesn't work at all (previously: SPACE+e)
2. Which key doesn't work (previously: SPACE)
3. Comment isn't working 

To be honest I'm not quite sure where to start with this debugging but figured it was worth recording this

Related issues (Will update if I find more):
https://github.com/ChristianChiarulli/LunarVim/issues/336

**Comment by rebuilt** [comment]
What's your neovim version?

**Comment by rebuilt** [comment]
It's either a version of neovim that doesn't include the lua JIT or a problem with packer not installing plugins.  
So either recompile 0.5 neovim
or 
```bash
sudo rm -R ~/.local/share/nvim
:PackerCompile
:PackerInstall
```

**Comment by alechp** [comment]
> What's your neovim version?

NVIM v0.5.0-dev+1256-gd19348923
Build type: Release
LuaJIT 2.1.0-beta3

> It's either a version of neovim that doesn't include the lua JIT or a problem with packer not installing plugins.
> So either recompile 0.5 neovim
> or
> 
> ```shell
> sudo rm -R ~/.local/share/nvim
> :PackerCompile
> :PackerInstall
> ```

Roger. I'll give that a shot

**Comment by alechp** [comment]
It's fixed now. Thanks @rebuilt 

Things I did:
1. `brew reinstall luijit`
> Was already installed at --HEAD, hence the reinstall

2. `sudo rm -Rf ~/.local/share/nvim`
3. Download neovim & moved contents to ~/.local/share/nvim

4. Re-ran to test
![Screen Shot 2021-05-01 at 5 22 57 PM](https://user-images.githubusercontent.com/3058939/116798183-e1d19f00-aaa1-11eb-96a6-c5a10a5513a6.png)

5. Run `:PackerSync:`
> Tried running PackerCompile and PackerInstall before this, but didn't seem to do anything. PackerSync worked. Not sure why

---

### Core Problems Resolved

At this point all of these started working again:
- Treesitter
- Whichkey
- Comments

w00t!

---

### Remaining Bug

The only issue I have now is TailwindCSS/LSP. Despite trying to install with LSP and restarting terminal, still seeing this error everytime I launch. But going to close now 
![Screen Shot 2021-05-01 at 5 19 55 PM](https://user-images.githubusercontent.com/3058939/116798220-3bd26480-aaa2-11eb-80af-f50011bc6501.png)

![Screen Shot 2021-05-01 at 5 21 30 PM](https://user-images.githubusercontent.com/3058939/116798211-2fe6a280-aaa2-11eb-823b-a67ceedbc982.png)

Going to close issue now since this is outside of the initial scope. Thanks for your help @rebuilt !

**Comment by rebuilt** [comment]
Look at #340
