### ISSUE TITLE
What themes are supported by Lunarvim?

### ISSUE THREAD

**Issue by etrigan63** [ChristianChiarulli/LunarVim#339]
I cannot find documentation anywhere. I only know of two:

lunar

nord

Is there a way to add themes?

**Comment by rebuilt** [comment]
Press '<space>sc'   Choose a different color scheme.  Most of the colors there come built in to neovim.  If you want a different color scheme you'll have to install it as a plugin.  

https://github.com/ChristianChiarulli/LunarVim#install-your-own-plugins

Which colorscheme are you interested in?

**Comment by rebuilt** [comment]
These are the good ones:   https://github.com/ChristianChiarulli/nvcode-color-schemes.vim

**Comment by etrigan63** [comment]
That is fine.
