### ISSUE TITLE
tailwindls.lua not found

### ISSUE THREAD

**Issue by etrigan63** [ChristianChiarulli/LunarVim#340]
I am getting this error when I open nvim:
![image](https://user-images.githubusercontent.com/7347264/116795124-a1255600-aaa0-11eb-9c1d-2554bc05048a.png)
Don't know how to fix it.

**Comment by rebuilt** [comment]
Create that file.  Put this in it
```bash
local configs = require 'lspconfig/configs'
local util = require 'lspconfig/util'
local nvim_lsp = require('lspconfig')

local server_name = 'tailwindls'

configs[server_name] = {
  default_config = {
    cmd = {server_name};
    filetypes = {'html','svelte','typescriptreact'};
    root_dir = util.root_pattern("package.json", ".git");
  };
  docs = {
    description = [[ ]];
    default_config = {
        root_dir = [[root_pattern("package.json", ".git")]];
    };
  }
} 
```

**Comment by etrigan63** [comment]
Thanks!

**Comment by ferran9908** [comment]
This happens even on a fresh install. Is this expected? Or does this need to be fixed? @ChristianChiarulli @rebuilt

**Comment by rebuilt** [comment]
The problem is that file is not in the https://github.com/neovim/nvim-lspconfig  repository.   I'm not sure if they removed it recently.  I think I need to test on a minimal config to see if it happens there as well.  If so, I can submit an issue with the lspconfig repository to put that file back.   I can't do it now though.  
@ferran9908  Want to look into it and submit the issue yourself?

**Comment by ferran9908** [comment]
@rebuilt Sure. I'll take a look at it. Although I may not get it done immediately, I'll get it done as soon as possible.

**Comment by luxus** [comment]
I can confirm on a fresh install I got the same error
`nvim ~/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig/lua/lspconfig/tailwindls.lua`
with the content from above fixed it

**Comment by jimcornmell** [comment]
Same issue on fresh install on Ubuntu.  I can confirm that fix of creating the file by hand fixes it.

**Comment by alechp** [comment]
This fix works on macOS as well. Thanks @rebuilt
