### ISSUE TITLE
How to make backgorund color transparent?

### ISSUE THREAD

**Issue by antonio-hickey** [ChristianChiarulli/LunarVim#342]
Where is the colorscheme located? i could probably figure it out myself if i could find the colorscheme file i think it's called lunar.vim, but it doesn't seem to be in this repo.

**Comment by rebuilt** [comment]
Color schemes are provided by [this repository](https://github.com/ChristianChiarulli/nvcode-color-schemes.vim).  Follow that link for information about editing specific colors for a colors cheme.  The provided color schemes are compatible with tree-sitter highlight groups.  Color schemes are installed to ~/.local/share/nvim/site/pack/packer/opt/nvcode-color-schemes.vim.  If you edit files in that directory, they will be overwritten the next time Packer compiles your plugins.  

Available color schemes:
```bash
    nvcode (basically just dark+)
    onedark
    nord
    aurora (more colorful nord)
    gruvbox
    palenight
    snazzy (Based on hyper-snazzy by Sindre Sorhus)
```

To switch color schemes on the fly, type the following command:
```bash
:Telescope colorscheme
```
To change the color scheme permanently, modify ~/.config/nvim/lv-settings.lua
