### ISSUE TITLE
Autopairs not ignoring \

### ISSUE THREAD

**Issue by atropos112** [ChristianChiarulli/LunarVim#351]
Hello everyone,

I've been switching from VS Code to nVim, initially trying to set things up from scratch but once I found LunarVim I was over the moon (Lunar, moon get it ; ) ). I installed VimTex as I want to write latex and installed LSP for it with `:LspInstall Latex ` and magic, it works. 

I have a problem however and I am unsure how to remedy this. I want to use a snipet `\(` which turns (via vsnip)  into `\( $1 \)` however when i write `\(` instead autopairs clicks in and gives `\()` at which point i can't trigger the snippet because  there is the ) part.

I noticed its the lv-autopairs closing the brackets and that if I look at https://github.com/jiangmiao/auto-pairs for example ,there is a "ignore when \ is used" feature. Is there any way I can turn it on here? That is can i somehow prevent autopairs from closing the bracket if the previous letter is \ ?

Thank you for your input !

**Comment by rebuilt** [comment]
Maybe the autopairs project can help?  https://github.com/windwp/nvim-autopairs

**Comment by rebuilt** [comment]
If you want to turn it off temporarily while you figure out the autopair rules, you can comment out 

```bash
        basic("(", ")")
            :with_pair(cond.check_is_bracket_line()),
```
From ~/.local/share/nvim/site/pack/packer/opt/nvim-autopairs/lua/nvim-autopairs/rules/basic.lua

**Comment by atropos112** [comment]
> Maybe the autopairs project can help? https://github.com/windwp/nvim-autopairs

Thank you for your response, I must admit i looked at the wrong repo (ooh lord...), looking at it right now.

**Comment by rebuilt** [comment]
The other rules already defined might be taking precedence.  I think there are two regexes that define any symbol is always bracketed

**Comment by atropos112** [comment]
I see two rules already existing there but they have the "lua" tag on them surely they wouldn't affect .tex file types ?

**Comment by rebuilt** [comment]
Autopairs also includes basic rules I think

**Comment by rebuilt** [comment]
Also check the filetype 
```bash
:set filetype?
```

**Comment by atropos112** [comment]
Im guessing u wanted me to run it on the file where I want to have that rule working, in that case `filetype=tex`

**Comment by rebuilt** [comment]
Literally run the command with the question mark appended.  It gives me filetype 'plaintext'

**Comment by rebuilt** [comment]
Now that you've set it, you might have to restart nvim for it to show the filetype detected on start

**Comment by atropos112** [comment]
When i write `:set filetype?` while running vim with a .tex file on i get `filetype=tex`

**Comment by rebuilt** [comment]
You're right, the examples aren't working for me either.

**Comment by rebuilt** [comment]
The rules only work if I leave off the filetype.  I think it must be some sort of regression.

**Comment by rebuilt** [comment]
Here's the rule you wanted.  Unfortunately, you have to apply it to all file types.

```bash
local cond = require('nvim-autopairs.conds')
require('nvim-autopairs').clear_rules()

npairs.add_rules({
  Rule("(", ")")
    :with_pair(cond.not_before_regex_check("\\", 1))
  }
)
```

**Comment by rebuilt** [comment]
You'll notice in the code I posted, I also had to clear the default rules for that to work

```bash
require('nvim-autopairs').clear_rules()
```

**Comment by atropos112** [comment]
Oh wow it works ! This is amazing (never thought I'd be happy about a bracket not closing but here we are). Thank you very much !!

**Comment by rebuilt** [comment]
Remember, if you want some of the basic rules back you'll have to manually add them back to your configuration.
Here are the basic rules we had to turn off.  
```bash
        Rule("<!--", "-->", 'html'):with_cr(cond.none()),
        Rule("```", "```" ),
        Rule("```.*$", "```", { 'markdown', 'vimwiki' })
            :only_cr()
            :use_regex(true)
        ,
        Rule('"""', '"""', 'python'),
        basic("'", "'")
            :with_pair(cond.not_before_regex_check("%w")) ,
        basic("`", "`"),
        basic('"', '"'),
        basic("(", ")")
            :with_pair(cond.check_is_bracket_line()),
        basic("[", "]")
            :with_pair(cond.check_is_bracket_line()),
        basic("{", "}")
            :with_pair(cond.check_is_bracket_line()),
        Rule(">", "<",
            { 'html', 'typescript', 'typescriptreact', 'svelte', 'vue', 'xml'})
            :only_cr()
```

**Comment by rebuilt** [comment]
Sorry to keep pinging you about this but I figured out you don't have to clear all the basic rules.  Just remove the basic rule you want to change 
```bash
npairs.remove_rule("(")
```

or get the rule and modify it
```
  require('nvim-autopairs').get_rule('(') -- get rule " then modify it
```

**Comment by atropos112** [comment]
That's even better thank you, I wasn't sure what the other rules did so i wasn't to fussed but I am guessing they are useful for something.
