### ISSUE TITLE
some issue with LSP

### ISSUE THREAD

**Issue by lakshyarao22** [ChristianChiarulli/LunarVim#353]
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyright: configuration checked.
  - ERROR: tsserver: The given command "/home/lakshya/.local/share/nvim/lspinstall/typescript/node_modules/.bin/typescript-language-server" is not executable.
  - ERROR: graphql: The given command "graphql-lsp" is not executable.
  - ERROR: terraformls: The given command "/home/lakshya/.local/share/nvim/lspinstall/terraform/terraform-ls" is not executable.
  - ERROR: bashls: The given command "/home/lakshya/.local/share/nvim/lspinstall/bash/node_modules/.bin/bash-language-server" is not executable.
  - ERROR: intelephense: The given command "/home/lakshya/.local/share/nvim/lspinstall/php/node_modules/.bin/intelephense" is not executable.
  - ERROR: efm: The given command "/home/lakshya/.local/share/nvim/lspinstall/efm/efm-langserver" is not executable.
  - ERROR: rust_analyzer: The given command "/home/lakshya/.local/share/nvim/lspinstall/rust/rust-analyzer" is not executable.
  - INFO: cssls: configuration checked.
  - INFO: html: configuration checked.
  - ERROR: svelte: The given command "/home/lakshya/.local/share/nvim/lspinstall/svelte/node_modules/.bin/svelteserver" is not executable.
  - ERROR: texlab: The given command "/home/lakshya/.local/share/nvim/lspinstall/latex/texlab" is not executable.
  - ERROR: yamlls: The given command "/home/lakshya/.local/share/nvim/lspinstall/yaml/node_modules/.bin/yaml-language-server" is not executable.
  - ERROR: emmet_ls: The given command "emmet-ls" is not executable.
  - ERROR: gopls: The given command "/home/lakshya/.local/share/nvim/lspinstall/go/gopls" is not executable.
  - ERROR: clangd: The given command "/home/lakshya/.local/share/nvim/lspinstall/cpp/clangd/bin/clangd" is not executable.
  - ERROR: vimls: The given command "/home/lakshya/.local/share/nvim/lspinstall/vim/node_modules/.bin/vim-language-server" is not executable.
  - INFO: dartls: configuration checked.
  - ERROR: dockerls: The given command "/home/lakshya/.local/share/nvim/lspinstall/dockerfile/node_modules/.bin/docker-langserver" is not executable.
  - INFO: jsonls: configuration checked.
  - ERROR: sumneko_lua: The given command "/home/lakshya/.local/share/nvim/lspinstall/lua/sumneko-lua-language-server" is not executable.

**Comment by rebuilt** [comment]
Neovim comes bundled with a language client but not a language server. To install a supported language server:
```bash
  :LspInstall <your_language_server>
```

Are you having trouble with a specific server?  I see you've installed python.  Is the language server for python not attaching?  If so, try 
```bash
:LspStart python
```
Then check
```bash
:messages
```
