### ISSUE TITLE
stuck at startup on ArchWsl

### ISSUE THREAD

**Issue by streetmask** [ChristianChiarulli/LunarVim#354]
Brand new installed. Every time I run 'nvim', it gets stuck forever until I press 'ctrl+c'. Here is part of startuptime:

![WindowsTerminal_p9jFmANU4L](https://user-images.githubusercontent.com/30765414/116959236-93094c80-accf-11eb-8969-c6a18ff9507b.png)

Solved for now by deleting the clipboard.vim file. But it doesn't appear to be a good solution.

**Comment by rebuilt** [comment]
Do you have a clipboard tool installed?

https://github.com/ChristianChiarulli/LunarVim#clipboard-support

**Comment by streetmask** [comment]
@rebuilt After I saw this problem, I ran these commands as written under "WSL2". And it's still the same. But now I installed xclip and it worked.(I used xsel before)    Thanks : )  It was my mistake.
