### ISSUE TITLE
error in setting up yaml formatter

### ISSUE THREAD

**Issue by ashincoder** [ChristianChiarulli/LunarVim#355]
This is the error I get

E5113: Error while calling lua chunk: /home/ashin/.config/nvim/init.lua:4
: Vim(luafile):E5113: Error while calling lua chunk: /home/ashin/.config/
nvim/lv-settings.lua:42: attempt to index field 'yaml' (a nil value)
Press ENTER or type command to continue

I was trying to set a yaml formatter and autoformat
O.yaml.formatter = 'prettier'
O.yaml.autoformat = true

what is the error please tell me

**Comment by rebuilt** [comment]
Those options don't exist in the global object 'O'.  Formatting options aren't modifiable for all language types.  For yaml, formatting is provided by the efm language server and it's hard coded to use prettier already.   Just make sure you :LspInstall efm, that you're in a git directory and that :LspInfo reports the efm language server is attached to the current buffer.  

Read this section of the readme:  https://github.com/ChristianChiarulli/LunarVim#lsp-errors

**Comment by rebuilt** [comment]
The global object 'O' is defined in ~/.config/nvim/lua/lv-globals.lua  if you're curious about the options you can change.
