### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by talefe** [ChristianChiarulli/LunarVim#356]
I am not sure if I need to change some permissions, but am getting the following error after a clean install 
![Screenshot 2021-05-04 at 13 24 00](https://user-images.githubusercontent.com/31940907/117002953-25afe880-acdc-11eb-8bab-34fd6240f744.png)

**Comment by rebuilt** [comment]
Did you install using sudo?  If so, follow the instructions for uninstalling https://github.com/ChristianChiarulli/LunarVim#uninstalling.

And try again without sudo.

**Comment by talefe** [comment]
I didn't... anyway, after uninstall and install again, it works! thanks @rebuilt !
