### ISSUE TITLE
Some nvim-tree keybinding stopped working

### ISSUE THREAD

**Issue by soerenmartius** [ChristianChiarulli/LunarVim#365]
After pulling in the latest updates, some keybindings stopped working:

- Can't expand / close nested directories anymore with the normal `h` and `l` navigation
- `l` won't load files anymore

**Comment by ChristianChiarulli** [comment]
yea, I think thats because I made it optional @rebuilt.

**Comment by rebuilt** [comment]
Probably.

**Comment by rebuilt** [comment]
I wonder if making them both required, instead of both optional will work.

**Comment by rebuilt** [comment]
I just don't know enough about how packer works.  Is it because these plugins are in different root directories?  Is it because optional plugins load after required plugins that causes an issue?  Hard to say.

**Comment by rebuilt** [comment]
I'm looking into it now.

**Comment by rebuilt** [comment]
@soerenmartius Did you run 
```bash
:PackerSync
:PackerCompile
```
The most recent changes move nvim-tree to the optional folder and those commands need to be run to perform the move.
This is only required if you pulled in recent changes, not if you installed a clean build.  Can you let us know how you got the new version?

**Comment by rebuilt** [comment]
I have no idea why this works.  Place 'require('lv-nvimtree')' above 'require('colorscheme')'. 

Nvimtree will not have the colorscheme applied to it but the controls will work as expected.  
Somthing about setting the color on it breaks the controls when it's lazy loaded.

**Comment by soerenmartius** [comment]
> I have no idea why this works. Place 'require('lv-nvimtree')' above 'require('colorscheme')'.
> 
> Nvimtree will not have the colorscheme applied to it but the controls will work as expected.
> Somthing about setting the color on it breaks the controls when it's lazy loaded.

Yip that works. Shall I open a PR?

**Comment by rebuilt** [comment]
@soerenmartius  I wanted to make some comments about further steps on the PR.  So I submitted it myself.
