### ISSUE TITLE
which key error

### ISSUE THREAD

**Issue by venson** [ChristianChiarulli/LunarVim#366]
After the lasted gitpull,
got error on whichkey

```
E5108: Error excuting lua ...te/pack/packer/opt/which-key.nvim/lua/which-key/view.lua:44: Invalid key 'border'
```

**Comment by ChristianChiarulli** [comment]
You need to update Neovim I think

**Comment by rebuilt** [comment]
After pulling did you run 
```bash
:PackerCompile
:PackerInstall
```

**Comment by rebuilt** [comment]
You may also need :PackerSync to update whichkey, depending on how old it is.

**Comment by venson** [comment]
1.neovim verison
NVIM v0.5.0-dev+1165-ge5bef5974
Build type: Release
LuaJIT 2.1.0-beta3

Just reinstalled from aur by  `yay -S neovim-git` just a minute ago, but I don't know why it is not the latest version

2. I did run PackerCompile and install ,even rm .local/share/nvim

**Comment by venson** [comment]
might be coutom repository problem 
work alright after manual delete old neovim

**Comment by dimas-cyriaco** [comment]
I had this problem too. Had to reinstall Neovim from source. Now it's working fine.
