### ISSUE TITLE
Issue of which-key floating-window "toggle" experience

### ISSUE THREAD

**Issue by daiyanze** [ChristianChiarulli/LunarVim#369]
### Major issue:
I'm not quite sure if toggling is the default behavior for the lunarvim. But it's very nice to have such feature.

The vim-which-key floating window seems not open by toggling the spacebar for the second time visit. When you tap the spacebar to display the which-key window, it pops out promptly. Then tap the spacebar to close that window, it closes promptly but it also shifts the cursor 3 whitespaces to the right. If you tap the spacebar during the "whitespace-shifting" then the which-key window will never show up. Instead, it will continue the shifting...

![2021-05-06 11-01-47 2021-05-06 11_05_17](https://user-images.githubusercontent.com/14920529/117231871-12775700-ae5b-11eb-8644-83ce7c4b00db.gif)

**Plus:** 
On my Mac, it takes around 1.5 second to open up this window. The pop-up speed is not as good as it was (I think it was a different window under the galaxyline, right?). Sometimes it's quite frustrating since I hope to open it up faster...

#### How to produce

1. Tap the spacebar, tap again after the window popup
2. Tap the spacebar right after the window closes

#### Expected Behavior

- The which-key window can be reopen by "toggling" the spacebar. (Should have)
- The which-key window can be open / closed without moving the cursor. (Good to have)
- The which-key window pops up faster (less than 1 second). (Good to have)

**Comment by ChristianChiarulli** [comment]
I think I'll add timeoutlen to lv-settings so people can choose what they like for the speed. For the space issue I recommend putting an issue in on the which key repo.

**Comment by thepenguinthatwants** [comment]
o.timeoutlen=100
So far it has felt to work like a breeze, but not sure what are the con's

**Comment by folke** [comment]
when you tap the first space, which key opens, then with the second space, we see no keybinding exist, so we emit the two spaces instead. Which results in literal spaces.

This is expected behavior. There's no toggling. You can close the popup with `<esc>` to cancel any pending keys.

**Comment by daiyanze** [comment]
@ChristianChiarulli @thepenguinthatwants 
Thanks! I second the idea of putting the "timeout" to lv-settings. Just checked the latest commit, the popup looks just fine.
Guess that "space shifting" triggered by "spacebar toggle" is the which-key issue then.

**Comment by daiyanze** [comment]
I'll consider to ask which-key for the "space shift" issue (perhaps it is expected behavior)
Allow me to close this issue for now.

**Comment by folke** [comment]
@daiyanze I am the author of which Key, see my comment above 😉

**Comment by daiyanze** [comment]
@folke 
Sorry, didn't notice your comment during typing. Thanks to your comment, I totally get why I got 2 whitespace shift now (I'm quite a Vim noob).

If I understand it correctly, that shifting is intended by vim itself. That 2 spaces (the "toggle" which I mistakenly think of as) were actually the delayed directives by the `timeoutlen`.

**Comment by folke** [comment]
@daiyanze yep, exactly that :)
