### ISSUE TITLE
Tabs are inserted instead of spaces

### ISSUE THREAD

**Issue by dklymenk** [ChristianChiarulli/LunarVim#372]
`vim.bo.expandtab = true` in `settings.lua` doesn't seem to work. In a freshly installed LunarVim pressing tab causes a tab character to be inserted instead of 2 (or 4 depending of file format) spaces to be inserted.

neovim build: `NVIM v0.5.0-dev+1282-gfbe18d9ca`

`vim.bo.expandtab = true` seems to work in clean `init.lua`, but not LunarVim.

For now my fix is replacing `vim.bo.expandtab = true` with `vim.cmd('set expandtab')`.

**Comment by rebuilt** [comment]
I don't think expandtab is under 'bo'.  It should be 'o'.

Try
```lua
vim.o.tabstop = 4  -- Insert 4 spaces for a tab
vim.o.shiftwidth = 4 -- Change the number of space characters inserted for indentation
vim.o.expandtab = true -- Converts tabs to spaces
```

Also, there are tab settings for individual file types in the ftplugin folder that define tabstops for filetypes.

**Comment by rebuilt** [comment]
After a little more research, yes, there is a 'tabstop' available under the buffer-local object but I think setting it like that will only apply to the first buffer you open.  This setting will not apply for all subsequent buffers.

**Comment by dklymenk** [comment]
Yes, thank you. `vim.o.expandtab = true` was the solution. 

I assume this line should be updated in the repo https://github.com/ChristianChiarulli/LunarVim/blob/master/lua/settings.lua#L24

Btw, does this mean that `vim.bo.smartindent = true` should be `vim.o.smartindent = true`?

**Comment by rebuilt** [comment]
Yep

**Comment by dklymenk** [comment]
Actually that seems to work only for js files. When I press tab in insert mode in of the lua files it still inserts a tab character and that's not the case with `vim.cmd('set expandtab')`

The `ftplugin/javascript.vim` only has these 2 lines:
```
set ts=2
set sw=2             
```

**Comment by rebuilt** [comment]
Huh.  Ok.  If that works, then let's go with that.  Want to make a PR or should I?

**Comment by dklymenk** [comment]
I'll do a PR. I'll also try to test `smartindent` to see if the lua way of setting it works or needs to be changed to `vim.cmd`

**Comment by rebuilt** [comment]
Also try explicitly turning on autoindent
From :h smartindent
```md
	Normally 'autoindent' should also be on when using 'smartindent'.
```
I think neovim turns autoindent on by default but I'm not sure.

**Comment by dklymenk** [comment]
@rebuilt I could not figure out the difference between `smartindent` and `nosmartindent`. No matter what I throw at it, the behavior is always the same.

For example, inserting a new line after `function test() {` always adds indent regardless of the setting. Adding `}` removes indent. All according to `:h smartindent`.

`autoindent` seems to be enabled in nvim by default too, so PR only applies the change to `expandtab` and doesn't touch anything else.

**Comment by dklymenk** [comment]
Closing the issue as relevant PR was merged into master.

**Comment by rebuilt** [comment]
Thanks for this PR
