### ISSUE TITLE
Support for neovide

### ISSUE THREAD

**Issue by lakshyarao22** [ChristianChiarulli/LunarVim#375]
Hey,
Can you guys add support for neovide in lunar vim config.

**Comment by rebuilt** [comment]
It works for some people.  Make sure you compile from source and have graphics drivers installed.

**Comment by lakshyarao22** [comment]
Sorry but I ment to say that add some gui configuration in script so experience is similar on both terminal and neovide.

**Comment by rebuilt** [comment]
What's different?

**Comment by lakshyarao22** [comment]
add configs for neovide like icons and font and other configs which neovide needs.

**Comment by ChristianChiarulli** [comment]
If someone has neovide specific config, consider making a PR

**Comment by rafamadriz** [comment]
> add configs for neovide like icons and font and other configs which neovide needs.

There is already a font setting in lunarvim https://github.com/ChristianChiarulli/LunarVim/blob/04f9f53914a7dd999117ed73c5fa0ab3b0dc95e4/lua/settings.lua#L27 and the rest of settings that neovide have are very specific to each user (like refresh rate, cursor blinking, etc).
