### ISSUE TITLE
PackerInstall issue with which-key

### ISSUE THREAD

**Issue by warscovich** [ChristianChiarulli/LunarVim#376]
Hi all,

I'm getting a packer initialization exception for which-key. I already tried re-installing packer and cleaning dependencies but no luck.

![Screen Shot 2021-05-06 at 6 18 51 PM](https://user-images.githubusercontent.com/5246972/117373028-87b54d00-ae98-11eb-8560-859c5982a3e7.png)

**Comment by rebuilt** [comment]
What's the output of 
```lua
:lua print(require("which-key.config").options.window.border)
```
It should be one of these
```
    border = "none", -- none, single, double, shadow
```

I know bqf makes modifications to quickfix windows and their borders.  Disable that plugin and see if it changes anything.

**Comment by warscovich** [comment]
Borders are "single". Let me try to disable that plugin but not sure if is the issue.

**Comment by warscovich** [comment]
After investigating further on view.lua:44 checked `nvim_open_win({buffer}, {enter}, {config}) ` and found out that border property is valid. Re-installed nvim again and worked!

Thanks for the support!
