### ISSUE TITLE
Received Error when clicking "Find file" after updating neovim to the latest version

### ISSUE THREAD

**Issue by septimochen** [ChristianChiarulli/LunarVim#379]
I had the same issue both on my WSL2 Ubuntu and fedora 34 workstation after updating the neovim to latest version today.
The error message is 
**"Error detected while processing function <SNR>63_call_line_function:
line    6:
E5108: Error executing lua ...ck/packer/opt/plenary.nvim/lua/plenary/window/border.lua:138: Vim(autocmd):E680: <buffer=7>: invalid buffer number"**

the neovim version on Ubuntu is **0.5.0+ubuntu2+git202105080115-516551319-d569569c9-fc99fc877~ubuntu20.04.1**
and on fedora is **v0.5.0-dev+1309-g516551319**

**Comment by Chiodood** [comment]
Same issue on macOS

**Comment by septimochen** [comment]
> I had the same issue a while ago but it was caused by an outdated version of Plenary. So in my case running PackerSync fixed it for me.

Issue is fixed, many thanks.
