### ISSUE TITLE
Clipboard not shared with OS

### ISSUE THREAD

**Issue by simonfontana** [ChristianChiarulli/LunarVim#380]
Clipboard from middle-mouse button (forgot what it's called) is not synced between Lunar and OS. I believe this is not intended.

How to reproduce:
1. Open vim. Write some nonsense. Highlight it. Exit vim.
2. Open vim. In another window, highlight text from terminal/browser/other application. 
3. Paste with middle-mouse into vim (insert-mode). 
Result: Nonsense text from step 1 was pasted.

The same works vice-versa:
1. Open vim. Write some nonsense. Highlight it. 
2. In another application, paste your nonsense with middle-mouse click. 
Result: Nonsense text from step 1 was not pasted. Instead whatever was in your OS clipboard was pasted. 

My system: Ubuntu 20.04. Clean installation of LunarVim, moved my .vimrc file to not interfere.

**Comment by rebuilt** [comment]
Do you have a clipboard tool installed?  https://github.com/ChristianChiarulli/LunarVim

**Comment by simonfontana** [comment]
I did not... But that only solved the first problem. I still can't copy from vim and paste somewhere else.

**Comment by rebuilt** [comment]
Comment out this line 
```bash
vim.o.mouse = "a" -- Enable your mouse
```

**Comment by rebuilt** [comment]
Look [here](https://unix.stackexchange.com/questions/139578/copy-paste-for-vim-is-not-working-when-mouse-set-mouse-a-is-on) for alternate solutions.

**Comment by simonfontana** [comment]
Thanks again. There are many options. I'll leave it as "a" and use shift+mark for now.

**Comment by simonfontana** [comment]
Maybe we should open a FAQ section in the documentation for these kinds of newbie questions. WDYT?

**Comment by rebuilt** [comment]
Be the PR you want to see in the repo.

**Comment by simonfontana** [comment]
Agreed. Just wanted to hear your opinion. I might make a PR for this in the future. Closing the issue since you answered my questions.
