### ISSUE TITLE
jsx/tsx commenting

### ISSUE THREAD

**Issue by cj** [ChristianChiarulli/LunarVim#384]
Hi all hope you're having a great weekend!

I just found this plugin https://github.com/JoosepAlviste/nvim-ts-context-commentstring and it works perfectly!

I'll create a pull request soon.

**Comment by ChristianChiarulli** [comment]
I tried this before and it didn't seem to work properly, if you get it working well I'd be interested in seeing how you set it up.

**Comment by aaronclimbs** [comment]
I've hacked around and gotten this to work with Kommentary for files that have the .jsx extension, but not the .js extension. It's not quite working to the point where I'd put in a PR but I'm curious as to how you have it configured.
