### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by jwnpoh** [ChristianChiarulli/LunarVim#385]
Hi there, thanks for this project. I'm loving the default settings that's making nvim quite a joy to use.

I'm getting this error quite persistently:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:394: Vim:E474: Error while dum
ping encode_tv2json() argument, key 'params', key 'settings', key 'root_dir': attempt to dump function reference
```
This error message aside I don't think I'm experiencing any issues with normal function of nvim. But the error msg is a little disconcerting. May I get some help for how to fix it please?

Thanks for your time.

**Comment by gfsd3v** [comment]
any update on that ?

**Comment by rebuilt** [comment]
Check the lsp logs for more info.  

You'll probably find the log in this directory ~/.cache/nvim/lsp.log
But if not
```
:lua print(vim.lsp.get_log_path())
```

**Comment by rebuilt** [comment]
Also run :checkhealth

**Comment by jwnpoh** [comment]
Hi there, thanks for your help and attention. In the end I re-installed LunarVim and the issue went away. I must've messed up my configs somewhere along the way the first time round. Everything's working fine now so I will close this.
