### ISSUE TITLE
Inconsistent indenting

### ISSUE THREAD

**Issue by dylantjb** [ChristianChiarulli/LunarVim#391]
Hello, I am hoping to get some help pinpointing the plugin creating this issue. In LunarVim, writing with indents seems fine until you see the actual file when you're finished. On the left and right is neovim with and without the config respectively.

![2021-05-13_00-19](https://user-images.githubusercontent.com/49583764/118056003-06225b00-b381-11eb-84e3-e55e32d80676.png)

**Comment by rebuilt** [comment]
Does :retab help?  That command will convert tabs to spaces.  

```
https://howchoo.com/g/m2u0nthkyti/vim-convert-tabs-to-spaces
```

**Comment by rebuilt** [comment]
:h retab

**Comment by dylantjb** [comment]
Tried, but it has no effect as they are spaces already

**Comment by phuongortheeast** [comment]
Personally, I alias `sudo -E nvim` so I can edit file as superuser with lunarvim, it will also help with the indenting

**Comment by ChristianChiarulli** [comment]
I think this should be solved with treesitter.

**Comment by rafamadriz** [comment]
Neovim help page for tabstop:

> 	Note: Setting 'tabstop' to any other value than 8 can make your file
	appear wrong in many places (e.g., when printing it).

LunarVim [sets tabstop](https://github.com/ChristianChiarulli/LunarVim/blob/04f9f53914a7dd999117ed73c5fa0ab3b0dc95e4/lua/default-config.lua#L22) to `2` by default, maybe that's the problem.

**Comment by luxus** [comment]
tab_stop is not changed anymore from the default.
maybe this issue can be closed

**Comment by rebuilt** [comment]
Closing since we no longer modify tabstops.  If you still experience this issue on the latest release please reopen
