### ISSUE TITLE
How to configure debuger?

### ISSUE THREAD

**Issue by habsfanongit** [ChristianChiarulli/LunarVim#395]
Hi,
I tried to configure the nvm-dap using the instructions here https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#Javascript by copying the configurations to `~/.config/nvim/lua/lv-nvim-dap/init.lua` like
```
  local dap = require('dap')
 dap.adapters.node2 = {
  type = 'executable',
  command = 'node',
  args = {os.getenv('HOME') .. /dev/microsoft/vscode-node-debug2/out/src/nodeDebug.js'},
 }
dap.configurations.javascript = {
  {
  type = 'node2',
 request = 'launch',
 program = '${file}',
cwd = vim.fn.getcwd(),
sourceMaps = true,
 protocol = 'inspector',
 console = 'integratedTerminal',
    },
 } 
```
then ran PackerSync and PackerUpdate then 
initialized node using `npm init` but I still get `No configuration found for JavaScript` when I try to debug a simple node app.
I must be missing something simple but I am stumped

**Comment by rebuilt** [comment]
Did you also include the configuration file in init.lua?

```
require('lv-nvim-dap')
```

**Comment by rmagillxyz** [comment]
@habsfanongit did you install vscode-node-debug2? You have to replace `/dev/microsoft/vscode-node-debug2/out/src/nodeDebug.js` with wherever you built it. Also, I couldn't get it to work on a single file, I had to create a git repo, a `package.json`, and replace `program = '${file}'` with the full path to the file before I got it to run. If you figure out how to get `'${file}'` to work let me know.  I'll try it on a full project later and see if I can get it to run on that.

**Comment by ChristianChiarulli** [comment]
I don't have an official solution for debugging in lunarvim yet

**Comment by epileftro85** [comment]
Is there an option for this inside lunarVim?
