### ISSUE TITLE
Lsp Formatting and preview definition

### ISSUE THREAD

**Issue by Lazk3r** [ChristianChiarulli/LunarVim#397]
`:LspInstall efm`
`:LspInstall python`

After that I tried to use LspFormatting command but doesn't work.

I also try to use Lspsaga preview_definition command and then a got this error:

![Captura de pantalla_2021-05-14_19-58-07](https://user-images.githubusercontent.com/82919717/118343454-ad85c600-b518-11eb-8e9a-29abf8ad7959.png)

**Comment by rebuilt** [comment]
In init.lua
Move lv-settings to line 2 below lv-globals
```lua
require('lv-globals')
vim.cmd('luafile ~/.config/nvim/lv-settings.lua')
```

Looks like the statements have been reordered in this version.  lv-settings needs to get imported before any files that depend on its settings.  
```
settings.lua
lv-compe/init.lua
lsp/ruby-ls.lua
lv-autocommands/init.lua
efm-general-ls.lua
colorscheme.lua
lv-treesitter/init.lua
and anything in the lsp folder
```

This should fix autoformatting.  I'm not sure about the Lspsaga error.

**Comment by Lazk3r** [comment]
I moved lv-settings to line 2, but still formatting doesn't work.
