### ISSUE TITLE
lsp csharp

### ISSUE THREAD

**Issue by zreus** [ChristianChiarulli/LunarVim#399]
.cs files dont detect language server status bar "No Active Lsp"
:LspInfo 

Configured servers: cssls, clangd, terraformls, vimls, html, gopls, graphql, jsonls, solargraph, yamlls, bashls, elmls, dartls, texlab, svelte, tsserver, kotlin_language_server, emmet_ls, angularls, pyright, intelephense, sumneko_lua, dockerls, efm, rust_analyzer, vuels

0 client(s) attached to this buffer: 

0 active client(s): 

Clients that match the filetype cs:

**Comment by rebuilt** [comment]
Csharp support isn't included in LunarVim yet.   You'll need to follow the instructions on the lspconfig project to configure it yourself.

https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#omnisharp

You'll need to include configuration that looks like the code below.  Make a file for it somewhere in the lsp folder and then include that file in your init.lua.  Make sure the path to the command matches what ends up on your system.  

```
local pid = vim.fn.getpid()
-- On linux/darwin if using a release build, otherwise under scripts/OmniSharp(.Core)(.cmd)
local omnisharp_bin = "/path/to/omnisharp-repo/run"
-- on Windows
-- local omnisharp_bin = "/path/to/omnisharp/OmniSharp.exe"
require'lspconfig'.omnisharp.setup{
    cmd = { omnisharp_bin, "--languageserver" , "--hostPID", tostring(pid) };
    ...
}
```


The LspInstall plugin includes omnisharp so you'll be able to install a language server with

```lua
:LspInstall csharp
```

Once you have it up and running, consider making a pr to add support for csharp in lunarvim so others can follow after you.

**Comment by kdav5758** [comment]
This is what mine looks like:

```lua
local pid = vim.fn.getpid()
local omnisharp_bin = DATA_PATH.."/lspinstall/csharp/run"

require'lspconfig'.omnisharp.setup{
    cmd = { omnisharp_bin, "--languageserver" , "--hostPID", tostring(pid) };
	filetypes = { "cs", "vb" },
    init_options = {},
    root_dir = root_pattern(".csproj", ".sln")
}
```

I'm on Fedora Linux btw.

**Comment by italo-amaya-utec** [comment]
how would including the config in the init.lua would look like?

**Comment by rafamadriz** [comment]
> how would including the config in the init.lua would look like?

Follow the lspconfig guide https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md

Closing for now.
