### ISSUE TITLE
Auto formatting not working in Python

### ISSUE THREAD

**Issue by YeluguriMonish** [ChristianChiarulli/LunarVim#400]
Hello,
I cannot get auto formatting to function for python files. I have looked at other similar issues opened by other users, but the solutions presented in those threads did not work for me. I have initialized a git repository in the location of the file, the efm lsp server is installed, yapf and flake8 were both installed using pip, there is no error message when I save, and :LspInfo shows that the pyright server and the efm server are both attached to the buffer. I have attached my nvim config and the directory i am using to test the formatter. Any help is appreciated.
[nvim.tar.gz](https://github.com/ChristianChiarulli/LunarVim/files/6488644/nvim.tar.gz)
[test.tar.gz](https://github.com/ChristianChiarulli/LunarVim/files/6488645/test.tar.gz)

**Comment by YeluguriMonish** [comment]
I also just tested the autoformatting for a javascript file and I am having the same issue. No error but no formatting either.

**Comment by rebuilt** [comment]
What's the output of :LspInfo and
```vim 
:set filetype?
```

**Comment by YeluguriMonish** [comment]
:LspInfo
Configured servers: html, efm, gopls, yamlls, dockerls, vuels, vimls, rust_analyzer, dartls, kotlin_language_server, emmet_ls, svelte, texlab, bashls, clangd, tsserver, terraformls, intelephense, sumneko_lua, cssls, jsonls, elmls, graphql, pyright, angularls, solargraph
Neovim logs at: /home/monish/.cache/nvim/lsp.log

2 client(s) attached to this buffer: efm, pyright

  Client: efm (id 1)
  	root:      /home/monish/test
  	filetypes: lua, python, javascriptreact, javascript, typescript, typescriptreact, sh, html, css, json, yaml, markdown, vue
  	cmd:       /home/monish/.local/share/nvim/lspinstall/efm/efm-langserver
  	


  Client: pyright (id 2)
  	root:      /home/monish/test
  	filetypes: python
  	cmd:       /home/monish/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	


2 active client(s): 

  Client: efm (id 1)
  	root:      /home/monish/test
  	filetypes: lua, python, javascriptreact, javascript, typescript, typescriptreact, sh, html, css, json, yaml, markdown, vue
  	cmd:       /home/monish/.local/share/nvim/lspinstall/efm/efm-langserver
  	


  Client: pyright (id 2)
  	root:      /home/monish/test
  	filetypes: python
  	cmd:       /home/monish/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	


Clients that match the filetype python:
  
  Config: efm
  	cmd:               /home/monish/.local/share/nvim/lspinstall/efm/efm-langserver
  	cmd is executable: True
  	identified root:   /home/monish/test
  	custom handlers:   

  Config: pyright
  	cmd:               /home/monish/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	cmd is executable: True
  	identified root:   /home/monish/test
  	custom handlers:   textDocument/publishDiagnostics

:set filetype
filetype=python

**Comment by rebuilt** [comment]
Make sure you've installed the autoformatter you want to use
```
pip install yapf
pip install black
```

In init.lua
Move lv-settings to line 2 below lv-globals
```lua
require('lv-globals')
vim.cmd('luafile ~/.config/nvim/lv-settings.lua')
```

Looks like the statements have been reordered in this version.  lv-settings needs to get imported before any files that depend on its settings.  
```
settings.lua
lv-compe/init.lua
lsp/ruby-ls.lua
lv-autocommands/init.lua
efm-general-ls.lua
colorscheme.lua
lv-treesitter/init.lua
and anything in the lsp folder
```

**Comment by YeluguriMonish** [comment]
Moving lv-settings to line 2 fixed the issue. Appreciate your help, thank you!
