### ISSUE TITLE
ranger linemode devicons 

### ISSUE THREAD

**Issue by zreus** [ChristianChiarulli/LunarVim#401]
dont show icons error:

if i run "ranger" in terminal icons are fine but if run "nvim ./" icons missing

loading...rangerInvalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime/humanreadablemtime/sizehumanreadablemti....

**Comment by ChristianChiarulli** [comment]
seems like an issue with ranger itself.
