### ISSUE TITLE
Ruby autoformatter no longer working

### ISSUE THREAD

**Issue by jonathan-raines** [ChristianChiarulli/LunarVim#402]
Good evening

At some point of updating to the latest master branch, I've noticed that the ruby auto formatter is no longer working for me. When it was first introduced, I would detect the changes being made on save. Now I don't see any changes ever being made on save. I'm not sure what diagnostics I can run to debug the issue.

Here's my current configuration of LunarVim (Under the ruby branch)  [git@github.com:jonathan-raines/LunarVim.git](url)

**Comment by rebuilt** [comment]
In init.lua
Move lv-settings to line 2 below lv-globals
```lua
require('lv-globals')
vim.cmd('luafile ~/.config/nvim/lv-settings.lua')
```

Looks like the statements have been reordered in this version.  lv-settings needs to get imported before any files that depend on its settings.  
```
settings.lua
lv-compe/init.lua
lsp/ruby-ls.lua
lv-autocommands/init.lua
efm-general-ls.lua
colorscheme.lua
lv-treesitter/init.lua
and anything in the lsp folder
```

**Comment by rebuilt** [comment]
Also add these lines to lv-autopairs/init.lua if you want endwise pairings.

```
  local endwise = require('nvim-autopairs.ts-rule').endwise

  npairs.add_rules({
    endwise('def', 'end',nil,nil),
    endwise('if', 'end',nil,nil)
  })
```

**Comment by jonathan-raines** [comment]
That solved it! Thank you for your help! I also added the endwise functionality to nvim-autopairs. It seems to not work with nvim-compe suggestions showing. I guess I need to play around a bit and try to figure out why. If the suggestions aren't showing, it does add end to those keywords.
