### ISSUE TITLE
MDX Syntax Highlighting

### ISSUE THREAD

**Issue by rkabrick** [ChristianChiarulli/LunarVim#405]
Hello, 

Is MDX syntax highlighting supposed to be included in any of the Typescript (or any other) LSP options offered? If so, which? 

If not, how would I go about porting the VSCode MDX plugin to NVIM? I'd gladly do that and submit a PR I would just need a nudge in the right direction. 

Thanks in advance!

**Comment by frontendwizard** [comment]
Would love to see that as well

**Comment by ChristianChiarulli** [comment]
look into treesitter
