### ISSUE TITLE
Python Code Actions and Auto Imports

### ISSUE THREAD

**Issue by numine777** [ChristianChiarulli/LunarVim#407]
I've fought with this all day to no avail, so I'm opening an issue here in hopes that I'm just doing something wrong.  I have LunarVim setup with one added plugin (which shouldn't be a major issue -- git-worktrees).  Initially, when I would start my nvim and navigate to a .py file in my repo, I would experience a situation in which the lsp takes about a minute to initialize each time followed by my local imports failing to resolve.  At that time, I was merely using pyenv with a global version (3.7.10) set.  Now I have set a virtualenv up to attempt to rectify the problem, however, the only difference now is that no imports resolve.  My python-ls.lua is configured as follows
```
require'lspconfig'.pyright.setup {
    cmd = {DATA_PATH .. "/lspinstall/python/node_modules/.bin/pyright-langserver", "--stdio"},
    on_attach = require'lsp'.common_on_attach,
    handlers = {
        ["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
            virtual_text = O.python.diagnostics.virtual_text,
            signs = O.python.diagnostics.signs,
            underline = O.python.diagnostics.underline,
            update_in_insert = true
        })
    },
         settings = {
      python = {
        venvPath = "/Users/michaelwalls/.pyenv/versions",
        venv = O.python.venv,
        analysis = {
                  typeCheckingMode = O.python.analysis.type_checking,
                  autoSearchPaths = O.python.analysis.auto_search_paths,
          useLibraryCodeForTypes = O.python.analysis.use_library_code_types
        }
      }
    }
}
```
Sadly, my situation refuses to resolve itself.  Is this an issue with the setup configuration?  Or is it probable that I'm missing something else?  Any and all help greatly appreciated!  Loving what you all have put together here!

**Comment by numine777** [comment]
Update for anyone else experiencing similar woes: pyls (python-language-server pip package) can be used instead by commenting the python-ls.lua file and adding `require'lspconfig'.pyls.setup{ on_attach=require'lsp'.on_attach }`.  Immediate performance jump.  However, I'm still invested in figuring out the pyright issue if anyone has any ideas.

**Comment by numine777** [comment]
Further update: PyRight is now working for the most part, my issue was largely the determination of the project root.  Adding `BUILD.bazel` to the `root_files` object referenced here https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/pyright.lua .  My only remaining issues are that imports from adjacent packages/svcs inside the monorepo aren't accessible and code actions (at least auto imports) are not showing up as available.  As always thanks in advance for any help!

**Comment by numine777** [comment]
Despite swapping out to pyls, pyright, pyls_ms, and jedi, I haven't managed to get code actions or auto imports to work with Python.  Other languages are unaffected so my only remaining question is: does anyone have a configuration that works?  I know CoC makes it happen, but haven't seen anything for the native LSP.

**Comment by Joellidin** [comment]
I have just started messing around with LunarVim and I cant get code actions to work with python either. But on the other hand I cant even get diagnostics to work when writing in C so I am doing something wrong.
