### ISSUE TITLE
netrw bug Cursor goes into num column/nvim_tree BUG

### ISSUE THREAD

**Issue by adhamramy** [ChristianChiarulli/LunarVim#409]
The cursor is on the line number column in both the dashboard and while editing a file.

It occurs after using gx to open a file in an external program.
does not occur after disabling by `nvim_tree_disable_netrw = 1` but this is not a fix

https://user-images.githubusercontent.com/63326537/118648604-43f10a80-b7eb-11eb-9382-6413d2483648.mp4

Config is unchanged only added a couple bindings
Using alacritty on wsl2 , tried different terminals same result

**Comment by adhamramy** [comment]
Tried again and was fine till I used gx so it is the cause for some reason.

**Comment by adhamramy** [comment]
also for wsl users could you add an option to enable this `vim.cmd('let g:netrw_browsex_viewer="wslview"')
` from lv-settings as without it, some files wont open like hrml files in browser

**Comment by rebuilt** [comment]
By default nvimtree enables netrw and rvimr disables netrw.  Not sure which one wins out.

**Comment by rmagillxyz** [comment]
I think this is caused by a keybinding. Try disabling [this line](https://github.com/ChristianChiarulli/LunarVim/blob/b4446a1a2148bb2af96a20adde373451755ebbe7/lua/keymappings.lua#L20). @adhamramy
