### ISSUE TITLE
Cant open a new buffer with ranger

### ISSUE THREAD

**Issue by GuanryA5** [ChristianChiarulli/LunarVim#41]
I cant open the file in ranger, it's always open a new vim in float ranger.  Eeven I saw the rnvimr FAQ, and add `-!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php = ${VISUAL:-$EDITOR} -- "$@"
+!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php|your_file_type = ${VISUAL:-$EDITOR} -- "$@"`  to ~/.config/ranger/rifle.conf

**Comment by alechp** [comment]
Can't open buffers with ranger anymore either.

1. In a file
![Screen Shot 2020-11-03 at 3 03 15 PM](https://user-images.githubusercontent.com/3058939/98050131-efa1b280-1de5-11eb-8ef5-d5db273bb1ad.png)

2. Open ranger (<leader> + r)
![Screen Shot 2020-11-03 at 3 03 10 PM](https://user-images.githubusercontent.com/3058939/98050186-00522880-1de6-11eb-9536-a6191e0ef9f7.png)

3. Select file, hit enter to open buffer. 
![Screen Shot 2020-11-03 at 3 03 02 PM](https://user-images.githubusercontent.com/3058939/98050221-106a0800-1de6-11eb-93de-9ff0d1328c06.png)

<details><summary>Full error</summary>
<code>
Error while loading plugin 'client'
Error while loading plugin 'hacks'
Error while loading plugin 'host'
Error while loading plugin 'patch'
Error while loading plugin 'rcommand'
Error while loading plugin 'rutil'
Error while loading plugin 'service'
Error while loading plugin 'urc'
Error detected while processing /Users/alechp/Documents/nvim-osx64/share/nvim/runtime/plugin/man.vim
:
line    9:
E10: \ should be followed by /, ? or &
line   10:
E10: \ should be followed by /, ? or &
Error detected while processing /Users/alechp/Documents/nvim-osx64/share/nvim/runtime/plugin/rplugin
.vim[65]..function <SNR>8_LoadRemotePlugins[1]..<SNR>8_GetManifest[1]..<SNR>8_GetManifestPath:
line    7:
E117: Unknown function: stdpath
--- Autocommands ---
Error detected while processing /Users/alechp/Documents/nvim-osx64/share/nvim/runtime/plugin/shada.v
im:
line    9:
E10: \ should be followed by /, ? or &
line   10:
E10: \ should be followed by /, ? or &
line   11:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   13:
E10: \ should be followed by /, ? or &
line   14:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   16:
E10: \ should be followed by /, ? or &
line   17:
E10: \ should be followed by /, ? or &
line   18:
E10: \ should be followed by /, ? or &
line   19:
E10: \ should be followed by /, ? or &
line   20:
E35: No previous regular expression
line   21:
E10: \ should be followed by /, ? or &
line   22:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   24:
E10: \ should be followed by /, ? or &
line   25:
E10: \ should be followed by /, ? or &
line   26:
E10: \ should be followed by /, ? or &
line   27:
E10: \ should be followed by /, ? or &
line   28:
E10: \ should be followed by /, ? or &
line   29:
E10: \ should be followed by /, ? or &
--- Autocommands ---
line   31:
E10: \ should be followed by /, ? or &
line   32:
E10: \ should be followed by /, ? or &
line   33:
E10: \ should be followed by /, ? or &
line   34:
</code>
</details>

4. Hit enter
![Screen Shot 2020-11-03 at 3 03 05 PM](https://user-images.githubusercontent.com/3058939/98050312-43ac9700-1de6-11eb-9710-7a9b25e79c13.png)

5. Quit (:q)

**Comment by ChristianChiarulli** [comment]
did you install ranger with python3?

**Comment by mybigman** [comment]
:checkhealth rnvimr

**Comment by aaronmcadam** [comment]
I'm seeing the same problem. My global version of Python is 3.9.3, but it looks like neovim is using the Apple system version: 
![CleanShot 2021-06-14 at 18 36 34](https://user-images.githubusercontent.com/37928/121934632-75ec8280-cd3f-11eb-8d00-4d6f4d6d969f.jpg)

**Comment by aaronmcadam** [comment]
So I narrowed this down to an issue with how Ranger should be installed: https://github.com/ChristianChiarulli/LunarVim/issues/27#issuecomment-663848337

I think the install script needs to be updated to not use brew on macOS.
