### ISSUE TITLE
Python slow to exit

### ISSUE THREAD

**Issue by the-anonymous-raven** [ChristianChiarulli/LunarVim#411]
There is around 1 second time that exiting a file ending in .py takes. 
There is no considerable delay in exiting any other file formats.

Is there any particular fix for this?

**Comment by rebuilt** [comment]
Are you using the default config or do you have other plugins loaded? 

Check the logs for more info.  

Find the logs in this directory ~/.cache/nvim/

**Comment by rebuilt** [comment]
Also run :checkhealth

**Comment by ChristianChiarulli** [comment]
this could also be the not head version fo efm is being used

**Comment by the-anonymous-raven** [comment]
The prominent errors are:
a. lint for Language Id not supported: python\n
b. completion for Language Id not supported: python\n

**Comment by kdav5758** [comment]
Experiencing the same here...

**Comment by kdav5758** [comment]
I debugged the issue! Or well, at least after doing some testing I concluded that this is **not** a LunarVim problem: in my case, both python and json files took way too long to quit, so after going through the lsp config it seems that it's an **efm-language-server** issue. For now, remove those two from the `filetypes = {}` table at the [config file for efm](https://github.com/ChristianChiarulli/LunarVim/blob/master/lua/lsp/efm-general-ls.lua#L91). It should look like this in thr end:

```lua
	filetypes = {
		"lua",
		-- "python",
		-- "json",
		"javascriptreact",
		"javascript",
		"typescript",
		"typescriptreact",
		"sh",
		"html",
		"css",
		"yaml",
		"markdown",
		"vue"
	},

```

**Comment by rebuilt** [comment]
Someone else was getting the lint for languageID not supported errors.  It seemed to be from an old version of nodejs.  Try updating your version of nodejs.

**Comment by the-anonymous-raven** [comment]
> Someone else was getting the lint for languageID not supported errors. It seemed to be from an old version of nodejs. Try updating your version of nodejs.

I am on version 16.2.0 which is the latest i guess.

**Comment by rebuilt** [comment]
Can you confirm you have yapf installed?

```bash
pip install yapf
```

If you don't have it installed, it will lag when writing a file but not when exiting neovim without writing.

**Comment by the-anonymous-raven** [comment]
> Can you confirm you have yapf installed?
> 
> ```shell
> pip install yapf
> ```
> 
> If you don't have it installed, it will lag when writing a file but not when exiting neovim without writing.

Yes, I do have the latest version of yapf(version 0.31.0), installed from arch repo.
