### ISSUE TITLE
Why indent-blankline.nvim plugin is  commented out?

### ISSUE THREAD

**Issue by thepenguinthatwants** [ChristianChiarulli/LunarVim#412]
Is there plans to configure and use that plugin or is there some issues if its enabled?

**Comment by justinbeatz** [comment]
I was about to ask the same question, did you know why is commented out? I uncomment that line but it seems to now work at all.

**Comment by rebuilt** [comment]
Delete the 'opt = true' value from that line

**Comment by thepenguinthatwants** [comment]
I've gotten it to work
