### ISSUE TITLE
errors at startup

### ISSUE THREAD

**Issue by bishnu-47** [ChristianChiarulli/LunarVim#413]
I am getting following errors while starting nvim:
```
E5113: Error while calling lua chunk: /home/wishnu/.config/nvim/lua/colorscheme.
lua:3: Vim(lua):E5108: Error executing lua vim.lua:296: loop or previous error l
oading module 'vim.lsp'
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading mod
ule 'nvim-tree'
```

**Comment by rebuilt** [comment]
Try running :PackerSync to make sure plugins are installed

**Comment by bishnu-47** [comment]
@rebuilt nothing happend

**Comment by rebuilt** [comment]
Did you install lunarvim using sudo?  If so, a normal user won't have permission to read file created during installation.  Delete the nvim folder and install again without sudo.

**Comment by bishnu-47** [comment]
yeah I recall using sudo, so the nvim folder is in `/snap/nvim` right? 
but I am facing "Read-only file system" problem, can you help me with the command

**Comment by rebuilt** [comment]
Follow the instructions for uninstalling. 

https://github.com/ChristianChiarulli/LunarVim#uninstalling

**Comment by bishnu-47** [comment]
thanks man, that's solves this problem :)
