### ISSUE TITLE
Need help in plugin configuration setup

### ISSUE THREAD

**Issue by bishnu-47** [ChristianChiarulli/LunarVim#414]
I know it's kinda childish, but I am new to this
I was able to Install this plugin
[iamcco/markdown-preview](https://github.com/iamcco/markdown-preview.nvim)
But I can't figure out how to setup the config file properly, I read the [colorizer-example](https://github.com/ChristianChiarulli/LunarVim#an-example-installation-of-the-colorizer-plugin) but I am not able to follow it properly

**Comment by rebuilt** [comment]
What have you tried so far?  What state is your config in?

**Comment by bishnu-47** [comment]
Listing what I did so far
1. Added the following to nvim/lua/plugins.lua
```
 use {"iamcco/markdown-preview.nvim", opt = true}
 require_plugin("iamcco/markdown-preview.nvim")
```

correct me if I did something wrong here

2. This step is what I can't figure out adding **nvim/lua/lv-markdown-preview** folder with init.lua, What should be the content of this init file? 
` require'markdown-preview'.setup()`
how to include the plugin configs here
3. And last step was adding `require('lv-markdown-preview')` to nvim/init.lua but it was giving me errors so I removed it

**Comment by rebuilt** [comment]
What you've done so far should install the plugin without any keybindings.  
Make sure you run :PackerSync so packer downloads the plugin and puts the files in the right place.
Then try :MarkdownPreview to make sure the plugin is installed.
From the readme of that plugin, it looks like it requires a lot of dependencies.
```bash
Katex for typesetting of math
Plantuml
Mermaid
Chart.js
sequence-diagrams
flowchart
dot
Toc
```

These can be installed with:
```bash
:call mkdp#util#install()
```

If all that works, the only think left is to set up a keybinding.  You can do that in lv-which-key.  
Command from the plugin readme:
```bash
" Start the preview
:MarkdownPreview

" Stop the preview"
:MarkdownPreviewStop
```

**Comment by rebuilt** [comment]
Also, that plugin looks dope.  I'll have to try it out myself.

**Comment by bishnu-47** [comment]
The 3 steps i mentioned above after doing that on startup nvim shows following err:
```
E5113: Error while calling lua chunk: /home/wishnu/.config/nvim/lua/lv-markdown-
preview/init.lua:1: module 'markdown-preview' not found:
        no field package.preload['markdown-preview']
        no file './markdown-preview.lua'
        no file '/home/wishnu/neovim/.deps/usr/share/luajit-2.1.0-beta3/markdown
-preview.lua'
        no file '/usr/local/share/lua/5.1/markdown-preview.lua'
        no file '/usr/local/share/lua/5.1/markdown-preview/init.lua'
        no file '/home/wishnu/neovim/.deps/usr/share/lua/5.1/markdown-preview.lu
a'
        no file '/home/wishnu/neovim/.deps/usr/share/lua/5.1/markdown-preview/in
it.lua'
        no file './markdown-preview.so'
        no file '/usr/local/lib/lua/5.1/markdown-preview.so'
        no file '/home/wishnu/neovim/.deps/usr/lib/lua/5.1/markdown-preview.so'
        no file '/usr/local/lib/lua/5.1/loadall.so' 
```
and after doing :PackerSync when I run `:call mkdp#util#install()` It shows following error
`E117: Unknown function: mkdp#util#install`

Maybe I am doing installation steps wrong?

**Comment by rebuilt** [comment]
Just install it as a required plugin not an optional one.  It's easier that way.  Remove the 'opt' from this line  
```
use {"iamcco/markdown-preview.nvim"}
```
You don't need this line if its an autoloaded plugin.
``` 
 require_plugin("iamcco/markdown-preview.nvim")
```

After making edits, restart neovim and run :PackerSync.  After the plugin has been installed run ':call mkdp#util#install()' to install the dependencies.  Then you can open the markdown preview with the command :MarkdownPreview. 

I just tested it myself.  It should work.

**Comment by bishnu-47** [comment]
You are a life saver thanks man.. everything is working fine now

**Comment by rebuilt** [comment]
> You are a life saver thanks man.. everything is working fine now
Great to hear.  You can set up keybindings for it in 'lv-whichkey/init.lua'
