### ISSUE TITLE
"unresolved import" for rust-analyzer and no autocomplete.

### ISSUE THREAD

**Issue by Folaht** [ChristianChiarulli/LunarVim#417]
I'm getting unresolved imports for any dependency I want to use.

I'm not sure but I believe something needs to be changed in the rust-analyzer setup in the rust-ls.lua file in order to fix this.

**Comment by rebuilt** [comment]
For unresolved imports, try reloading as discussed here https://github.com/neovim/nvim-lspconfig/issues/754

**Comment by ChristianChiarulli** [comment]
rust should be fully supported now
