### ISSUE TITLE
Might wanna use this https://github.com/fsouza/prettierd/

### ISSUE THREAD

**Issue by kuator** [ChristianChiarulli/LunarVim#418]
https://github.com/fsouza/prettierd/ runs as a server instead of spawning a new nodejs process every time prettier is run

**Comment by Uzaaft** [comment]
@ChristianChiarulli Is this still of interest? If so, I'll go ahead and try to implement this into LunarVim.

**Comment by ChristianChiarulli** [comment]
I would wait until we implement formatter.nvim, then yes I'm very interested in this.

**Comment by abzcoding** [comment]
we now support perttierd as a part of null-ls
