### ISSUE TITLE
Range file manager throws error when selecting a file on nvim start

### ISSUE THREAD

**Issue by juanlopez4691** [ChristianChiarulli/LunarVim#419]
If I start neovim with `nvim ./`, Ranger file manager is shown, allowing to navigate folders and select a file to edit. The problem is that when I select a file to edit, I get the following error:
```
Error detected while processing function <lambda>6[1]..<SNR>72_defer_check_dir[3]..rnvimr#open[6]..rnvimr#toggle[13]..<SNR>72_reopen_win:
line    2:
E5555: API call: Invalid buffer id: 4
Press ENTER or type command to continue
```
If I press ENTER as stated by the error message, I get a new error line:
```
Error detected while processing function <lambda>8[1]..<SNR>72_defer_check_dir:
line    2:
E5601: Cannot close window, only floating window would remain
Press ENTER or type command to continue
```
Then, If I press ENTER again I get an empty gray floating window.

At this point, I need to quit neovim.

**Comment by rebuilt** [comment]
I dont have a computer this week so I can't check it myself but I'd start by checking this value in lv-globals 'nvim_tree_disable_netrw = 0, '  That enables netrw as the file explorer and a similar value in the rnvimr config that disables netrw.  Also run checkhealth.  

```
Run nvim +'checkhealth rnvimr' in shell. If everything is OK, it will output like these:
health#rnvimr#check
========================================================================
## OS
  - OK: Name: Linux

## Ranger
  - OK: Version: ranger-master

## Python
  - OK: Version: 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]

## Pynvim
  - OK: Version: 0.4.1

## Ueberzug (optional)
  - OK: Ueberzug is ready

## RPC
  - OK: RPC echo: Neovim send "Give me 

```

Try disabling nvimtree entirely to see if there's some conflict.

**Comment by juanlopez4691** [comment]
This is what I get when I run `nvim +'checkhealth rnvimr'`
```
health#rnvimr#check
========================================================================
## OS
  - OK: Name: Mac

## Ranger
  - OK: Version: ranger 1.9.3

## Python
  - OK: Version: 3.9.5 (default, May  3 2021, 19:12:05) [Clang 12.0.5 (clang-1205.0.22.9)]

## Pynvim
  - OK: Version: 0.4.3

## Ueberzug (optional)
  - INFO: Ueberzug is not support for Mac

## RPC
  - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"
```

The `INFO: Ueberzug is not support for Mac` line probably explains why I don't get images previews in rnrvimr (although I can see them in ranger, out of vim). But this would be a different issue.

Finally, setting `nvim_tree_disable_netrw = 1` in file `lv-globals` seems to fix the reported issue.
