### ISSUE TITLE
Install in one command not working

### ISSUE THREAD

**Issue by Nikhil0504** [ChristianChiarulli/LunarVim#421]
I downloaded the latest version of neovim first using the README steps given and it works but when try to do the "Install In One Command!" it raises and error saying:

`Please move your ~/.config/vim folder before installing`

But while checking the directory that folder wasn't present at all and so I created that folder and tried it again which led to the same error. I have no idea what to do.

PS: I am a beginner at this.

**Comment by Nikhil0504** [comment]
Update I delete the folders and tired in a new terminal and it worked but now I am getting this error.

```
Installing LunarVim
pip installed, moving on...
node installed, moving on...
pynvim installed, moving on...
fatal: could not create leading directories of '/home/fuzion/.local/share/nvim/site/pack/packer/start/packer.nvim': Permission denied
```

**Comment by black-eagle17** [comment]
Sounds like you need to run that command as root...just my two cents. Not an expert.

**Comment by kdav5758** [comment]
Don't worry, it's a simple error. Just type `sudo` before the command itself for installing LunarVim, afterwards you'll be prompted to type your password.

**Comment by Nikhil0504** [comment]
> Don't worry, it's a simple error. Just type `sudo` before the command itself for installing LunarVim, afterwards you'll be prompted to type your password.

I tired `sudo bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh) ` and it said directory not found

**Comment by rebuilt** [comment]
Don't install using sudo.  That will lead to permissions errors.  Follow the steps for uninstalling(in the readme) and run the installer again without sudo

**Comment by davibarreira** [comment]
I'm also facing an issue with the installer, but in my case, I get:
```
Command 'nvim' not found, but can be installed with:
sudo apt install neovim
```

**Comment by Nikhil0504** [comment]
Ahh thanks it worked. I am going to close this issue then.
