### ISSUE TITLE
Support for Julia?

### ISSUE THREAD

**Issue by davibarreira** [ChristianChiarulli/LunarVim#423]
First of all, awesome project!
I see that there is no LspInstall for Julia. Any tips on how to setup LunarVim for Julia programming? Could I request addition of support for Julia? I'm more of a user of vim than a developer, so if anyone provides instructions on how to add Julia to LunarVim, I could try to implement a PR.

**Comment by rebuilt** [comment]
Lunarvim is a configuration that uses many external plugins.  LspInstall is a plugin.  If it doesn't support julia, you'll have to install julials on your own.  Lspconfig is another plugin used by lunarvim.  Look on the lspconfig project page for instructions on installing julials and for how to configure lsp for it.  https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md

**Comment by davibarreira** [comment]
Thanks. I was looking into it. I was able to write the `julia-ls.lua` configuration inside my `.config/nvim/lua/lsp`. I've also added the `require('lsp.julia-ls')` to my `init.lua`. How do I then install the lsp server?

**Comment by rebuilt** [comment]
These are the instructions from the lspconfig readme.  

LanguageServer.jl can be installed with julia and Pkg:

julia -e 'using Pkg; Pkg.add("LanguageServer"); Pkg.add("SymbolServer")'

**Comment by davibarreira** [comment]
Yeah, I've done that already. But still not working after all this. I'm guessing there is a step missing...

**Comment by rebuilt** [comment]
What's the output of :LspInfo ?

Make sure it matches the example in the lunarvim readme

**Comment by davibarreira** [comment]
```
Configured servers: dockerls, gopls, cssls, clangd, texlab, emmet_ls, elmls, tsserver, graphql, html, julials, elixirls, pyright, bashls, yamlls, solargraph, dartls, angularls, vimls, terraformls, svelte, kotlin_language_server, vuels, rust_analyzer, jsonls, sumneko_lua, efm, intelephense
Neovim logs at: /home/davibarreira/.cache/nvim/lsp.log

0 client(s) attached to this buffer: 

0 active client(s): 

Clients that match the filetype dashboard:
```

**Comment by rebuilt** [comment]
You may have multiple errors to sort out.  The first is that no language server is matched to the filetype.  Run 'set: filetype?'  To figure out the filetype it's detecting, then in your julials configuration, make sure you add the corresponding filetypes.

**Comment by davibarreira** [comment]
I just got another error, that might be related. I was trying to see if it was working with python, and it seems that the `efm` server is not working. I try installing it, and I get an error.
Here is the LspInfo for the python file:
```
Clients that match the filetype python:
  
  Config: pyright
  	cmd:               /home/davibarreira/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	cmd is executable: True
  	identified root:   /home/davibarreira/.config/nvim
  	custom handlers:   textDocument/publishDiagnostics
  
  Config: efm
  	cmd:               /home/davibarreira/.local/share/nvim/lspinstall/efm/efm-langserver
  	cmd is executable: False. Please check your path and ensure the server is installed
  	identified root:   /home/davibarreira/.config/nvim
  	custom handlers: 
```
Here is the error when trying to run `:LspInstall efm`:
```/bin/bash: line 1: go: command not found

[Process exited 127]```

**Comment by rebuilt** [comment]
Look at the lsp logs or run :messages to get more info on efm errors.  One language server failing won't affect the operation of another language server.  Julials should run whether or not efm runs

**Comment by davibarreira** [comment]
Thanks, it seems that indeed the filetype was the issue. I'll now try to figure out the `efm`.

**Comment by davibarreira** [comment]
Would you know how automate the filetype detection in LunarVim?

**Comment by rebuilt** [comment]
In theory, you can set up something like the code below in a command to run on a keypress or an autocommand to run after a buffer is read(BufWritePost).  But you'd have to check every known filetype for every known language every time you open a buffer.  The expected way for things to work in the current architecture is for the defaults in lspconfig to just work out of the box.  If they don't work for you, you might consider submitting a pull request with lspconfig to add the missing filetype so everyone, not just lunarvim users, will get a good default config for julia.  


```
function _G.check_filetype()
  local lspinstall = require'lspinstall'
  for _, server in ipairs(lspinstall.installed_servers()) do
   If  vim.bo.filetype == 'julia' then
require'lspconfig'.[server].setup {
filetypes =  { "jl"}
end
  end
end

vim.cmd 'command! -nargs=0 LspReinstallAll call v:lua.check_filetype()'
```

**Comment by jvaverka** [comment]
I really want Julia support as well! Happy to help in this effort.

Found a good resource on Julia's discourse that might help us, leaving [here](https://discourse.julialang.org/t/neovim-languageserver-jl/37286) for reference.

**Comment by jvaverka** [comment]
@davibarreira @rebuilt - please review at your convenience.

**Comment by abzcoding** [comment]
Lv now supports Julia : 🎉
