### ISSUE TITLE
"No results form workspace/symbol. Maybe try a different query" when using Telescope lsp_workspace_symbols in a go project

### ISSUE THREAD

**Issue by fabriziosestito** [ChristianChiarulli/LunarVim#425]
Hi, thanks for the great work!

**How to reproduce**
I am getting the no result message when searching for symbols in a Go project with `<leader>lS`

Workspace symbols in a lua project works fine, and issuing the command manually (e.g. `:Telescope lsp_workspace_symbols query=main` ) works as expected.

**Expected result**
Telescope popup opens with no pre-filled search term and it works as in find files.

**Comment by jameswalmsley** [comment]
Telescope now has a lsp_workspace_dynamic_symbols which will work as you expect.

We should change the default which-key binding to do that..

**Comment by fabriziosestito** [comment]
Great, thanks! I'll test it and open a PR in case it works as expected.

**Comment by ChristianChiarulli** [comment]
did we ever fix this?

**Comment by ChristianChiarulli** [comment]
oh, looks like something was merged, thanks.
