### ISSUE TITLE
java errors on startup

### ISSUE THREAD

**Issue by bishnu-47** [ChristianChiarulli/LunarVim#427]
I'm getting these errors while opening java file in nvim:
```
Error detected while processing FileType Autocommands for "java":
E5113: Error while calling lua chunk: /home/wishnu/.config/nvim/lua/lsp/java-ls.
lua:26: module 'jdtls' not found:
        no field package.preload['jdtls']
        no file './jdtls.lua'
        no file '/home/wishnu/neovim/.deps/usr/share/luajit-2.1.0-beta3/jdtls.lu
a'
        no file '/usr/local/share/lua/5.1/jdtls.lua'
        no file '/usr/local/share/lua/5.1/jdtls/init.lua'
        no file '/home/wishnu/neovim/.deps/usr/share/lua/5.1/jdtls.lua'
        no file '/home/wishnu/neovim/.deps/usr/share/lua/5.1/jdtls/init.lua'
        no file '/home/wishnu/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua
/5.1/jdtls.lua'
        no file '/home/wishnu/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua
/5.1/jdtls/init.lua'
        no file '/home/wishnu/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luaro
cks/rocks-5.1/jdtls.lua'
        no file '/home/wishnu/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luaro
cks/rocks-5.1/jdtls/init.lua'
        no file './jdtls.so'
        no file '/usr/local/lib/lua/5.1/jdtls.so'
        no file '/home/wishnu/neovim/.deps/usr/lib/lua/5.1/jdtls.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

guess have to install some kinda lsp.. what are the steps to resolve this?

**Comment by rebuilt** [comment]
Have you installed jdtls? https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#jdtls

**Comment by darkerbess** [comment]
Could you solve it? I also have the same error

**Comment by bishnu-47** [comment]
@darkerbess no I was't able to figure out to configure jdtls in LunarVim

**Comment by pserey** [comment]
Hello! I'm having the same problem. Have someone solved it yet? I've already installed jdtls with `LspInstall java` and all the configuration files seem to be right. But when I open a .java file it shows the same error as in the main issue.

**Comment by pserey** [comment]
Hello @bishnu-47, after days trying to configure my vim for java developing, I'm giving up today. Some people have acomplished to do that, but I can't find a way to do it myself. About the `LspInstall`, I think that as soon as you install lunar vim it would already work, I don't know why it isn't working for you...

[This neovim configuration](https://github.com/s1n7ax/dotnvim) ended kind of working for me a bit, see if you like it and can work with it!

Best regards

**Comment by bishnu-47** [comment]
@pserey are you able to configure the jdtls plugin mentioned by @rebuilt above?
The normal nvim configuration is ok, but I am not able to configure it for lunar vim as its using lua and I am completely unaware of the work flow of Lunar vim

**Comment by pserey** [comment]
Yes, I was too! I kind of did but it didn't work. The `jdtls` is a pain to configure and install, but there's a more detailed tutorial in the issue #312, it might be worth it to take a look there!

**Comment by darkerbess** [comment]
@bishnu-47 first download the jdt.ls from this [link](https://download.eclipse.org/jdtls/milestones/?d) (I used version 1.1.0) and unzip it, then make a bash file called `java-linux-ls` in your `~/.local/bin` that contains this (change the path to where you have them located)

#!/usr/bin/env bash
export JAVA_HOME="path/to/java_home"
export GRADLE_HOME=$HOME/gradle
export JAR="path/to/jdt.ls/eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_{version}.jar"
export JDTLS_CONFIG="path/to/jdt.ls/eclipse.jdt.ls/config_{select os}"
export WORKSPACE="$HOME/workspace"

$JAVA_HOME/bin/java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -jar           $(echo "$JAR") \
  -configuration "$JDTLS_CONFIG" \
  -data          "$WORKSPACE" \

Update `init.lua`

require('lsp.java-ls')

Update `lua/plugins.lua`

use {"mfussenegger/nvim-jdtls", opt = true}
require_plugin("nvim-jdtls")

Close and open LunarVim and run `:PackerSync`

tell me if it worked for you

**Comment by bishnu-47** [comment]
@darkerbess did all the steps told by you,  getting error
`Vim(write):E32: No file name`
Whats wrong am I doing?

**Comment by pserey** [comment]
First you have to have the directory you putted `java-linux-ls` in the `%PATH`, I prefer putting it in `/usr/bin`. After that you'll have to make it executable using chmod (`chmod +x /path/to/java-linux-ls`). To test if it worked you must type `java-` in terminal and testing if TAB completes.

**Comment by bishnu-47** [comment]
@pserey I have kept the `java-linux-ls` file insde `~/.local/bin/`, which in my `$PATH`.
And the file is executable also, as you said when I type `java-` it auto completes it
this is my `java-linux-ls` file:
```
#!/usr/bin/env bash
export JAVA_HOME="/opt/java-11"
export JAR="/opt/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_*.jar"
export JDTLS_CONFIG="/opt/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux"
export WORKSPACE="$HOME/workspace"

$JAVA_HOME/bin/java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -jar           $(echo "$JAR") \
  -configuration "$JDTLS_CONFIG" \
  -data          "$WORKSPACE" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED
```
have everything on `/opt` as when i run `ls /opt` result:
```
amazon-corretto-11.0.11.9.1-linux-x64  idea-IC-211.6693.111  microsoft
eclipse.jdt.ls                         java-11               sublime_text
```
but I have one question, as steps mentioned in [instruction](https://github.com/jimcornmell/LunarVim#java-lsp-install) on 4rth step the command `./mvnw clean verify`.. is it necessary to successfully run it? I have a low-end pc. I tried running that 3times every time I ran that command, my whole memory gets used and system hangs.. so I skipped that step

**Comment by pserey** [comment]
Hello @bishnu-47, with the command in `$PATH` it should work and you should be able to go to the next step. And about the `./mvnw clean verify`, I think that is necessary to run it as it installs `eclipse.jdtls`, it is indeed a little heavy, but I don't think there's a way to skip it.

As I said in the beginning, I've run all the commands and got all the installation files in the right places, but it still didn't worked for me. I'll be waiting and getting updated hoping that some easier and faster way of installing it shows up. I really love vim, but Java workflow is still impossible to me :/

**Comment by ChristianChiarulli** [comment]
java is a huge pain, I will create a java mega issue, where all issues will be tracked there.
