### ISSUE TITLE
Can I install LunarVim next to my main configuration?

### ISSUE THREAD

**Issue by osenvosem** [ChristianChiarulli/LunarVim#433]
And run it with separate command?

**Comment by rebuilt** [comment]
You can start neovim with the u flag to specify a different config to use.  

-u* *E282*
-u {vimrc}	The file {vimrc} is read for initializations.  Most other
		initializations are skipped; see |initialization|.

		This can be used to start Vim in a special mode, with special
		mappings and settings.  A shell alias can be used to make
		this easy to use.  For example:
			alias vimc vim -u ~/.config/nvim/c_init.vim !*
 		Also consider using autocommands; see |autocommand|.

		When {vimrc} is "NONE" (all uppercase), all initializations
		from files and environment variables are skipped.  Plugins and
		syntax highlighting are also skipped.

		When {vimrc} is "NORC" (all uppercase), this has the same
		effect as "NONE", but plugins and syntax highlighting are not
		skipped.

**Comment by osenvosem** [comment]
@rebuilt yep, but how can I install LunarVim in a different folder to use it alongside with my main setup? When I try to install it, the installer gives me a notice that there is already `nvim` folder exists. Setting up the `XDG_CONFIG_HOME` inline doesn't help.

**Comment by rebuilt** [comment]
Either manually clone the repo and install dependencies yourself,  OR rename your current nvim folder temporarily(nvim_bak), run the installer and change the folder names after installation.

**Comment by osenvosem** [comment]
Created a separate .config folder for it.
