### ISSUE TITLE
nvim-tree shortcuts stopped working

### ISSUE THREAD

**Issue by soerenmartius** [ChristianChiarulli/LunarVim#444]
After pulling the master, all uppercase shortcuts for `nvim-tree.lua` defined in https://github.com/ChristianChiarulli/LunarVim/blob/master/lua/lv-nvimtree/init.lua stopped working. (e.g. show/hide hidden or dotfiles). The lowercase shortcuts are still working.

**Comment by rebuilt** [comment]
Try upgrading your version of neovim.  Based on this issue.

https://github.com/kyazdani42/nvim-tree.lua/issues/396

**Comment by soerenmartius** [comment]
thanks! that solved the issue!
