### ISSUE TITLE
Unexpected behaviour when triggering which-key and telescope focusing nvim-tree

### ISSUE THREAD

**Issue by fabriziosestito** [ChristianChiarulli/LunarVim#445]
When focusing nvim-tree and pressing the leader button:

![image](https://user-images.githubusercontent.com/828651/120221883-6ea57f00-c23f-11eb-9688-c0ff328abd10.png)

If I press a combination fast enough so that the which-key windows does not appear, it works fine (e.g. toggling nvim-tree).

Also If I trigger telescope inside nvim-tree I get:

![image](https://user-images.githubusercontent.com/828651/120222101-b62c0b00-c23f-11eb-954d-a5dd4dde9dce.png)

and 

![image](https://user-images.githubusercontent.com/828651/120222165-cd6af880-c23f-11eb-8363-603e531bd282.png)

with <leader>p

All windows are closed except nvim-tree and I do not seem to be able recover from this, only quitting neovim and starting again works.

**Comment by rebuilt** [comment]
```md
If I press a combination fast enough so that the which-key windows does not appear
```
This is usually a sign timeoutlen is too short a time interval.  Edit timeoutlen in lv-settings.lua

Not sure about the telescope issue.

**Comment by fabriziosestito** [comment]
> ```lisp
> If I press a combination fast enough so that the which-key windows does not appear
> ```
> 
> This is usually a sign timeoutlen is too short a time interval. Edit timeoutlen in lv-settings.lua
> 
> Not sure about the telescope issue.

With this I meant that if I am fast enough, the toggling works fine. If I am too slow so that the which-key window appears, it breaks neovim as in the first screenshot.

It could be related to this: https://github.com/kyazdani42/nvim-tree.lua/issues/418

**Comment by fabriziosestito** [comment]
I've tried the PR: https://github.com/kyazdani42/nvim-tree.lua/pull/421, which reverts the commit mentioned in kyazdani42/nvim-tree.lua#418 and I can confirm nvim-tree is back working fine.

Closing this since not related to LunarVim's config.
