### ISSUE TITLE
Lunar Vim Install error 

### ISSUE THREAD

**Issue by KittyX29** [ChristianChiarulli/LunarVim#447]
Hey, 
I installed lunar vim following the readme and the vid. 
There are installation error : 

E492: Not an editor command: require('lv-comment')
line   13:
E492: Not an editor command: require('lv-gitblame')
line   14:
E492: Not an editor command: require('lv-compe')
line   15:
E492: Not an editor command: require('lv-barbar')
line   16:
E492: Not an editor command: require('lv-dashboard')
line   17:
E492: Not an editor command: require('lv-telescope')
line   18:
E492: Not an editor command: require('lv-gitsigns')
line   19:
E492: Not an editor command: require('lv-treesitter')
line   20:
E492: Not an editor command: require('lv-matchup')
line   21:
E492: Not an editor command: require('lv-autopairs')
line   22:
E492: Not an editor command: require('lv-rnvimr')
line   23:
E492: Not an editor command: require('lv-which-key')

**Comment by Binx-Codes** [comment]
Make sure you're using Neovim 0.5

**Comment by rebuilt** [comment]
Make sure you have at least version 0.5 of neovim.   Make sure it was compiled with luajit.  If you installed using sudo, follow the steps to uninstall and try again without sudo.  Make sure the dependencies were installed.  The dependencies are in the readme.  Search for 'depends on'.  Make sure your plugins are installed.  Run :PackerSync
