### ISSUE TITLE
Telescope error?

### ISSUE THREAD

**Issue by PabloMartinMoreno** [ChristianChiarulli/LunarVim#449]
When opening nvim the following message appears (It forces me to read it and when I get to the end I can just access nvim):

true
{
  check_ts = true,
  disable_filetype = { "TelescopePrompt", "spectre_panel" },
  enable_afterquote = true,
  enable_check_bracket_line = true,
  enable_moveright = true,
  ignored_next_char = "[%w%%%'%[%\"%.]",
  ts_config = {
    java = false,
    javascript = { "template_string" },
    lua = { "string" },
    <metatable> = {
      __tostring = <function 1>
    }
  }
}
true
{
  check_ts = true,
  disable_filetype = { "TelescopePrompt", "spectre_panel" },
  enable_afterquote = true,
  enable_check_bracket_line = true,
  enable_moveright = true,
  ignored_next_char = "[%w%%%'%[%\"%.]",
  ts_config = {
    java = false,
    javascript = { "template_string" },
    lua = { "string" },
    <metatable> = {
      __tostring = <function 1>
    }
  }
}
true
{
  check_ts = true,
  disable_filetype = { "TelescopePrompt", "spectre_panel" },
  enable_afterquote = true,
  enable_check_bracket_line = true,
  enable_moveright = true,
  ignored_next_char = "[%w%%%'%[%\"%.]",
  ts_config = {
    java = false,
    javascript = { "template_string" },
    lua = { "string" },
    <metatable> = {
      __tostring = <function 1>
    }
  }
}
true
{
  check_ts = true,
  disable_filetype = { "TelescopePrompt", "spectre_panel" },
  enable_afterquote = true,
  enable_check_bracket_line = true,
  enable_moveright = true,
  ignored_next_char = "[%w%%%'%[%\"%.]",
  rules = { {
      cr_cond = { <function 1> },
      del_cond = {},
      end_pair = "-->",
      end_pair_func = false,
      filetypes = { "html" },
      is_endwise = false,
      is_regex = false,
      key_map = "",
      pair_cond = {},
      start_pair = "",
      end_pair_func = false,
      filetypes = { "html" },
      is_endwise = false,
      is_regex = false,
      key_map = "",
      pair_cond = {},
      start_pair = "",
      end_pair_func = false,
      filetypes = { "html" },
      is_endwise = false,
      is_regex = false,
      key_map = "",
      pair_cond = {},
      start_pair = "<!--",
      <metatable> = {
        __index = <1>{
          can_cr = <function 2>,
          can_del = <function 3>,
          can_move = <function 4>,
          can_pair = <function 5>,
          end_wise = <function 6>,
          get_end_pair = <function 7>,
          new = <function 8>,
          only_cr = <function 9>,
          replace_endpair = <function 10>,
          use_regex = <function 11>,
          with_cr = <function 12>,
          with_del = <function 13>,
          with_move = <function 14>,
          with_pair = <function 15>
        }
      }
    }, {
 cr_cond = {},
      del_cond = {},
      end_pair = "```",
      end_pair_func = false,
      filetypes = { "markdown", "vimwiki" },
      is_endwise = false,
      is_regex = false,
      key_map = "",
      pair_cond = {},
      start_pair = "```",
      <metatable> = {
        __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = false,
      end_pair = "```",
      end_pair_func = false,
      filetypes = { "markdown", "vimwiki" },
      is_endwise = false,
      is_regex = true,
      key_map = "",
      move_cond = false,
      pair_cond = false,
      start_pair = "```.*$",
      <metatable> = {
        __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = {},
      end_pair = '"""',
      end_pair_func = false,
      filetypes = { "python" },
      is_endwise = false,
      is_regex = false,
      key_map = "",
 pair_cond = {},
      start_pair = '"""',
      <metatable> = {
        __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = {},
      end_pair = "'",
      end_pair_func = false,
      is_endwise = false,
      is_regex = false,
      key_map = "",
      move_cond = { <function 16> },
      pair_cond = { <function 17>, <function 18>, <function 19> },
      start_pair = "'",
      <metatable> = {
        __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = {},
      end_pair = "`",
      end_pair_func = false,
      is_endwise = false,
      is_regex = false,
      key_map = "",
      move_cond = { <function 20> },
      pair_cond = { <function 21>, <function 22> },
      start_pair = "`",
      <metatable> = {
        __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = {},
      end_pair = '"',
 end_pair_func = false,
      is_endwise = false,
      is_regex = false,
      key_map = "",
      move_cond = { <function 23> },
      pair_cond = { <function 24>, <function 25> },
      start_pair = '"',
      <metatable> = {
        __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = {},
      end_pair = ")",
      end_pair_func = false,
      is_endwise = false,
      is_regex = false,
      key_map = "",
      move_cond = { <function 26> },
      pair_cond = { <function 27>, <function 28>, <function 29> },
      start_pair = "(",
      <metatable> = {
        __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = {},
      end_pair = "]",
      end_pair_func = false,
      is_endwise = false,
      is_regex = false,
      key_map = "",
      move_cond = { <function 30> },
      pair_cond = { <function 31>, <function 32>, <function 33> },
      start_pair = "[",
      <metatable> = {
  __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = {},
      end_pair = "}",
      end_pair_func = false,
      is_endwise = false,
      is_regex = false,
      key_map = "",
      move_cond = { <function 34> },
      pair_cond = { <function 35>, <function 36>, <function 37> },
      start_pair = "{",
      <metatable> = {
        __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = false,
      end_pair = "<",
      end_pair_func = false,
      filetypes = { "html", "typescript", "typescriptreact", "svelte", "vue", "xml" },
      is_endwise = false,
      is_regex = false,
      move_cond = false,
      pair_cond = false,
      start_pair = ">",
      <metatable> = {
        __index = <table 1>
      }
    } },
  ts_config = {
    java = false,
    javascript = { "template_string" },
    lua = { "string" },
    <metatable> = {
      __tostring = <function 38>
  __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = {},
      end_pair = "}",
      end_pair_func = false,
      is_endwise = false,
      is_regex = false,
      key_map = "",
      move_cond = { <function 34> },
      pair_cond = { <function 35>, <function 36>, <function 37> },
      start_pair = "{",
      <metatable> = {
        __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = false,
      end_pair = "<",
      end_pair_func = false,
      filetypes = { "html", "typescript", "typescriptreact", "svelte", "vue", "xml" },
      is_endwise = false,
      is_regex = false,
      move_cond = false,
      pair_cond = false,
      start_pair = ">",
      <metatable> = {
        __index = <table 1>
      }
    } },
  ts_config = {
    java = false,
    javascript = { "template_string" },
    lua = { "string" },
    <metatable> = {
      __tostring = <function 38>
  __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = {},
      end_pair = "}",
      end_pair_func = false,
      is_endwise = false,
      is_regex = false,
      key_map = "",
      move_cond = { <function 34> },
      pair_cond = { <function 35>, <function 36>, <function 37> },
      start_pair = "{",
      <metatable> = {
        __index = <table 1>
      }
    }, {
      cr_cond = {},
      del_cond = false,
      end_pair = "<",
      end_pair_func = false,
      filetypes = { "html", "typescript", "typescriptreact", "svelte", "vue", "xml" },
      is_endwise = false,
      is_regex = false,
      move_cond = false,
      pair_cond = false,
      start_pair = ">",
      <metatable> = {
        __index = <table 1>
      }
    } },
  ts_config = {
    java = false,
    javascript = { "template_string" },
    lua = { "string" },
    <metatable> = {
      __tostring = <function 38>
     }
   }
}

**Comment by rebuilt** [comment]
Run :PackerSync to update.

https://github.com/windwp/nvim-autopairs/issues/63
