### ISSUE TITLE
Disable autoformatting on save

### ISSUE THREAD

**Issue by denisdifazio** [ChristianChiarulli/LunarVim#450]
Is it possible to disable file formatting on save? Currently, every time I save a `.ts` file, it auto formats it.

**Comment by rebuilt** [comment]
Edit the lv-settings.lua file.  On dashboard start, select settings.  

```
O.tsserver.autoformat = true
```

**Comment by denisdifazio** [comment]
Awesome! It worked, thanks @rebuilt !
