### ISSUE TITLE
No Active Lsp - Typescript

### ISSUE THREAD

**Issue by willparsons** [ChristianChiarulli/LunarVim#457]
When I'm in a typescript file I see `No Active Lsp`.

So I've installed the typescript lsp and tried doing `:LspStart tsserver` but then I see `Autostart for tsserver failed: matching root directory not detected`.

**Comment by rebuilt** [comment]
Make sure you're in a git-managed directory.

**Comment by willparsons** [comment]
> Make sure you're in a git-managed directory.

Not on my machine to try yet but why does it require I'm in a git directory?

**Comment by rebuilt** [comment]
A language server looks through an entire project to figure out the structure of your code.  The best way to define the boundaries of a project is by looking for a git directory.  This is why you can rename a method in one file and it will apply the rename in other files... assuming the language server supports that.  Capabilities of different servers differ per implementation.

**Comment by willparsons** [comment]
That makes sense. I think it would be nice to be able to define the root as some folder you want but I suppose it's not really necessary.

**Comment by rebuilt** [comment]
You could tell it to identify the root directory with 
```
# Get the current working directory
vim.fn.getcwd()
```
but that may break functionality of the language server.
