### ISSUE TITLE
Osx terminal's color scheme is not showing properly

### ISSUE THREAD

**Issue by vahidhashemi** [ChristianChiarulli/LunarVim#458]
Hi,

Color schemes aren't showing properly but in iterm2 I can see color schemes working correctly.

OS Version : Big Sur

![image](https://user-images.githubusercontent.com/1707050/120847873-53ad7480-c589-11eb-8b20-a55c5f06ac76.png)

**Comment by rebuilt** [comment]
Seems like it might be an issue with terminal.app.  Maybe try one of the suggestions here: 
https://www.reddit.com/r/vim/comments/2ahs64/vim_colorscheme_not_working_in_os_x_terminal/
or 
https://stackoverflow.com/questions/1653538/how-can-i-activate-vim-color-schemes-in-os-xs-terminal

I don't have a mac so I can't test.  I'm just trying to be helpful.
