### ISSUE TITLE
Extendable configs

### ISSUE THREAD

**Issue by imbolc** [ChristianChiarulli/LunarVim#461]
I'd like to benefit from further changes in LunarVim. But as I understand, for now, I can only change it's files directly. The simplest thing coming to my mind is having my changes in a separate git branch, and then merging LunarVim changes from the main branch. But it has obvious downsides. Is it possible to have some kind of extension files which won't be in the LunarVim repo, but it would be possible to change defaults by adding them? Something like
```lua
require('lv-globals')
require-if-exists('overrides/lv-globals')
```

**Comment by fabriziosestito** [comment]
>  The simplest thing coming to my mind is having my changes in a separate git branch, and then merging LunarVim changes from the main branch. 

This is exactly what I am doing, and rebasing/solving conflicts is very much prone to error.

In the TODO part of the README, it is mentioned "Move user config" as high priority. 
Is this related to what @imbolc is proposing?

**Comment by ChristianChiarulli** [comment]
I'm working on a more comprehensive user config now,

for now that looks like:

capability to enable common plugins,
lazyload as much as possible,
I think that will solve 90% 

Then I will focus on opening the config up to user extension while also being decoupled from updates.

This part will focus on letting people pull in there own plugins, and configuring them.

**Comment by ChristianChiarulli** [comment]
To close this I want the following:

- User defined extra plugin list
- User config overrides

**Comment by colutti** [comment]
It should not be complicated to implement. Inside every major config file, such as keymaps.lua we could call a default folder/ file like user-extension/keymaps.lua. Them we would add those files to .gitignore so it wouldnt be pushed to the repo. 

If you guys like the idea I could do it for plugins and keymaps for now and see how it goes. We just need to define the name of the folder / file pattern.

**Comment by ChristianChiarulli** [comment]
should we have other files besides lv-config?

**Comment by gnmearacaun** [comment]
This issue could probably move to https://github.com/ChristianChiarulli/LunarVim/issues/758 . Where @rebuilt has broken lv-config into 4 files.

If it resides in `lua` and be called `config/` to be at the top of the directory (for nvimtree and ranger) and the first to autocomplete on bash/zsh cli.

To that end, it could be nice to put default-config.lua, keymappings.lua, plugins.lua and settings.lua were contained in a lua/default-config/ as a neighbor to config/ .

**Comment by colutti** [comment]
@gnmearacaun  I like this idea.

**Comment by gnmearacaun** [comment]
Thanks @colutti , there is a pull request to use lua/config [for plugin configs](https://github.com/ChristianChiarulli/LunarVim/pull/687/commits/bb819fe59ae2c975a849d5cedeab0f7f7a92b2c9#) so [I requested](https://github.com/ChristianChiarulli/LunarVim/pull/687#issuecomment-877767339) whether a different name (maybe lv- prefixed ) for that folder could be be considered instead.

**Comment by kylo252** [comment]
I've thinking about this and have taken a look at both https://github.com/ChristianChiarulli/LunarVim/pull/851 and https://github.com/ChristianChiarulli/LunarVim/issues/758 but I'm still not sure any of them is that robust. 

My solution might be controversial, but I think LunarVim should not be the one controlling `~/.config/nvim`, instead it should rather behave as a submodule for your configuration.

That would present some technical challenges no doubt, but it's pretty clear to me that maintaining personal configuration for additional plugins would require _additional_ lengthy configuration. And I'd definitely need this extra config files to be version-controlled for my own sanity.. 😄

**Comment by jameswalmsley** [comment]
@kylo252 thanks for taking a look at my PR.
#851 is really a solution for the branch and rebase workflow.. whereby you won't really get conflicts due to the base not modifying it. 

The idea is that once the main config is stable this will be effective.

I'm currently maintaining a global installation where I want to have some defaults and plugins setup for my engineering colleagues.. so I'm using this "distrib" folder so it doesn't conflict with the users config which can override and extend my distribution config.

In terms of managing my own config, I just pull the standard lunarvim repo.. I have a special alias on my shell that sets GIT_DIR and GIT_WORKING_DIR (for my dot files).. so I can prefix any git command with that and o can manage my user config that way.

(Think of it like an overlay git repo).

**Comment by gnmearacaun** [comment]
@jameswalmsley I think you're onto a good thing. [The point I was making] was if there is going to be a user-config folder to manage profiles, to keep it out of the forest of lv-directories because it's something we, as users, need to touch often.
@kylo252 if I understand what you're saying, nvim/ is the config file for lunarvim. The user settings must not be a symlink outside of the directory otherwise autocompletion with `O.` will not be present.

**Comment by rebuilt** [comment]
You can still get autocompletion on the O variable on a symlinked directory.  You have to manualy source the lua file. 

```
local user = os.getenv("USER")
O = dofile("/home/" .. user .. "/.config/nvim_lunar/lua/default-config.lua")

```

The problem with this method is you effectively source the file twice.  But I think it doesn't even add another millisecond to source it twice.  


To avoid sourcing it twice I'm using a git submodule inside lv-user-config.  


The name lv-user-config can be easily changed but it requires adding a line to the .gitignore file with the name of the folder where you want to place your configs.

**Comment by gnmearacaun** [comment]
Ah okay, I had read somewhere that autocompletion would not work outside of ~config/nvim 
I don't get why it would be called lua/lv-user rather than something less confusing for new users like lua/config

**Comment by rebuilt** [comment]
> Ah okay, I had read somewhere that autocompletion would not work outside of ~/.config/nvim

That's probably my fault.  It's in the readme of my repo.  I'll change it when I get home Tuesday

**Comment by gnmearacaun** [comment]
That's a riot, I didn't even notice. I had cloned [your project](https://github.com/rebuilt/lv-user-config) and added it to my fork. Heartily looking forward to making use of your generous offering very soon.

**Comment by rebuilt** [comment]
Looks like lunarvim has changed while I was away.  The 'dofile' thing doesn't work anymore. In fact, most things are broken.  I've gotta get up to speed with the changes and rework the solution.

**Comment by luxus** [comment]
I would prefer have the lv-config.lua in lua/lv-user/ (imho I still would prefer the name custom, but that's just me:D)
we could add support in the installer for automatically downloading a config `--user luxus` (defaulting to https://github.com/luxus/lv-user)

benefits would not have to symlink files and have a git repo with commits for a custom config.
sure we could have the file in the lua root and symlink it from a Git repo that sits somewhere else.

with this change it would be even easily possible to switch between lv branches and different user configs with 1 command.

**Comment by rebuilt** [comment]
Configurations have been completely separated and live in their own folder.  There are now mechanisms to add your own plugins, override default keybindings, whichkey mappings, and autocommands.  I think the goals of this pr have been achieved.  The api for this will change before 1.0, but everything is in place and I think it's safe to close this issue.
