### ISSUE TITLE
PackerSync, PackerClean and PackerUpdate not working

### ISSUE THREAD

**Issue by meehirmanitrips** [ChristianChiarulli/LunarVim#464]
The above wriiten packer commands are not working, they were working just fine a few hours ago and then just starting giving me this problem from out of nowhere:

```
Error executing vim.schedule lua callback: ~/local/share/nvim/site/pack/packer/start/packer.nvim/lua/packer/display.lua : 152 : Invalid Key 'noautocmd'     
```
Can someone help me out with this....I can't seem to understand what the problem is........is it because the api key is invalid?

**Comment by abzcoding** [comment]
```
~/local/share/nvim/site/pack/packer/start/packer.nvim/lua/packer/display.lua : 152 : Invalid Key 'noautocmd'
```
1. open that file, comment line 149 and save and exit neovim: 

```lua
--    noautocmd = true, -- comment this line
  }

  local win = api.nvim_open_win(buf, false, opts) -- the issue raises from this line
  local check = vim.loop.new_prepare()
```

2. open neovim and then run:
```
PackerCompile
PackerInstall
PackerClean
```

3. and then uncomment that line 149 again, and everything will work.

**Comment by meehirmanitrips** [comment]
>     1. and then uncomment that line 149 again, and everything will work.

Thank you so much......its working now.
But i don't understand why it was behaving that way......could you please explain to me what was wrong with it.

**Comment by abzcoding** [comment]
Glad it worked, sadly I don't know the root cause either.
but these issues might be related:

https://github.com/wbthomason/packer.nvim/issues/354
https://github.com/wbthomason/packer.nvim/issues/388
https://github.com/wbthomason/packer.nvim/issues/389

**Comment by meehirmanitrips** [comment]
> Glad it worked, sadly I don't know the root cause either.
> but these issues might be related:
> 
> https://github.com/wbthomason/packer.nvim/issues/354
> https://github.com/wbthomason/packer.nvim/issues/388
> https://github.com/wbthomason/packer.nvim/issues/389
> 

No problem and thanks again for your help.

**Comment by seandewar** [comment]
`noautocmd` was a compatibility option recently added to Neovim to restore the old behaviour of `nvim_open_win` that many plugins relied upon.

The correct solution here is to update your version of Neovim.
