### ISSUE TITLE
`gf` not working when paths aren't relative

### ISSUE THREAD

**Issue by talefe** [ChristianChiarulli/LunarVim#465]
https://user-images.githubusercontent.com/31940907/120911221-f2fb6600-c674-11eb-8e79-60e754011775.mov

**Comment by talefe** [comment]
for context: `'os/application'` is a path within `src`

**Comment by talefe** [comment]
@rebuilt can you help with this?

**Comment by rebuilt** [comment]
You can add ** to your path:

```
set path+=**
```
This way it will find every file recursively based on your current directory. But apparently it's [not recommended.](https://twitter.com/tpope/status/612991667751264256)

If you want to add other paths, you can just add them as follow:

```
set path+=/path/to/your/lib
set path+=c:/include
```

Answer found [here](https://vi.stackexchange.com/questions/7453/access-a-file-under-subdirectories-of-a-path-through-gf-command)

I tested this in a react project.  It seems to work.  

Also read through [this](https://damien.pobel.fr/post/configure-neovim-vim-gf-javascript-import/)

**Comment by rebuilt** [comment]
https://github.com/ChristianChiarulli/LunarVim/pull/472

**Comment by rmagillxyz** [comment]
@talefe I just created a pull request which should fix this. The issue is that the `gx` command was not working correctly and I found a hack which fixed it, but didn't realize it broke `gf` for remote paths. Let me know if there are any other issues with netrw's `g` commands as I've been trying to fix this for awhile now and want to get this working correctly! 
Here is the pull request, there are only a few small changes: https://github.com/ChristianChiarulli/LunarVim/pull/472

**Comment by rebuilt** [comment]
@rmagillxyz 

Thanks! Good work.

**Comment by rmagillxyz** [comment]
@rebuilt There is a small plugin if any other issues arise. It may be more of a full-proof fix, but I haven't tested anything but my pr with `gx` and `gf`. There is a thread that goes back several years with people frustrated with this issue and people digging into netrw commits from over 20 years ago! 

[plugin](https://github.com/felipec/vim-sanegx.git)
[from issue](https://github.com/vim/vim/issues/4738#issuecomment-856925080)

**Comment by rmagillxyz** [comment]
hmm. `gd`, `gf`, and `gx` all seem to be working properly for me (finally!). Did you also remove `vim.g.loaded_netrwPlugin = 1` from `lua/settings.lua`? 

You could also try to remove all those lines from my pr, including the old `gx` binding and try out (this plugin)[https://github.com/felipec/vim-sanegx]. If that works for you, maybe we should just pull those other lines and make a pr for that plugin instead. @talefe

**Comment by rmagillxyz** [comment]
@talefe So, I just tried the plugin, and it is working. I'm going to cancel my pr and submit the plugin in a pr instead as it deals with more use cases. What OS are you using?

**Comment by rmagillxyz** [comment]
updated pull request to hopefully fix this [#479](https://github.com/ChristianChiarulli/LunarVim/pull/479)
@rebuilt @talefe

**Comment by talefe** [comment]
I am using macOS Catalina. I am sorry to say it didn't work for me...

**Comment by felipec** [comment]
For the record my plugin is only for `gx`. I have not investigated any other issues.

**Comment by rmagillxyz** [comment]
@felipec What happened was I had submitted a different `gx` fix from that thread which unintentionally changed the behavior of `gf` for remote paths. I tested your plugin yesterday and it does indeed fix `gx`, and `gf` was still working as expected for remote paths, so unless there are any unforeseen issues, this is the best solution. Thanks.

**Comment by rmagillxyz** [comment]
> I am using macOS Catalina. I am sorry to say it didn't work for me...
When you say `this`, do you mean #472 or #479 or both? Also, it was working before at some point? If it was and you don't care about `gx`, you should be able to get it working again by removing a few small changes.  These two commits should point you in the right direction: #394 and #431 @talefe

**Comment by talefe** [comment]
Opened a new issue #550 , hoping to make the situation clearer, will close this one
