### ISSUE TITLE
Elixir file type does not have syntax highlight

### ISSUE THREAD

**Issue by joaop-oliveira1** [ChristianChiarulli/LunarVim#469]
I created an Elixir project and the LSP works perfectly(nice job on this one) but the color schemes does not highlight the language,
although we can work without colorful words it is kind of boring hehehehe.

![image](https://user-images.githubusercontent.com/78939755/121043442-03056980-c78b-11eb-9b24-d3a2a662d370.png)

It is not something urgent but anyone has any leads on how to make this work?

Thanks in advance

**Comment by fabriziosestito** [comment]
Happy to see another Alchemist in here, maybe a theme related issue? 
Syntax highlighting works fine for me using the original theme and miramare.

![image](https://user-images.githubusercontent.com/828651/121045330-05c98400-c7b6-11eb-8b0f-06052c0e9213.png)

**Comment by joaop-oliveira1** [comment]
Not an Alchemist yet just an apprentice! But glad to see such a friendly community!
I tried to switch my themes but no luck at all....

**Comment by rebuilt** [comment]
@joaop-oliveira1 
Which terminal are you running?  And do colorschemes work for other languages?
What's the output of running 
```
:colorscheme lunar
```
Is the treesitter parser installed for elixir?
```
:TSInstall elixir
```

Are there any error messages in 
```
:messages
```

**Comment by joaop-oliveira1** [comment]
Took a print of my nvim.
![Screenshot from 2021-06-07 14-11-10](https://user-images.githubusercontent.com/78939755/121069400-cf830900-c7a3-11eb-809c-70204792b390.png)

Don't think that tree-sitter is installed anywhere in my OS.
How do I install it?

**Comment by rebuilt** [comment]
The installer code is located [here](https://github.com/ChristianChiarulli/LunarVim/blob/master/utils/installer/install.sh) if you want to read it

**Comment by joaop-oliveira1** [comment]
@rebuilt done tree-sitter-cli was not installed running ```npm i -g tree-sitter-cli``` solved this for me!

**Comment by joaop-oliveira1** [comment]
Thanks for the help guys!!

**Comment by rebuilt** [comment]
From the error messages you're also missing a clipboard provider.

sudo dnf install -y xclip
