### ISSUE TITLE
help me for tsserver

### ISSUE THREAD

**Issue by 1096015776** [ChristianChiarulli/LunarVim#470]
hi,i really like this neovim, give me all i want these.but i don't know why i cannot use tsserver with js.

i read these issues.but i cannot use this.

i use NVIM v0.5.0-dev+1374-

![截屏2021-06-08 下午8 21 13](https://user-images.githubusercontent.com/40203327/121183854-143b9c80-c897-11eb-8083-8944cb9fd0cd.png)

![截屏2021-06-08 下午8 22 24](https://user-images.githubusercontent.com/40203327/121184013-3d5c2d00-c897-11eb-9f31-f0a644c4a1fe.png)
maybe i'm not a smart man

**Comment by rebuilt** [comment]
https://github.com/ChristianChiarulli/LunarVim/issues/457

**Comment by 1096015776** [comment]
Thanks for your answer,i test for this. it is useful for me.Thanks,maybe,i should read more in these issue,i'm sorry for this.
