### ISSUE TITLE
Create a off-GH community (discord/discourse/slack/etc) to handle Q&A, development, etc.

### ISSUE THREAD

**Issue by pard68** [ChristianChiarulli/LunarVim#475]
As of this posting, the project has been forked 719 times and has been starred 3.2k times. There are 85 issues currently (not counting this one). I haven't looked at all 85 of the issues, but my cursory scroll of the first two pages leads me to believe a lot of these issues would be better in some sort of community. Additionally, similar projects have some form of community outside of GH (Doom Emacs, Spacevim, etc).

I believe that you could really reduce the number of issues created if there was a place to send general questions, and this would in turn result in faster answers for users and less work for you, Christian, since the q&a would be largely crowd sourced by the rest of your user base.

**Comment by rmagillxyz** [comment]
@pard68  He has matrix and discord. Lots of answer and questions being discussed there already. Are you thinking something different than this? 
[check it out](https://matrix.to/#/+atmachine:matrix.org)

**Comment by pard68** [comment]
That works! It's not advertised anywhere in this repo -- that I have seen -- so I was merely suggesting _something_ be created. Since it already exists, I guess just a section in the readme to point people there. Do you have the Discord URI as well? I'll type something up to point people to these resources in the README

**Comment by rmagillxyz** [comment]
@pard68 all his links are in the description of his yt channel in any recent video:  [yt](https://www.youtube.com/watch?v=6Pyk9wbm1g4)

The matrix and discord are bridged
