### ISSUE TITLE
Does not work csharp

### ISSUE THREAD

**Issue by italo-amaya-utec** [ChristianChiarulli/LunarVim#481]
When i do :LspInstall csharp, firstly no lsp server is attached to the buffer even if I close the buffer and open it. I tried to install omnisharp separately and found the the actual :LSPInstall csharp uses a Http server too but it was too complicated for me.
Is this a problem or it is just not supported yet?

Thankyou

**Comment by alexpetrean80** [comment]
check #399

**Comment by rebuilt** [comment]
What have you tried so far?  What does your csharp configuration file look like.  How have you included it in your config?

**Comment by italoaa** [comment]
this is my csharp-ls.lua
```
local pid = vim.fn.getpid()
-- On linux/darwin if using a release build, otherwise under scripts/OmniSharp(.Core)(.cmd)
local omnisharp_bin = "/path/to/omnisharp-repo/run"
-- on Windows
-- local omnisharp_bin = "/path/to/omnisharp/OmniSharp.exe"
require'lspconfig'.omnisharp.setup{
    cmd = { omnisharp_bin, "--languageserver" , "--hostPID", tostring(pid) };
    ...
} ```
I just downloaded the omnisharp-roslyn, but know i dont know how to include it to the config file

**Comment by rebuilt** [comment]
The line that defines 'omnisharp_bin' must be changed.  That's where you need to set the path to omnisharp.  

Try going through the readme to understand lsp a bit better.  https://github.com/ChristianChiarulli/LunarVim#lsp
