### ISSUE TITLE
flake8 is disabled by default

### ISSUE THREAD

**Issue by regzon** [ChristianChiarulli/LunarVim#486]
Hi there, thank you for your great work on LunarVim!

Is there any reason the line `O.python.linter = 'flake8'` is commented out in `lv-settings.lua`?

**Comment by rebuilt** [comment]
I assume it's because not everyone needs it.  It's optional.

**Comment by regzon** [comment]
Actually, the problem is that the commit that comments this line out is related to neither the python nor the flake8 (from what I can see). So, if this change is intentional, then okay. We should, probably, ask @ChristianChiarulli about this.

**Comment by ChristianChiarulli** [comment]
everything should be disabled by default.
