### ISSUE TITLE
[question] what config is responsible for keeping nvim-tree visible in all windows?

### ISSUE THREAD

**Issue by brijow** [ChristianChiarulli/LunarVim#487]
Hi there, I am trying out LunarVim and enjoying many features. I mostly have just been cherry picking certain parts of this config and replicating it in my own. One thing I am having a hard time figuring out though is how nvim-tree has been configured (+ other configurations I expect other than just nvim-tree) so that it appears in every window that gets opened?

I was looking through the plugin config files for nvim-tree but it seems there is more to it than just pure nvim-tree configuration to make this happen.... 

Thanks in advance for any help here, and for LunarVim overall!

**Comment by ChristianChiarulli** [comment]
I'm not sure exactly what you mean, I would recommend tuning into one of the streams if possible, I may be able to better demonstrate the config there.
