### ISSUE TITLE
Issue with LunarVim installation on macOS

### ISSUE THREAD

**Issue by ciscohack** [ChristianChiarulli/LunarVim#488]
Hi Christian,

I am facing installation problem on LunarVim on macOS bigSur. i used the curl script method to install but getting lots of error and it's failing second i don't see neovim have version 0.5 released which is one of requirement mentioned in documentation. need your help on this to get installation done.

Here are some of errors

".CONFIG_PATH..'/lv-settings.lua')" [New DIRECTORY]
Cannot open file ".CONFIG_PATH..'/lv-settings.lua')"

E480: No match: cmd('luafile '

".CONFIG_PATH..'/vimscript/functions.vim')" [New DIRECTORY]
Cannot open file ".CONFIG_PATH..'/vimscript/functions.vim')"

**Comment by rmagillxyz** [comment]
What is the output of the command `uname` on your machine? @ciscohack

**Comment by rmagillxyz** [comment]
If you have it cloned already, open up `~/.config/nvim/utils/installer/install.sh` and search for `mac` and run the commands by hand. Then you'll know where it is failing. Don't forget to run the commands in the functions which are not os dependent (node, pip, pynvim, packer, ect). It's not very long; it shouldn't take you long at all. @ciscohack

**Comment by ciscohack** [comment]
> If you have it cloned already, open up `~/.config/nvim/utils/installer/install.sh` and search for `mac` and run the commands by hand. Then you'll know where it is failing. Don't forget to run the commands in the functions which are not os dependent (node, pip, pynvim, packer, ect). It's not very long; it shouldn't take you long at all. @ciscohack

Thanks for quick response. yeah this indeed took long time. I will check later then

**Comment by jsccosta** [comment]
Hello,
I'm running into the same issue. In my case, after installing the pre-requisites (node, pip, etc) I eventually get this error:

Error detected while processing /Users/xxx/.config/nvim/init.lua:
line    1:
E492: Not an editor command: require('lv-globals')
".CONFIG_PATH..'/lv-settings.lua')" [New DIRECTORY]
Cannot open file ".CONFIG_PATH..'/lv-settings.lua')"
line    2:
E480: No match: cmd('luafile '
line    3:
E492: Not an editor command: require('settings')
line    4:
E492: Not an editor command: require('lv-gitblame')

Any idea as to what it may be the cause?

**Comment by rebuilt** [comment]
@jsccosta 
Make sure you have at least version 0.5 of neovim. Make sure it was compiled with luajit. If you installed using sudo, follow the steps to uninstall and try again without sudo. Make sure the dependencies were installed. The dependencies are in the readme. Search for 'depends on'. Make sure your plugins are installed. Run :PackerSync

**Comment by ciscohack** [comment]
> @jsccosta
> Make sure you have at least version 0.5 of neovim. Make sure it was compiled with luajit. If you installed using sudo, follow the steps to uninstall and try again without sudo. Make sure the dependencies were installed. The dependencies are in the readme. Search for 'depends on'. Make sure your plugins are installed. Run :PackerSync

Could you please share the repo of version of neovim and luajit because i installed through brew and it showing neovim version 0.4

**Comment by rebuilt** [comment]
https://github.com/neovim/neovim/wiki/Building-Neovim#quick-start
Follow the instructions for installing the prerequisites for your system.  The default complilation steps should automatically include luajit

**Comment by jsccosta** [comment]
Upgrading to 0.5 was enough to get it working. I was under the wrong assumption that brew installed 0.5. 
Thanks for the help

**Comment by rebuilt** [comment]
@ChristianChiarulli  
This can be closed
