### ISSUE TITLE
are all features documented somewhere?

### ISSUE THREAD

**Issue by AggamR** [ChristianChiarulli/LunarVim#490]
are all the features documented somewhere? I wanna learn how to use all the features of the plugins but I don't know where to start.

**Comment by rebuilt** [comment]
Start on the project page for each plugin.  That's where they'll be documented best.

**Comment by AggamR** [comment]
> Start on the project page for each plugin. That's where they'll be documented best.

and where can i see the list of plugins? or their keybinds?

**Comment by rebuilt** [comment]
https://github.com/ChristianChiarulli/LunarVim#important-configuration-files

**Comment by rebuilt** [comment]
Read the sections for Leader and Whichkey, other key bindings, and important configuration files

**Comment by AggamR** [comment]
> Read the sections for Leader and Whichkey, other key bindings, and important configuration files

Hi, sorry, I can't find the keybind for IntelliSense-like features like seeing definitions and going to them and stuuf like that

**Comment by rebuilt** [comment]
They are defined in the whichkey configuration file

```lua
   l = {
      
      
                name = "+LSP",
      
      
                a = {"&lt;cmd&gt;Lspsaga code_action&lt;cr&gt;", "Code Action"},
      
      
                A = {"&lt;cmd&gt;Lspsaga range_code_action&lt;cr&gt;", "Selected Action"},
      
      
                d = {"&lt;cmd&gt;Telescope lsp_document_diagnostics&lt;cr&gt;", "Document Diagnostics"},
      
      
                D = {"&lt;cmd&gt;Telescope lsp_workspace_diagnostics&lt;cr&gt;", "Workspace Diagnostics"},
      
      
                f = {"&lt;cmd&gt;LspFormatting&lt;cr&gt;", "Format"},
      
      
                i = {"&lt;cmd&gt;LspInfo&lt;cr&gt;", "Info"},
      
      
                l = {"&lt;cmd&gt;Lspsaga lsp_finder&lt;cr&gt;", "LSP Finder"},
      
      
                L = {"&lt;cmd&gt;Lspsaga show_line_diagnostics&lt;cr&gt;", "Line Diagnostics"},
      
      
                p = {"&lt;cmd&gt;Lspsaga preview_definition&lt;cr&gt;", "Preview Definition"},
      
      
                q = {"&lt;cmd&gt;Telescope quickfix&lt;cr&gt;", "Quickfix"},
      
      
                r = {"&lt;cmd&gt;Lspsaga rename&lt;cr&gt;", "Rename"},
      
      
                t = {"&lt;cmd&gt;LspTypeDefinition&lt;cr&gt;", "Type Definition"},
      
      
                x = {"&lt;cmd&gt;cclose&lt;cr&gt;", "Close Quickfix"},
      
      
                s = {"&lt;cmd&gt;Telescope lsp_document_symbols&lt;cr&gt;", "Document Symbols"},
      
      
                S = {"&lt;cmd&gt;Telescope lsp_workspace_symbols&lt;cr&gt;", "Workspace Symbols"}
      
      
            },
```

Hit the space key and then the 'l' key to bring up the menu.  (That's a lower case L)

**Comment by rebuilt** [comment]
From the readme

```
The default leader key is set to <Space>. Pressing it will also open up Whichkey. Whichkey will help you easily access many of the default keybindings. Whichkey defines keymappings in this file: ~/.config/nvim/lua/lv-which-key/init.lua
```

**Comment by jvaverka** [comment]
As mentioned in the video titled "**_Chris@Machine Debugging DAP and DAPInstall, Colorscheme updates, other bug fixes._**, " maybe all feature documentation can be linked to a corresponding video. E.g., [HERE](https://youtu.be/4ZzSLk4KQzk?t=7043) is the link where this was brought up first. Video snippets should probably be content regarding:

- feature demo
- plugin config
- troubleshooting

I found this type of content helpful when starting out with some of the channels early videos where the blog also contained every command.

Also, this way the live streams can be long form, and then more _targeted_ sections are still available without additional recordings (although there is effort in capturing the video links with time stamps).

@rebuilt - looks like you have worked a good bit on documentation. Would be interested in your take.

**Comment by jvaverka** [comment]
^ I should also say, this depends on how quickly the recordings for each language could be shot, like @ChristianChiarulli mentions in the video

**Comment by ChristianChiarulli** [comment]
I will be making those videos pretty soon btw, first I need to do a couple things. 

- LunarVim refactor, just cleaning up code and exposing which-key bindings to lv-config
- Documentation overhaul, I plan to fix up the readme and wiki before doing the videos

So as long as there are no catastrophic bugs or unforeseen events I should begin the LunarVim series next week.

**Comment by rebuilt** [comment]
[![Test of embedded video](https://img.youtube.com/vi/4ZzSLk4KQzk/0.jpg)](https://www.youtube.com/watch?v=4ZzSLk4KQzk&time=550 "Test of embedded video")
