### ISSUE TITLE
Error upon install: telescope.project

### ISSUE THREAD

**Issue by bulaybulayRJ** [ChristianChiarulli/LunarVim#492]
Hey Chris, 
I got this error upon installing
E5113: Error while calling lua chunk: ...e-project.nvim/lua/telescope/_extensions/project/git.lua:28: bad argument #1 to 'lines' (/tmp/found_projects.txt: No such file or directory)

**Comment by rebuilt** [comment]
https://github.com/nvim-telescope/telescope-project.nvim/issues/35

**Comment by rebuilt** [comment]
Looks like the issue has been fixed in the latest patch.  Try :PackerSync to update your version of telescope-project

**Comment by gfsd3v** [comment]
Came across this problem yesterday, can confirm that nvim-telescope/telescope-project.nvim#35 fix it

**Comment by jameswalmsley** [comment]
@ChristianChiarulli we can close this one.
