### ISSUE TITLE
[eslint --fix] doesn't work

### ISSUE THREAD

**Issue by theprojectguy** [ChristianChiarulli/LunarVim#493]
Hello 👋,

I wanted to thank you for the great config that you made it is really helpful 🚀 !

I have a problem with `eslint --fix` on my project when I put these 2 lines in the `lv-settings.lua`
```lua
O.tsserver.formatter = 'prettier'
O.tsserver.linter = 'eslint'
O.tsserver.autoformat = true
```
If I understand well the config, in the `efm-general-ls.lua` it should take it in account
```lua
-- tsserver/web javascript react, vue, json, html, css, yaml
local prettier = {formatCommand = "prettier --stdin-filepath ${INPUT}", formatStdin = true}
-- You can look for project scope Prettier and Eslint with e.g. vim.fn.glob("node_modules/.bin/prettier") etc. If it is not found revert to global Prettier where needed.
-- local prettier = {formatCommand = "./node_modules/.bin/prettier --stdin-filepath ${INPUT}", formatStdin = true}

local eslint = {
    lintCommand = "./node_modules/.bin/eslint -f unix --stdin --stdin-filename ${INPUT}",
    lintIgnoreExitCode = true,
    lintStdin = true,
    lintFormats = {"%f:%l:%c: %m"},
    formatCommand = "./node_modules/.bin/eslint --fix-to-stdout --stdin --stdin-filename=${INPUT}",
    formatStdin = true
}

local tsserver_args = {}

if O.tsserver.formatter == 'prettier' then table.insert(tsserver_args, prettier) end

if O.tsserver.linter == 'eslint' then table.insert(tsserver_args, eslint) end

-- local markdownlint = {
--     -- TODO default to global lintrc
--     -- lintcommand = 'markdownlint -s -c ./markdownlintrc',
--     lintCommand = 'markdownlint -s',
--     lintStdin = true,
--     lintFormats = {'%f:%l %m', '%f:%l:%c %m', '%f: %l: %m'}
-- }

local markdownPandocFormat = {formatCommand = 'pandoc -f markdown -t gfm -sp --tab-stop=2', formatStdin = true}

require"lspconfig".efm.setup {
    -- init_options = {initializationOptions},
    cmd = {DATA_PATH .. "/lspinstall/efm/efm-langserver"},
    init_options = {documentFormatting = true, codeAction = false},
    filetypes = {"lua", "python", "javascriptreact", "javascript", "typescript", "sh", "html", "css", "json", "yaml", "markdown", "vue"},
    settings = {
        rootMarkers = {".git/"},
        languages = {
            python = python_arguments,
            lua = lua_arguments,
            sh = sh_arguments,
            javascript = tsserver_args,
            javascriptreact = tsserver_args,
        typescript = {tsserver_args},
            html = {prettier},
            css = {prettier},
            json = {prettier},
            yaml = {prettier},
            markdown = {markdownPandocFormat}
            -- javascriptreact = {prettier, eslint},
            -- javascript = {prettier, eslint},
            -- markdown = {markdownPandocFormat, markdownlint},
        }
    }
}
-- Also find way to toggle format on save
-- maybe this will help: https://superuser.com/questions/439078/how-to-disable-autocmd-or-augroup-in-vim
```
The `eslint` errors are well displayed in the `js` file, but when I save it, `eslint` does not format the file.

I'm not a `lua` expert, maybe there is something that I don't understand ?
I'm running it on `arch` with `nvim=0.5.0`
I can provide you more information if needed !

**Comment by rebuilt** [comment]
Did you install the efm language server?  :Lspinstall efm

What's the output of :LspInfo

**Comment by theprojectguy** [comment]
When I run `:LspInstall efm` I got this output, I can remember that I have already installed it.
<img width="1792" alt="Screenshot 2021-06-15 at 10 33 55" src="https://user-images.githubusercontent.com/40181807/122020593-31a3c580-cdc5-11eb-99b7-c7eb75bbfec0.png">

Here is a screenshot with the `:LspInfo` output.
<img width="1433" alt="Screenshot 2021-06-15 at 10 32 55" src="https://user-images.githubusercontent.com/40181807/122020496-19cc4180-cdc5-11eb-931e-0f6f9d7e3ff9.png">

**Comment by rebuilt** [comment]
How did you install prettier and eslint? If installing locally for the project doesn't work, try installing globally with the -g flag

**Comment by theprojectguy** [comment]
Yes I installed all of them with the following commands:
`npm install -g prettier`
`npm install -g eslint`

I even installed `eslint-config-prettier` just in case
`npm install -g eslint-config-prettier`

To be more precise, I'm running `arch linux` on a `vagrant` virtual machine, as you can see on the previous screenshots, but I don't think it changes something.

**Comment by rebuilt** [comment]
Try running just one; either just prettier or just eslint.  If one works we know efm is doing its job.

**Comment by rebuilt** [comment]
Also check :messages.  
And look at the error logs ~./cache/nvim

**Comment by theprojectguy** [comment]
I finally get `prettier` and `eslint` working, but it does not solve the eslint format problem, because I set the following rule in my `.eslintrc.yml`

```yml
semi: ["error", "never"]
```

So I don't want semi colons in my files, but when `prettier` formats the files, it always adds one at the end of line.

Also I show you the content of the `~/.cache/nvim/lsp.log` file. I just opened a `js` file, save it, and quit `nvim`.
```bash
[ START ] 2021-06-15T09:51:05+0000 ] LSP logging initiated
[ ERROR ] 2021-06-15T09:51:05+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]    "rpc"   "/home/vagrant/.local/share/nvim/lspinstall/efm/efm-langserver" "stderr"    "2021/06/15 09:51:05 efm-langserver: no configuration file\n2021/06/15 09:51:05 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-06-15T09:51:08+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]    "rpc"   "/home/vagrant/.local/share/nvim/lspinstall/efm/efm-langserver" "stderr"    "2021/06/15 09:51:08 ./node_modules/.bin/eslint --fix-to-stdout --stdin --stdin-filename=/home/vagrant/delivery/platform/lambda/function/stepDocumentAnalyze/index.js: Invalid option '--fix-to-stdout' - perhaps you meant '--fix-dry-run'?\n\n2021/06/15 09:51:08 format succeeded\n"
[ ERROR ] 2021-06-15T09:51:10+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]    "rpc"   "/home/vagrant/.local/share/nvim/lspinstall/efm/efm-langserver" "stderr"    "2021/06/15 09:51:10 jsonrpc2 handler: sending response 3: jsonrpc2: connection is closed\n2021/06/15 09:51:10 efm-langserver: connections closed\n"
```

**Comment by theprojectguy** [comment]
I finally get it working by using `eslint_d` for linter and formatter, thank you !
