### ISSUE TITLE
Setting to disable tabs and dashboard?

### ISSUE THREAD

**Issue by mgutz** [ChristianChiarulli/LunarVim#494]
I would like to disable the dashboard as use buffers not tabs. Is there an easy way to do that? I can't find anything in the settings nor  a similar question in issues.

**Comment by rebuilt** [comment]
You can remove the 'dashboard' entry from plugins.lua.  There's no boolean you can flip to do this automatically.  That's the simplest solution.  

I've set up conditional loading for myself for testing but it requires a lot of code that seems unnecessary in your case .  

You can checkout this branch to see how I did it: https://github.com/rebuilt/DeathStar-Vim/tree/lv-rebuilt

TLDR: I set up a new global P in this file https://github.com/rebuilt/DeathStar-Vim/blob/lv-rebuilt/lua/pluginconfig.lua
And then in the plugins.lua file I check that boolean value and load it using packer's 'cond' feature.
