### ISSUE TITLE
Getting E5113 plenary.log not found error.

### ISSUE THREAD

**Issue by thepenguinthatwants** [ChristianChiarulli/LunarVim#497]
Hi, When I try to open nvim I get this error.
Only way to fix is to comment out lv-telescope from init.lua.
Any clue how to fix?

E5113: Error while calling lua chunk: ...ite/pack/packer/opt/telescope.nvim/lua/telescope/log.lua:3: module 'plenary.log' not found:

**Comment by rebuilt** [comment]
Make sure all plugins are installed by running the command :PackerSync.  Then look at :PackerStatus

**Comment by thepenguinthatwants** [comment]
Seems like I didnt do a git pull for a while and there were quite amount of breakage.
