### ISSUE TITLE
hop not working in vscode

### ISSUE THREAD

**Issue by snoosmoomrik** [ChristianChiarulli/LunarVim#498]
Hi. I know that the main purpose of this repository is changed and now it's concentrated on neovim but could you help me with this issue with vscode please?
Few months ago I could use ```\s + 2 letters``` to find text and jump to it in vscode but after update this command is just deletes symbol under cursor. It still works great in neovim (with ```s + 2 letters```) but vscode is now lost this functionality.
I'm noob in neovim configuring and don't even know where to start. Could you give me some advises?

**Comment by rebuilt** [comment]
I don't know anything about vscode but Chris did a video on it a while back https://www.youtube.com/watch?v=g4dXZ0RQWdw
timestamp 12:50

**Comment by snoosmoomrik** [comment]
I learned about this repository just from this video but it's outdated now.

**Comment by rebuilt** [comment]
Add this to plugins.lua

```
use {
  'phaazon/hop.nvim',
  as = 'hop',
  config = function()
    -- you can configure Hop the way you like here; see :h hop-config
    require'hop'.setup { keys = 'etovxqpdygfblzhckisuran' }
  end
}
```

Read about how to use hop on the plugin page https://github.com/phaazon/hop.nvim

You'll also need to set up some keybindings in keybindings.lua
 ~/.config/nvim/lua/keymappings.lua

Copy the style in the keybindings file to make your own keybindings.  If you still can't figure it out read about keybindings here:
https://github.com/nanotee/nvim-lua-guide

Although, I think Chris additionally set up a call to VScode so it registers keybinding there.  Watch the video again to see what he did.  I don't use vscode so I can't help you further down that path.

**Comment by snoosmoomrik** [comment]
Thanks! I installed easyvim plugin similar to this commit https://github.com/ChristianChiarulli/LunarVim/commit/3bb29920e7dea9e43244f7d9fc0306dca6442e40 and it is working for now but I will definitely try to configure hop to work with vscode
