### ISSUE TITLE
Unable to fold HTML/Typescript code

### ISSUE THREAD

**Issue by ChrisBFusion** [ChristianChiarulli/LunarVim#500]
I noticed that code folding wasn't working out of the box for HTML and Typescript React files so I added the line `vim.cmd('set foldmethod=syntax')` to ~/.config/nvim/lua/settings.lua and I still get "No fold found" at obvious code blocks.

**Comment by ChrisBFusion** [comment]
It started working for some reason <shrug>

**Comment by yassinebridi** [comment]
For anyone coming to this issue, add this to config.lua
```lua
vim.cmd [[
  au BufNewFile,BufRead *.ts setlocal filetype=typescript
  au BufNewFile,BufRead *.tsx setlocal filetype=typescriptreact
  filetype plugin indent on
  syntax on
  set foldmethod=syntax
  set foldcolumn=1
  let javaScript_fold=1
  set foldlevelstart=99
]]
```
for javascript files, it doesn't seem to work
