### ISSUE TITLE
getting error while install LunarVim in linux(manjaro)

### ISSUE THREAD

**Issue by TechWithOmid** [ChristianChiarulli/LunarVim#501]
hi, I see your youtube video about LunarVim and I like your config I try to install LunarVim using thing command:
`bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)
`

and I'm sure neovim is installed on my manjaro. but i get this error every time:

`Error detected while processing /home/omid/.config/nvim/init.lua:
line    1:
E492: Not an editor command: require('lv-globals')
".CONFIG_PATH..'/lv-settings.lua')" [New DIRECTORY]
Cannot open file ".CONFIG_PATH..'/lv-settings.lua')"
line    2:
E480: No match: cmd('luafile '
line    3:
E492: Not an editor command: require('settings')
line    4:
E492: Not an editor command: require('lv-gitblame')
line    5:
E492: Not an editor command: require('plugins')
line    6:
E492: Not an editor command: require('lv-utils')
line    7:
E492: Not an editor command: require('lv-autocommands')
line    8:
E492: Not an editor command: require('keymappings')
line    9:
E492: Not an editor command: require('lv-nvimtree') -- This plugin must be required somewhere before colorscheme.  Placing i
t after will break navigation keymappings
line   10:
E492: Not an editor command: require('colorscheme') -- This plugin must be required somewhere after nvimtree. Placing it bef
ore will break navigation keymappings
line   11:
E492: Not an editor command: require('lv-galaxyline')
line   12:
E492: Not an editor command: require('lv-comment')
line   13:
E492: Not an editor command: require('lv-gitblame')
line   14:
E492: Not an editor command: require('lv-compe')
line   15:
E492: Not an editor command: require('lv-barbar')
line   16:
E492: Not an editor command: require('lv-dashboard')
line   17:
E492: Not an editor command: require('lv-telescope')
line   18:
E492: Not an editor command: require('lv-gitsigns')
line   19:
E492: Not an editor command: require('lv-treesitter')
line   20:
E492: Not an editor command: require('lv-matchup')
line   21:
E492: Not an editor command: require('lv-autopairs')
line   22:
E492: Not an editor command: require('lv-rnvimr')
line   23:
E492: Not an editor command: require('lv-which-key')
line   24:
E492: Not an editor command: require('lv-lsp-rooter')
line   25:
E492: Not an editor command: require('lv-zen')
line   27:
E492: Not an editor command: -- extras
line   28:
E121: Undefined variable: O
E15: Invalid expression: O.extras then
line   38:
E492: Not an editor command: -- TODO is there a way to do this without vimscript
".CONFIG_PATH..'/vimscript/functions.vim')" [New DIRECTORY]
Cannot open file ".CONFIG_PATH..'/vimscript/functions.vim')"
line   39:
E480: No match: cmd('source '
line   41:
E492: Not an editor command: -- LSP
line   42:
E492: Not an editor command: require('lsp')
line   43:
E492: Not an editor command: require('lsp.angular-ls')
line   44:
E492: Not an editor command: require('lsp.bash-ls')
line   45:
E492: Not an editor command: require('lsp.clangd')
line   46:
E492: Not an editor command: require('lsp.cmake-ls')
line   47:
E492: Not an editor command: require('lsp.css-ls')
line   48:
E492: Not an editor command: require('lsp.dart-ls')
line   49:
E492: Not an editor command: require('lsp.docker-ls')
line   50:
E492: Not an editor command: require('lsp.efm-general-ls')
line   51:
E492: Not an editor command: require('lsp.elm-ls')
line   52:
E492: Not an editor command: require('lsp.emmet-ls')
line   53:
E492: Not an editor command: require('lsp.graphql-ls')
line   54:
E492: Not an editor command: require('lsp.go-ls')
line   55:
E492: Not an editor command: require('lsp.html-ls')
line   56:
E492: Not an editor command: require('lsp.json-ls')
line   57:
E492: Not an editor command: require('lsp.js-ts-ls')
line   58:
E492: Not an editor command: require('lsp.kotlin-ls')
E492: Not an editor command: require('lsp.html-ls')
line   59:
E492: Not an editor command: require('lsp.latex-ls')
line   60:
E492: Not an editor command: require('lsp.lua-ls')
line   61:
E492: Not an editor command: require('lsp.php-ls')
line   62:
E492: Not an editor command: require('lsp.python-ls')
line   63:
E492: Not an editor command: require('lsp.ruby-ls')
line   64:
E492: Not an editor command: require('lsp.rust-ls')
line   65:
E492: Not an editor command: require('lsp.svelte-ls')
line   66:
E492: Not an editor command: require('lsp.terraform-ls')
line   67:
E492: Not an editor command: -- require('lsp.tailwindcss-ls')
line   68:
E492: Not an editor command: require('lsp.vim-ls')
line   69:
E492: Not an editor command: require('lsp.vue-ls')
line   70:
E492: Not an editor command: require('lsp.yaml-ls')
line   71:
E492: Not an editor command: require('lsp.elixir-ls')
Error detected while processing command line:
E492: Not an editor command: PackerInstall
Press ENTER or type command to continue
`

**Comment by rebuilt** [comment]
Make sure you have at least version 0.5 of neovim. Make sure it was compiled with luajit. If you installed using sudo, follow the steps to uninstall and try again without sudo. Make sure the dependencies were installed. The dependencies are in the readme. Search for 'depends on'. Make sure your plugins are installed. Run :PackerSync
