### ISSUE TITLE
vim command "gg" issue?

### ISSUE THREAD

**Issue by MarkKang05** [ChristianChiarulli/LunarVim#503]
When I edit the code in Vim, if I enter "gg", a menu appears at the bottom when I first type "g".
This menu can be accessed by pressing space and then g.
I am uncomfortable with this
I don't use the menu window very well, and it bothers me that the screen is slightly obscured when I type a command.
can i disable this?

**Comment by rmagillxyz** [comment]
This is caused by [which-key](https://github.com/folke/which-key.nvim). Check out the presets on the gh readme page. 

```lua
    presets = {
      operators = true, -- adds help for operators like d, y, ... and registers them for motion / text object completion
      motions = true, -- adds help for motions
      text_objects = true, -- help for text objects triggered after entering an operator
      windows = true, -- default bindings on <c-w>
      nav = true, -- misc bindings to work with windows
      z = true, -- bindings for folds, spelling and others prefixed with z
      g = true, -- bindings for prefixed with g
    },
@MarkKang05 
```

**Comment by MarkKang05** [comment]
Okay,, I changed the g value to false.
But after saving, the same thing happens.
I think I need to update the packer. What command should I use?
(I'm new to packer...)

**Comment by Walkability** [comment]
Did you close and reopen nvim? @MarkKang05 
The packer command is `PackerSync`, but you shouldn't have to use that because it's plugin is already installed; just close and reopen. You could also try sourcing init.lua with `: luafile $MYVIMRC`, but I have found this to not work with everything so it's just better to restart nvim.

**Comment by MarkKang05** [comment]
I reopened countless times.
No change...

**Comment by MarkKang05** [comment]
presets = {
       operators = true, -- adds help for operators like d, y, ... and registers them for motion / text object completion
       motions = true, -- adds help for motions
       text_objects = true, -- help for text objects triggered after entering an operator
       windows = true, -- default bindings on <c-w>
       nav = true, -- misc bindings to work with windows
       z = true, -- bindings for folds, spelling and others prefixed with z
       g = true, -- bindings for prefixed with g
     },

Can't I just replace "g = true" with "g = false" here?
After testing, the changes are loaded.
Did I change another value?

**Comment by rmagillxyz** [comment]
@MarkKang05 I think you need to also set `operators = false` as some other g commands are also in there also. Does the page look different than it did before?

**Comment by MarkKang05** [comment]
> @MarkKang05 I think you need to also set `operators = false` as some other g commands are also in there also. Does the popup look different than it did before?
@rmagillxyz 

It just disappears the option below from the popup window.
toggle case
lowercase
uppercase

**Comment by rebuilt** [comment]
You can also increase timeoutlen.  If you finish the key combo within the timeout, you'll never see whichkey pop up

**Comment by jameswalmsley** [comment]
@ChristianChiarulli this issue is resolved.

**Comment by MarkKang05** [comment]
@rebuilt 
Okay..so how can i adjust timeoutlen?

**Comment by rebuilt** [comment]
Change this value in lv-settings.  1000 = 1 second.  1000 is the default value vim ships with.
```
O.timeoutlen = 100
```
