### ISSUE TITLE
Petition to add preamble to issues page.

### ISSUE THREAD

**Issue by rmagillxyz** [ChristianChiarulli/LunarVim#504]
There needs to be something on the issues page which discourages people from asking questions on the lunarvim page about other plugins. The appropriate place to ask about an issue or question someone has with a plugin is on that plugin's issue page not here. More than often, while checking out that plugin's page, their questions will be answered without opening an issue. Take a look at the `barbar.vim` [bug reporting](https://github.com/romgrk/barbar.nvim/issues/new?assignees=&labels=&template=bug-report--d.md&title=) page. Something like this directing people to the plugin which they have an issue or question about would prevent the issues page from being cluttered with largely irrelevant issues. 
![pic-selected-2021-06-15_225402](https://user-images.githubusercontent.com/75113855/122151888-597b4380-ce2e-11eb-9d01-b1d4fbd393ee.png)

**Comment by rebuilt** [comment]
I agree that there should be a reporting template. In my experience, plugin specific questions aren't very numerous.  The bigger problem is people not reading the readme.

**Comment by rmagillxyz** [comment]
@rebuilt Yeah, the readme is pretty darn good. Merely mentioning the readme would probably be enough tbh. Also directing people to the matrix server would be good. Most issues are legitimate, and I don't want to deter those who are having real issues, but just a little something to deter the uninitiated.  

```md
Preamble (you can delete this section):
 - Are you using a recent build (november 2020 & up) of neovim 0.5?
 - If not, rebuild it now before reporting the issue.
 - Do you certify having read the [readme](https://github.com/ChristianChiarulli/LunarVim/blob/master/README.md) 
 - If you have questions about modifying a specific plugin's config, be sure to check out that plugin's readme or come and join the lunarvim [matrix](https://matrix.to/#/+atmachine:matrix.org) or [discord](https://discord.com/invite/Xb9B4Ny) server.

**Description**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```
 What do you think about this ^ ?

**Comment by rebuilt** [comment]
> @rebuilt Yeah, the readme is pretty darn good. 

Thanks, I wrote most of it.  

The template looks great.  The only thing I would add is the output of relevant error messages depending on the problem.
General issues:
nvim -v
:checkhealth
:messages

Lsp issues:
:LspInfo
grep ERROR ~/.cache/nvim/lsp.log


Also, thanks for the matrix link.  I didn't know about it. It should probably also be in the readme.

**Comment by rmagillxyz** [comment]
Oh really. Yeah you did a great job, and good suggestions. @rebuilt

**Comment by jameswalmsley** [comment]
We should do this :)
