### ISSUE TITLE
Instructions on how to install new plugins don't work with non-lua plugins.

### ISSUE THREAD

**Issue by t-minski** [ChristianChiarulli/LunarVim#505]
Hi there,

I'm trying to install some additional plugins like explained in the README (i think):

I did the following:
To ~/.config/nvim/lua/plugins.lua I added:
```
    use {"vimwiki/vimwiki", opt = true}
    require_plugin("vimwiki")
```

My only line in ~/.config/nvim/lua/lv-vimwiki/init.lua right now is:
`require'vimwiki'.setup()`

Finally in ~/.config/nvim/init.lua I added:
`require('lv-vimwiki')
`
I did
:PackerCompile
:PackerInstall

I reopen nvim and get
```
Error detected while processing /home/minski/.config/nvim/init.lua:
line    1:
E5113: Error while calling lua chunk: /home/minski/.config/nvim/lua/lv-vimwiki/init.lua:1: module 'vimwiki' not found:
        no field package.preload['vimwiki']
        no file './vimwiki.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vimwiki.lua'
        no file '/usr/local/share/lua/5.1/vimwiki.lua'
        no file '/usr/local/share/lua/5.1/vimwiki/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vimwiki.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vimwiki/init.lua'
        no file './vimwiki.so'
        no file '/usr/local/lib/lua/5.1/vimwiki.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vimwiki.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue
```
Maybe this has something to do with vimwiki not being written in lua? I don't know.
If I leave out the "require'vimwiki'.setup()" bit I don't get the error but I also can't configure the plugin (I tried setting some properties of the plugin in lua (maybe I did something wrong there) but to no effect).

Thanks

**Comment by rebuilt** [comment]
After you make your edits make sure to close and reopen neovim.  At that point, you can :PackerCompile, :PackerInstall.  Optionally, you can :PackerSync to do compiling and installing in one go.  But this also has other side effects you may not want, it updates all your other plugins and it removes any plugins that are no longer referenced in your configs.

**Comment by rebuilt** [comment]
In theory you can run 
```
:luafile %  
```

To source the file again but I've found it unreliable.

**Comment by t-minski** [comment]
Ah thanks for the tip with :luafile %. I was wondering wether there was a better way.
Sadly this does not solve my issue.

**Comment by rebuilt** [comment]
I read though the readme for this plugin:  https://github.com/vimwiki/vimwiki
It's not a lua plugin.  It also doesn't require configuration.  

You only need the changes in the plugin folder for it to work.  Remove any other changes.
I've set it up the plugin in this branch:  https://github.com/rebuilt/DeathStar-Vim/tree/vimwiki

I tested by running :Vimwiki2HTML.  This worked correctly.  The default keybindings look like they've been set.  
I'm not sure what else it's supposed to do but I don't need it so I'm not going to spend more time on it.

**Comment by t-minski** [comment]
Okay thank you. So how can one add non-lua plugins to LunarVim?

**Comment by rebuilt** [comment]
There is no answer to "how do I install in lunarvim" because the question should really be 'how do I install plugins in neovim using packer?'   Lunarvim is not a program.  It's just a set of configurations for neovim.  It uses packer as the plugin manager.  I'd recommend you go through the packer readme to understand how to work with it.  https://github.com/wbthomason/packer.nvim .   The only thing that's lunarvim specific when installing plugins is the 'require_plugin("vimwiki")' function.  But you're not required to use it.  

To get an understanding of the more advanced options of packer you can read through this pull request https://github.com/ChristianChiarulli/LunarVim/pull/416/files

  To really understand adding plugins, I also recommend reading the neovim lua guide.   https://github.com/nanotee/nvim-lua-guide

**Comment by rebuilt** [comment]
To more specifically address your concern about adding configurations to non-lua plugins.  You were on the right track when you created  ~/.config/nvim/lua/lv-vimwiki/init.lua .  But you need to follow the readme for each plugin to understand what to put inside of it.  If it requires keymappings, put those in there.  If it requires something else, the readme for the plugin should tell you what it requires.

**Comment by t-minski** [comment]
Okay thank you that was the answers to my question. I simply misinterpreted the readme to mean that one has to add the require'<plugin>'.setup part for every plugin one adds. Even if it is not a lua plugin. Now I understand that I can just put lua directly into the lua/myplugin/init.lua and it should work if I correctly translated the options from vimlang into lua. Thank You!

**Comment by rebuilt** [comment]
If the readme for the plugin tells you how to configure it in lua.  You can just copy and paste the instructions.  If the instructions are written in vimscript, you'll need to wrap the vimscript in a special lua function

vim.cmd([[ 
YOUR_VIMSCRIPT_GOES_HERE
]])
