### ISSUE TITLE
disable nvim-compe on certain filetypes

### ISSUE THREAD

**Issue by sainivasmangu** [ChristianChiarulli/LunarVim#507]
I use vimwiki and I want to disable certain plugins in .wiki files. I used this command to disable `lua-colorizer` plugin
```
vim.cmd('autocmd VimEnter *.wiki ColorizerDetachFromBuffer')
```
I also want to disable `nvim-compe`. I read the repo readme and went through some issues. What I understood is that there is a way to do this (buffer local config, issue 84) but not as an editor command (so I can't do what I did for the `lua-colorizer`). I didn't understand how I can do this in the `lv-compe/init.lua` file and I need help. Thanks in advance.

**Comment by rebuilt** [comment]
Packer has built-in functionality that can help you achieve this.  

You have one of two options.  
* Either use the 'ft' option to load compe only on certain filetypes.   However, I don't think you're able to disable on certain filetypes.  
* Or use the 'cond' option to load compe conditionally based on certain conditions.  Here you'd have to write a lua function to detect the filetype and return false if the filetype is 'wiki'

```lua
 use {"hrsh7th/nvim-compe",
        cond = function()  
                    local file_type = vim.fn.expand("%:e")
                    return file_type ~= "wiki"
        end,
        config = function() require("lv-compe") end
}
                 ```
Then you'd remove the this line from init.lua
```
require('lv-compe')
```

and remove this line in plugins.lua
```
    require_plugin("nvim-compe")
```

I haven't tested it myself so see if it works and let me know.  
To check the filetype in vim run the command 
```
:set filetype?  
```

You can see if a plugin is loaded with the command :PackerStatus

**Comment by sainivasmangu** [comment]
it worked. thanks so much!
