### ISSUE TITLE
Lsp language server (r_language_server) crashing when using completion

### ISSUE THREAD

**Issue by marc-brouard** [ChristianChiarulli/LunarVim#509]
Thank you for producing a great configuration, been really useful. Unfortunatly I have hit an issue that I am not sure how to fix, if it is a configuration problem, or where to report if it is a bug.

I have added r_language_server to your configuration, and it works fine until i use completion. Looking at the logs I can see the following errors

```
[ START ] 2021-06-15T01:21:42+0100 ] LSP logging initiated
[ ERROR ] 2021-06-15T01:21:54+0100 ] ...im/HEAD-141647c_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"R"	"stderr"	'[2021-06-15 01:21:54.586] error handling json:  Error: parse error: premature EOF\n                                       {"method": "textDocument/didCha\n                     (right here) ------^\n\nStack trace:\n1: parse_string(txt, bigint_as_char)\n2: parseJSON(txt, bigint_as_char)\n3: parse_and_simplify(txt = txt, simplifyVector = simplifyVector, \n    simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, \n    flatten = flatten, ...)\n4: jsonlite::fromJSON(data, simplifyVector = FALSE)\n'
[ ERROR ] 2021-06-15T01:21:54+0100 ] ...im/HEAD-141647c_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"R"	"stderr"	'[2021-06-15 01:21:54.597] Error: Unexpected non-empty line\nCall: self$read_header()\nStack trace:\n1: stop("Unexpected non-empty line")\n2: self$read_header()\n3: self$fetch(blocking = FALSE)\n'
[ ERROR ] 2021-06-15T01:21:54+0100 ] ...im/HEAD-141647c_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"R"	"stderr"	"[2021-06-15 01:21:54.598] exiting\n"
```

I am using NVIM v0.5.0-dev+1403-g141647cfb

I would guess that it is an error with the R language server, but I am not sure. Can you suggest if this is a configuration problem on my part or if it is a bug either in NeoVim's lsp code, nvim-compe or R language server?

Thank you
Marc

**Comment by ChristianChiarulli** [comment]
Anyone who knows how to configure the R lang server, some help would be nice.

**Comment by rebuilt** [comment]
The lspconfig project may be a better place to ask this question.  https://github.com/neovim/nvim-lspconfig

**Comment by ChristianChiarulli** [comment]
Do they have a config?

**Comment by rebuilt** [comment]
https://github.com/neovim/nvim-lspconfig/pull/226

**Comment by marc-brouard** [comment]
Thank you for the comments. Apologies for not replying sooner. I have gone through the diagnostics suggested by [https://github.com/neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig). But can not replicate the crashing of the R Lang Server when using the minimal configuration. I have been trying to identify what is causing the issue but not getting anywhere at the moment.

I have yet to try updating to the latest version of NeoVim and LunarVim. Hope to try this asap, to see if the behaviour with R Lang Server is still the same.

**Comment by rebuilt** [comment]
Getting the lastest version of neovim is a must.  There have been many breaking changes in the development of 0.5.

**Comment by marc-brouard** [comment]
Thank you. 

Installed the latest stable version of both NeoVim and LunarVim and added r.lua to the ftplugin directory. The r_language_server is no longer crashing. I am afraid I have no idea what was causing the r_language_server tto crash previously.

The contents of the r.lua file is
```
require'lspconfig'.r_language_server.setup{
    cmd = { "R", "--slave", "-e", "languageserver::run()" },
    on_attach = require'lsp'.common_on_attach
}
```
I have closed this issue. I will continue working with the configuration though

Thank you again, your configuration is saving me a great deal of time and frustration
