### ISSUE TITLE
Key Lag

### ISSUE THREAD

**Issue by LinuxIsCool** [ChristianChiarulli/LunarVim#510]
There is something happening where about 1 in 20 keystrokes will lag for about 1 second or until I press another key. It's very jarring for the typing experience.
 
I'm not certain that this is due to lunarvim, but it only started happening since I installed it and I'm pretty sure it only starts happening after opening nvim. 

Pop!_OS 20.10
Kernel 5.11.0-7614-generic

I will post more information as I discover more. Posting now in case anyone is experiencing something similar.

**Comment by rebuilt** [comment]
Can you check the error logs in ~/.cache/nvim please?

**Comment by rebuilt** [comment]
Also run :checkhealth
