### ISSUE TITLE
Treesitter error installing on 14 languages

### ISSUE THREAD

**Issue by jordisantamaria** [ChristianChiarulli/LunarVim#514]
Hi, today I updated nvim to last version and reinstall the project, then treesitter gived error installing 14 languages, some of them are vue, python, yaml, etc... error looks like this
![スクリーンショット 2021-06-21 0 22 12](https://user-images.githubusercontent.com/6263700/122680551-adb96580-d22a-11eb-8c69-f7ac1f08a1c1.png)

**Comment by rebuilt** [comment]
There have been some breaking changes in neovim.  You'll probably also need to update your plugins.  

```
:PackerSync
```

**Comment by jordisantamaria** [comment]
As I said, I reinstalled all from 0 (uninstalled nvim and LunarVim and installed again), so all plugins are up to date.

**Comment by rebuilt** [comment]
Plugins will be up to date if you also deleted .local/share/nvim/site
If you didn't, packer will see that they're already installed and not update anything.  
:PackerUpdate or PackerSync will both update your plugins.  

This is the relevant line from the installer.  You'll notice it only does an install, not a sync or update
```
	nvim -u $HOME/.config/nvim/init.lua +PackerInstall
```

**Comment by jordisantamaria** [comment]
Seems It's fixed uninstalling xcode.
