### ISSUE TITLE
rnvmr not working

### ISSUE THREAD

**Issue by genesis-algorithms** [ChristianChiarulli/LunarVim#515]
Hi, thank you for the awesome project! I've been trying to migrate to vim/nvim for a long time but the configuration overhead was always keeping me back. But with this project, it seems like a possible thing now and I'm so excited.

Though currently I have few problems and would like to ask them here:
1. Running RnvimrToggle triggers a popup but it's empty:
![Screen Shot 2021-06-20 at 19 11 57](https://user-images.githubusercontent.com/5767281/122681106-64055680-d1fb-11eb-9a73-eb0c0017d797.png)
It seems like I have the package under `~/.config/nvim/lua` and `~/.local/share/nvim/site/pack/packed/start/nvimr` but have no idea why it's not working (I'm pretty new to this ecosystem and have no idea how to troubleshoot this sadly).
2. I want to make the nvim-tree to open on bottom side and if I'm not wrong I have to write something like `O.nvimtree.nvim_tree_side = 'bottom'` in the settings file but when I do this it breaks the configuration. I was able to make it work by typing the command `nvim_tree_side` directly in lv-nvimtree/init.lua file but I guess it's not the proper way of doing this.
3. I'm a js dev mainly working with react and the tools around it how do I make the intellisense work like in VSCode? Like for example how to make nvim show available imports when importing?
4. I would like to increase the text line height how do I do this with init.lua or the settings file?
5. Is it possible to decrease the space between nvim command input and the tmux bar?
![Screen Shot 2021-06-20 at 19 40 53](https://user-images.githubusercontent.com/5767281/122681942-6ff31780-d1ff-11eb-86da-e8d67dc636ca.png)

OS: macOS Catalina
Terminal: Alacritty
Shell: Zsh with OhMyZsh

I hope the thread doesn't get closed because of the other questions. I know I lack an embarrassing amount of info but don't know where else I could ask them. Especially now when things changed with the new Lua file system a lot of the answers on the internet seem old and not work for me :(

Thanks in advance!

**Comment by rmagillxyz** [comment]
is ranger installed on your machine? `> which ranger` 
if not install it and that should fix the empty rnvmr

**Comment by genesis-algorithms** [comment]
@rmagillxyz Thanks! Yeah, the problem was me not having ranger installed, sorry. Can you help with my other questions also 😅

**Comment by genesis-algorithms** [comment]
Thanks for the help I was able to resolve my other questions within the discord community and now going to close this thread.
