### ISSUE TITLE
Diagnostics error color

### ISSUE THREAD

**Issue by turutupa** [ChristianChiarulli/LunarVim#516]
First of all, thanks for the awesome work, lunarvim is simply awesome!

Minor problem, I can't seem to figure out how to change the in-line error messages? Currently I am using gruvbox theme and error message appears in sort of white, don't know if this is how is supposed to be. 

Ideally error message would pop out better in red. How could I change this? 

![image](https://user-images.githubusercontent.com/44581951/122685750-9e77ef00-d20d-11eb-8b38-aa406d06edf8.png)

Thanks in advance!

**Comment by rebuilt** [comment]
Are you using a version of gruvbox with tree-sitter support?  If not, find one here: https://github.com/rockerBOO/awesome-neovim#treesitter-support

**Comment by turutupa** [comment]
@rebuilt I am using the colorscshemes that comes with this repo. So I expected them to already work properly (red colored in diagnostic).

I changed to snazzy colorscheme for a more vibrant color but diagnostics color is still white. Do I have to download a compatible colorscheme? Are the ones in this repo not working out of the box? 

Thx for your help!

**Comment by turutupa** [comment]
@rebuilt Hey man, you were totally right. I tried downloading themes from the repo you provided and it works now. Million thanks!!! cheers!!!

**Comment by rebuilt** [comment]
For anyone else reading this.  This version of gruvbox provides red error highlights: https://github.com/npxbr/gruvbox.nvim 
I think this issue should be created in Chris's colorscheme repo  https://github.com/ChristianChiarulli/nvcode-color-schemes.vim

I imagine gruvbox is missing this:

```
LspDiagnosticsSignError: "error_red"
```

But I've never edited colorschemes so it's just a wild guess.

**Comment by rebuilt** [comment]
> Are the ones in this repo not working out of the box?

I use lunar and it highlights errors in red.  I haven't really tried the other colorschemes.

**Comment by turutupa** [comment]
Oh! You're right! Lunar does work!

**Comment by turutupa** [comment]
@rebuilt interestingly, I've tried copying the LspDiagnostics properties from lunar into the gruvbox theme, but still doesn't work with the inbuilt gruvbox theme. Themes from the repo you shared earlier seem to work though. Although I can't seem to be able to set them as default theme.

**Comment by rebuilt** [comment]
Did you remove the nvcode colorscheme plugin?  When I tested it I removed that plugin because of the name clash on 'gruvbox'.  I also removed the nvcode line from colorscheme.lua.

**Comment by turutupa** [comment]
@rebuilt Thank you so much. I...
- Removed nvcode plugin from plugins.lua
- Deleted first line from colorscheme.lua, the one that sets nvcode colors to 256.
- Set default to colorscheme in lv-settings.lua to gruvbox colorscheme (gruvbox from the repo shared prev https://github.com/rockerBOO/awesome-neovim#treesitter-support) 

and everything working perfectly!!! Default theme working plus red colors rendering correctly

Thank you so much! :)

I'll close the ticket now and hopefully this will contain enough info for other people with same problem to solve it.
