### ISSUE TITLE
The screen of the editor

### ISSUE THREAD

**Issue by Jasylum** [ChristianChiarulli/LunarVim#521]
Is the padding around the screen a addition?
![2021-06-22-150639_1920x1080_scrot](https://user-images.githubusercontent.com/52153618/122900140-26740b00-d36c-11eb-98fb-28786585ea55.png)

**Comment by Tastyep** [comment]
Not sure what you are talking about, but it seems to be a problem with the software handling the window, not vim.
Look into your terminal's settings ?

**Comment by Jasylum** [comment]
oh my bad, I had padding set in my terminal emulator.
