### ISSUE TITLE
TypeScript: Ranger opens VLC instead of a new buffer

### ISSUE THREAD

**Issue by aaronmcadam** [ChristianChiarulli/LunarVim#522]
Ranger is recognising `.ts` files a Video Mpeg files (TS files)! 

I think this is to do with `rifle` settings, but I can't find out how to remove those!

**Comment by rebuilt** [comment]
https://codeyarns.com/tech/2015-03-12-how-to-set-file-association-in-ranger.html

**Comment by aaronmcadam** [comment]
So, I had to configure rifle to open `.ts` files within vim: https://github.com/aaronmcadam/dotfiles/commit/967133f4b91851c060fa79be94f46d77dc71f9c4

I think this config should be part of LunarVim somehow, maybe just a note about it?

**Comment by aaronmcadam** [comment]
Thanks @rebuilt, do you think we could update the docs because I'm sure other TypeScript engineers will run into this problem! Feel free to close this issue if you think it's resolved, though 😄
