### ISSUE TITLE
:LspInstall efm giving errors

### ISSUE THREAD

**Issue by bishnu-47** [ChristianChiarulli/LunarVim#528]
I am getting following error:

```
/bin/bash: line 1: go: command not found

[Process exited 127]
```

`.../site/pack/packer/opt/nvim-lspinstall/lua/lspinstall.lua:16: [nvim-lspinstall] Could not install language server for efm`

**Comment by rebuilt** [comment]
Install golang

**Comment by bishnu-47** [comment]
@rebuilt same error for :LspInstall go

**Comment by Tastyep** [comment]
Please follow this install procedure for installing golang on your system
https://golang.org/doc/install

`/bin/bash: line 1: go: command not found`
This means that bash can't find the go executable (looking into the $PATH variable)

**Comment by bishnu-47** [comment]
ok Thank @Tastyep that solved LspInstall problem, but what about `PackerSync` why am I getting that error?

**Comment by rebuilt** [comment]
For the autocmd error, upgrade neovim.  There have been few breaking changes in neovim but this was one of them.  

https://github.com/ChristianChiarulli/LunarVim/issues/464

**Comment by bishnu-47** [comment]
Everything is fine now thanks :smiley:
