### ISSUE TITLE
nonumber, norelativenumber in terminal

### ISSUE THREAD

**Issue by crucificados666** [ChristianChiarulli/LunarVim#530]
where should i place code to avoid numbers, relativenumbers in terminal?

**Comment by rebuilt** [comment]
~/.config/nvim/lua/lv-globals.lua
lines 11-12

**Comment by nawfalmrouyan** [comment]
Add this in vimscript/functions.vim

augroup neovim_terminal
    autocmd!
    " Enter Terminal-mode (insert) automatically
    autocmd TermOpen * startinsert
    " Disables number lines on terminal buffers
    autocmd TermOpen * :set nonumber norelativenumber
    " allows you to use Ctrl-c on terminal window
    autocmd TermOpen * nnoremap <buffer> <C-c> i<C-c>
augroup END

**Comment by crucificados666** [comment]
works. cheers!

**Comment by qkzk** [comment]
Thanks for the tip, but it also removes all line number from files you open after having opened a terminal.

I just changed it like that and it's perfect.

```diff
augroup neovim_terminal
    autocmd!
    " Enter Terminal-mode (insert) automatically
    autocmd TermOpen * startinsert
    " Disables number lines on terminal buffers
-    autocmd TermOpen * :set nonumber norelativenumber
+   autocmd TermOpen * :setlocal nonumber norelativenumber
    " allows you to use Ctrl-c on terminal window
    autocmd TermOpen * nnoremap <buffer> <C-c> i<C-c>
augroup END
```
