### ISSUE TITLE
One Line Install Fails

### ISSUE THREAD

**Issue by w-r-z-k** [ChristianChiarulli/LunarVim#533]
The one line install fails with this error:

Error detected while processing /Users/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/user/.config/nvim/lua/lv-nvimtree/init.lua:23: module 'nvim-tree.config' not found:
        no field package.preload['nvim-tree.config']
        no file './nvim-tree/config.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/luajit-2.1.0-beta3/nvim-tree/config.lua'
        no file '/usr/local/share/lua/5.1/nvim-tree/config.lua'
        no file '/usr/local/share/lua/5.1/nvim-tree/config/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/nvim-tree/config.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/nvim-tree/config/init.lua'
        no file './nvim-tree/config.so'
        no file '/usr/local/lib/lua/5.1/nvim-tree/config.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/nvim-tree/config.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './nvim-tree.so'
        no file '/usr/local/lib/lua/5.1/nvim-tree.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/nvim-tree.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by rebuilt** [comment]
85  README.md 
@@ -25,6 +25,8 @@ Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-squ
- [Project Goals](#project-goals)
- [Install In One Command!](#install-in-one-command)
  * [Get the latest version of Neovim](#get-the-latest-version-of-neovim)
  * [Troubleshooting installation
    problems](#troubleshooting-installation-problems)
- [Getting started](#getting-started)
  * [Home screen](#home-screen)
  * [Leader and Whichkey](#leader-and-whichkey)
@@ -52,6 +54,7 @@ Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-squ
- [Useful commands for
  troubleshooting](#useful-commands-for-troubleshooting)
- [Uninstalling](#uninstalling)
- [Community links](#community-links)
- [TODO](#todo)

# What’s included?
@@ -135,7 +138,20 @@ or if you are on Arch you can get it from the AUR
yay -S neovim-git
```

if you are on Gentoo you have to emerge the 9999 neovim version with luajit as the lua single target
If you are on Gentoo you have to emerge the 9999 neovim version with luajit as the lua single target

## Troubleshooting installation problems
If you encounter problems with the installation check the following: 
1. Make sure you have at least version 0.5 of neovim. 
2. Make sure neovim was compiled with luajit. 
  ```bash
  # The output of version information should include a line for: LuaJIT 
  nvim -v
  ```
3. If you installed using sudo, follow the steps to [uninstall](#uninstalling) and try again without sudo. 
4. Make sure the [dependencies](#useful-programs) were installed.  
5. Make sure your plugins are installed and updated. Run :PackerSync

**Comment by SnekCode** [comment]
> If you encounter problems with the installation check the following:
> 
> 1. Make sure you have at least version 0.5 of neovim.
> 2. Make sure neovim was compiled with luajit.
> 
> ```shell
> # The output of version information should include a line for: LuaJIT 
> nvim -v
> ```
> 
> 1. If you installed using sudo, follow the steps to [uninstall](#uninstalling) and try again without sudo.
> 2. Make sure the [dependencies](#useful-programs) were installed.
> 3. Make sure your plugins are installed and updated. Run :PackerSync

Hello, I'm also running into similar issues.

output of nvim -v 
```
NVIM v0.5.0-dev+1436-g510ed996d
Build type: Release
LuaJIT 2.1.0-beta3
```

The links you posted seem to be broken because both route back to this issue.

**Comment by rebuilt** [comment]
https://github.com/ChristianChiarulli/LunarVim#uninstalling
https://github.com/ChristianChiarulli/LunarVim#useful-programs

If the install script doesn't work for you try to manual install 

First make sure you have version [0.5 of
neovim](#get-the-latest-version-of-neovim).


Install xclip, python3, ripgrep, fzf, npm, nodejs, pip, and ranger with the package manager for your distribution.

```bash
# Ubuntu
sudo apt install xclip python3-pip nodejs npm ripgrep fzf ranger libjpeg8-dev zlib1g-dev python-dev python3-dev libxtst-dev python3-pip
# Arch
sudo pacman -S xclip python python-pip nodejs npm ripgrep fzf ranger
# Fedora
sudo dnf groupinstall "X Software Development"
sudo dnf install -y xclip python3-devel pip nodejs npm ripgrep fzf ranger 
pip3 install wheel ueberzug
# Gentoo
sudo emerge -avn sys-apps/ripgrep app-shells/fzf app-misc/ranger dev-python/neovim-remote virtual/jpeg sys-libs/zlib
sudo emerge -avn dev-python/pip
# Optional.   Enable npm USE flag with flaggie
sudo flaggie net-libs/nodejs +npm
sudo emerge -avnN net-libs/nodejs
# Mac
brew install lua node yarn ripgrep fzf ranger
sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
rm get-pip.py
```

Install tree-sitter.  To globally install packages without the need for sudo
follow [this guide](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)

```bash
npm install -g tree-sitter-cli
```

Install ueberzug, neovim-remote, and pynvim with pip3

```bash
pip3 install ueberzug neovim neovim-remote pynvim --user
```

Clone LunarVim and Packer

```bash
git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
git clone https://github.com/ChristianChiarulli/lunarvim.git ~/.config/nvim
```

Install plugins
```
nvim -u $HOME/.config/nvim/init.lua +PackerInstall
```

**Comment by SnekCode** [comment]
No dice for me after following the manual install guide.  I'm on a fresh macOS install.  Waiting to here if @w-r-z-k has had any luck!

**Comment by rebuilt** [comment]
> 
> 
> No dice for me after following the manual install guide. I'm on a fresh macOS install. Waiting to here if @w-r-z-k has had any luck!

Do you have the same error message or a different one?

**Comment by SnekCode** [comment]
Same error.  `E5113: Error while calling lua chunk: vim.lua:97: module 'vim.uri' not found:`

**Comment by rebuilt** [comment]
> 
> 
> Same error. `E5113: Error while calling lua chunk: vim.lua:97: module 'vim.uri' not found:`

Did you compile this yourself or download the binary?
https://github.com/neovim/nvim-lspconfig/issues/443

To compile yourself:
Install the prerequisites for compiling on mac
```
https://github.com/neovim/neovim/wiki/Building-Neovim#macos
```

Compile and install
```
cd $(mktemp -d)
git clone https://github.com/neovim/neovim --depth 1
cd neovim
sudo make CMAKE_BUILD_TYPE=Release install
cd ..
sudo rm -r neovim
```

**Comment by SnekCode** [comment]
@rebuilt sorry just got a chance to re attack this.

Originally I downloaded the binary.  After compiling locally I get the same error as @w-r-z-k when using the single command install script.  
Error: `E5113: Error while calling lua chunk: /Users/snekcode/.config/nvim/lua/lv-nvimtree/init.lua:23: module 'nvim-tree.config' not found:`

Though the error only seems to pop up during the actual install.  When running nvim <Leader>e opens the nvim-tree `¯\_(ツ)_/¯`

After an uninstall, I followed the manual steps list above now using the locally compiled version of nvim.  I received the same error, E5113 for nvim-tree.config.  

For both install cases using the command :PackerInstall inside nvim worked with out issue and it seems this error is only happens for the initial invocation of `nvim -u $HOME/.config/nvim/init.lua +PackerInstall`

**Comment by rebuilt** [comment]
Ah, ok.  I assumed this was the error message each time neovim was started.  

That's an expected error message at that point.  I'm not sure why it's being printed now when it historically has not been seen.  The first time you open neovim, none of the plugins have been installed.  All those error messages are related to the plugins not being found.  After they've been installed, you won't see the message again.

**Comment by w-r-z-k** [comment]
Thanks. All working now.  It was just that install error on the one-line install that threw me off; thinking something had gone wrong.
