### ISSUE TITLE
Has anyone got this to work with Windows?

### ISSUE THREAD

**Issue by DuckyDaDuck** [ChristianChiarulli/LunarVim#534]
ive been trying to get this to work with windows 10 but as of now am unsuccessful in doing so

**Comment by rebuilt** [comment]
Are you trying to get the neovim portion to work or the [vscodium](https://github.com/ChristianChiarulli/LunarVim#vscodium) integration?

**Comment by DuckyDaDuck** [comment]
both i switch between both from time to time

**Comment by rebuilt** [comment]
What have you tried. What's working and what isn't?  What error messages do you get?

**Comment by DuckyDaDuck** [comment]
ive tried the regular installation and i remember seeing something in the issues about a way to install it on windows but i cant recall it and a few other random things to no avail as for errors i cant remember the exact errors id have to retry it to see

**Comment by DuckyDaDuck** [comment]
when running bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh) in git bash i get Error detected while processing C:/Users/Wright/.config/nvim/init.lua:

**Comment by DuckyDaDuck** [comment]
this is what i get when trying to install with wsl2 with ubuntu in windows terminal

**Comment by DuckyDaDuck** [comment]
```
Error detected while processing /home/ducky/.config/nvim/init.lua:
line    1:
E492: Not an editor command: require('lv-globals')
".CONFIG_PATH..'/lv-settings.lua')" [New DIRECTORY]
Cannot open file ".CONFIG_PATH..'/lv-settings.lua')"
line    2:
E480: No match: cmd('luafile '
line    3:
E492: Not an editor command: require('settings')
line    4:
E492: Not an editor command: require('lv-gitblame')
line    5:
E492: Not an editor command: require('lv-matchup')
line    6:
E492: Not an editor command: require('plugins')
line    7:
E492: Not an editor command: require('lv-utils')
line    8:
E492: Not an editor command: require('lv-autocommands')
line    9:
E492: Not an editor command: require('keymappings')
line   10:
E492: Not an editor command: require('lv-nvimtree') -- This plugin must be required somewhere before colorscheme.  Placing it after will break na
vigation keymappings
line   11:
E492: Not an editor command: require('colorscheme') -- This plugin must be required somewhere after nvimtree. Placing it before will break naviga
tion keymappings
line   12:
E492: Not an editor command: require('lv-galaxyline')
line   13:
E492: Not an editor command: require('lv-comment')
line   14:
E492: Not an editor command: require('lv-gitblame')
line   15:
```

**Comment by DuckyDaDuck** [comment]
ive tried other methods of installing but this is as far as i get

**Comment by rmagillxyz** [comment]
is lua and luajit installed? @DuckyDaDuck

**Comment by DuckyDaDuck** [comment]
lua should be not sure about luajit

**Comment by rebuilt** [comment]
@DuckyDaDuck can you please run 
```
nvim -v 
```
and post the output.

This looks like version 0.4 of neovim is being used, not 0.5.

**Comment by DuckyDaDuck** [comment]
yeah NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by DuckyDaDuck** [comment]
thats when i run via ubuntu in windows terminal in bash its 0.5

**Comment by rebuilt** [comment]
Follow the instructions to compile 0.5 version of neovim https://github.com/ChristianChiarulli/LunarVim#get-the-latest-version-of-neovim

**Comment by DuckyDaDuck** [comment]
im already doing it

**Comment by DuckyDaDuck** [comment]
although im shocked i thought i already installed 0.5 in wsl2 ubuntu terminal guess i got mixed up

**Comment by DuckyDaDuck** [comment]
alright i compiled im assuming try the install again

**Comment by DuckyDaDuck** [comment]
once i tried to reinstall i get this
Error detected while processing /home/ducky/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/ducky/.config/nvim/lua/lv-nvimtree/init.lua:23: module 'nv
im-tree.config' not found:
        no field package.preload['nvim-tree.config']
        no file './nvim-tree/config.lua'
        no file '/tmp/tmp.xXEV9CgaDE/neovim/.deps/usr/share/luajit-2.1.0-beta3/nvim-tree/config.lua'
        no file '/usr/local/share/lua/5.1/nvim-tree/config.lua'
        no file '/usr/local/share/lua/5.1/nvim-tree/config/init.lua'
        no file '/tmp/tmp.xXEV9CgaDE/neovim/.deps/usr/share/lua/5.1/nvim-tree/config.lua'
        no file '/tmp/tmp.xXEV9CgaDE/neovim/.deps/usr/share/lua/5.1/nvim-tree/config/init.lua'
        no file './nvim-tree/config.so'
        no file '/usr/local/lib/lua/5.1/nvim-tree/config.so'
        no file '/tmp/tmp.xXEV9CgaDE/neovim/.deps/usr/lib/lua/5.1/nvim-tree/config.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './nvim-tree.so'
        no file '/usr/local/lib/lua/5.1/nvim-tree.so'
        no file '/tmp/tmp.xXEV9CgaDE/neovim/.deps/usr/lib/lua/5.1/nvim-tree.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by DuckyDaDuck** [comment]
although it did still bring me into nvim in the terminal
and everything from the packer.nvim has installed

**Comment by muditbatra** [comment]
Are you trying to install in WSL or using the nvim-qt.exe/nvim.exe. I got it working to some extent on windows using the 0.5 version with nvim.exe, you would need cygwin/mingw to run the shell script and cater to few linux based dependancy. I believe it works best in WSL if you are windows user.
I haven't seen the below error though, more details would be helpful
> once i tried to reinstall i get this
> Error detected while processing /home/ducky/.config/nvim/init.lua:
> E5113: Error while calling lua chunk: /home/ducky/.config/nvim/lua/lv-nvimtree/init.lua:23: module 'nv
> im-tree.config' not found:
> no field package.preload['nvim-tree.config']
> no file './nvim-tree/config.lua'
> no file '/tmp/tmp.xXEV9CgaDE/neovim/.deps/usr/share/luajit-2.1.0-beta3/nvim-tree/config.lua'
> no file '/usr/local/share/lua/5.1/nvim-tree/config.lua'
> no file '/usr/local/share/lua/5.1/nvim-tree/config/init.lua'
> no file '/tmp/tmp.xXEV9CgaDE/neovim/.deps/usr/share/lua/5.1/nvim-tree/config.lua'
> no file '/tmp/tmp.xXEV9CgaDE/neovim/.deps/usr/share/lua/5.1/nvim-tree/config/init.lua'
> no file './nvim-tree/config.so'
> no file '/usr/local/lib/lua/5.1/nvim-tree/config.so'
> no file '/tmp/tmp.xXEV9CgaDE/neovim/.deps/usr/lib/lua/5.1/nvim-tree/config.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'
> no file './nvim-tree.so'
> no file '/usr/local/lib/lua/5.1/nvim-tree.so'
> no file '/tmp/tmp.xXEV9CgaDE/neovim/.deps/usr/lib/lua/5.1/nvim-tree.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by DuckyDaDuck** [comment]
i got it working now thanks for all the help :)

**Comment by DuckyDaDuck** [comment]
i actually have it setup nice for me lunar vim runs in wsl2 and have another separate config for windows

**Comment by DuckyDaDuck** [comment]
one last question where would the /home/USERNAME/.config/ be on windows i checked my ~/.config in windows but didnt find the config there

**Comment by muditbatra** [comment]
For nvim.exe/nvim-qt.exe mine is in, C:\Users\your_user_name\AppData\Local\nvim
For WSL it is in ~/.config/nvim

> one last question where would the /home/USERNAME/.config/ be on windows i checked my ~/.config in windows but didnt find the config there
