### ISSUE TITLE
cmd is executable: false

### ISSUE THREAD

**Issue by mayankdutta** [ChristianChiarulli/LunarVim#537]
Facing `cmd is executable`: `false` in EVERY FILE. <br> <br>
`Operating system`
```
macOS big sur
Version 11.2.3
```

`terminal`
```
kitty
```

`nvim -v`

    NVIM v0.5.0-dev+nightly-347-gbdf3df402
    Build type: Release
    LuaJIT 2.1.0-beta3
    Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210626-3873-1sz0s1q/build/config -I/tmp/neovim-20210626-3873-1sz0s1q/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210626-3873-1sz0s1q/build/src/nvim/auto -I/tmp/neovim-20210626-3873-1sz0s1q/build/include
    Compiled by info@Mayanks-MacBook-Air.local
    
    Features: +acl +iconv +tui
    See ":help feature-compile"
    
       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-bdf3df4_2/share/nvim"

command `LspInfo` <br>
![Screenshot 2021-06-27 at 7 36 09 PM](https://user-images.githubusercontent.com/33067129/123547748-9b39b180-d77f-11eb-8922-9856c2d7e410.png)

<br> <br> Please tell where i am going wrong.

**Comment by rebuilt** [comment]
Have you installed the servers?
```
:LspInstall efm
:LspInstall typescript 
```

Have you read through the lsp section of the readme?

**Comment by mayankdutta** [comment]
yeah 
- I tried to install the servers by `LspInstall` faced some errors.  
- then manually by `npm install -g typescript typescript-language-server`.
- then went to `last resort` done that remove part and all those steps.

**Comment by mayankdutta** [comment]
> Have you installed the servers?
> 
> ```
> :LspInstall efm
> :LspInstall typescript 
> ```
> 
> Have you read through the lsp section of the readme?

Sorry In haste, misread `typescript` to `tsserver`, and kept my focus on `npm install -g typescript typescript-language-server`.

**Comment by rebuilt** [comment]
What's the output of 
```
which typescript-language-server
which efm-langserver
```
Since you did a global install I expect them to be in /usr/bin/
If so, you'll need to change the 'cmd' variable to match the location

```
    cmd = {"/usr/bin/typescript-language-server", "--stdio"},
```

Also try
```
:LspStart 
```

**Comment by mayankdutta** [comment]
> which typescript-language-server

sorry but this returned nothing, 
I again installed `typescript` using npm 
and then `which` command, but again nothing. 

here is the screen shot of the same. 
![Screenshot 2021-06-27 at 9 01 15 PM](https://user-images.githubusercontent.com/33067129/123550431-0ccb2d00-d78b-11eb-8902-43b02f1729c9.png)

**Comment by rebuilt** [comment]
Looks like you haven't added .nmp-global to your path.  That is done in the .profile file by convention.  You can add the folder to your path. 

Either place this in ~/.profile
```
export PATH=/Users/info/.npm-global/bin:$PATH
```

The output of the npm global install command shows the location of the typescript language server: /Users/info/.npm-global/bin/typescript-language-server   That's the path for your cmd variable

**Comment by mayankdutta** [comment]
Thank you very much, you saved my day !!
