### ISSUE TITLE
LunarVim No StartScreen  / No Ranger 

### ISSUE THREAD

**Issue by oedon23** [ChristianChiarulli/LunarVim#538]
Hi,

just a quick question. I just pulled the newest version of lunar vim. Is it intended that the start screen is not showing anymore?
Also when i execute "vim ." in a folder it opens a file called "." and not ranger in the directory.

Thanks

**Comment by rebuilt** [comment]
Looks like Chris has started to make changes but hasn't finished yet.

```
commit aa78accb6fbe76b8e257909ab301b672f613002d
Author: Chris <chrisatmachine@gmail.com>
Date:   Sun Jun 27 01:31:33 2021 -0400

    removing plugins increasing speed by 100%, still needs more work

```

You can go back a few commits if you like.  

```
git checkout 2cf8580eb79b24a3d565aba8bb3305417811f2c8
```

**Comment by rebuilt** [comment]
You can enable extras in lv-globals but it doesn't include ranger. 

If you want to enable it yourself you'll need to add this to plugins.lua
```
         use {"kevinhwang91/rnvimr", config = function() require('lv-rnvimr') end}
```

remove this line from init.lua
```
require('lv-rnvimr')
```

Change lv-rnvimr/init.lua

```
vim.g.rnvimr_ex_enable = 1
vim.g.rnvimr_draw_border = 1
vim.g.rnvimr_pick_enable = 1
vim.g.rnvimr_bw_enable = 1
vim.api.nvim_set_keymap('n', '-', ':RnvimrToggle<CR>', {noremap = true, silent = true})
vim.cmd([[
    let g:rnvimr_layout = { 'relative': 'editor', 'width': float2nr(1.0 * &columns), 'height': float2nr(1.0 * &lines) - 2, 'col': 0, 'row': 0, 'style': 'minimal' }
let g:rnvimr_presets = [{}]
]])
```

**Comment by ChristianChiarulli** [comment]
things needed to be thinned out, there will be an option to enable specific plugins via, lv-settings in the future.

**Comment by ChristianChiarulli** [comment]
but for now things are very much in alpha, remember Neovim 0.5 isn't even out yet.
