### ISSUE TITLE
Unsupported front, icons of file types or other things are not supported when you are using bash terminal

### ISSUE THREAD

**Issue by RonaldsonBellande** [ChristianChiarulli/LunarVim#539]
![unsupported_front](https://user-images.githubusercontent.com/47253433/123554615-d4a5f900-d74e-11eb-8cdd-557b12d5b537.png)

This picture provides and image using bash terminal, but it does not have any supported front for implementation (shows no icons) in Lunar Vim. I would say to have it so that it auto install the supported front in the repository without trying to search for a supported front. Making it so that every time you run any functionality it will show up in the supported front you want it to show as.

**Comment by rebuilt** [comment]
You'll need to install nerd-fonts https://www.nerdfonts.com/
You have to change your terminal settings as well. Set your terminal font to a nerd font

https://github.com/ChristianChiarulli/LunarVim/issues/383
https://github.com/ChristianChiarulli/LunarVim/issues/281
https://github.com/ChristianChiarulli/LunarVim/issues/235
https://github.com/ChristianChiarulli/LunarVim/issues/112
https://github.com/ChristianChiarulli/LunarVim/issues/22

**Comment by RonaldsonBellande** [comment]
yea, I fixed it but it should really be implemented. So, it is really easy to do so. Don't know why it has not been none, I will create a pull request; maybe
