### ISSUE TITLE
How to disable cursor animations?

### ISSUE THREAD

**Issue by Pocco81** [ChristianChiarulli/LunarVim#540]
Hello! I haven't been able to find what controls the cursor animations here (when yanking text it stays highlighted for a few milliseconds and when pasting text the cursor is left behind, the word appears and after a few milliseconds the cursor goes to the end of the word as expected).

Is it a plugin? If so, which one is it?

**Comment by rebuilt** [comment]
When did you install LunarVim?  Chris made some changes today.  Not sure if this issue is related to those changes.

**Comment by rebuilt** [comment]
Also, how are you using neovim? As a terminal app or are you using neovide or some other neovim frontend?   Or are you using the vscodium integration?

**Comment by Pocco81** [comment]
I'm using the CLI. This is one of the cursor animations:

https://user-images.githubusercontent.com/58336662/123560679-5efb5680-d769-11eb-9c60-b02c2df3928a.mp4

I forked his setup a long time ago, probably 3-4 weeks ago(?)

**Comment by rebuilt** [comment]
Do you get the same behavior with no config?

```
nvim -u NONE <file-to-edit>
```

It might be some problem with a keymapping.  Can you run

```
:map   
:verbose map y
```

If it's a plugin problem, you might try profiling.  Look here: https://vi.stackexchange.com/questions/276/how-to-find-what-slows-down-vim

**Comment by ChristianChiarulli** [comment]
this is in the config somewhere, but I do not recall where.

**Comment by ChristianChiarulli** [comment]
it's in autocommands

**Comment by Pocco81** [comment]
Thanks!
