### ISSUE TITLE
Telescope error on Find Word

### ISSUE THREAD

**Issue by w-r-z-k** [ChristianChiarulli/LunarVim#547]
If I do a clean install; then open vim to the LunarVim dashboard; and select "Find Word"; then enter some text, I get this message:

```
[telescope].^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:425: in function <...ck/packer/start/telescope.nvim/lua/
telescope/pickers. lua:385>
```

**Comment by angryheng** [comment]
yout need to install ripgrep

**Comment by w-r-z-k** [comment]
You're right; it is not installed.

But it is part of the _Install-in-One-Command_ script.  And I see it in the installonmac() function.  But somehow it was not installed.

**Comment by ChristianChiarulli** [comment]
interesting that ripgrep wasn't installed.
