### ISSUE TITLE
can't get `gf` and `gd` to work on react project

### ISSUE THREAD

**Issue by talefe** [ChristianChiarulli/LunarVim#550]
![Screenshot 2021-06-29 at 15 45 02](https://user-images.githubusercontent.com/31940907/123818699-1bcbef80-d8f1-11eb-80aa-7f84ce34e150.png)
Here's an example so you can see what I mean: both `BaseModel` and `UserTypes` are required in a "strange" way in the sense that they don't contain the whole path, but the path *from* the `lib` directory. 
Here you can see the configuration that makes that possible, in a file `jsconfig.json`
![Screenshot 2021-06-29 at 15 49 24](https://user-images.githubusercontent.com/31940907/123819311-96950a80-d8f1-11eb-9a7d-457073d26160.png)
Now, when I try using those commands, I get a `Can't find "BaseModel" in path` which makes sense, since it probably doesn't know how to resolve the paths.
Any ideas on what I might do to make this possible? I have been trying to play with it, but since I don't know lua, I'm a bit lost.

Any help would be appreciated. @ChristianChiarulli

**Comment by ChristianChiarulli** [comment]
Could you try adding this: O.plugin.sanegx.active = true
to lv-config?

Also don't forget to :PackerInstall and :PackerCompile

If this fixes it I will default this plugin to true.

**Comment by ChristianChiarulli** [comment]
If not I have a jsconfig in my blog repo that works for me, you could also try that.

**Comment by talefe** [comment]
`O.plugin.sanegx.active = true` did not work, however...
I just noticed only the `efm` lsp is active when I open `nvim` on the project. Could that be the problem? It is a git repo, so I can't figure out why it isn't attaching. Tried doing [this](https://github.com/ChristianChiarulli/LunarVim/blob/master/README.md#last-resort), no luck.

<img width="1626" alt="Screenshot 2021-06-30 at 00 09 40" src="https://user-images.githubusercontent.com/31940907/123878675-7a1bc100-d937-11eb-84ea-adcb477f4e52.png">

**Comment by talefe** [comment]
Ok, just watched your stream @ChristianChiarulli, and got it fixed! I needed `O.lang.tsserver.active = true`. And btw, no need for `sanegx` to be active. `gf` and `gd` now working, although quite slowly. Thanks anyway! Love the project, keep it up! ❤️

**Comment by orenteriab** [comment]
hi @talefe! -- I'm having this very same issue on `release-1.2/neovim-0.8-8f4a7bde` can you guide me to fix it.
I tried setting `O.lang.tsserver.active = true` in my `lv-settings.lua` but it seems `O` is not defined, trying using command mode `:set O.lang.tsserver.active = true` but I get the same error.

I know this happened some years ago, so may be things changed.
