### ISSUE TITLE
Potentially create LunarVim Organization

### ISSUE THREAD

**Issue by ChristianChiarulli** [ChristianChiarulli/LunarVim#553]
If there is enough interest and buy in from some serious developers I am considering creating a separate org and hosting LunarVim there.

LunarVim will aim to be an opinionated IDE layer for Neovim. Focused on speed, extendibility, and sane defaults.

**Comment by rebuilt** [comment]
I'm in.

**Comment by Tastyep** [comment]
I would be interested as well ! In the meantime, what would be the scope for this repository ?

**Comment by ChristianChiarulli** [comment]
I think a solid 1.0 for LunarVim this repo looks like:

- LVInstall for languages (wrapping NvimLspInstall or whatever happens to be the standard)

- A plugin marketplace (We could begin developing this here or in the organization) LVMarketPlace

- A stable sane user config where a user can define custom configs for installed plugins and languages.

**Comment by Pocco81** [comment]
Awesome!

**Comment by jameswalmsley** [comment]
I'm in

**Comment by chaeing** [comment]
I'm in.

**Comment by rafamadriz** [comment]
Hey @ChristianChiarulli this is an awesome idea, I'd like to be part too.

**Comment by jvaverka** [comment]
I'm in.

Started following your original NVCode articles this year, and got inspired to write my own config which I now use across personal and work machines - even got some team members interested as well. It's Neovim or bust for me now.

My day job is developer at GM where I make some cool stuff for vehicle simulations. I write a good bit of JavaScript & Julia for personal projects. Want to contribute more to FOSS - would love to help out here!

**Comment by brymer-meneses** [comment]
I'm in!

**Comment by IndianBoy42** [comment]
I'm in too, your initial config from weeks ago got me to switch from vscode to neovim, and keeping up with the development its only gotten better. I have a few changes in my fork that I am thinking of organizing and sending as pull requests soon.

**Comment by nitishvelu** [comment]
Im in,
using it since the nvcode days
Haven't touched vscode in about 6 months
Love to see the project go mainstream

**Comment by nkoturovic** [comment]
This would be great!! I'm in too! Like it very much already!

**Comment by luxus** [comment]
i would love to help..

**Comment by abzcoding** [comment]
https://github.com/LunarVim :tada: :partying_face:

**Comment by afridley** [comment]
im in
