### ISSUE TITLE
Error detected while processing .config/nvim/init.lua:

### ISSUE THREAD

**Issue by Juantamayo26** [ChristianChiarulli/LunarVim#554]
I have tried installing LunarVim without success. My OS is Ubuntu 20.04.2 LTS.

![image](https://user-images.githubusercontent.com/47239906/123918162-3762e480-d949-11eb-8420-c75e2517604e.png)

This is my nvim version:

![image](https://user-images.githubusercontent.com/47239906/123918205-4053b600-d949-11eb-8669-96ced6be8bad.png)

**Comment by rebuilt** [comment]
Did packer install the plugins? Run

```
:PackerSync
```

And then post the output of
```
:PackerStatus
```

**Comment by Juantamayo26** [comment]
> Did packer install the plugins? Run
> 
> ```
> :PackerSync
> ```
> 
> And then post the output of
> 
> ```
> :PackerStatus
> ```

Yes, I did
![image](https://user-images.githubusercontent.com/47239906/123923401-8f501a00-d94e-11eb-9ae5-de03829df217.png)

**Comment by rebuilt** [comment]
Did you use sudo with the install script?  If so, follow the steps in the readme to uninstall and try again without sudo

**Comment by RajceP** [comment]
I did fresh manual installation few minutes ago and i face same problem with Packer.

`Not an editor command: PackerInstall`

**Comment by rebuilt** [comment]
I'll test the new version when I get home.  Not sure if Chris changed the behavior of packer.

**Comment by rebuilt** [comment]
In the meantime delete the 'plugin' folder in ~/config/nvim.  That's where packer keeps the compiled file.

**Comment by RajceP** [comment]
> In the meantime delete the 'plugin' folder in ~/config/nvim. That's where packer keeps the compiled file.

I delete these folder before installation:

`~/.config/nvim
~/.cache/nvim
~/.local/share/nvim`

**Comment by rebuilt** [comment]
Looks like the lv-settings file is trying to use the colorscheme before it actually gets installed.  
Install the colorscheme manually with this command. 

```
git clone https://github.com/ChristianChiarulli/nvcode-color-schemes.vim ~/.local/share/nvim/site/pack/packer/opt/nvcode-color-schemes.vim
```

The colorscheme call will need to be in a separate file and required after the plugins get installed by packer.

**Comment by nkoturovic** [comment]
Got same issue with AutoInstall script on Arch with with both AUR packages:
- `neovim-git` (build-from-src)
- `neovim-nightly-bin`

```
Installing LunarVim
pip installed, moving on...
node installed, moving on...
pynvim installed, moving on...
Cloning into '/home/kotur/.local/share/nvim/site/pack/packer/start/packer.nvim'...
remote: Enumerating objects: 2270, done.
remote: Counting objects: 100% (573/573), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 2270 (delta 477), reused 475 (delta 435), pack-reused 1697
Receiving objects: 100% (2270/2270), 707.18 KiB | 2.46 MiB/s, done.
Resolving deltas: 100% (1277/1277), done.
Cloning LunarVim configuration
Cloning into '/home/kotur/.config/nvim'...
remote: Enumerating objects: 4953, done.
remote: Counting objects: 100% (481/481), done.
remote: Compressing objects: 100% (191/191), done.
remote: Total 4953 (delta 285), reused 361 (delta 232), pack-reused 4472
Receiving objects: 100% (4953/4953), 9.73 MiB | 2.73 MiB/s, done.
Resolving deltas: 100% (2825/2825), done.
I recommend you also install and activate a font from here: https://github.com/ryanoasis/nerd-fonts
```
Opens neovim and produces this output in bottom left corner:
```
rror detected while processing /home/kotur/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/kotur/.config/nvim/init.lua:2: Vim(luafile):E5113: Error while calling lua chunk: /home/kotur/.config/nvim/lv-config.lua:13: Vim(colorscheme):
E185: Cannot find color scheme 'lunar'
Error detected while processing command line:
E492: Not an editor command: PackerInstall
Press ENTER or type command to continue
```

Install script worked before latest NeoVim nightly release.

**Comment by rebuilt** [comment]
I made a pull request for this issue.  To test the pull request
```
git fetch origin pull/556/head:colorscheme
git checkout colorscheme

# open nvim
:PackerSync
```

**Comment by ChristianChiarulli** [comment]
is this fixed with the colorscheme update?

**Comment by rebuilt** [comment]
@ChristianChiarulli   

Yeah.  The colorscheme pull request was for this issue.  I tested a new install in a virtual machine.  The install runs smoothly again.

**Comment by dimitarvp** [comment]
I outright deleted all caches _and_ did reinstall because of this (did not test with only deleting caches). After that I made a Borg backup repo tracking the directory before each update so I can easily roll back.

I understand that using the `rolling` branch is accepting some risks so I am not complaining. Here's the LunarVim update mini-script I came up with:

```bash
# LunarVim, the `rolling` branch.
(
     pushd ~/.local/share/lunarvim/lvim &&
     git reset --hard HEAD &&
     git pull &&
     LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-$HOME/.local/share/lunarvim}" &&
     bash "$LUNARVIM_RUNTIME_DIR/lvim/utils/installer/install_bin.sh" &&
     lvim +LvimCacheReset +PackerUpdate +PackerSync +q &&
     popd
)
```
