### ISSUE TITLE
Error while trying to open up nvim.tree

### ISSUE THREAD

**Issue by daiyanze** [ChristianChiarulli/LunarVim#555]
Hi there! I've encountered some error with the recent commit
https://github.com/ChristianChiarulli/LunarVim/commit/96ffccc3e37cb123aecc2ae26276665986b7abbf

This introduced an error when I tried to toggle Nvim tree without opening buffer (file).
![Screen Shot 2021-06-30 at 17 23 37](https://user-images.githubusercontent.com/14920529/123927925-4ccb2380-d9c8-11eb-8173-4b710a23cd22.png)

I think this is where it triggers the error.
![image](https://user-images.githubusercontent.com/14920529/123928265-b77c5f00-d9c8-11eb-8bbc-9282bda04681.png)

How to reproduce:

1. Open neovim
2. Press Space + E

**Comment by rebuilt** [comment]
I recommend using the default nvim-tree toggle function.  
Replace line 64 of ~/.config/nvim/lua/lv-which-key/init.lua with the following

```
vim.api.nvim_set_keymap('n', '<Leader>e',
                        ":lua require'nvim-tree'.toggle()<CR>",
                        {noremap = true, silent = true})

```

I'm not sure what goal @ChristianChiarulli  wanted to achieve with his toggle_tree function so I won't create a pull request for this.  I assume the 'bufferline.state' is for [nvim-bufferline.lua](https://github.com/akinsho/nvim-bufferline.lua).  But that plugin isn't used in this project.

**Comment by daiyanze** [comment]
@rebuilt 
Thank you! Your solution fixed the error. I also wondered if it's meant to use together with another plugin.
Btw, [nnvim-bufferline.lua](https://github.com/akinsho/nvim-bufferline.lua) looks like a very charming plugin. Hope to see it being integrated any day.

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/123972317-bcb9b980-d988-11eb-8ece-0f27b2d7220f.png)

Normally it puts some space between the tree and other tabs

**Comment by nawfalmrouyan** [comment]
Maybe we can use https://github.com/akinsho/nvim-bufferline.lua. It has configuration to set an offset for NvimTree. No need to write a function for that. 

![image](https://user-images.githubusercontent.com/10271030/123987298-a4ce4e00-d9f9-11eb-9bc3-61b325fd31de.png)

**Comment by ChristianChiarulli** [comment]
@nawfalmrouyan Yea that would be great, I would need to figure out how to set it up tho. If anyone wants to tackle implementing that I would welcome a PR, until then it would be nice to get it working with barbar.

**Comment by ChristianChiarulli** [comment]
package.loaded was my friend here
