### ISSUE TITLE
LspInstall fail to configure server properly

### ISSUE THREAD

**Issue by nkoturovic** [ChristianChiarulli/LunarVim#561]
When running LspInstall (tested with cpp, rust, angular) it does not automatically configure LSP server Config.

- When open cpp/rust/angular project it says in status bar: `No Active Lsp`
- LspInfo does not show newly installed LSP in list of configured LSPs. (not showing at all)
- This worked before my new LunarVim install (used to just run LspInstall and it works!)
- Tried multiple times with multiple Arch systems and AUR packages (neovim-git, neovim-nightly-bin) 

**It works for `LspInstall python`**: Maybe Python LSP comes preconfigured with `LunarVim`?

After `LspInstall` `cpp`/`rust`/`angular`:
- It' says successfully installed LSP
- But opening related project `LspInfo` just shows:
```
Configured servers: efm, pyright, sumneko_lua
Neovim logs at: /home/kotur/.cache/nvim/lsp.log

0 client(s) attached to this buffer: 

0 active client(s): 

Clients that match the filetype NvimTree:
```
**Newly installed server is not showing in configured servers**

**Comment by ChristianChiarulli** [comment]
gotta activate it in lv-config O.lang.rust.active = true

there are no docs fo this, there will be hopefully soon.

**Comment by rebuilt** [comment]
Add the following lines to lv-config.lua

```
O.lang.clang.active = true
O.lang.rust.active = true
O.lang.tsserver.active = true
```
