### ISSUE TITLE
Indentation issue in cpp files. 

### ISSUE THREAD

**Issue by mayankdutta** [ChristianChiarulli/LunarVim#563]
i have indentation issue while editing `cpp` file 

1. with `autopairs` and `treesitter indent` enabled
```
        if (something) {|}


        if (something) {
        |
        }

        /* expected */
        if (something) {
             |
        }
```
2. With `treesitter indent off` and enabling `cindent` and `autoindent`
    I get the expected behaviour. 
    
```
         if (something) {
               |
         }
```

`Question` Is there option to include `clang-formatter`, same as `tsserver using prettier`? so that it can format my file after saving.  if yes, How to enable it?

**Comment by rebuilt** [comment]
No, there isn't a clang-formatter yet.  

Do you have the language server on?
If so, can you try formatting by pressing 

```
<space>lf   
```
(That's a lowercase L)

If that works, you can create an autocommand to format on save with 

```
BufWritePre *.cpp lua vim.lsp.buf.formatting_sync(nil,1000)
```

**Comment by ChristianChiarulli** [comment]
we may need to remove cpp from the list of autoindents with treesitter then. Also do you have a link to the clang formatter?

**Comment by mayankdutta** [comment]
> we may need to remove cpp from the list of autoindents with treesitter then. Also do you have a link to the clang formatter?

dont know much about that, [saw this online](https://clang.llvm.org/docs/ClangFormat.html#vim-integration), tried to integrate this but couldn't.

**Comment by mayankdutta** [comment]
> No, there isn't a clang-formatter yet.
> 
> Do you have the language server on?
> If so, can you try formatting by pressing
> 
> ```
> <space>lf   
> ```
> 
> (That's a lowercase L)
> 
> If that works, you can create an autocommand to format on save with
> 
> ```
> BufWritePre *.cpp lua vim.lsp.buf.formatting_sync(nil,1000)
> ```

Thanks, also i want to point out that even after disabling `treesitter indent`, I also had to disable `autopairs` to get correct indentation. I tried to disable them individually but only case in which `both disabled` gave desired indentation.

**Comment by rebuilt** [comment]
https://github.com/windwp/nvim-autopairs/issues/66

**Comment by ChristianChiarulli** [comment]
Can this b closed after merging #569

**Comment by mayankdutta** [comment]
Thanks for quick support.

**Comment by mayankdutta** [comment]
I am using current version of LunarVim and I observed few bugs in indentation. 

## Case-1, In nested if else
`Current Result` <br>
![issue1](https://user-images.githubusercontent.com/33067129/124168115-533dc600-dac2-11eb-9c2b-ca17c0a26d7c.png)

`Expected` <br>
![expected1](https://user-images.githubusercontent.com/33067129/124168098-5042d580-dac2-11eb-9e0a-d65f0e74918f.png)

## Case-2, In for-loops
`Current Result` <br>
![issue2](https://user-images.githubusercontent.com/33067129/124168118-533dc600-dac2-11eb-888a-bc64ef552eb2.png)

`Expected` <br>
![expected2](https://user-images.githubusercontent.com/33067129/124168113-52a52f80-dac2-11eb-9d49-35f9abcb2474.png)


Though i am getting desired output via `clang-format` after enabling `format on saving` #562  . hence doesn't matter that much now, but still this `bug` is here.

**Comment by rebuilt** [comment]
It looks like there was more than one problem to fix.  We've fixed the problem with autopairs.

I think now the indenting behavior is related to how treesitter handles the different cases.  I turned off autopairs to confirm.  It's treesitter that's defining the indenting.  When you open the if statement treesitter adds an indent.  When you add an else statement, treesitter does not add an indentation.  

I will double check the treesitter docs to make sure we've set everything up correctly.  But if I can't find anything, this issue will probably be better handled by the [tree-sitter project](https://github.com/nvim-treesitter/nvim-treesitter).  

Treesitter may not yet have all the rules for every case fleshed out.  

P.S.  The for loop example works correctly if you add curly brackets.  I'm no cpp expert but I think the curly brackets are safer practice.

**Comment by rebuilt** [comment]
I haven't been able to make any progress on this.  Maybe you should ask on the treesitter project.  Specifically, the [cpp grammar maintainer](https://github.com/tree-sitter/tree-sitter-cpp)

To ensure treesitter indentation is enabled run
```
:set indentexpr?
```
If treesitter is enabled for that file, the command should return.  
```
indentexpr=nvim_treesitter#indent()
```

**Comment by mayankdutta** [comment]
Yeah sure, I will raise issue there too,  
and as of now all my `cpp` files working amazingly well, after adding
```
BufWritePre *.cpp lua vim.lsp.buf.formatting_sync(nil,1000)
```

Please feel free to close this issue if you want to or keep this for the future reference.

**Comment by rebuilt** [comment]
Closing since the leftover issues are treesitter related, not LunarVim.
