### ISSUE TITLE
"new zen mode, other one didn't work with lazy loading" - Why can't you lazy load TrueZen.nvim?

### ISSUE THREAD

**Issue by Pocco81** [ChristianChiarulli/LunarVim#568]
Hello again. I'm a little bit concerned by this because in my case lazy loading the plugin does work as shown below:

https://user-images.githubusercontent.com/58336662/124066700-c4b44080-d9fe-11eb-9a42-1daa31a032aa.mp4

As you can see I'm lazy loading TrueZen by setting `cmd  = {"TZAtaraxis", "TZMinimalist", "TZFocus"}`. After any of those commands gets executed the config gets loaded, which should print `ran -------------------`. If the plugin wasn't lazy loaded then `ran -------------------` would have appeared after starting nvim rather than after running `TZAtaraxis`.

Did you try [TrueZen.nvim](https://github.com/Pocco81/TrueZen.nvim) with the latest commits? If so, was the problem still there?

(Btw, the plugin was refactored completely. I'd recommend you try it out)

Edit: I just tried lazy loading the "older version" of TrueZen and it works just fine.

**Comment by ChristianChiarulli** [comment]
I'm not sure what exactly the issue was, but I wasn't able to lazy load and have the first call to `:TZAtaraxis` from which-key work. Just running the command was fine tho. 

I will mark this as an enhancement and give it another shot after a few other pressing refactors.

**Comment by rafamadriz** [comment]
Closing because of #578, Configuration examples were added to the wiki https://github.com/ChristianChiarulli/LunarVim/wiki/Example-plugin-configurations#truezen

**Comment by Pocco81** [comment]
Thanks @rafamadriz! I didn't know about this part of the wiki. Also, kind of unrelated to the issue it self but the padding here is a little bit off:

![image](https://user-images.githubusercontent.com/58336662/125357621-7885cc00-e32d-11eb-8ec3-6e05f2c86d60.png)

Perhaps the lack of indentation in inner tables was added on purpose?

**Comment by rafamadriz** [comment]
Oh yeah I also noticed that. To be honest I don't know why it is like that, wasn't me who added those examples to the wiki. But you're right it should get fixed.
