### ISSUE TITLE
[Suggestion] use DAPInstall.nvim: a plugin for managing several debuggers for Nvim-dap.

### ISSUE THREAD

**Issue by Pocco81** [ChristianChiarulli/LunarVim#574]
From [DAPInstall.nvim's(https://github.com/Pocco81/DAPInstall.nvim) TL;DR:
> DAPInstall.nvim is a NeoVim plugin written in Lua that extends nvim-dap's functionality for managing various debuggers. Everything from installation, configuration, setup, etc... can be done using DAPInstall.nvim. To get started, install it with your favorite plugin manager and then install the debuggers you'd like to use using the ':DIInstall ' command and [optionally] use their default configs.

It works similarly to LSPInstall, but instead of installing language servers it installs debuggers.

**Comment by ChristianChiarulli** [comment]
I will try to look into this soon, adding to To Do.

**Comment by abzcoding** [comment]
@Pocco81 @ChristianChiarulli  this has been merged to master, we can close this issue.

**Comment by Pocco81** [comment]
Awesome!

**Comment by endlesscpp** [comment]
> Awesome!

Is it still work? I have enabled dap and DAPInstall, nvim-dap plugins are installed.
However, LunarVim still report ":DIInstall isn't a valid editor command", could you please help on this? (neovim 0.7.0)

**Comment by Pocco81** [comment]
@endlesscpp it's still under dev. Check out the `dev` branch tho. That one has the old codebase.

**Comment by abzcoding** [comment]
> > Awesome!
> 
> Is it still work? I have enabled dap and DAPInstall, nvim-dap plugins are installed. However, LunarVim still report ":DIInstall isn't a valid editor command", could you please help on this? (neovim 0.7.0)

we are currently using the `dev` branch of dap-buddy
https://github.com/LunarVim/LunarVim/blob/d868dc14fe04792fc989bb94592f3ba697edd692/lua/lvim/plugins.lua#L215-L222

you just need to add this to your config
```lua
lvim.builtin.dap.active = true
```

**Comment by endlesscpp** [comment]
It works now, thank you guys very much :)
