### ISSUE TITLE
vim.lsp.buf.formatting_sync(nil, 1000) always times out for lua, python and rust (but not clang)

### ISSUE THREAD

**Issue by IndianBoy42** [ChristianChiarulli/LunarVim#575]
You can look at my config in my fork here: https://github.com/IndianBoy42/LunarVim.git

But diffing with your master branch doesn't seem to show significant differences related to the formatting changes.

I have 'black', 'yapf' and 'lua-format' installed, although even if I change the config to try and run a nonexistent executable (in efm-general-ls.lua) I don't get a command not found.

Running `nvim -V10nvim.log` doesn't show anything past timeout either

**Comment by IndianBoy42** [comment]
Wait actually the rust thing was just a misconfiguration on my part, but lua and python (which is handled by efm still doesn't) work

**Comment by rebuilt** [comment]
What's the output of :LspInfo?

**Comment by IndianBoy42** [comment]
```
Configured servers: rust_analyzer, texlab, jsonls, clangd, pyright, sumneko_lua, efm
Neovim logs at: /home/amedhi/.cache/nvim/lsp.log

2 client(s) attached to this buffer: efm, sumneko_lua

  Client: efm (id 1)
  	root:      /home/amedhi/.config/nvim
  	filetypes: lua, python, javascriptreact, javascript, typescript, typescriptreact, sh, html, css, yaml, markdown, vue
  	cmd:       /home/amedhi/.local/share/nvim/lspinstall/efm/efm-langserver
  	


  Client: sumneko_lua (id 2)
  	root:      /home/amedhi/.config/nvim/lua
  	filetypes: lua
  	cmd:       /home/amedhi/.local/share/nvim/lspinstall/lua/sumneko-lua-language-server -E /home/amedhi/.local/share/nvim/lspinstall/lua/main.lua
  	


2 active client(s): 

  Client: efm (id 1)
  	root:      /home/amedhi/.config/nvim
  	filetypes: lua, python, javascriptreact, javascript, typescript, typescriptreact, sh, html, css, yaml, markdown, vue
  	cmd:       /home/amedhi/.local/share/nvim/lspinstall/efm/efm-langserver
  	


  Client: sumneko_lua (id 2)
  	root:      /home/amedhi/.config/nvim/lua
  	filetypes: lua
  	cmd:       /home/amedhi/.local/share/nvim/lspinstall/lua/sumneko-lua-language-server -E /home/amedhi/.local/share/nvim/lspinstall/lua/main.lua
  	


Clients that match the filetype lua:
  
  Config: sumneko_lua
  	cmd:               /home/amedhi/.local/share/nvim/lspinstall/lua/sumneko-lua-language-server -E /home/amedhi/.local/share/nvim/lspinstall/lua/main.lua
  	cmd is executable: True
  	identified root:   /home/amedhi/.config/nvim
  	custom handlers:   
  
  Config: efm
  	cmd:               /home/amedhi/.local/share/nvim/lspinstall/efm/efm-langserver
  	cmd is executable: True
  	identified root:   /home/amedhi/.config/nvim
  	custom handlers:   
```

Both the lua ls and efm server are enabled and running (installed via LspInstall). And I do get diagnostics

**Comment by rebuilt** [comment]
Lets troubleshoot lua first
I'll assume you're using the default formatter.  What's the output of

```
which lua-format
```

If you haven't installed it yet, install from here: 
https://github.com/Koihik/LuaFormatter

**Comment by IndianBoy42** [comment]
```
❯ which lua-format                                                                                (base)
/home/amedhi/.local/bin/lua-format
```

and running `lua-format -i $file` works perfectly

**Comment by IndianBoy42** [comment]
yup I have 

```
O.lang.lua.active = true
O.lang.lua.formatter = 'lua-format'
O.lang.lua.autoformat = true
```

**Comment by rebuilt** [comment]
And then line 67 should also be set to true

```
O.lang.lua.autoformat = true
```

**Comment by rebuilt** [comment]
Do you have any output in 
```
:messages
```
Also check the lsp error logs
```
grep ERROR ~/.cache/nvim/lsp.log
```

**Comment by IndianBoy42** [comment]
For the first, just:

```
vim.lsp.buf.formatting_sync: timeout
```

Everytime i run

```
:lua vim.lsp.buf.formatting_sync(nil, 1000)
```

In `lsp.log` I have this i think when I open nvim

```
[ ERROR ] 2021-07-01T21:19:06+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/amedhi/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/01 21:19:06 efm-langserver: no configuration file\n2021/07/01 21:19:06 efm-langserver: reading on stdin, writing on stdout\n"
```

**Comment by rebuilt** [comment]
I've pulled down your config to test.
Formatting works for me in lua.

I don't think its a problem with the configuration.  I think it's your system.  
I'd start by updating your local plugins:

```
:PackerSync
```

If that doesn't work maybe try reinstalling all the other relevant software: lua-format, updating your compiled version of neovim, etc

**Comment by IndianBoy42** [comment]
Thats really strange... 

Packer has everything up to date, lua-format was just installed today. neovim is up to date as per the unstable ppa for neovim. should I compile it myself?

What could it be in the system, considering I can run lua-format/black/yapf manually no problem. Only neovim times out.
Is there any way to get a more detailed log output?

**Comment by rebuilt** [comment]
You can try manually running the formatter and reading the messages.  

```
:lua vim.lsp.buf.formatting_sync(nil, 1000)
:messages
```

You can manually put a print statement in lua-ls.lua to make sure it starts to run

Place this code after _lua_autoformat = {}, line 38

```
            _print_log = {
                'BufWritePre', '*.lua',
                "lua print('this should be autoformatting')"
            }
```

**Comment by IndianBoy42** [comment]
I have been trying to run it manually, there is no message except "timeout"

**Comment by rebuilt** [comment]
I think your best bet is compiling neovim from source.

**Comment by rebuilt** [comment]
What's the output of 

```
:checkhealth
```

**Comment by rebuilt** [comment]
Look at these instructions to fix the 'no configuration file error'.  But as far as I know, that will only fix problems for prettier and eslint formatters.  https://github.com/ChristianChiarulli/LunarVim/issues/508

Although maybe efm is trying to run all formatters instead of just those that match the filetype?   

Try turning off all the other languages and formatters you don't need or else set up prettier and eslint correctly with configuration files.

**Comment by IndianBoy42** [comment]
It seems a reboot has fixed it. I have no idea, i reinstalled a bunch of stuff but it didn't work until rebooting

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
