### ISSUE TITLE
Lspsaga actions not found

### ISSUE THREAD

**Issue by aaronmcadam** [ChristianChiarulli/LunarVim#589]
Did this plugin get removed? I can't do any code actions anymore.

**Comment by rebuilt** [comment]
It's still there, it's just lazy loaded.  
Run :PackerSync to move the plugin files to the opt folder

**Comment by aaronmcadam** [comment]
Hi @rebuilt. Thanks for  your reply, but I've already run PackerSync a few times and it still doesn't work 😅

**Comment by rebuilt** [comment]
Hm.  You might have to make it a required plugin again.  Chris is trying to improve the startuptime right now and things are being lazy loaded that weren't before.  Remove this from line 37 of plugins.lua
```
event = "BufRead"
```

Then run :PackerSync again.

**Comment by aaronmcadam** [comment]
Cool, that fixed it, thanks! 😄
