### ISSUE TITLE
Git signs aren't showing

### ISSUE THREAD

**Issue by aaronmcadam** [ChristianChiarulli/LunarVim#591]
I followed the same advice given in  #589, but it's still not working.

**Comment by rebuilt** [comment]
I just tested.  They're on for me. 

If you press this key combination do you see blame information?  That's provided by gitsigns
```
<space>l
```
That's a lowercase L

**Comment by aaronmcadam** [comment]
I can see blame, but I don't see any signs when making changes

**Comment by aaronmcadam** [comment]
Weird, it's working for me now 🤷
