### ISSUE TITLE
Bug:keybinding jj as escape in keybindigs.lua is not working out of the box

### ISSUE THREAD

**Issue by 3301n** [ChristianChiarulli/LunarVim#605]

**Comment by barun108** [comment]
It is already there with LunarVim's default settings 

jj
jk
kj

Just check the keymappings file , you should find it

**Comment by 3301n** [comment]
> It is already there with LunarVim's default settings
> 
> jj
> jk
> kj
> 
> Just check the keymappings file , you should find it

Just tell me how to enable it

**Comment by rebuilt** [comment]
Looks like there's a bug.  The mapping is there.  It should be enabled, but it's not working.

**Comment by 3301n** [comment]
This is not a bug just change the timeoutlen in default-config.lua inside lua  folder to some higher value if you are slower at typing or just type jk as fast as you can.
