### ISSUE TITLE
[LSP] Clangd is not being activated.

### ISSUE THREAD

**Issue by danger44** [ChristianChiarulli/LunarVim#610]
I removed the old config and then installed new from stable branch using "one line bash command".
Lsp for Lua , python is working fine for me but for c++ it is not working? 
Do I need to do :`O.lang.clang.active = true` like in previous versions? I tried this but still not working.

**Comment by jameswalmsley** [comment]
What does LspInfo say when you are in a cup file?

**Comment by jameswalmsley** [comment]
Can you confirm what happens if you open a .c file also.
Which neovim version are you using? (Assuming the 0.5 release or greater...).

**Comment by jameswalmsley** [comment]
Ok can confirm master is broken for me also... I'm just investigating now :)

**Comment by danger44** [comment]
Oh thank you. 
Does one liner bash installer also update the nvim to latest release? Because I have not updated neovim 0.5 new release from yesterday.
Nvim version:
NVIM v0.5.0-dev+5aaa1a1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by jameswalmsley** [comment]
I've provided a PR #612 which fixes the issue.
Apologies, I clearly messed up the changes to the config..

**Comment by jameswalmsley** [comment]
> Oh thank you.
> Does one liner bash installer also update the nvim to latest release? Because I have not updated neovim 0.5 new release from yesterday.
> Nvim version:
> NVIM v0.5.0-dev+5aaa1a1
> Build type: Release
> LuaJIT 2.1.0-beta3

The install-latest-neovim script will clone and compile the neovim master branch and install to /usr/local/bin/nvim

**Comment by danger44** [comment]
It still not working.
I changed file from this :
`        clang = {
            diagnostics = {
                virtual_text = {spacing = 0, prefix = ""},
                signs = true,
                underline = true,
                cross_file_rename = true,
                header_insertion = 'never'
            }
        }, `
to this:
`         clang = {
            diagnostics = {
                virtual_text = {spacing = 0, prefix = ""},
                signs = true
          },
            cross_file_rename = true,
            header_insertion = "never"
        },
`

**Comment by jameswalmsley** [comment]
What's your output of LspInfo?

`:LspInfo`

**Comment by jameswalmsley** [comment]
I've pushed an update to my PR, it should work now..
(Note it symlinks cpp.lua to c.lua).

I'm going to put in issue in with neovim directly, as cpp files should source c file types also. (They do for vim scripts at least).

I also tried to make an explicit cpp.lua, that `require('c')` but that didn't work.

**Comment by danger44** [comment]
Thank you. After creating a symlink to cpp, it is working now. :D
