### ISSUE TITLE
How to personalize LunarVim? (and still be able to rebase)

### ISSUE THREAD

**Issue by LogeshG5** [ChristianChiarulli/LunarVim#614]
I want to locally personalize or override 

- key mappings
- plugin configurations
- install extra plugins

The defaults are mostly good, but I really need to modify certain settings. I am glad what has happened lately with LunarVim. I want to keep up to date while still be able to have my preferences and certain settings maintained separately.

Currently lv-config.lua is loaded first as it is used to configure the rest of LunarVim. So I cannot use this for overriding any settings. 

I don't know if for example, lv-overrides.lua (loaded at the end) could solve the problem. How then would I override dashboard plugin configuration?

**Comment by abzcoding** [comment]
`lv-config.lua` has been removed from the config and a sample config is available [here](https://github.com/ChristianChiarulli/LunarVim/blob/master/utils/installer/lv-config.example.lua) you can replace everything in that. 

for reference, the default config is located [here](https://github.com/ChristianChiarulli/LunarVim/blob/master/lua/default-config.lua)

**Comment by ChristianChiarulli** [comment]
plugin overrides and additional plugins will be supported for LunarVim 1.0. 

For now we're focusing on achieving stability and performance.

**Comment by williamgoulois** [comment]
@LogeshG5 you can create your own local branch like `config` for instance and rebase it from master !

You will have to merge changes each time you rebase but it's the only solution before LunarVim 1.0

**Comment by LogeshG5** [comment]
I agree stability and performance should be prioritized. I will wait until LumarVim 1.0

@williamgoulois I have a local config branch, but I could not keep up with the recent amount of changes :) 

If roadmap already has plans to implement this and if it is tracked separately, we can close this issue.

**Comment by rafamadriz** [comment]
Closing in favor of #461
