### ISSUE TITLE
REQUEST: add option for transparent bg

### ISSUE THREAD

**Issue by Pasqat** [ChristianChiarulli/LunarVim#615]
I'm wondering if it could be pollible add the option in lv-config.lua to toggle the background transparency.
Maybe it could be just a cmd "hi Normal guibg=none"

**Comment by ChristianChiarulli** [comment]
I could probably add a setting for that.

**Comment by williamgoulois** [comment]
I just opened a PR to add this option

**Comment by Pasqat** [comment]
Thank you all.
I opened a PR to add `hi SignColumn guibg=none ...`.
I think that this issue could be closed
