### ISSUE TITLE
Clean up and update the Wiki

### ISSUE THREAD

**Issue by ChristianChiarulli** [ChristianChiarulli/LunarVim#616]

**Comment by rebuilt** [comment]
The information in the wiki is now accurate.  The next step will be to split it up into multiple pages.

**Comment by rebuilt** [comment]
The pages have been split up.  

The formatters and linters section needs to be updated.  That's a good task for anyone who'd like to help. We've recently moved away from efm and set up Neoformat as the default formatter.  It's on by default.  The docs should probably mention how to turn it off.  https://github.com/ChristianChiarulli/LunarVim/wiki/Formatters-and-Linters

There is also a new 'Example plugin configurations' page that needs some attention.  If you have a favorite plugin and a sample working configuration, that would be a good place to put it.  https://github.com/ChristianChiarulli/LunarVim/wiki/Example-plugin-configurations#nvim-lastplace

If you're a new user and you find something inaccurate or outdated in the wiki, please let us know.  That's also a good way to help out.

**Comment by HagaiHargil** [comment]
Hi,

Thanks for this important work! In the [Installing Plugins](https://github.com/ChristianChiarulli/LunarVim/wiki/Installing-Plugins) page I believe that the last snippet should point to `0.user_plugins` instead of `0.custom_plugins`. Also, I believe you want to link from this page to the new example plugin configurations.

**Comment by rebuilt** [comment]
Thanks!  Updated.

**Comment by gnmearacaun** [comment]
Very good work with parting out the pages @rebuilt. 
It would be great to have a page to share user tips and tricks such as swapping `:` and `;` and handy <c-s> save keybindings. Also a place for links to colorschemes and blogposts about lunarvim?
How does one contribute to the wiki, is it by doing a pull request?

**Comment by Uzaaft** [comment]
@rebuilt Wouldn't it be advantageous to create a wiki which everyone can fork? Something which uses this: https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html
I'd very much like to help out with it.

**Comment by rebuilt** [comment]
Yes, that's ideal.  I'm traveling without a computer at the moment.  I'll do it Tuesday if Chris doesn't do it first.

**Comment by justinGilmer** [comment]
One thing I noticed today when following [The plugin configuration for `nvim-lastplace`](https://github.com/ChristianChiarulli/LunarVim/wiki/Example-plugin-configurations#nvim-lastplace-declaration-and-configs), is that there is a missing comma in this setup and will not work if just copying/pasting.

I added a comment in the snippet below, the line `event = "BufRead"` is missing a comma before moving to the `config = function()` section.

```lua
{
    "ethanholz/nvim-lastplace",
    event = "BufRead" -- The issue is here, there is supposed to be a comma (`,`) after "BufRead"
        config = function()
        require'nvim-lastplace'.setup {
            lastplace_ignore_buftype = {"quickfix", "nofile", "help"},
            lastplace_ignore_filetype = {
                "gitcommit", "gitrebase", "svn", "hgcommit"
            },
            lastplace_open_folds = true
        }
    end,

}
```

**Comment by rebuilt** [comment]
This is no longer relevant.  Perhaps we should make a new issue about lunarvim.org?

**Comment by abzcoding** [comment]
lunarvim.org

**Comment by gnmearacaun** [comment]
I created a PR [over there](https://github.com/LunarVim/lunarvim.org/pull/20) at https://github.com/LunarVim/lunarvim.org
