### ISSUE TITLE
Packer problem

### ISSUE THREAD

**Issue by moumax** [ChristianChiarulli/LunarVim#619]
Hi !

I just done a fresh install of LunarVim  on a wsl ubuntu. But, on the first packer install, the luarocks-hererocks stay on "installing hererocks". I tried to quit and PackerUpdate but, with no luck !

What's going on ??? 
Thanks !

**Comment by rebuilt** [comment]
That one takes a long time.  Even longer on slow connections.  Give it at least 10 minutes.  I also think they are rate limiting this download on their servers

**Comment by moumax** [comment]
> That one takes a long time. Even longer on slow connections. Give it at least 10 minutes. I also think they are rate limiting this download on their servers

It is stuck since 3 hours. Maybe, it is a limitation.. I will try tomorrow ! Thanks

**Comment by jameswalmsley** [comment]
I'm having problems with this on my machines too. Some of them fail to access lua rocks.
I think there must be some rate-limiting going on??

**Comment by ChristianChiarulli** [comment]
disabling snap for now due to this issue.

**Comment by rafamadriz** [comment]
Snap is not being use anymore. Closing for now.
