### ISSUE TITLE
Function args suggestions/completion

### ISSUE THREAD

**Issue by nkoturovic** [ChristianChiarulli/LunarVim#620]
- Is there a way to enable function argument completion (preview/suggestions)?
- If not, also not sure if there is already related issue or plan to include this feature.

I found some Lua plugin that seems to do this nicely:
[https://github.com/ray-x/lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim)

- In this plugin there are also popups and suggestions if there are multiple function overloads.
- Did not tried to integrate this plugin with LunarVim nor is it possible.

**Comment by IndianBoy42** [comment]
I use that plugin, I think its quite useful, and just works, although you may want to customize the look to make it consisten with the rest of lunarvim

**Comment by ChristianChiarulli** [comment]
does it work with compe?

**Comment by IndianBoy42** [comment]
The windows overlap technically, but I think/hope this can be configured I just haven't gotten around to it. this plugin has been mentioned a lot in the subreddit so I think it is the most well known function signature plugin

**Comment by nkoturovic** [comment]
Someone on Reddit posted this link as sample configuration with compe:

[https://github.com/ray-x/lsp_signature.nvim/issues/1#issuecomment-809995087](https://github.com/ray-x/lsp_signature.nvim/issues/1#issuecomment-809995087)

So I guess that at least is possible.

**Comment by nkoturovic** [comment]
I've managed to configure this `lsp_signature` plugin, with LspSaga popup it works out of the box but it is not as good as default popup method. (It does not update which argument is selected on the fly).
Issue i have with standard configuration is:
- When press <CR> and accept compe suggestion it works just great
- But i think that most of the people will not use <CR> to accept suggestion, they would naturally type '(' 
- When type '(' compe does not accept suggestion but leaves it's own popup open and therefore prevents this new plugin to show suggestion popup.
- When second argument is on the turn (after ',' it starts to work again).
- Tried to imap '(' with compe to use as complete char but no success, it doesn't allow that kind of behaviour
```lua
vim.api.nvim_set_keymap("i", "(", "compe#confirm('<CR>')", {noremap = true, silent = true, expr = true})
```
Kinda newbie and lack of knowledge for what is possible, any bright ideas?

**Comment by nkoturovic** [comment]
## Created Pull Request for integrating `lsp_signature` plugin
**Pull requiest**: #672

**Important**: Plugin is disabled by default both in: 
- `lua/default-config.lua`
- `utils/installer/lv-config.example.lua`

To enable plugin add in `lv-config.lua`
```lua
O.plugin.lsp_signature.active = true
```
Then run `:PackerInstall`, `:PackerCompile`

- After bugfix hrsh7th/nvim-compe#436 in compe repo is resolved it should work perfectly (I think)
- It's my first PR and be free to give me feedback if I made some mistakes/bad design decisions.

**Plugin is disabled by default for now because of mentioned compe issue**

**Comment by abzcoding** [comment]
After recent changes to the plugins, I think we can suggest users to add this as a custom plugin
inside `lv-config.lua`:
```lua
O.custom_plugins = {
      {
          "ray-x/lsp_signature.nvim",
          config = function() require"lsp_signature".on_attach() end,
          event = "BufRead"
      }
```

**Comment by nkoturovic** [comment]
> After recent changes to the plugins, I think we can suggest users to add this as a custom plugin
> inside `lv-config.lua`:
> 
> ```lua
> O.custom_plugins = {
>       {
>           "ray-x/lsp_signature.nvim",
>           config = function() require"lsp_signature".on_attach() end,
>           event = "BufRead"
>       }
> }
> ```

Updated Pull Request #672 (left open for now - read info in PR)

**Comment by abzcoding** [comment]
as describe [here](https://github.com/ChristianChiarulli/LunarVim/issues/553#issuecomment-871892568) we're going to keep core plugins to a minimum and tackle these additions using [LunarModules](https://github.com/ChristianChiarulli/LunarVim/wiki/WIP:-Lunar-Modules) or a LV market place
