### ISSUE TITLE
Netrw Failing on Fresh Install

### ISSUE THREAD

**Issue by Tripex48** [ChristianChiarulli/LunarVim#622]
After performing a fresh install of LunarVim stable, I am noticing that the built-in Netrw features of Neovim is failing.

`E117: Unknown function: netrw#Explore`

Technically, one can still navigate and move around with NvimTree but it would be nice to restore/allow the Netrw features to be used as well.

**Comment by Tripex48** [comment]
I found the fix after digging into the lua scripts.

Line 41 of settings.lua has been commented, leaving the value of vim.g.nvim_tree_disable_netrw to be unassigned. When the line is re-introduced; the Netrw features operate as expected.

**Comment by ChristianChiarulli** [comment]
I need to check to see if having netrw enabled conflicts with nvimtree at all.

**Comment by rafamadriz** [comment]
> I need to check to see if having netrw enabled conflicts with nvimtree at all.

No, I don't think it does. I use netrw to open nvim in a folder since nvim-tree does support that yet, and never have had a problem.

**Comment by JuanVqz** [comment]
I had the same issue NeoVim is not able to open Explore after install lunar vim, in fact I removed lunar and tried to get **netrw** working again, and didn't work.

I ran the opposite of this line but didn't work. 
https://github.com/ChristianChiarulli/LunarVim/blob/327955348174646e8f4c0eea62f9f25462f4ac28/lua/settings.lua#L55

```vim
let g:loaded_netrw = 0
```
I removed and reinstalled NeoVim in different versions but didn't work too.

do you know how can I enable it again?

**Comment by JuanVqz** [comment]
I solved it!! Yay!!

In my particular case LunarVim (or maybe neovim) creates a folder in this following path `~/.local/shared/nvim`.

I just changed its name and reopen neovim then execute `:Explore` and it works.
then I removed the folder.

thank you for LunarVim, it's pretty good.

**Comment by rafamadriz** [comment]
Awesome, that's a pretty weird behavior. Never seen that happen and I don't why removing that folder world fixed since netrw is a built-in plugin but nice to see you fixed it.

**Comment by JuanVqz** [comment]
I feel like vim's plugins are downloaded like we do with `packer` or `vim-plug` but internally and we didn't know.
@rafamadriz thank you!
