### ISSUE TITLE
[Bug]: fresh install on arch throw some errors 

### ISSUE THREAD

**Issue by luxus** [ChristianChiarulli/LunarVim#627]
### Problem description

after i run the install script i got this errors on garuda linux (arch based)

### LunarVim version

0.3.1

### Neovim version (>= 0.5)

0.5

### Relevant log output

```shell
E5113: Error while calling lua chunk: /home/luxus/.config/nvim/lua/settings.lua:23: attempt to index local 'opt' (a nil value)
Error detected while processing command line:
E492: Not an editor command: PackerInstall
Press ENTER or type command to continue
```

### I have read

- [X] The readme
- [X] The wiki

**Comment by luxus** [comment]
other error got on a fresh install
```
Error detected while processing /home/luxus/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/luxus/.config/nvim/lua/lv-galaxyline/init.lua:1: module 'galaxyline' not found:
no field package.preload['galaxyline']
no file './galaxyline.lua'
no file '/usr/share/luajit-2.0.5/galaxyline.lua'
no file '/usr/local/share/lua/5.1/galaxyline.lua'
no file '/usr/local/share/lua/5.1/galaxyline/init.lua'
no file '/usr/share/lua/5.1/galaxyline.lua'
no file '/usr/share/lua/5.1/galaxyline/init.lua'
no file './galaxyline.so'
no file '/usr/local/lib/lua/5.1/galaxyline.so'
no file '/usr/lib/lua/5.1/galaxyline.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by weiss-d** [comment]
Same here

**Comment by luxus** [comment]
@weiss-d it runs fine after a :PackerCompile

**Comment by pantasio** [comment]
Cant run :PackerInstall and :PackerCompile

E492: Not an editor command: PackerInstall

**Comment by luxus** [comment]
i don't think its related..
how did u install? at best uninstall first:
```
# Delete the configuration files
sudo rm -R ~/.config/nvim

# Delete the plugins
rm -Rf ~/.local/share/nvim

# Delete the logs
rm -R ~/.cache/nvim
```
and then try the bash script 
`bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/stable/utils/installer/install.sh)`
maybe try the master branch at the moment.. (sounds funny but its more stable at the moment)
`bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)`

**Comment by atropos112** [comment]
> i don't think its related..
> how did u install? at best uninstall first:
> 
> ```
> # Delete the configuration files
> sudo rm -R ~/.config/nvim
> 
> # Delete the plugins
> rm -Rf ~/.local/share/nvim
> 
> # Delete the logs
> rm -R ~/.cache/nvim
> ```
> 
> and then try the bash script
> `bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/stable/utils/installer/install.sh)`
> maybe try the master branch at the moment.. (sounds funny but its more stable at the moment)
> `bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)`

I have the same

```
E5113: Error while calling lua chunk: /home/atropos/.config/nvim/lua/settings.lua:24: attempt to index local 'opt' (a nil value)
```

No Packer command works


> ### Problem description
> 
> after i run the install script i got this errors on garuda linux (arch based)
> ### LunarVim version
> 
> 0.3.1
> ### Neovim version (>= 0.5)
> 
> 0.5
> ### Relevant log output
> 
> ```shell
> E5113: Error while calling lua chunk: /home/luxus/.config/nvim/lua/settings.lua:23: attempt to index local 'opt' (a nil value)
> Error detected while processing command line:
> E492: Not an editor command: PackerInstall
> Press ENTER or type command to continue
> ```
> 
> ### Screenshots
> 
> _No response_
> ### I have read
> 
>     * [x]  The readme
> 
>     * [x]  The wiki

I had the same issue when running neovim nightly, once i changed to stable 0.5.0-1 the error disappeared.

**Comment by thetomato2** [comment]
> Cant run :PackerInstall and :PackerCompile
> 
> E492: Not an editor command: PackerInstall
> 
> Maybe issues is Packer: #619

It worked for me, but you compile there is no indication that anything happened. Just on a fresh install do
:PackerInstall
:PackerCompile
exit

**Comment by rafamadriz** [comment]
The reason this is happening is because the configuration for some plugins is being required from the main [init.lua](https://github.com/ChristianChiarulli/LunarVim/blob/a469c710bfc01f291df68dba40464caaa2b496da/init.lua#L7) So when the install script runs, it is trying to require a module that doesn't exist yet. Will fix soon.

**Comment by luxus** [comment]
https://github.com/ChristianChiarulli/LunarVim/pull/646 fixes the PackerCompile after a fresh install

**Comment by barun108** [comment]
> The reason this is happening is because the configuration for some plugins is being required from the main [init.lua](https://github.com/ChristianChiarulli/LunarVim/blob/a469c710bfc01f291df68dba40464caaa2b496da/init.lua#L7) So when the install script runs, it is trying to require a module that doesn't exist yet. Will fix soon.

I have installed it on my Arch Linux many times since last Saturday(June 3rd) 

it produces this error every first run of nvim(neovim / LunarVim) , but
that is the case with any plugin manager and configuration files

then, after updating the plugins (:PackerSync , :PackerUpdate) etc.,
it works fine

**Comment by luxus** [comment]
It's not true that this issue happens on all configs.
I used lvim https://github.com/lvim-tech/lvim for some weeks and the installation worked even without a installation script and with no errors

**Comment by luxus** [comment]
no more errors in the latest release

**Comment by glenn-logivan** [comment]
same error got on fresh install:
`E5113: Error while calling lua chunk: /Users/glennleo/.config/nvim/lua/settings.lua:25: attempt to index local 'opt' (a nil value)Press ENTER or type command to continue`

**Comment by iapicca** [comment]
after this [error](https://github.com/ChristianChiarulli/LunarVim/issues/882) 
I wiped everything and installed from the scratch...
and now I'm experiencing this :/
