### ISSUE TITLE
[Help]: Not able to setup prettier formatting for js, ts files. 

### ISSUE THREAD

**Issue by mayankdutta** [ChristianChiarulli/LunarVim#630]
prettier working fine for `json` after mentioning `prettier`,  files but not for `js`, `ts` files.

`lunarVim: master branch`
`neovim`: 
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

```

`:LspInfo`

![Screenshot 2021-07-04 at 2 20 54 AM](https://user-images.githubusercontent.com/33067129/124366604-a2c0f500-dc6e-11eb-8bd7-2335d4026151.png)
![Screenshot 2021-07-04 at 2 21 11 AM](https://user-images.githubusercontent.com/33067129/124366607-a5bbe580-dc6e-11eb-8be4-da202f3b0662.png)

`
which prettier
`
```
/usr/local/bin/prettier
```
 
`lv-config.lua`

```
O.auto_complete = true
O.colorscheme = 'spacegray'
O.auto_close_tree = 0
O.wrap_lines = false
O.timeoutlen = 100
O.document_highlight = true
O.extras = false
O.leader_key = ' '
O.ignore_case = true
O.smart_case = true
O.lushmode = false

-- After changing plugin config it is recommended to run :PackerCompile
O.plugin.hop.active = false
O.plugin.dial.active = false
O.plugin.dashboard.active = true
O.plugin.matchup.active = false
O.plugin.colorizer.active = false
O.plugin.numb.active = false
O.plugin.ts_playground.active = false
O.plugin.indent_line.active = false
O.plugin.gitlinker.active = false
O.plugin.zen.active = false

-- dashboard
-- O.dashboard.custom_header = {""}
-- O.dashboard.footer = {""}

-- if you don't want all the parsers change this to a table of the ones you want
O.treesitter.ensure_installed = "all"
O.treesitter.ignore_install = {"haskell"}
O.treesitter.highlight.enabled = true

O.lang.clang.diagnostics.virtual_text = true
O.lang.clang.diagnostics.signs = true
O.lang.clang.diagnostics.underline = true

-- python
-- add things like O.python.formatter.yapf.exec_path
-- add things like O.python.linter.flake8.exec_path
-- add things like O.python.formatter.isort.exec_path
O.lang.python.formatter = 'yapf'
-- O.python.linter = 'flake8'
O.lang.python.isort = true
O.lang.python.autoformat = true
O.lang.python.diagnostics.virtual_text = true
O.lang.python.diagnostics.signs = true
O.lang.python.diagnostics.underline = true
O.lang.python.analysis.type_checking = "off"
O.lang.python.analysis.auto_search_paths = true
O.lang.python.analysis.use_library_code_types = true


-- lua
-- TODO look into stylua
O.lang.lua.formatter = 'lua-format'
-- O.lua.formatter = 'lua-format'
O.lang.lua.autoformat = false

-- javascript
O.lang.tsserver.autoformat = true
O.lang.tsserver.formatter = 'prettier'
O.lang.tsserver.linter = nil

-- json
O.lang.json.autoformat = true
O.lang.json.formatter = 'prettier'

-- ruby
O.lang.ruby.autoformat = true

-- go
O.lang.go.autoformat = true

-- rust
O.lang.rust.autoformat = true

-- clang
O.lang.clang.autoformat = true

```

**Comment by ChristianChiarulli** [comment]
are you on master or stable?

**Comment by ChristianChiarulli** [comment]
Also did you install efm?

**Comment by mayankdutta** [comment]
I am on `master` branch, and yes I installed all the required ones using `LspInstall` like lua, efm, cpp, typescript and json.

**Comment by mayankdutta** [comment]
reinstalled `LunarVim`, `node`, `npm global packages`. 
 - `efm`,  `typescript`, `cpp`, `lua` etc.. installed again using `LspInstall` 
 - `tsserver` running fine, detecting errors and all. 
 - `jsonls` also running file and `prettier` also working there. 
 
Now if i do manual formatting in `js`, `ts` files using `<Leader>lf`, got this message this time. <br>
![Screenshot 2021-07-04 at 12 39 49 PM](https://user-images.githubusercontent.com/33067129/124376594-65d41d00-dcc5-11eb-8680-4468f69e6b85.png)

`lv-config.lua` file is same as mentioned above.

**Comment by barun108** [comment]
![2021-07-04-132401_832x641_scrot](https://user-images.githubusercontent.com/12285528/124377862-ef86e900-dccb-11eb-9970-cb11555d36b8.png)

I was also having issues
everything was good with init.vim , I mean prettier , tslint etc.

so today morning after reinstalling LunarVim again i made little changes in 'default-config.lua' file
but it was not 'auto formatting' , 

I was following this issue here too

so after your previous comment I tried <leader>lf , and it is working for me, 
tested in Javascript, angular ( ts file ) and dart (flutter) just now, please see the picture 

please update if you can solve the problem for 'auto-format'

Thank You

**Comment by mayankdutta** [comment]
I just tried your version of default-config but sadly `<leader>  + lf` still showing same error, and auto-formatting still not working. 🥲

**Comment by mayankdutta** [comment]
#  ✅  Solved 

### What solved?
In file [ts-fmt-lint.lua](https://github.com/ChristianChiarulli/LunarVim/blob/master/lua/lsp/ts-fmt-lint.lua), I replaced this part
```

    if vim.fn.glob("node_modules/.bin/prettier") then
        prettier = {
            formatCommand = "./node_modules/.bin/prettier --stdin-filepath ${INPUT}",
            formatStdin = true
        }
    end
```
to `my global location of prettier`

```
    -- if vim.fn.glob("node_modules/.bin/prettier") then
    if vim.fn.glob("/usr/local/bin/prettier") then
        prettier = {
            -- formatCommand = "./node_modules/.bin/prettier --stdin-filepath ${INPUT}",
            formatCommand = "prettier --stdin-filepath ${INPUT}",
            formatStdin = true
        }
    end
```

and luckily prettier started working.

### Why that solved?
I think my system has some serious issue with npm global packages `location`, one reason maybe I didn't make `~/.npm-global` default location for my global packages. 

### If I am wrong can you please correct me !!

**Comment by bob3000** [comment]
I ran into the same issue today. What I figured out is that `vim.fn.glob("node_modules/.bin/prettier")` returns an empty string if the path does not exist which is a truthy value in lua. So the effect is that the path to the global prettier is replaced by the potentially non existent prettier from the project level.

https://github.com/ChristianChiarulli/LunarVim/pull/678

**Comment by mayankdutta** [comment]
thanks !!
