### ISSUE TITLE
Manual set up guide in Wiki doesn't suggest you copy the default lv-config.lua causing subsequent steps to fail

### ISSUE THREAD

**Issue by account-sxf** [ChristianChiarulli/LunarVim#635]
### Problem description

Wiki doesn't suggest you copy the default lv-config.lua causing subsequent steps to fail

**Comment by account-sxf** [comment]
If this isn't the appropriate place to suggest this improvement, feel free to slap me.
Seems really cool so far though :)

**Comment by account-sxf** [comment]
Note: Worked fine using the installer.sh, this only impacts the manual set up documentation.

**Comment by ChristianChiarulli** [comment]
the wiki is out of date unfortunately, It will become a priority once everything is stable. I'll leave this up until then.

**Comment by rebuilt** [comment]
Updated the wiki with this step.
