### ISSUE TITLE
QuickFixToggle?

### ISSUE THREAD

**Issue by brandoncc** [ChristianChiarulli/LunarVim#639]
The config comes with `<C-q>` mapped to a missing function called `QuickFixToggle`. Where do I get that function?

**Comment by abzcoding** [comment]
It was defined inside `vimscript/functions.vim` like this:
```vim
function! QuickFixToggle()
    if empty(filter(getwininfo(), 'v:val.quickfix'))
        copen
    else
        cclose
    endif
endfunction
```

but that config file has been removed from the project

**Comment by brandoncc** [comment]
Thanks. My previous config had [something I got from ThePrimeagen](https://github.com/brandoncc/nvim/blob/master/lua/brandoncc/quickfix.lua) which has something like that plus easy qf navigation. I'll probably bring that over to my LV config once I figure out where I should put it.
