### ISSUE TITLE
[Bug]: error when opening a file

### ISSUE THREAD

**Issue by osenvosem** [ChristianChiarulli/LunarVim#647]
### Problem description

Open js or ts file. Maybe other filetypes too.

### LunarVim version

Latest master version

### Neovim version (>= 0.5)

NVIM v0.5.0

### Relevant log output

```shell
Error executing vim.schedule lua callback: /Users/srg/.configalt/nvim/lua/lsp/init.lua:109: attempt to call field 'common_on_attach' (a nil value)
```

### Screenshots

<img width="966" alt="Screenshot 2021-07-04 at 11 29 51" src="https://user-images.githubusercontent.com/6762673/124379374-46d28c80-dcbf-11eb-90c5-7388d9da1367.png">

### I have read

- [X] The readme
- [X] The wiki

**Comment by ChristianChiarulli** [comment]
I can't seem to reproduce this. Try pulling the latest from master.
