### ISSUE TITLE
Disable built-in plugins.  

### ISSUE THREAD

**Issue by rebuilt** [ChristianChiarulli/LunarVim#652]
I need input from someone who knows more about the topic since I'm not sure how to go about disabling the built-in plugins.

This is how glepnir does it:

```
local disable_distribution_plugins = function()
    vim.g.loaded_gzip = 1
    vim.g.loaded_tar = 1
    vim.g.loaded_tarPlugin = 1
    vim.g.loaded_zip = 1
    vim.g.loaded_zipPlugin = 1
    vim.g.loaded_getscript = 1
    vim.g.loaded_getscriptPlugin = 1
    vim.g.loaded_vimball = 1
    vim.g.loaded_vimballPlugin = 1
    vim.g.loaded_matchit = 1
    --     vim.g.loaded_matchparen = 1
    vim.g.loaded_2html_plugin = 1
    vim.g.loaded_logiPat = 1
    vim.g.loaded_rrhelper = 1
    vim.g.loaded_netrw = 1
    vim.g.loaded_netrwPlugin = 1
    vim.g.loaded_netrwSettings = 1
    vim.g.loaded_netrwFileHandlers = 1
end

disable_distribution_plugins()
```

This doesn't seem to prevent plugins from loading.  Even on glepnir's own config, these plugins still get listed when running --startuptime.    

I tested with 1000 runs each:
| Default LunarVim | Attempting to disable default plugins  |   
|------------------|--------------------------------|
| 64.275           | 64.094                         |  

They're effectively the same amount of time given the variance in startuptimes for each run.

**Comment by rafamadriz** [comment]
Doing this work for me. Effectively disables the plugins:
```lua
vim.g.loaded_gzip = 1
vim.g.loaded_tar = 1
vim.g.loaded_tarPlugin = 1
vim.g.loaded_zipPlugin = 1
vim.g.loaded_2html_plugin = 1
vim.g.loaded_spec = 1
```

**Comment by luxus** [comment]
i saw the same method like @rafamadriz posted on this file
https://github.com/vhyrro/neovhy/blob/main/init.lua
```
vim.g.loaded_gzip = false
vim.g.loaded_matchit = false
vim.g.loaded_netrwPlugin = false
vim.g.loaded_tarPlugin = false
vim.g.loaded_zipPlugin = false
vim.g.loaded_man = false
vim.g.loaded_2html_plugin = false
vim.g.loaded_remote_plugins = false
```

**Comment by ChristianChiarulli** [comment]
I feel like I have tried every option and none of them work or me.

**Comment by luxus** [comment]
tested and confirmed that its not working :D
i using lvim at the moment with over 50 plugins and it starts in 44ms

**Comment by rebuilt** [comment]
> tested and confirmed that its not working :D (plugins still get loaded)
> i'm using https://github.com/lvim-tech/lvim at the moment with over 50 plugins and it starts in 44ms

Lvim-tech is based on the glepnir config.  How fast does the latest lunarvim load for you?

**Comment by luxus** [comment]
63ms with 13 plugins @rebuilt

**Comment by rafamadriz** [comment]
@ChristianChiarulli @luxus don't just look at the log from `--startuptime` option. Try to use the functionality of those plugins to see it works. For me, disabling some plugins still shows them being loaded but when trying to use them, it doesn't work.

Test this netrw for example:

1. Have enable netrw and open with nvim in some dir (`nvim --startuptime log .`)
2. See that netrw works and it shows being loaded in log
3. Disable netrw, and open nvim once again
4. Netrw doesn't show up when opening nvim on a dir, yet it shows as sourced in log loaded. 

Not just with netrw but I also tested this with matchit and matchparen plugins. It seems like that's the default behavior, disabling plugins doesn't stop them from being sourced, but it disables their functionality.

Also, this is not a big deal. I was testing all of this yesterday and the startup time doesn't improve significantly by disabling "builtin" plugins.

**Comment by luxus** [comment]
i think thats the point... even if we can disable it(that its not working).. the startup time doesn't change.
i think there should be other ways to save some ms..

**Comment by rafamadriz** [comment]
> i think there should be other ways to save some ms..

Yes, I was looking at the plugins.lua file and there a few little improvements that can be made. But to be honest,at this point the startuptime is not going to improve a lot, the vast majority of plugins are already being lazy loaded.

**Comment by ChristianChiarulli** [comment]
I have a few other ideas to improve startup time, also there are some startup plugins that can be removed like lspsaga.

**Comment by rafamadriz** [comment]
> also there are some startup plugins that can be removed like lspsaga.

Yes, lsasaga should be removed from the "core" plugins that always get loaded. It does way to much and all of its functionality can be done without it. I'm gonna start working today on a PR today for refactoring a few things. 

Also, @ChristianChiarulli we need to define formatting rules. A bunch of files have trailing white spaces everywhere and extra empty lines. 

 I propose lua-fmt:

1. easy to install with `npm i -g lua-fmt`
2. Already have sane defaults without any configuration 
3. No need for a LSP attached for formatting, and this is really important. We shouldn't rely on LSP for formatting.

**Comment by ChristianChiarulli** [comment]
@rafamadriz sure we can go with lua-fmt any opinion on stylua?

Whenever you update the formatter I'll stick to that and make sure to format before pushing anything.

**Comment by IndianBoy42** [comment]
I just tried stylua btw, It is quite a lot different to lua-format which I was using before. It uses tabs instead of 4-spaces by default but that can be configured. Other than that its pretty good in that includes things like always adding parens around function calls (even though lua considers though optional)

I would use 

```
column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "AutoPreferSingle"
no_call_parentheses = true
```

I don't think the choices are bad, but there is gonna be a huge format commit unless you just incrementally reformat as you edit files

**Comment by IndianBoy42** [comment]
stylua and lua-format are both much faster than lua-fmt. Its hard to get an accurate comparison as they are not technically making the same amount of changes (although stylua is doing the most and is still by far the fastest)

Running stylua on my fork of the lua branch takes 3ms (using hyperfine to benchmark). lua-format takes 6ms and lua-fmt takes 140ms

**Comment by rafamadriz** [comment]
> stylua and lua-format are both much faster than lua-fmt. Its hard to get an accurate comparison as they are not technically making the same amount of changes (although stylua is doing the most and is still by far the fastest)
> 
> Running stylua on my fork of the lua branch takes 3ms (using hyperfine to benchmark). lua-format takes 6ms and lua-fmt takes 140ms

@IndianBoy42 Oh thanks for giving an inside on that, I've always use lua-fmt and you're right, it is slow at moments. 

> sure we can go with lua-fmt any opinion on stylua? 

@ChristianChiarulli Tried stylua once but didn't like the defaults, and I didn't want to search through the formatting options to get things as I liked. That's way I went back to lua-fmt.

But considering what @IndianBoy42 said about speed. And the fact that you can customize stylua (you can't customize lua-fmt), it may be better to go with stylua instead of what I suggested before.

**Comment by luxus** [comment]
looks like neovim planing to use stylua too
https://github.com/neovim/neovim/pull/14987/commits/2cd58a7cebbac7d35b7e7ac7c59de1bad7a7a03a
maybe we should adopt these settings to stay close to neovim
```
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
no_call_parentheses = true
```

**Comment by ChristianChiarulli** [comment]
@luxus this is probably what we should do.

**Comment by ChristianChiarulli** [comment]
lspsaga has been removed

**Comment by folke** [comment]
The plugin files always get sourced, regardless of the loaded value, but at the top of each plugin there's a check for loaded and if this is the case they return immediately.

**Comment by rebuilt** [comment]
Closing this since the original question has been answered.
