### ISSUE TITLE
[Bug]: Can't delete default mappings

### ISSUE THREAD

**Issue by osenvosem** [ChristianChiarulli/LunarVim#662]
### Problem description

Place this into lv-config.lua

```lua
vim.api.nvim_del_keymap('i', 'jk')
vim.api.nvim_del_keymap('i', 'kj')
vim.api.nvim_del_keymap('i', 'jj')
```

The error

```
E5113: Error while calling lua chunk: /Users/srg/.configlvim/nvim/init.lua:2: Vim(luafile):E5113: Error while calling lua chunk: /Users/srg/.configlvim/nvim/lv-config.lua:4: E31: No such mapping
```

### LunarVim version

Latest master

### Neovim version (>= 0.5)

NVIM v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by IndianBoy42** [comment]
`lv-config.lua` is loaded before `keymappings.lua`, see the beginning of `init.lua`

I would suggest just edit `keymappings.lua`. There isnt a place user customizable place for running vim code after all the the config is done yet. Just be careful when pulling updates (I maintain a fork so that I can use git to keep track of changes and merge conflicts)

**Comment by osenvosem** [comment]
@IndianBoy42 yep, I know that. So we definitely have a couple of issues that need to be solved in order to have the opportunity to configure LunarVim avoiding issues with updates.

**Comment by ChristianChiarulli** [comment]
master now loads keymaps before your config.

**Comment by IndianBoy42** [comment]
> master now loads keymaps before your config.

This prevents having keymaps (defined in `keymappings.lua` that is) that depend on things in `lv-config.lua` like the plugin activation status. I was doing this although I could just as easily move the keymappings to another file, I liked organizing all my keymaps in one file even if they were 'optional'
