### ISSUE TITLE
By default, formatting should not be done with a LSP server. 

### ISSUE THREAD

**Issue by rafamadriz** [ChristianChiarulli/LunarVim#663]
This is one of the braking changes I was thinking on doing. A lot of people don't always have LSP enable for a variety of reasons,  either you're doing small changes and don't want a server attached, or maybe the LSP is slowing down your editor.  Either way, if the user disables the LSP, it would mean that they can't format their code, because by default, that's how this config does all the formatting.

### Alternative:

[Neoformat](https://github.com/sbdchd/neoformat) is the best alternative, it already has the configuration for literally every format tool you will ever need, this means that we don't need to worry about setting up formatting at all, the only thing that users need to worry about is having the formatter installed and in their path (which is already the case with LSP).

And I think that this should be the default option for formatting, then if the user wants to use LSP for formatting, that should be a secondary option. 

#### NOTE: there's also [fomatter.nvim](https://github.com/mhartington/formatter.nvim) written in lua, but it doesn't have the configuration for anything which is even worse than using LSP, this would mean us having to create and maintain all the formatters configuration that people may want. 

@ChristianChiarulli @rebuilt What do you think about this ?

**Comment by ChristianChiarulli** [comment]
After taking a look it does look very promising. I think at least for now it seems like a great ootb solution.

Does it support using `node_modules/.bin/prettier` by default?

**Comment by rebuilt** [comment]
I've used it.  It's great because it supports everything.  It's noticeably slower than the lsp option but that doesn't matter for this use case.

**Comment by ChristianChiarulli** [comment]
I think we should go with neoformat for now and keep it in the back of our minds that we'll move to a lua based solution if one becomes available.

**Comment by ChristianChiarulli** [comment]
Does anyone wanna try and tackle this? I was planning to work on lua colorschemes and DAP.

**Comment by rafamadriz** [comment]
> Does it support using node_modules/.bin/prettier by default?

Yes, of course. https://github.com/sbdchd/neoformat#supported-filetypes (Here you can see all the supported formatters by filetype)

> Does anyone wanna try and tackle this? I was planning to work on lua colorschemes and DAP.

I can work on this, it's already what I use in my config.

**Comment by ChristianChiarulli** [comment]
@rafamadriz Awesome this seems like a great addition.

**Comment by brymer-meneses** [comment]
This does exactly what neoformat does but it is written in lua.

https://github.com/mhartington/formatter.nvim

**Comment by brymer-meneses** [comment]
>NOTE: there's also fomatter.nvim written in lua, but it doesn't have the configuration for anything which is even worse than using LSP, this would mean us having to create and maintain all the formatters configuration that people may want.

Can we just port the commands from neoformat and use formatter.nvim?

**Comment by ChristianChiarulli** [comment]
We can work on that while still using neoformat in the meantime, probably the best solution imo.

**Comment by rafamadriz** [comment]
> > NOTE: there's also fomatter.nvim written in lua, but it doesn't have the configuration for anything which is even worse than using LSP, this would mean us having to create and maintain all the formatters configuration that people may want.
> 
> Can we just port the commands from neoformat and use formatter.nvim?
> I think it is relatively straight forward plus we will get to stay away from vimscript lol

If someone is going to do that, it should be done as a PR to formatter.nvim. I think I read in one of their issues that they may add the configurations in the future. However, there's nothing wrong with neoformat for using vimscript, there's literally no configuration needed to make it work. Install and done.

**Comment by rafamadriz** [comment]
#715 was merged. Closing.
