### ISSUE TITLE
[Bug] Sourcing LunarVim 'init.lua' return a error when using Neovim in Windows 10 x64

### ISSUE THREAD

**Issue by pidgeon777** [ChristianChiarulli/LunarVim#668]
### Problem description

1. Download Neovim nightly from here:

https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip

2. Create the folder tree `config\nvim` in Neovim base folder.

3. Clone `LunarVim` repository in `config\nvim`.
4. Move file from `config\nvim\utils\installer\lv-config.example.lua` to `config\nvim\lv-config.lua`.
5. Run `nvim -u C:\Work\MEGA\Portable\Neovim\config\nvim\init.lua`.

The following error appears:

````log
Errore/i eseguendo C:\Work\MEGA\Portable\Neovim\config\nvim\init.lua:
E5113: Error while calling lua chunk: config\nvim\init.lua:1: module 'default-config' not found:
	no field package.preload['default-config']
	no file '.\default-config.lua'
	no file 'C:\Work\MEGA\Portable\Neovim\bin\lua\default-config.lua'
	no file 'C:\Work\MEGA\Portable\Neovim\bin\lua\default-config\init.lua'
	no file '.\default-config.dll'
	no file 'C:\Work\MEGA\Portable\Neovim\bin\default-config.dll'
	no file 'C:\Work\MEGA\Portable\Neovim\bin\loadall.dll'
````

### LunarVim version

0.3.1

### Neovim version (>= 0.5)

0.6.0-dev+8-g75f758b99

### Relevant log output

```shell
nvim --version:

NVIM v0.6.0-dev+8-g75f758b99
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilato da runneradmin@fv-az159-229

Features: -acl +iconv +tui
See ":help feature-compile"

   file vimrc di sistema: "$VIM\sysinit.vim"
         $VIM di riserva: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by pidgeon777** [comment]
`:set rtp?`:

`runtimepath=~\AppData\Local\nvim,~\AppData\Local\nvim-data\site,~\AppData\Local\nvim-data\site\pack\packer\start\rnvimr,~\AppData\Local\nvim-data\site\pack\packer\start\packer.nvim,~\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter,C:\Work\MEGA\Portable\Neovim\share\nvim\runtime,C:\Work\MEGA\Portable\Neovim\share\nvim\runtime\pack\dist\opt\matchit,C:\Work\MEGA\Portable\Neovim\lib\nvim,~\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\after,~\AppData\Local\nvim-data\site\after,~\AppData\Local\nvim\after`

`echo $VIMRUNTIME`:

````
C:\Work\MEGA\Portable\Neovim\share\nvim\runtime
````

**Comment by luxus** [comment]
the file `'C:\Work\MEGA\Portable\Neovim\bin\lua\default-config.lua'` should be there?

**Comment by pidgeon777** [comment]
No, it is as if it is looking for that `default-config.lua` file inside those folders.

**Comment by luxus** [comment]
ahh okay i see it now.. it search in the bin folder for the configs :(
maybe there is a command to change the "config-directory" ?
easiest fix would be if you would clone the repo to C:\Work\MEGA\Portable\Neovim\bin\

**Comment by pidgeon777** [comment]
> easiest fix would be if you would clone the repo to C:\Work\MEGA\Portable\Neovim\bin\

Yes, but then a horrible mess would be obtained.

I'm confident that there is be a way to set some environment or VIM variable to fix this issue.

**Comment by luxus** [comment]
i checked the docs https://neovim.io/doc/user/starting.html#config and looks like u have to put the files into `~/AppData/Local/nvim/`
from the name of your folders u want to have it portable? maybe thats not possible right now

**Comment by pidgeon777** [comment]
You're right, but I'm sure that there are some variables that help to define alternative locations for the VIM config files.

EDIT:

I created a file in this path:

`$VIM\sysinit.vim` (in my case : `C:\Work\MEGA\Portable\Neovim\share\nvim\sysinit.vim`):

````vim
if has('win32')
  let $VIMCONFIG = fnamemodify(expand("$VIM"), ':h:h') . '\config\nvim' " Get the path equivalent to $VIM\..\..\config
  let &rtp .= ',' . $VIMCONFIG                                          " Add custom runtime path
  let $MYVIMRC = $VIMCONFIG . '\init.lua'                               " Set $MYVIMRC to point to the init.lua file
  exec 'luafile ' . $MYVIMRC
endif
````

Now this message appears when starting Neovim:

````log
Errore/i eseguendo C:\Work\MEGA\Portable\Neovim\share\nvim\sysinit.vim:
riga    9:
E5113: Error while calling lua chunk: C:\Work\MEGA\Portable\Neovim\config\nvim\init.lua:3: Vim(luafile):E5112: Error while creating lua chunk: cannot open C:\Users\MyUsername\AppData\Local\nvim/lv-config.lua: No such file or directory
````

I solved this error by replacing in `default-config.lua`, the following line:

`CONFIG_PATH = vim.fn.stdpath('config')`

with

`CONFIG_PATH = vim.fn.expand('$VIMCONFIG')`

So, I ask:

1. Would this classify as a bug?
2. Which should be the simplest way to be able to load LunarVim `init.lua` in Neovim, eventually without making use of the `sysinit.vim` file?

**Comment by luxus** [comment]
you can try to make ur own config and see if its loads in different folder (not sure if it will) 
if it works then we have a bug.. if not.. then its a Neovim problem or 'missing feature'?

**Comment by rafamadriz** [comment]
Closing since it was solved.
