### ISSUE TITLE
Formatting rules applied, using stylua. 

### ISSUE THREAD

**Issue by rafamadriz** [ChristianChiarulli/LunarVim#674]
@ChristianChiarulli @rebuilt @jameswalmsley (I don't know who else is a collaborator :/) 

Following what was discussed in #652, stylua is being use as the default formatter for the project. The config file is  in [`utils/.stylua.toml`](https://github.com/ChristianChiarulli/LunarVim/blob/master/utils/.stylua.toml).

### Installing.

```sh
cargo install stylua
``` 

### Usage

Copy the config file located in [`utils/.stylua.toml`](https://github.com/ChristianChiarulli/LunarVim/blob/master/utils/.stylua.toml) to the root of the project. 

- You can run sylua directly on files. E.g `stylua init.lua` or you can also use a regex `stylua lua/lv*/*.lua` 
- Neoformat is going to be added as the default formatting option for lunarvim (instead of using LSP efm),
in this case just running `Neoformat` will format the file. And of course, I'm going to add the option for autoformatting on save with an autocommand. 

I'll work on this tomorrow, and I'll add a CONTRIBUTING.md for letting users know that they need stylua with the specified config for formatting before doing PR

**Comment by ChristianChiarulli** [comment]
This is great, any reason not to keep `.stylua.toml` directly in the root?

**Comment by rafamadriz** [comment]
@ChristianChiarulli From my point of view. I don't think we should put more things on the users config folder, at least at root of it, even if is just a hidden file. For example: I hate when applications clutter my home folder with their hidden files, instead of following the XDG spec and put things in `~/.config`. My point being that I can already see people complaining about this, And creating issues with **"Can I delete this file ?"**. That config file is just for the collaborators and people who want to make PR's, not for the rest of users, hence they don't need that file in there. That's just my point of view, let me know what you think.

**Comment by ChristianChiarulli** [comment]
I think you're probably right, I'm of a similar mind when it comes to the XDG spec. Also when I see repos with like 50 million files in the root it can be overwhelming. Good work 👍🏻

**Comment by rafamadriz** [comment]
@ChristianChiarulli Do you know who else has access to this repo as collaborator ? To tag and let them know. Do we have some private channel for communication? for the people collaborating on this.

**Comment by ChristianChiarulli** [comment]
We should start one somewhere, likely that place will be the discord. I can create a channel only visible my mods and lunarvim collaborators.

**Comment by rafamadriz** [comment]
> We should start one somewhere, likely that place will be the discord. I can create a channel only visible my mods and lunarvim collaborators.

cool, let me know when that happens.
