### ISSUE TITLE
[Bug]: Can't install even I have deleted my nvim directory

### ISSUE THREAD

**Issue by imanaspaul** [ChristianChiarulli/LunarVim#679]
### Problem description

![image](https://user-images.githubusercontent.com/34214453/124432908-c2037380-dd8f-11eb-82dc-19a7abef2c8b.png)

### LunarVim version

I have use the bash script

### Neovim version (>= 0.5)

NVIM v0.4.3

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
You need to upgrade your version of neovim.  Follow the instructions on the wiki to compile from source if 0.5 isn't available on your distro's repository.

**Comment by ChristianChiarulli** [comment]
You need neovim 0.5, closing since this isn't a lunarvim issue.
