### ISSUE TITLE
[Bug]: No syntax highlight nor code completion for Terraform files

### ISSUE THREAD

**Issue by colutti** [ChristianChiarulli/LunarVim#688]
### Problem description

Open a terraform file (.tf). Code completion does not work neither sintax highlighting.

### LunarVim version

Master

### Neovim version (>= 0.5)

v0.6.0-dev+1485-g18bfcfe77

### Screenshots

![image](https://user-images.githubusercontent.com/9368892/124460912-46ee8d00-dd90-11eb-99c2-daaccab4dafb.png)

![image](https://user-images.githubusercontent.com/9368892/124461430-eb70cf00-dd90-11eb-9cd3-db267bf8df6e.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by IndianBoy42** [comment]
`nvim ~/.cache/nvim/lsp.log` - Check the LSP logs 

you may need `vim.lsp.set_log_level(3)` near the beginning of `init.lua` to get enough info

**Comment by colutti** [comment]
@IndianBoy42 

https://pastebin.com/LzjENVUk

**Comment by IndianBoy42** [comment]
```
[ ERROR ] 2021-07-05T13:48:45+0200 ] ...ovim/HEAD-18bfcfe/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/Users/rafaelcolucci/.local/share/nvim/lspinstall/terraform/terraform-ls"	"stderr"	"2021/07/05 13:48:45 module_loader.go:163: failed to obtain schema: exit status 1\n\nError: Backend initialization required, please run \"terraform init\"\n\nReason: Backend configuration changed for \"azurerm\"\n\nThe \"backend\" is the interface that Terraform uses to store state,\nperform operations, etc. If this message is showing up, it means that the\nTerraform configuration you're using is using a custom configuration for\nthe Terraform backend.\n\nChanges to backend configurations require reinitialization. This allows\nTerraform to set up the new configuration, copy existing state, etc. Please\nrun\n\"terraform init\" with either the \"-reconfigure\" or \"-migrate-state\" flags to\nuse the current configuration.\n\nIf the change reason above is incorrect, please verify your configuration\nhasn't changed and try again. At this point, no changes to your existing\nconfiguration or state have been made.\n\n2021/07/05 13:48:45 module_loader.go:165: finished \"OpTypeObtainSchema\" for /Users/rafaelcolucci/Documents/projects/work/InfolexTerraform/environments/qa\n"
```

Does this error message help? Specifically 
```
Backend initialization required, please run \"terraform init\"
```

**Comment by colutti** [comment]
The log changed a little bit, but it is still not working.

https://pastebin.com/kUmNY4Uz

**Comment by IndianBoy42** [comment]
it seems like terraformls is just always send errors responses, maybe try reinstalling it?

**Comment by colutti** [comment]
I just did, same thing. I ran a docker instance with Lunar and got the same results ....

**Comment by colutti** [comment]
OK, so now it seems to be working but I get no highlights. Am I supposed to?

**Comment by ChristianChiarulli** [comment]
highlights are treesitter dependent, so check if treesitter supports, if not we could get a regex plugin that only loads for terraform.

**Comment by colutti** [comment]
@ChristianChiarulli  it does support HCL:

https://github.com/nvim-treesitter/nvim-treesitter#supported-languages

**Comment by rebuilt** [comment]
I tested the example  from the [treesitter-hcl repo](https://github.com/MichaHoffmann/tree-sitter-hcl).  This is what it looks like

![terraform-highlighting](https://user-images.githubusercontent.com/16025007/124520736-99aa6200-dded-11eb-9231-76ca5cd7ed05.png)

**Comment by rebuilt** [comment]
According to the health information, treesitter doesn't support indents or locals for terraform.

As for highlighting, try the following

```
# Update tree-sitter
:TSUpdate
# Make sure there are no errors here
:checkhealth nvim_treesitter
# print the filetype of the current file
:set filetype?
# prints the completion method in the current file
:set omnifunc?
# indentation isn't supported, but if it were
:set indentexpr?
```

**Comment by colutti** [comment]
![image](https://user-images.githubusercontent.com/9368892/124547189-0e9c8c80-de2c-11eb-9b83-2755e1debac9.png)

![image](https://user-images.githubusercontent.com/9368892/124547220-1ceaa880-de2c-11eb-9002-e67f5951dea2.png)

![image](https://user-images.githubusercontent.com/9368892/124547275-2e33b500-de2c-11eb-9c46-c65b21bfa9a2.png)

![image](https://user-images.githubusercontent.com/9368892/124547309-3a1f7700-de2c-11eb-8f7a-7f35890d5122.png)

Still no highlighting :(

**Comment by colutti** [comment]
I think I got it! Does that seem ok to you?

![image](https://user-images.githubusercontent.com/9368892/124548050-71daee80-de2d-11eb-8933-91f31379b90e.png)

**Comment by alex-petrov-vt** [comment]
Could you share what you did to get it working if you don't mind?
