### ISSUE TITLE
Sequence of Sourcing the files in init.vim

### ISSUE THREAD

**Issue by lalitmee** [ChristianChiarulli/LunarVim#69]
@ChristianChiarulli , thank you for coming up the way you manage your config. I started follow the same way and I noticed that the sequence of sourcing the files matters in `init.vim`.

So what was happeing is that I have a key mappings for sourcing and editing my `init.vim`
```vim
nmap <leader>r :so ~/.config/nvim/init.vim<CR>
nmap <leader>e :e ~/.config/nvim/init.vim<CR>
```
When I put my `plug-config/coc.vim` file below the `keys/mappings.vim`, the mapping for editing the `init.vim` file was overridden by `coc-extensions` key mapping. So I had to change the order. 

Same thing was happing with `quickscope` too. I just wanted to know that did you know about this?

Are you following some order to source the files in `init.vim`? If yes please mention it in the readme. I watched your videos and I didn't notice you mentioning about this.

**Comment by ChristianChiarulli** [comment]
If you're remapping something I suggested searching through the config for nmap, map, etc and make sure the mapping you want isn't overridden somewhere. The coc.vim file should be one of the only places that maps occur.
