### ISSUE TITLE
[Bug]: Leader + c doesn't close the buffer with latest install

### ISSUE THREAD

**Issue by barun108** [ChristianChiarulli/LunarVim#703]
### Problem description

```<leader> + c``` doesn't close the buffer, with latest install

### LunarVim version

latest as on 5 July 2021, 20:37 Indian Time

### Neovim version (>= 0.5)

nvim >=0.5

### Screenshots

![2021-07-05-204010_445x228_scrot](https://user-images.githubusercontent.com/12285528/124491849-58a45480-ddd1-11eb-858b-942660139541.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by IndianBoy42** [comment]
The change to fix this hasn't been merged into stable yet. Change BufferClose to bdelete! in lua/lv-which-key/init.lua (#690)

**Comment by luxus** [comment]
hey @barun108,
is it fixed with 0.4?

**Comment by ChristianChiarulli** [comment]
this should be fixed in 0.4
