### ISSUE TITLE
What's the best way to add my own plugin and keymap?

### ISSUE THREAD

**Issue by YukoOshima** [ChristianChiarulli/LunarVim#704]
### Problem description

Every time I modified the plugin and which-key config key, there's always conflict if I pull the newest version to my local machine. What's the best way to keep my plugin and keymap without conflict?

### LunarVim version

newest

### Neovim version (>= 0.5)

newest

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
lv-config.lua is the place for your personal configuration.  There are plans to improve this so you can override options that get loaded later in the config.  But those are not yet implemented.

https://github.com/ChristianChiarulli/LunarVim/issues/614

**Comment by gnmearacaun** [comment]
You could source this file in your lv-config, create the file and it will work with your old init.vim settings.
`
vim.cmd('source ' .. CONFIG_PATH .. '/utils/lv-user-settings/init.vim')
`
This guide is recommended while you figure out how to convert your settings into lua: https://github.com/nanotee/nvim-lua-guide

I'm part way through converting [my settings](https://github.com/gnmearacaun/LunarVim/blob/master/lv-config.lua).

As for plugins, I just edited lua/settings.lua

**Comment by YukoOshima** [comment]
Thank you!
