### ISSUE TITLE
[Help wanted]: Autocomplete styled-components in .js .ts

### ISSUE THREAD

**Issue by mbalazy** [ChristianChiarulli/LunarVim#705]
### Problem description

Is there any chance for now, to get an autocomplete for styled-components styling in .ts or .js files?

### LunarVim version

last one

### Neovim version (>= 0.5)

0.6

### Screenshots

![2021-07-05-175058_1687x498_scrot](https://user-images.githubusercontent.com/49127168/124496583-e70cdc00-ddb9-11eb-9eea-53ee62dc00d3.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rafamadriz** [comment]
That's not possible. You would need to attach the css server in a javascript/typescript file, the other option would be css snippets but that's not a ideal solution either.

The tsserver only understands about javascript or typescript, that's why it can't complete css.

**Comment by mbalazy** [comment]
Ok, I have to say that I figured it out.

Just install this:
https://github.com/microsoft/typescript-styled-plugin

`yarn add -D typescript-styled-plugin typescript`

Then add a plugins section to your tsconfig.json or jsconfig.json

`{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin"
      }
    ]
  }
}`

It works OOTB, I dont have to install any other plugin into lunarvim.

**Comment by rafamadriz** [comment]
> Ok, I have to say that I figured it out.
> 
> Just install this:
> https://github.com/microsoft/typescript-styled-plugin
> 
> `yarn add -D typescript-styled-plugin typescript`
> 
> Then add a plugins section to your tsconfig.json or jsconfig.json
> 
> `{
>   "compilerOptions": {
>     "plugins": [
>       {
>         "name": "typescript-styled-plugin"
>       }
>     ]
>   }
> }`
> 
> It works OOTB, I dont have to install any other plugin into lunarvim.
> 
> 
> EDIT: 
> Ok, it worked for 2minutes, then stop showing autocomplete...

That's kinda cool, didn't know there were plugins that you can add to tsserver.
