### ISSUE TITLE
[Bug]: Ranger (rnvimr) plugin

### ISSUE THREAD

**Issue by barun108** [ChristianChiarulli/LunarVim#718]
### Problem description

rnvimr plugin is not opening first time

it gives some error

but after that RnvimrTogggle command works fine
and shortcut ```<leader> + - ``` works too

### LunarVim version

0.4.0

### Neovim version (>= 0.5)

nvim >=0.5

### Screenshots

![2021-07-06-072432_699x569_scrot](https://user-images.githubusercontent.com/12285528/124531485-3d1a6780-de2c-11eb-95aa-1bd27b615d51.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you provide your `lv-config.lua`, i think instead of 
```lua
O.plugin.something.active=true
```
you have 
```lua
O.plugin.something=true
```

**Comment by ChristianChiarulli** [comment]
rnvimr will now be a user defined plugin so we don't manage it in core anymore.
