### ISSUE TITLE
[Bug]: <Leader>c does not work on FloatTerm

### ISSUE THREAD

**Issue by colutti** [ChristianChiarulli/LunarVim#720]
### Problem description

Trying to close a FloatTerm buffer with Leader + c

![image](https://user-images.githubusercontent.com/9368892/124553368-efeec380-de34-11eb-8c2b-04c1355dcecb.png)

### LunarVim version

Master

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+1488-ga6cdfa27d

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by barun108** [comment]
I think that's Terminal windows and only option you would get there to exit is ```'q' or ':q' or '$exit'```

**Comment by abzcoding** [comment]
I've added this to my `lv-config.lua`:
```lua
-- Keybindings
local map = vim.api.nvim_set_keymap
local opts = {noremap = true, silent = true}

map('n', 'T', '<CMD>lua require("FTerm").toggle()<CR>', opts)
map('t', 'T', '<C-\\><C-n><CMD>lua require("FTerm").toggle()<CR>', opts)
```
so I can close the floating terminal with `T` in normal mode

**Comment by colutti** [comment]
@abzcoding 

That is a nice solution. I ended up using a cleaner version:

`vim.api.nvim_set_keymap('n', 'T', ':FloatermToggle<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('t', 'T', '<C-\\><C-n>:FloatermToggle<CR>', {noremap = true, silent = true})`
