### ISSUE TITLE
[Bug]: Resize with arrows does not work on Macs

### ISSUE THREAD

**Issue by colutti** [ChristianChiarulli/LunarVim#722]
### Problem description

In keymappings.lua:

-- resize with arrows
vim.api.nvim_set_keymap("n", "<C-Up>", ":resize -2<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<C-Down>", ":resize +2<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<C-Left>", ":vertical resize -2<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<C-Right>", ":vertical resize +2<CR>", { silent = true })

It does not work on Macs since those key are already bound to desktop navigation.

Can we change those maps to something else?

### LunarVim version

Master

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+1488-ga6cdfa27d

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
I've added this to my `lv-config.lua` on mac:
```lua
-- resize with arrows
vim.api.nvim_set_keymap("n", "<A-Up>", ":resize -2<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<A-Down>", ":resize +2<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<A-Left>", ":vertical resize -2<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<A-Right>", ":vertical resize +2<CR>", { silent = true })
```

**Comment by colutti** [comment]
Yes, this works but I was wondering if we could change the default mapping for everyone. Maybe we can add an IF to detect if the SO is Mac and if it is we would change the mapping to ALT instead of CTRL

**Comment by rebuilt** [comment]
This is how sumneko detects the os
```
local system_name
if vim.fn.has("mac") == 1 then
  system_name = "macOS"
elseif vim.fn.has("unix") == 1 then
  system_name = "Linux"
elseif vim.fn.has('win32') == 1 then
  system_name = "Windows"
else
  print("Unsupported system for sumneko")
end
```

**Comment by colutti** [comment]
So, the code would be that right?

`if vim.fn.has("mac") == 1 then
	vim.api.nvim_set_keymap("n", "<A-Up>", ":resize -2<CR>", { silent = true })
	vim.api.nvim_set_keymap("n", "<A-Down>", ":resize +2<CR>", { silent = true })
	vim.api.nvim_set_keymap("n", "<A-Left>", ":vertical resize -2<CR>", { silent = true })
	vim.api.nvim_set_keymap("n", "<A-Right>", ":vertical resize +2<CR>", { silent = true })
else
	vim.api.nvim_set_keymap("n", "<C-Up>", ":resize -2<CR>", { silent = true })
	vim.api.nvim_set_keymap("n", "<C-Down>", ":resize +2<CR>", { silent = true })
	vim.api.nvim_set_keymap("n", "<C-Left>", ":vertical resize -2<CR>", { silent = true })
	vim.api.nvim_set_keymap("n", "<C-Right>", ":vertical resize +2<CR>", { silent = true })
end`

**Comment by abzcoding** [comment]
@colutti created a PR for it
