### ISSUE TITLE
[Feature]: Routine to update LunarVim

### ISSUE THREAD

**Issue by Uzaaft** [ChristianChiarulli/LunarVim#733]
### Feature motivation

Usually, I stash, pull , and then apply my stash. But this often results in a lot of labour to go trough the files, merge files, etc... Which made me thought, is there a better way to update LunarVim, which reduces the amount of work done by the user between updates. 

### Describe the expected solution

Oh my zsh is able to update automatically, without me doing any manual labour. Now, I am going to be the first person to say that I don't understand the how, but it would be a nice feature to have lunar vim update similarly to oh my zsh. 

Now I am not asking for a fully automated solution. I understand that this is not possible, but some instructions on updating would be nice to ease the update process. I just used Oh my zsh as an example because it's the best example I could come up with. But a shell script that unifies the way people update Neovim would be one step towards making updating easier.

**Comment by Uzaaft** [comment]
Edit: Added more about expected solution description.

**Comment by colutti** [comment]
My own process to update LunarVim:

I forked the project and pulled the main branch. 
I added all my stuff (maps, plugins, config) into the lv-config.lua since this file is not versioned. 
From time to time I fetch all changes from the original project and merge then into main.
When I want to test something or send a PR i just create a new branch from main.

**Comment by rebuilt** [comment]
The way to do this has gotten much more robust in the last few days.  ~/.config/nvim/lv-config.lua is the place you should store most of your personal settings.  It's in the .gitignore file so it won't be overwritten when you pull recent changes.  You can also define your own set of plugins from this file.  I've added a section describing this in the [wiki](https://github.com/ChristianChiarulli/LunarVim/wiki/Installing-Plugins).  

I want to keep my plugin configuration in a separate file.  For this, I've created a ~/.config/nvim/lua/user-settings folder.  This is not part of LunarVim.  It's just something I've done.  It would be nice if Lunarvim would include a .gitignored folder where I could keep all the configuration I wanted.  That may or may not be coming in the future.  

I'm keeping my own personal configs on my fork in a branch called 'rebuilt'.  If you're curious to see how it works, you can pull down the repo.

```
# First back up your current config
mv ~/.config/nvim ~/.config/nvim.bak

git clone --branch rebuilt https://github.com/rebuilt/DeathStar-Vim.git ~/.config/nvim
cd nvim
cp utils/installer/lv-config.example.lua lv-config.lua
```

@ChristianChiarulli  Can we get a .gitignored folder to keep our user settings?

**Comment by luxus** [comment]
isn't this folder planned for that?
[lv-user](https://github.com/ChristianChiarulli/LunarVim/tree/master/lua/lv-user)
but there is nothing in [.gitgnore](https://github.com/ChristianChiarulli/LunarVim/blob/master/.gitignore)

**Comment by rebuilt** [comment]
If it's not ignored there will problems pulling and merging code.

**Comment by luxus** [comment]
@rebuilt 
this should be added right?
```
lua/lv-user/*
!lua/lv-user/README.md
```

**Comment by rebuilt** [comment]
Maybe the right approach is git submodules.  Not sure though.  I've never used submodules.

**Comment by luxus** [comment]
thats a good idea. so people could even share their custom configs if they want.
at best there should be a lv-user repo that user should fork

**Comment by ChristianChiarulli** [comment]
I think for now as a quick solution, lv-user is fine, nobody was really even supposed to find it anyway.

**Comment by rebuilt** [comment]
https://github.com/ChristianChiarulli/LunarVim/issues/758

**Comment by Uzaaft** [comment]
Thanks guys for the tips and tricks! I'm going to go ahead and close this, since rebuilt created #758 .
Just wanted to close this by saying thank you to the maintainers and dev's. Without you guys, I wouldn't be as comfortable with Neovim as I am today. Keep up the great work!
