### ISSUE TITLE
[Bug]: New install isn't fully functional

### ISSUE THREAD

**Issue by ChrisBFusion** [ChristianChiarulli/LunarVim#735]
### Problem description

1. Clean install LunarVim
2. Start NeoVim
3. LunarVim menu screen doesn't appear
4. Try to install lua language server protocol
5. Error message: `E492: Not an editor command LspInatall lua`
6. Try to find a file to open for editing(\<space\> f)
7. Error message: `E492: Not an editor command Telescopr find_files`

### LunarVim version

0.4.1

### Neovim version (>= 0.5)

0.6.0-dev+14-gdf33f30e8

### Screenshots

https://user-images.githubusercontent.com/6013872/124644612-78cf2480-de60-11eb-9d85-7fe58b484e7a.mov

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Did you try :PackerSync

**Comment by ChrisBFusion** [comment]
PackerSync did it.
