### ISSUE TITLE
[Feature]: Guide on configuring efm langserver

### ISSUE THREAD

**Issue by nathanielks** [ChristianChiarulli/LunarVim#741]
### Feature motivation

I would like to be able to add additional formatters and linters, but it is not immediately clear how I go about doing that with the efm langserver. I'm not sure what file(s) I need to put configuration into, and what configuration needs to be added. I've seen other issues bringing up adding additional linters/formatters, but they seem to fall back on linters that have already been configured instead of adding support for new ones (https://github.com/ChristianChiarulli/LunarVim/issues/508, https://github.com/ChristianChiarulli/LunarVim/issues/493). A number of issues also mention files that don't exist in this repo, which makes it confusing to try and deduce what actions should be taken without reaching out to package maintainers for help.

### Describe the expected solution

I'd love a wiki page or similar outlining how to go about adding support for additional linters/formatters using the efm langserver.

### Describe the alternatives you've considered

I've looked into the aforementioned issues, as well as the efm langserver docs themselves. They're not incredibly clear either.

**Comment by abzcoding** [comment]
@nathanielks the formatting/linting has changed a lot recently
can you update pull the latest or install it again and check if it works or not:
also, [wiki](https://github.com/ChristianChiarulli/LunarVim/wiki/Formatters-and-Linters) has been updated 
and a couple of examples has been added to `lv-config.lua` e.g:
```lua
-- to change default formatter from yapf to black uncomment the following lines
-- O.lang.python.formatter.exe = "black"
-- O.lang.python.formatter.args = {"-"}
```

I'm closing this issue for now, but feel free to reopen it this didn't help you
