### ISSUE TITLE
[Bug]: Initialzation error - Neoformat

### ISSUE THREAD

**Issue by colutti** [ChristianChiarulli/LunarVim#746]
### Problem description

I have this configured in my lv-config:

`O.format_on_save = false`

No changes on master, when I open vim I get this error and nothing else loads properly:

![image](https://user-images.githubusercontent.com/9368892/124707764-92707a80-def9-11eb-9216-38cb7460fbd6.png)

![image](https://user-images.githubusercontent.com/9368892/124707799-9ef4d300-def9-11eb-8a5c-963f8a36a802.png)

### LunarVim version

Master

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+1488-ga6cdfa27d

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
Can you try `:PackerUpdate`?

**Comment by abzcoding** [comment]
I have tried that as well it doesn't solve anything

**Comment by colutti** [comment]
@ChristianChiarulli it doesnt solve the issue

I have this enabled in my lv-config:

O.format_on_save = false

**Comment by colutti** [comment]
@abzcoding PR solves the issue

**Comment by abzcoding** [comment]
@ChristianChiarulli  if we want to enable/disable `autocmd` group on the fly we might need to do something like this:
```vim
function! ToggleAutoFormat()
    if !exists('#TestAutoFormat#BufWritePre')
        augroup TestAutoFormat
            autocmd BufWritePre * [[try | undojoin | Neoformat | catch /^Vim\%((\a\+)\)\=:E790/ | finally | silent Neoformat | endtry]]
        augroup END
    else
        augroup TestAutoFormat
            autocmd!
        augroup END
    endif
endfunction

nnoremap <F4> :call ToggleTestAutoFormat()<CR>
```
