### ISSUE TITLE
[Bug]: Escape does not work on lazzygit when opening it inside neovim

### ISSUE THREAD

**Issue by colutti** [ChristianChiarulli/LunarVim#759]
### Problem description

If I open lazzygit inside neovim, the esc does not work on lazzygit but in VIM.

The esc key is used on lazzygit as a <GO BACK> action, but since it is opened on nvim the esc behaves just like it behaves on buffers. 

The same would be applied to other apps opened inside floatterm.

### LunarVim version

Master

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+1488-ga6cdfa27d

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
@colutti have you tried [this](https://github.com/jesseduffield/lazygit/issues/992)

**Comment by abzcoding** [comment]
by adding this to your `lv-config.lua`
```lua
vim.api.nvim_exec(
  [[
    function AddTerminalNavigation()

    echom &filetype
    if &filetype ==# 'FTerm'
        tnoremap <Esc> q
        tnoremap <C-v><Esc> <Esc>
    endif

endfunction
  ]]
, true)
O.user_autocommands = {
   {"TermEnter", "*", "call AddTerminalNavigation()"}
}
```

you can change the functionality of `ESC` key inside `FTerm`

**Comment by colutti** [comment]
Yeah, that worked. I think you should send a PR ...

**Comment by abzcoding** [comment]
after #749 gets fixed, I would send a PR to make this part of the `lua/lv-floatterm/init.lua`
