### ISSUE TITLE
Change formatter to formatter.nvim

### ISSUE THREAD

**Issue by ChristianChiarulli** [ChristianChiarulli/LunarVim#775]
https://github.com/mhartington/formatter.nvim

**Comment by Jacob87** [comment]
Good idea. I have nothing against Neoformat but I think it is a better solution in the long run. Also, it would be cool if we could just choose whatever formater we want from the user settings, for example prettierd instead of prettier.

**Comment by ChristianChiarulli** [comment]
https://github.com/mhartington/formatter.nvim

**Comment by brymer-meneses** [comment]
I will give this a try later.

**Comment by rafamadriz** [comment]
> I will give this a try later.
> 
> Perhaps I could just port the args from neoformat?

Yes, you can do that. I thought about doing this a long time ago when I wanted to have every single plugin in lua, but Neoformat just works for me so I kinda forgot about it.

**Comment by ChristianChiarulli** [comment]
Neoformat was a great bandaid that covers 80% of use cases. 

I think formatter.nvim will bring us another 15% of the way there.
