### ISSUE TITLE
[Feature]: lsp-status

### ISSUE THREAD

**Issue by arxra** [ChristianChiarulli/LunarVim#779]
### Feature motivation

Not knowing why you are not getting smartness from LV can be very confusing, especially for new (vim) users. Adding something like lsp-status (nvim-lua/lsp-status.nvim) to Galaxyline would give that information.

This is even more true for LSP's which perform a lot of indexing before giving any feedback, such as rust-analyzer which downloads all your dependencies in the background.

### Describe the expected solution

It should be clear what the LSP is doing when its "not working". As a user I expect some feedback from my editor on what is happening when I'm waiting.

### Describe the alternatives you've considered

Not sure if another plugin is the right call or how files with multiple LSP's would/should be handled.

### Additional context

Came as a question in the matrix chat.

**Comment by rebuilt** [comment]
It should already be there.  Try :LspInfo

Or this keybind

```
<space>li
```

**Comment by arxra** [comment]
LspInfo doesn't tell the user what is happening though. For example, opening a large  python or rust project and hitting <space>li before diagnostics are available doesn't tell me that it is still indexing libraries or checking types, which nvim-lua/lsp-status.nvim does.

**Comment by arxra** [comment]
But maybe it should? This might be a feature request for the package with LspInfo more than LV itself

**Comment by rebuilt** [comment]
Have you already configured nvim-lua/lsp-status.nvim for yourself?  If so, I can add those configurations to the wiki right now.  

I think we've reached the feature-freeze state for LunarVim 1.0.  We're trying to work out any bugs, and get formatting working before release:  https://www.youtube.com/watch?v=KVxsCvXr7sE&t=5925s

**Comment by rebuilt** [comment]
Thanks for the link to this project.  Honestly it looks very interesting.  I'm going to have to spend some time with it.

**Comment by arxra** [comment]
I had it configured in galaxyline, but that was before 0.1 and so much have changed since then (maintaining my fork was too much with the constant stream of new features). It wasn't too bad, its just a lua function and there are many examples around for how to integrate it with Galaxyline.

I might have more time to play with it after work, I'll keep you posted on how that goes

**Comment by arxra** [comment]
Looks like one would need to rewrite each and every LS file to report its status and features to `nvim-lua/lsp-status.nvim`, which is a lot of work for some information.
Maybe for neovim .6 we'll have a cleaner API for this, making it more feasable for generalists configs to include it

**Comment by abzcoding** [comment]
> Looks like one would need to rewrite each and every LS file to report its status and features to `nvim-lua/lsp-status.nvim`, which is a lot of work for some information.
> Maybe for neovim .6 we'll have a cleaner API for this, making it more feasable for generalists configs to include it

@arxra we're currently overhauling the lsp stuff, so it will change a lot till the end of the month
feel free to reopen this issue if it was not satisfactory after those changes
