### ISSUE TITLE
[Bug]: Terraform LSP and formatting

### ISSUE THREAD

**Issue by soerenmartius** [ChristianChiarulli/LunarVim#782]
### Problem description

At the moment, Terraform files `*.hcl,*.tf,` are exposed as `:set filetype=tf`. On the contrary, `nvim-treesitter` and `neoformat` are working with the filetype `hcl`. (e.g. https://github.com/nvim-treesitter/nvim-treesitter#supported-languages)

In https://github.com/ChristianChiarulli/LunarVim/blob/master/lua/lv-treesitter/init.lua I've configured the following lines to have treesitter working but it doesn't work either:

```lua
local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
parser_config.hcl.used_by = "tf"
```

E.g., If I have a `*.tf` file opened and manually run `:set filetype=hcl`, formatting and treesitter seem to be working!

### LunarVim version

0.4.5

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+18bfcfe77

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
https://github.com/wbthomason/packer.nvim/issues/457#issuecomment-876506973

**Comment by ChristianChiarulli** [comment]
https://github.com/ChristianChiarulli/LunarVim/commit/6da71bab94302d9d8e4afbf5f18da24487fdd294

This should fix the treesitter issue although I'm not sure the formatter works with this.

**Comment by soerenmartius** [comment]
it will not fix the formatter as neoformat only considered files of the type `terraform`

**Comment by soerenmartius** [comment]
thanks for providing the treesitter fix! Works like a charm!

**Comment by colutti** [comment]
It does not work for me:

![image](https://user-images.githubusercontent.com/9368892/125073526-63eecd00-e0bc-11eb-9281-9b59061ef2fd.png)

![image](https://user-images.githubusercontent.com/9368892/125073541-6a7d4480-e0bc-11eb-835b-2a4ab4f660c3.png)

**Comment by ChristianChiarulli** [comment]
yea the formatter won't work for this, we're about to overhaul formatting soon, so I'm not sure if it's worth getting working with neoformat.

**Comment by colutti** [comment]
Well, as a strong user of Terraform for my job, I would say that it is worthy it but I understand if your priorities are different.

**Comment by colutti** [comment]
Uf i fix it myself would you merge my PR?

**Comment by soerenmartius** [comment]
@colutti I can't find your PR? Could you post the link here? Many thanks

**Comment by abzcoding** [comment]
@soerenmartius we've overhauled the formatters and added support for terraform last night, can you pull the latest changes and check if the issue is resolved or not?

**Comment by soerenmartius** [comment]
It works now! Thanks!
