### ISSUE TITLE
[Bug]: Can't lazy load Galaxyline with the VimEnter event

### ISSUE THREAD

**Issue by Pocco81** [ChristianChiarulli/LunarVim#793]
### Problem description

Today I was trying to lazy load Galaxyline by loading it after entering vim (VimEnter event). But it wasn't working, only a gray bar appeared. I came to LunarVim to see if you guys were lazy loading the plugin and the `event` line was commented [here](https://github.com/ChristianChiarulli/LunarVim/blob/master/lua/plugins.lua#L124-L130). Can't Galaxyline be lazy loaded? Why?

If this ends up being a galaxyline issue I'll open this issue in their repo then.

### LunarVim version

Very old fork

### Neovim version (>= 0.5)

latest stable

### Relevant log output

```shell
Not needed.
```

### Screenshots

Lazy loading the plugin:
![image](https://user-images.githubusercontent.com/58336662/124951341-df774e00-dfd8-11eb-9026-25e437b5141f.png)

After entering vim, galaxyline doesn't appear.
![image](https://user-images.githubusercontent.com/58336662/124951415-f28a1e00-dfd8-11eb-8ceb-bc0ea4d0e111.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you test if this works?
```lua
 use {
    "glepnir/galaxyline.nvim",
    config = function()
      require "lv-galaxyline"
    end,
    event = {"VimEnter", "BufRead"},
  }

```

**Comment by ChristianChiarulli** [comment]
I have galaxyline lazyloading in master I think.

**Comment by Pocco81** [comment]
I think I should've been more specific. So, after doing some tests it seems that you can't lazy load it using the "VimEnter" event, but any other works as expected.

**Comment by Pocco81** [comment]
Huh? So no explanation for closing this issue?

**Comment by rafamadriz** [comment]
> Huh? So no explanation before closing the issue?

My apologies, I was going through all the issues and closing things not related to the LunarVim config. This is more of a packer/galaxyline/lazy loading problem. But you're 100% right, I should have said that. 

> So, after doing some tests it seems that you can't lazy load it using the "VimEnter" event, but any other works as expected.

Didn't this answer the original question ?
