### ISSUE TITLE
vim-rooter may still be useful

### ISSUE THREAD

**Issue by ChristianChiarulli** [ChristianChiarulli/LunarVim#794]
https://github.com/airblade/vim-rooter

**Comment by pidgeon777** [comment]
I also use it and it very useful, indeed.

**Comment by maxime50** [comment]
What's the difference with [ahmedkhalf/lsp-rooter.nvim](https://github.com/ahmedkhalf/lsp-rooter.nvim)?

**Comment by ChristianChiarulli** [comment]
@maxime50 may be too lsp specific? idk

**Comment by maxime50** [comment]
@ChristianChiarulli oh yeah I see... Support for non-LSP projects is in their Todos tho, but no idea how long it will take.

**Comment by ChristianChiarulli** [comment]
I find it to be essential, it is now a default plugin.
