### ISSUE TITLE
Potentially replace efm with nvim-lint

### ISSUE THREAD

**Issue by ChristianChiarulli** [ChristianChiarulli/LunarVim#797]
https://github.com/mfussenegger/nvim-lint

**Comment by kylo252** [comment]
It's in *alpha* state right now, but maybe give [null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim) a consideration as well. 

> null-ls includes a library of built-in sources meant to provide out-of-the-box functionality. Built-in sources run with optimizations to reduce startup time and enable user customization.
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#available-sources
