### ISSUE TITLE
Duplicated functionality between "O.lang...autoformat" and "O.format_on_save"

### ISSUE THREAD

**Issue by kylo252** [ChristianChiarulli/LunarVim#810]
### Feature motivation

There's an overlap between the two options and we should probably just stick to one of them:

https://github.com/ChristianChiarulli/LunarVim/blob/1154032f64eec889e12d4e39ce141ed1bc8f4f28/lua/lv-neoformat/init.lua#L2-L12

https://github.com/ChristianChiarulli/LunarVim/blob/1154032f64eec889e12d4e39ce141ed1bc8f4f28/ftplugin/lua.lua#L35-L45

I vote for keeping the granular `O.lang.xxx.autoformat` option.

**Comment by rafamadriz** [comment]
Thanks, for reporting, one is for formatting with the language server and the other was using neoformat (it's has been changed to formatter.nvim)
