### ISSUE TITLE
lv-telescope path_display should be smart

### ISSUE THREAD

**Issue by abzcoding** [ChristianChiarulli/LunarVim#812]
Current configuration inside `lua/lv-telescope/init.lua`  is `path_display = { "shorten" }` which is pretty useless IMO, as shown in the picture ( when searching for `init.lua` file inside LunarVim)
![path_display](https://user-images.githubusercontent.com/10992695/125079942-70cde980-e0d9-11eb-92fc-83a24fb4831a.png)

There is a [PR](https://github.com/caojoshua/telescope.nvim/pull/1) to fix this, an `smart` option. I'm just putting this here so we can change the config as soon as that gets merged.

**Comment by abzcoding** [comment]
in case anyone wants to change it until the upstream is merged, add this to your `lv-config.lua`
```lua
O.plugin.telescope.defaults.path_display = {"absolute"}
```

**Comment by abzcoding** [comment]
we need to check [this](https://github.com/nvim-telescope/telescope.nvim/pull/886) out

**Comment by l-kershaw** [comment]
@abzcoding if you want something more specific than available with the current options, you could always use [this](https://github.com/nvim-telescope/telescope.nvim/pull/1000). This PR allows you to write a custom function that is used to determine how paths are displayed.

I don't think it would allow something like "smart" in [this](https://github.com/nvim-telescope/telescope.nvim/pull/914), as the function only has access to one path at a time, but it might work if you have something else in mind.

**Comment by abzcoding** [comment]
> @abzcoding if you want something more specific than available with the current options, you could always use [this](https://github.com/nvim-telescope/telescope.nvim/pull/1000). This PR allows you to write a custom function that is used to determine how paths are displayed.
> 
> I don't think it would allow something like "smart" in [this](https://github.com/nvim-telescope/telescope.nvim/pull/914), as the function only has access to one path at a time, but it might work if you have something else in mind.

Thanks, I haven't yet figured out what I prefer, but i'll look into `custom_display`
