### ISSUE TITLE
[Bug]: gopls LSP fails to attach to dependent go modules  

### ISSUE THREAD

**Issue by PellePedro** [ChristianChiarulli/LunarVim#817]
### Problem description

Lsp for go works es expected for local sources and 3rd party vendor directory. 
 However, if dependency are used as go modules then the lsp configuration fails to configure the root_dir for gopls
 e.g. "~/go/pkg/mod/github.com/digitalocean/go-openvswitch@v0.0.0-20210610204619-e0e0c7890c6b

A third party module might not have a .git or go.mod file which fails to attach the lip client to the buffer when browsing a dependency library.

/ftplugin/go.lua

 require("lspconfig").gopls.setup {
    cmd = { DATA_PATH .. "/lspinstall/go/gopls" },
    settings = { gopls = { analyses = { unusedparams = true }, staticcheck = true } },
    **root_dir = require("lspconfig").util.root_pattern(".git", "go.mod"),**
    init_options = { usePlaceholders = true, completeUnimported = true },
    on_attach = require("lsp").common_on_attach,
  }
end

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

0.4.6

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+8-g75f758b99

### Screenshots

**Working LSP in own code base**

<img width="1306" alt="Screen Shot 2021-07-09 at 8 07 31 AM" src="https://user-images.githubusercontent.com/746060/125114482-05bfeb00-e0b8-11eb-8a49-a3a56caae499.png">

**Failing LSP in dependent go module located under $GO_PATH/pkg/mod**
<img width="1295" alt="Screen Shot 2021-07-09 at 8 08 27 AM" src="https://user-images.githubusercontent.com/746060/125114695-4c154a00-e0b8-11eb-89c2-b16865cfd069.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
Can you test if changing this line inside `ftplugin/go.lua`:
```lua
root_dir = require("lspconfig").util.root_pattern(".git", "go.mod"),
```
to
```lua
root_dir = require("lspconfig").util.root_pattern(".git", "go.mod", "."),
```
fixes this issue or not?
> you might need to run `:PackerCompile` after changing it

**Comment by PellePedro** [comment]
Adding "." to the list fixes this issue.

root_dir = require("lspconfig").util.root_pattern(".git", "go.mod", "."),

Thanks,

**Comment by ChristianChiarulli** [comment]
This has been such a back and forth for this lsp. If that is important for this than I'm assuming we need it correct?

**Comment by abzcoding** [comment]
> This has been such a back and forth for this lsp. If that "." is important for this than I'm assuming we need it correct?

the problem is that there are some cases in which `.` is causing problems and some other cases that it fixes problems :sob:

**Comment by abzcoding** [comment]
@ChristianChiarulli  this PR is the one where it got removed #471

**Comment by abzcoding** [comment]
@PellePedro can you check if this works or not?
```lua
root_dir = require("lspconfig").util.root_pattern(".git", "go.mod", "Gopkg.lock"),
```
instead of the one with the `.`

**Comment by PellePedro** [comment]
"Gopkg.lock" is an old form of dependency management and deprecated with the introduction of go modules as dependency management in go 1.11 a couple of years ago.

Dependency with go modules. 
With go modules, the dependent library/source code is not located under your project directory, but in a central module cache that's default stored under ~/go/pkg/mod

Dependency prior to go modules.
Prior to go modules, the dependencies were stored as source code under the project directory and a "vendor" folder, therefore all source code had the same project root.

The same applies when browsing code in the go the standard library, located under /usr/local/go/src.

**Comment by mjlbach** [comment]
this isn't a lunarvim issue, this is an lspconfig issue. I haven't decided yet how to handle attaching the client to system libraries. For go, see https://github.com/neovim/nvim-lspconfig/issues/804 and the linked PR.

**Comment by PellePedro** [comment]
I will close this issue with a comment to neovim/nvim-lspconfig#804 , but everything works fine by appending  "." to the root_dir in ftplugin/go.lua 

In my workflow I'm using Lir as my primary file browser and I experience the behaviour after adding "." is as follow.

- Nwimtree and Telescope stays within the project
- The Lsp Client is attached to all go files i.e. (in project files, system library g modules)
- Lir is configured to open the enclosing directory of the current buffer. i.e. after navigation to a file in the system library, opening Lir will show the content of the enclosing directory in the system library (which is the desired behaviour for my workflow)


As an example below. 
1. I checked out the code base of Kubernetes
2. Opened file pkg/contolplane/controller.go
3. Used LSP to navigate to a symbol in system library "time"

<img width="1389" alt="Screen Shot 2021-07-11 at 12 15 35 PM" src="https://user-images.githubusercontent.com/746060/125202500-dd63f800-e241-11eb-98d7-6008a338a2a0.png">

**Comment by mjlbach** [comment]
You should not add ('.') post-pended to the root dir.  The solution is to modify lspconfig to accept a list of additional "library" roots.

**Comment by PellePedro** [comment]
See neovim/nvim-lspconfig#804
