### ISSUE TITLE
Pyright not working with conda environment.

### ISSUE THREAD

**Issue by adarshchbs** [ChristianChiarulli/LunarVim#821]
### Problem description

Pyright is not recognising the correct python interpreter although Nvim is recognising the correct conda environment.
<img width="1505" alt="Screenshot 2021-07-09 at 11 59 11 PM" src="https://user-images.githubusercontent.com/38124313/125121624-d1791880-e111-11eb-90d1-4a295e8d6416.png">

<img width="594" alt="Screenshot 2021-07-10 at 12 03 03 AM" src="https://user-images.githubusercontent.com/38124313/125121885-3af92700-e112-11eb-93b5-7c5b5322230c.png">

### LunarVim version

0.4.6

### Neovim version (>= 0.5)

0.5.0

### Screenshots

<img width="733" alt="Screenshot 2021-07-09 at 11 48 55 PM" src="https://user-images.githubusercontent.com/38124313/125121146-18b2d980-e111-11eb-8311-978c600eb7ff.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
what's the output of `conda list`?

**Comment by adarshchbs** [comment]
packages in environment at /Users/adarsh.gupta3/anaconda3:

# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0  
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
act-development           1.0.0                     dev_0    <develop>
aiohttp                   3.7.4.post0              pypi_0    pypi
aiohttp-cors              0.7.0                    pypi_0    pypi
aioredis                  1.3.1                    pypi_0    pypi
alabaster                 0.7.12                     py_0  
alembic                   1.4.1                    pypi_0    pypi
anaconda                  custom                   py38_1  
anaconda-client           1.7.2                    py38_0  
anaconda-navigator        1.10.0                   py38_0  
anaconda-project          0.8.4                      py_0  
aniso8601                 9.0.1                    pypi_0    pypi
ansiwrap                  0.8.4                    pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
applaunchservices         0.2.1                      py_0  
appnope                   0.1.0                 py38_1001  
appscript                 1.1.1            py38haf1e3a3_0  
argh                      0.26.2                   py38_0  
argon2-cffi               20.1.0           py38haf1e3a3_1  
asn1crypto                1.4.0                      py_0  
astroid                   2.4.2                    py38_0  
astropy                   4.0.2            py38haf1e3a3_0  
async-timeout             3.0.1                    pypi_0    pypi
async_generator           1.10                       py_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.4                      py_0  
azure-core                1.12.0                   pypi_0    pypi
azure-storage-blob        12.8.0                   pypi_0    pypi
babel                     2.8.1              pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.6.1                      py_0  
backports.shutil_get_terminal_size 1.0.0                    py38_2  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.8.2                    pypi_0    pypi
big-sleep                 0.8.5                    pypi_0    pypi
bitarray                  1.6.1            py38h9ed2024_0  
bitmath                   1.3.3.1                  pypi_0    pypi
bkcharts                  0.2                      py38_0  
black                     21.4b2                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
blessings                 1.7                      pypi_0    pypi
blis                      0.7.4                    pypi_0    pypi
blosc                     1.20.1               hab81aa3_0  
bokeh                     2.2.3                    py38_0  
boto                      2.49.0                   py38_0  
boto3                     1.17.29                  pypi_0    pypi
botocore                  1.20.29                  pypi_0    pypi
bottleneck                1.3.2            py38hf1fa96c_1  
bpemb                     0.3.2                    pypi_0    pypi
brotli                    1.0.9                    pypi_0    pypi
brotlipy                  0.7.0           py38haf1e3a3_1000  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2020.12.5            h033912b_0    conda-forge
cachetools                4.2.1                    pypi_0    pypi
catalogue                 2.0.1                    pypi_0    pypi
catboost                  0.25.1                   pypi_0    pypi
certifi                   2020.12.5        py38h50d1736_1    conda-forge
cffi                      1.14.3           py38hed5b41f_0  
chardet                   3.0.4                 py38_1003  
cheroot                   8.5.2                    pypi_0    pypi
click                     7.1.2                      py_0  
cloudpickle               1.6.0                      py_0  
clyent                    1.2.2                    py38_1  
colorama                  0.4.4                      py_0  
colorful                  0.5.4                    pypi_0    pypi
conda                     4.10.1           py38h50d1736_0    conda-forge
conda-build               3.20.5                   py38_1  
conda-env                 2.6.0                         1  
conda-package-handling    1.7.2            py38h22f3db7_0  
conda-verify              3.4.2                      py_1  
contextlib2               0.6.0.post1                py_0  
coverage                  5.5                      pypi_0    pypi
cryptography              3.1.1            py38hddc9c9b_0  
cssutils                  1.0.2                    pypi_0    pypi
curl                      7.71.1               hb0a8c7a_1  
cycler                    0.10.0                   py38_0  
cymem                     2.0.5                    pypi_0    pypi
cython                    0.29.21          py38hb1e8313_0  
cytoolz                   0.11.0           py38haf1e3a3_0  
dash                      1.17.0                   pypi_0    pypi
dash-bootstrap-components 0.9.1                    pypi_0    pypi
dash-colorscales          0.0.4                    pypi_0    pypi
dash-core-components      1.13.0                   pypi_0    pypi
dash-daq                  0.5.0                    pypi_0    pypi
dash-html-components      1.1.1                    pypi_0    pypi
dash-renderer             1.8.3                    pypi_0    pypi
dash-table                4.11.0                   pypi_0    pypi
dask                      2.30.0                     py_0  
dask-core                 2.30.0                     py_0  
databricks-cli            0.14.3                   pypi_0    pypi
dataclasses               0.7                      py38_0  
dbus                      1.13.18              h18a8e69_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
deprecated                1.2.11                   pypi_0    pypi
diff-match-patch          20200713                   py_0  
dill                      0.3.3                    pypi_0    pypi
distlib                   0.3.1                    pypi_0    pypi
distributed               2.30.1           py38hecd8cb5_0  
docker                    4.4.4                    pypi_0    pypi
docutils                  0.16                     py38_1  
dotmap                    1.3.23                   pypi_0    pypi
dtale                     1.43.0                   pypi_0    pypi
einops                    0.3.0                    pypi_0    pypi
elastic-apm               6.0.0                    pypi_0    pypi
elasticsearch             7.10.0                   pypi_0    pypi
entrypoints               0.3                      py38_0  
et_xmlfile                1.0.1                   py_1001  
expat                     2.2.10               hb1e8313_2  
faiss-cpu                 1.6.3                    pypi_0    pypi
farm                      0.6.2                    pypi_0    pypi
farm-haystack             0.7.0                    pypi_0    pypi
fastapi                   0.63.0                   pypi_0    pypi
fastcache                 1.1.0            py38h1de35cc_0  
filelock                  3.0.12                     py_0  
filetype                  1.0.7                    pypi_0    pypi
fire                      0.4.0                    pypi_0    pypi
flair                     0.8                      pypi_0    pypi
flake8                    3.8.4                      py_0  
flask                     1.1.2                      py_0  
flask-babel               1.0.0                    pypi_0    pypi
flask-caching             1.10.1                   pypi_0    pypi
flask-compress            1.9.0                    pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
flask-ngrok               0.0.25                   pypi_0    pypi
flask-restplus            0.13.0                   pypi_0    pypi
flask-themes2             0.1.5                    pypi_0    pypi
freetype                  2.10.4               ha233b18_0  
fsspec                    0.8.3                      py_0  
ftfy                      5.9                      pypi_0    pypi
future                    0.18.2                   py38_1  
fuzzywuzzy                0.18.0                   pypi_0    pypi
gdown                     3.12.2                   pypi_0    pypi
gensim                    3.8.3                    pypi_0    pypi
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             hb0f4f8b_2  
gevent                    20.9.0           py38haf1e3a3_0  
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.14                   pypi_0    pypi
glib                      2.66.1               h9bbe63b_0  
glob2                     0.7                        py_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py38h6ef4df4_3  
google-api-core           1.26.2                   pypi_0    pypi
google-auth               1.28.0                   pypi_0    pypi
googleapis-common-protos  1.53.0                   pypi_0    pypi
gpustat                   0.6.0                    pypi_0    pypi
greenlet                  0.4.17           py38haf1e3a3_0  
grpcio                    1.36.1                   pypi_0    pypi
gunicorn                  20.0.4                   pypi_0    pypi
h11                       0.12.0                   pypi_0    pypi
h5py                      2.10.0           py38h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
heapdict                  1.0.1                      py_0  
hiredis                   2.0.0                    pypi_0    pypi
html5lib                  1.1                        py_0  
httptools                 0.1.1                    pypi_0    pypi
huggingface-hub           0.0.6                    pypi_0    pypi
hydra-core                1.0.6                    pypi_0    pypi
hyperopt                  0.2.5                    pypi_0    pypi
icu                       58.2                 h0a44026_3  
idna                      2.10                       py_0  
imageio                   2.9.0                      py_0  
imagesize                 1.2.0                      py_0  
importlib-metadata        2.0.0                      py_1  
importlib-resources       5.1.2                    pypi_0    pypi
importlib_metadata        2.0.0                         1  
iniconfig                 1.1.1                      py_0  
intel-openmp              2019.4                      233  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.19.0           py38h01d92e1_0  
ipython_genutils          0.2.0                    py38_0  
ipywidgets                7.5.1                      py_1  
isodate                   0.6.0                    pypi_0    pypi
isort                     5.6.4                      py_0  
itsdangerous              1.1.0                      py_0  
janome                    0.4.1                    pypi_0    pypi
jaraco-functools          3.3.0                    pypi_0    pypi
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4.1                      py_0  
jedi                      0.17.1                   py38_0  
jinja2                    2.11.2                     py_0  
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.0.0                    pypi_0    pypi
jpeg                      9b                   he5867d9_2  
js2py                     0.71                     pypi_0    pypi
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py38_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py38_0  
jupyterlab                2.2.6                      py_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         1.2.0                      py_0  
kaleido                   0.2.1                    pypi_0    pypi
kaptan                    0.5.12                   pypi_0    pypi
keyring                   21.4.0                   py38_1  
kiwisolver                1.3.0            py38h23ab428_0  
konoha                    4.6.3                    pypi_0    pypi
krb5                      1.18.2               h75d18d8_0  
langdetect                1.0.8                    pypi_0    pypi
lazy-object-proxy         1.4.3            py38h1de35cc_0  
lazypredict               0.2.9                    pypi_0    pypi
lcms2                     2.11                 h92f6f08_0  
libarchive                3.4.2                haa3ed63_0  
libcurl                   7.71.1               h8a08a2b_1  
libcxx                    11.0.1               habf9029_0    conda-forge
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.16                 h1de35cc_0  
liblief                   0.10.1               h0a44026_0  
libllvm10                 10.0.1               h76017ad_5  
libllvm9                  9.0.1                h223d4b2_3    conda-forge
libpng                    1.6.37               ha441bb4_0  
libprotobuf               3.13.0.1             hab81aa3_0  
libsodium                 1.0.18               h1de35cc_0  
libspatialindex           1.9.3                h0a44026_0  
libssh2                   1.9.0                ha12b0ac_1  
libtiff                   4.1.0                hcb84e12_1  
libtmux                   0.8.5                    pypi_0    pypi
libuv                     1.40.0               haf1e3a3_0  
libxgboost                1.3.3                he49afe7_0    conda-forge
libxml2                   2.9.10               h7cdb67c_3  
libxslt                   1.1.34               h83b36ba_0  
lightgbm                  3.2.1                    pypi_0    pypi
llvm-openmp               11.0.1               h7c73e74_0    conda-forge
llvmlite                  0.34.0           py38h739e7dc_4  
locket                    0.2.0                    py38_1  
logger                    1.4                      pypi_0    pypi
lxml                      4.5.0                    pypi_0    pypi
lz4                       3.1.3                    pypi_0    pypi
lz4-c                     1.9.2                h79c402e_3  
lzo                       2.10                 haf1e3a3_2  
mako                      1.1.4                    pypi_0    pypi
markupsafe                1.1.1            py38h1de35cc_1  
matplotlib                3.3.2                         0  
matplotlib-base           3.3.2            py38h181983e_0  
mccabe                    0.6.1                    py38_1  
missingno                 0.4.2                    pypi_0    pypi
mistune                   0.8.4           py38h1de35cc_1001  
mkl                       2019.4                      233  
mkl-service               2.3.0            py38hfbe908c_0  
mkl_fft                   1.2.0            py38hc64f4ea_0  
mkl_random                1.1.1            py38h959d312_0  
mlflow                    1.13.1                   pypi_0    pypi
mock                      4.0.2                      py_0  
modin                     0.9.1                    pypi_0    pypi
more-itertools            8.6.0              pyhd3eb1b0_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.2                h9066e36_1  
mpld3                     0.3                      pypi_0    pypi
mpmath                    1.1.0                    py38_0  
msgpack-python            1.0.0            py38h04f5b5a_1  
msrest                    0.6.21                   pypi_0    pypi
multidict                 5.1.0                    pypi_0    pypi
multipledispatch          0.6.0                    py38_0  
multiprocess              0.70.11.1                pypi_0    pypi
murmurhash                1.0.5                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
navigator-updater         0.2.1                    py38_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.4.2              pyhd3eb1b0_0  
networkx                  2.5                        py_0  
ninja                     1.10.2           py38hf7b0b51_0  
nltk                      3.5                        py_0  
nose                      1.3.7                 py38_1004  
notebook                  6.1.4                    py38_0  
numba                     0.51.2           py38h6440ff4_1  
numexpr                   2.7.1            py38hce01a72_0  
numpy                     1.19.1                   pypi_0    pypi
numpy-base                1.19.2           py38hcfb5961_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
nvidia-ml-py3             7.352.0                  pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0  
omegaconf                 2.0.6                    pypi_0    pypi
opencensus                0.7.12                   pypi_0    pypi
opencensus-context        0.1.2                    pypi_0    pypi
openpyxl                  3.0.5                      py_0  
openssl                   1.1.1k               h0d85af4_0    conda-forge
overrides                 3.1.0                    pypi_0    pypi
packaging                 20.4                       py_0  
pandas                    1.0.5                    pypi_0    pypi
pandoc                    2.11                 h0dc7051_0  
pandocfilters             1.4.3            py38hecd8cb5_1  
papermill                 2.3.2                    pypi_0    pypi
parso                     0.7.0                      py_0  
partd                     1.1.0                      py_0  
path                      15.0.0                   py38_0  
path.py                   12.5.0                        0  
pathlib2                  2.3.5                    py38_1  
pathos                    0.2.5                    pypi_0    pypi
pathspec                  0.8.1                    pypi_0    pypi
pathtools                 0.1.2                      py_1  
pathy                     0.4.0                    pypi_0    pypi
patsy                     0.5.1                    py38_0  
pcre                      8.44                 hb1e8313_0  
pep8                      1.7.1                    py38_0  
pexpect                   4.8.0                    py38_1  
pickleshare               0.7.5                 py38_1001  
pillow                    8.0.1            py38h5270095_0  
pip                       20.2.4                   py38_0    anaconda
pkginfo                   1.6.1            py38hecd8cb5_0  
plotly                    4.12.0                   pypi_0    pypi
pluggy                    0.13.1                   py38_0  
ply                       3.11                     py38_0  
pox                       0.2.9                    pypi_0    pypi
ppft                      1.6.6.3                  pypi_0    pypi
ppscore                   1.2.0                    pypi_0    pypi
preshed                   3.0.5                    pypi_0    pypi
prometheus-flask-exporter 0.18.1                   pypi_0    pypi
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
protobuf                  3.13.0.1         py38hb1e8313_1  
psutil                    5.7.2            py38haf1e3a3_0  
psycopg2-binary           2.8.6                    pypi_0    pypi
ptyprocess                0.6.0                    py38_0  
py                        1.9.0                      py_0  
py-lief                   0.10.1           py38haf313ee_0  
py-spy                    0.3.5                    pypi_0    pypi
py-xgboost                1.3.3            py38h50d1736_0    conda-forge
pyarrow                   1.0.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pybind11                  2.6.2                    pypi_0    pypi
pycodestyle               2.6.0                      py_0  
pycosat                   0.6.3            py38h1de35cc_1  
pycparser                 2.20                       py_2  
pycurl                    7.43.0.6         py38hddc9c9b_0  
pydantic                  1.7.3                    pypi_0    pypi
pydocstyle                5.1.1                      py_0  
pyflakes                  2.2.0                      py_0  
pygments                  2.7.2              pyhd3eb1b0_0  
pyjarowinkler             1.8                      pypi_0    pypi
pyjsparser                2.7.1                    pypi_0    pypi
pylint                    2.6.0                    py38_0  
pyload-ng                 0.5.0a9.dev806           pypi_0    pypi
pymupdf                   1.18.6                   pypi_0    pypi
pynvim                    0.4.3                    pypi_0    pypi
pyodbc                    4.0.30           py38h0a44026_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38h655552a_2  
pyrsistent                0.17.3           py38haf1e3a3_0  
pysocks                   1.7.1                    py38_1  
pytables                  3.6.1            py38h4727e94_0  
pytest                    5.4.3                    pypi_0    pypi
python                    3.8.5                h26836e1_1  
python-dateutil           2.8.1                      py_0  
python-docx               0.8.10                   pypi_0    pypi
python-editor             1.0.4                    pypi_0    pypi
python-graphviz           0.16                     pypi_0    pypi
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.35.1                     py_0  
python-levenshtein        0.12.2                   pypi_0    pypi
python-libarchive-c       2.9                        py_0  
python-multipart          0.0.5                    pypi_0    pypi
python-telegram           0.14.0                   pypi_0    pypi
python.app                2                       py38_10  
python_abi                3.8                      1_cp38    huggingface
pytorch                   1.7.1                   py3.8_0    pytorch
pytorch-pretrained-biggan 0.1.1                    pypi_0    pypi
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py38haf1e3a3_2  
pyyaml                    5.3.1            py38haf1e3a3_1  
pyzmq                     19.0.2           py38hb1e8313_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 1.0.1                      py_0  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
querystring-parser        1.2.4                    pypi_0    pypi
ranger-fm                 1.9.3                    pypi_0    pypi
ray                       1.1.0                    pypi_0    pypi
readline                  8.0                  h1de35cc_0  
redis                     3.5.3                    pypi_0    pypi
regex                     2020.10.15       py38haf1e3a3_0  
requests                  2.24.0                     py_0  
requests-oauthlib         1.3.0                    pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
ripgrep                   12.1.1                        0  
rope                      0.18.0                     py_0  
rsa                       4.7.2                    pypi_0    pypi
rtree                     0.9.4                    py38_1  
ruamel_yaml               0.15.87          py38haf1e3a3_1  
s3transfer                0.3.4                    pypi_0    pypi
sacremoses                master                     py_0    huggingface
scikit-image              0.17.2           py38h81aa140_0  
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
seaborn                   0.11.1                   pypi_0    pypi
segtok                    1.5.10                   pypi_0    pypi
semver                    2.13.0                   pypi_0    pypi
send2trash                1.5.0                    py38_0  
sentence-transformers     0.4.1.2                  pypi_0    pypi
sentencepiece             0.1.95                   pypi_0    pypi
seqeval                   1.2.2                    pypi_0    pypi
setuptools                50.3.1           py38hecd8cb5_1  
shap                      0.37.0                   pypi_0    pypi
shapash                   1.3.2                    pypi_0    pypi
simplegeneric             0.8.1                    py38_2  
simplejson                3.17.2                   pypi_0    pypi
singledispatch            3.4.0.3                 py_1001  
sip                       4.19.8           py38h0a44026_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sklearn                   0.0                      pypi_0    pypi
skorch                    0.9.0                    pypi_0    pypi
slicer                    0.0.3                    pypi_0    pypi
smart-open                3.0.0                    pypi_0    pypi
smmap                     3.0.5                    pypi_0    pypi
snappy                    1.1.8                hb1e8313_3    conda-forge
snowballstemmer           2.0.0                      py_0  
sortedcollections         1.2.1                      py_0  
sortedcontainers          2.2.2                      py_0  
soupsieve                 2.0.1                      py_0  
spacy                     3.0.3                    pypi_0    pypi
spacy-legacy              3.0.1                    pypi_0    pypi
sphinx                    3.2.1                      py_0  
sphinxcontrib             1.0                      py38_1  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
sphinxcontrib-websupport  1.2.4                      py_0  
spyder                    4.1.5                    py38_0  
spyder-kernels            1.9.4                    py38_0  
sqlalchemy                1.3.20           py38h9ed2024_0  
sqlalchemy-utils          0.36.8                   pypi_0    pypi
sqlite                    3.33.0               hffcf06c_0  
sqlitedict                1.7.0                    pypi_0    pypi
sqlparse                  0.4.1                    pypi_0    pypi
squarify                  0.4.3                    pypi_0    pypi
srsly                     2.4.0                    pypi_0    pypi
ssttp-code                1.0.0                     dev_0    <develop>
starlette                 0.13.6                   pypi_0    pypi
statsmodels               0.12.0           py38haf1e3a3_0  
strsimpy                  0.2.0                    pypi_0    pypi
sympy                     1.6.2            py38hecd8cb5_1  
tabulate                  0.8.7                    pypi_0    pypi
tbb                       2021.1.1             h940c156_0    conda-forge
tblib                     1.7.0                      py_0  
tenacity                  7.0.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.1                    py38_0  
testpath                  0.4.4                      py_0  
textwrap3                 0.9.2                    pypi_0    pypi
tg                        0.17.0                   pypi_0    pypi
thinc                     8.0.1                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tifffile                  2020.10.1        py38h0cf3a3e_2  
tika                      1.24                     pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0  
tmuxp                     1.7.2                    pypi_0    pypi
tokenizers                0.9.4                    py38_0    huggingface
toml                      0.10.1                     py_0  
toolz                     0.11.1                     py_0  
torchaudio                0.7.2                      py38    pytorch
torchvision               0.8.2                  py38_cpu    pytorch
tornado                   6.0.4            py38h1de35cc_1  
tox                       3.23.0                   pypi_0    pypi
tqdm                      4.56.0                   pypi_0    pypi
traitlets                 5.0.5                      py_0  
transformers              4.1.1              pyh39e3cac_0    huggingface
typer                     0.3.2                    pypi_0    pypi
typing_extensions         3.7.4.3                    py_0  
tzlocal                   2.1                      pypi_0    pypi
ujson                     4.0.1            py38hb1e8313_0  
unicodecsv                0.14.1                   py38_0  
unixodbc                  2.3.9                haf1e3a3_0  
urllib3                   1.25.11                    py_0  
uvicorn                   0.13.4                   pypi_0    pypi
uvloop                    0.15.2                   pypi_0    pypi
virtualenv                20.4.3                   pypi_0    pypi
visidata                  2.3                      pypi_0    pypi
wasabi                    0.8.2                    pypi_0    pypi
watchdog                  0.10.3           py38haf1e3a3_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
websocket-client          0.58.0                   pypi_0    pypi
werkzeug                  0.16.1                   pypi_0    pypi
wheel                     0.36.2                   pypi_0    pypi
widgetsnbextension        3.5.1                    py38_0  
wrapt                     1.11.2           py38h1de35cc_0  
wurlitzer                 2.0.1                    py38_0  
xarray                    0.17.0                   pypi_0    pypi
xgboost                   1.3.3            py38h50d1736_0    conda-forge
xlrd                      1.2.0                      py_0  
xlsxwriter                1.3.7                      py_0  
xlwings                   0.20.8                   py38_0  
xlwt                      1.3.0                    py38_0  
xmltodict                 0.12.0                     py_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
yapf                      0.30.0                     py_0  
yarl                      1.6.3                    pypi_0    pypi
zeromq                    4.3.3                hb1e8313_3  
zict                      2.0.0                      py_0  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h1de35cc_3  
zope                      1.0                      py38_1  
zope.event                4.5.0                    py38_0  
zope.interface            5.1.2            py38haf1e3a3_0  
zstd                      1.4.5                h41d2c2f_0

**Comment by ChristianChiarulli** [comment]
what about another env other than base? do they also not work?

**Comment by abzcoding** [comment]
@ChristianChiarulli  why is `efm` is enabled and showing in the bottom left corner?
shouldn't only `pyright` be used here?

**Comment by mjlbach** [comment]
Did you active the virtual environment *before* starting neovim?

**Comment by adarshchbs** [comment]
> what about another env other than base? do they also not work?

It is same for other env too.

**Comment by adarshchbs** [comment]
> Did you active the virtual environment _before_ starting neovim?

yes, I did.

**Comment by Uzaaft** [comment]
@adarshchbs Could you make the conda list output collapsable?

**Comment by Uzaaft** [comment]
I cant replicate the problem on macOS or Ubuntu(VM).
Have you configured your LunarVim with any custom settings besides a fresh install? If so, could you provide a screenshot or a gist of the python section of any custom settings?

**Comment by adarshchbs** [comment]
> I cant replicate the problem on macOS or Ubuntu(VM).
> Have you configured your LunarVim with any custom settings besides a fresh install? If so, could you provide a screenshot or a gist of the python section of any custom settings?

<img width="544" alt="Screenshot 2021-07-12 at 11 06 20 AM" src="https://user-images.githubusercontent.com/38124313/125236272-4e1e1980-e301-11eb-80b8-36c8fe531cf7.png">

I have only configured it this much. Without it nvim was not choosing the correct env.

**Comment by abzcoding** [comment]
@adarshchbs, can you test this again using the `rolling` branch? We've changed quite a bit since then.

**Comment by adarshchbs** [comment]
Resolved the issue. It was mainly because of python clash from homebrew and conda. I solved it by removing the conda env whenever brew is running by including this script in my .zshrc.
`
brew() {
    local -a conda_envs
    while [ "$CONDA_SHLVL" -gt 0  ]; do
        conda_envs=("$CONDA_DEFAULT_ENV" $conda_envs)
        conda deactivate
    done
    command brew $@
    local brew_status=$?
    for env in $conda_envs; do
        conda activate "$env"
    done
    unset env
    return "$brew_status"
}
`
followed by uninstalling nvim and reinstalling is agian using brew.
