### ISSUE TITLE
filetype unknown randomly appears

### ISSUE THREAD

**Issue by abzcoding** [ChristianChiarulli/LunarVim#822]
sometimes while searching with `telescope` a `filetype unknown` error appears, we need to find the root cause and address it
![file-type](https://user-images.githubusercontent.com/10992695/125124003-ae983580-e10c-11eb-8315-bf7c5d8e43bd.png)

**Comment by ChristianChiarulli** [comment]
@abzcoding that's gotta be an auto command somewhere, I've noticed this as well.

**Comment by abzcoding** [comment]
> @abzcoding that's gotta be an auto command somewhere, I've noticed this as well.

I thought this is the culprit, since it should be `FTerm` instead of `floaterm`
```lua
-- line 88 inside lua/lv-utils/init.lua
{ "FileType", "floaterm", "nnoremap <silent> <buffer> q :q<CR>" },
```
but it was not :sob:

**Comment by ChristianChiarulli** [comment]
maybe check the issues on treesitter and telescope

**Comment by IvanAquino** [comment]
i had that problem with channel stable and when i change to master with new installer i didn't happend again

**Comment by abzcoding** [comment]
> i had that problem with channel stable and when i change to master with new installer i didn't happend again

Sadly it still happens at random.

**Comment by ChristianChiarulli** [comment]
for me it's when ever I am about to select a file with a filetype eg .lua, .py, .json etc...

**Comment by jameswalmsley** [comment]
I was going through the NeoFormat code the other day.. and I have a feeling this message comes from NeoFormat.

I think its buffers like telescope and dashboard that cause it.

**Comment by johanronkko** [comment]
I don't use the floating window plugin and still got this message everytime I open telescope.

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/issues/1033

**Comment by Conni2461** [comment]
This bug should be fixed in the latest telescope version

**Comment by abzcoding** [comment]
Fixed via [this](https://github.com/nvim-telescope/telescope.nvim/pull/1034)
