### ISSUE TITLE
[Bug]: Confusing lazygit configuration documentation

### ISSUE THREAD

**Issue by gikari** [ChristianChiarulli/LunarVim#835]
### Problem description

Open [this](https://github.com/ChristianChiarulli/LunarVim/wiki/Installing-Plugins) wiki page. It implies, that `lazygit` can be  enabled with
```lua
O.plugin.lazygit.active = true
```

However, on the stable branch the `lazygit` integration is enabled via `floatterm` plugin, which is not listed in the wiki, and using the above option breaks the configuration. Also, it is not obvious, that by enabling `floatterm` plugin, you also enable `lazygit`. Maybe we can add a comment in the default config about the fact, that `lazygit` is one of the preconfigured options for `floatterm`?

I assume the wiki documents the stable branch.

### LunarVim version

stable

### Neovim version (>= 0.5)

NVIM v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
@gikari nice catch :eyes: , updated the page
