### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shinze** [ChristianChiarulli/LunarVim#836]
### Problem description

On an Intel Macbook Pro.
Nvim and LunarVim where ok, until I did an update last night.
Here is what I did to update to the latest version

```shell
rm -rf ~/.config/nvim
cd ~/.config
bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)
```

And here is the message I had

```shell
Installing LunarVim
pip installed, moving on...
node installed, moving on...
pynvim installed, moving on...
packer already installed
Cloning LunarVim configuration
Clonage dans '/Users/gaetan.ark/.config/nvim'...
remote: Enumerating objects: 6811, done.
remote: Counting objects: 100% (414/414), done.
remote: Compressing objects: 100% (195/195), done.
remote: Total 6811 (delta 241), reused 329 (delta 206), pack-reused 6397
Réception d'objets: 100% (6811/6811), 10.10 Mio | 15.97 Mio/s, fait.
Résolution des deltas: 100% (3982/3982), fait.
OK to remove? [y/N] OK to remove? [y/N] y
```

I tried [y] and nothing for 15 minutes, the console stopped here, no more log. Tried [N] too, same problem.

### LunarVim version

Latest

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+28-g1c4168928

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
First [uninstall](https://github.com/ChristianChiarulli/LunarVim/wiki/Uninstalling-LunarVim) LunarVim properly
then try again, if the problem still there react to this message with :facepalm: and if the problem is fixed react with :rocket:

**Comment by shinze** [comment]
Thank you ! I just did the manual installation process and figured out my mistake. Could be a good idea to show that in the update process documentation.

**Comment by abzcoding** [comment]
@shinze what happened? I thought the issue was fixed

**Comment by shinze** [comment]
Well I was a bit fast, I tried again as my manual installation wasn’t right.

1. Did all the steps to uninstall LunarVim properly;
2. Tried again to install via the bash script and got the same message and a blocked shell.

**Comment by abzcoding** [comment]
> Well I was a bit fast, I tried again as my manual installation wasn’t right.
> 
>     1. Did all the steps to uninstall LunarVim properly;
> 
>     2. Tried again to install via the bash script and got the same message and a blocked shell.

I'm gonna do PR in a couple of minutes, hopefully, that fixes this issue :rocket:

**Comment by abzcoding** [comment]
> Well I was a bit fast, I tried again as my manual installation wasn’t right.
> 
>     1. Did all the steps to uninstall LunarVim properly;
> 
>     2. Tried again to install via the bash script and got the same message and a blocked shell.

@shinze can you test if this fixes the issue or not

```bash
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim/pack/packer
rm -rf ~/.cache/nvim
bash <(curl -s https://github.com/abzcoding/LunarVim/blob/hotfix/mac-installation-issue/utils/installer/install.sh)
```

**Comment by shinze** [comment]
```shell
/dev/fd/11: line 7: syntax error near unexpected token `newline'
/dev/fd/11: line 7: `<!DOCTYPE html>'
```

I changed the URL you gave me by using the raw file : https://raw.githubusercontent.com/abzcoding/LunarVim/hotfix/mac-installation-issue/utils/installer/install.sh

But got this message

```shell
/Users/shinze/.local/share/nvim/site/pack/packer/start/packer.nvim folder already exists…
```

**Comment by abzcoding** [comment]
> ```shell
> /dev/fd/11: line 7: syntax error near unexpected token `newline'
> /dev/fd/11: line 7: `<!DOCTYPE html>'
> ```
> 
> I changed the URL you gave me by using the raw file : https://raw.githubusercontent.com/abzcoding/LunarVim/hotfix/mac-installation-issue/utils/installer/install.sh
> 
> But got this message
> 
> ```shell
> /Users/shinze/.local/share/nvim/site/pack/packer/start/packer.nvim folder already exists…
> ```

can you run the whole thing (all 4 commands):
```bash
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim/pack/packer
rm -rf ~/.cache/nvim
bash <(curl -s https://raw.githubusercontent.com/abzcoding/LunarVim/hotfix/mac-installation-issue/utils/installer/install.sh)
```

**Comment by shinze** [comment]
I have the same error message telling me that *.local/share/nvim/site/pack/packer/start/packer.nvim* already exists an is not empty.

**Comment by lakshyarao22** [comment]
Tried running 
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim/pack/packer
rm -rf ~/.cache/nvim
bash <(curl -s https://raw.githubusercontent.com/abzcoding/LunarVim/hotfix/mac-installation-issue/utils/installer/install.sh)

still stuck on same

**Comment by abzcoding** [comment]
> Tried running
> rm -rf ~/.config/nvim
> rm -rf ~/.local/share/nvim/pack/packer
> rm -rf ~/.cache/nvim
> bash <(curl -s https://raw.githubusercontent.com/abzcoding/LunarVim/hotfix/mac-installation-issue/utils/installer/install.sh)
> 
> still stuck on same

@lakshyarao22 @shinze 
try this one maybe 🤔 
```bash
rm -rf ~/.config/nvim && rm -rf ~/.local/share/nvim/site/pack/packer && rm -rf ~/.cache/nvim && bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/LunarVim/master/utils/installer/install.sh)
```

**Comment by shinze** [comment]
Thank you ! The last command seems to fix the issue.
