### ISSUE TITLE
[Bug]: Navigating to a .png file fucks up the whole config.

### ISSUE THREAD

**Issue by johanronkko** [ChristianChiarulli/LunarVim#842]
### Problem description

Reproduce:
Telescope into, or navigate via nvimtree, to a .png file.

Error output:
* `Error detected while processing CursorMoved Autocommands for "*":`
* `Error executing vim.schedule lua callback: Vim:E731: using Dictionary as a String`.

After error messages the neovim session is basically unusable. Running <leader>e don't open nvimtree but creates another window with the the .png file copied over it to. Telescope doesn't work properly.

### LunarVim version

Running my own version with BufferLine instead of barbar, but have been keeping up with the commits for weeks

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+1476-g62d67de59

### Relevant log output

```shell
nvim -v:

`NVIM v0.6.0-dev+1476-g62d67de59
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-53531-1mbzyyf/build/config -I/tmp/neovim-20210702-53531-1mbzyyf/src -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210702-53531-1mbzyyf/build/src/nvim/auto -I/tmp/neovim-20210702-53531-1mbzyyf/build/include
Compiled by johanronkko@j

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-62d67de/share/nvim"

Run :checkhealth for more info`
```

### Screenshots

<img width="950" alt="Screenshot 2021-07-10 at 18 09 48" src="https://user-images.githubusercontent.com/16175775/125169360-118bda00-e1aa-11eb-9d0a-463c55793f0e.png">
<img width="1419" alt="Screenshot 2021-07-10 at 18 09 58" src="https://user-images.githubusercontent.com/16175775/125169361-1486ca80-e1aa-11eb-9e8c-89180a3f71c6.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by johanronkko** [comment]
Also, really appreciate the LunarVim community. It has been a great experience and I've learned so much the past months following the project.

**Comment by williamgoulois** [comment]
Why would you want to open jpg or png files inside of neovim ? If you want to preview images in telescope here is what to do :

1. add to `lv-config` this plugin : { 'nvim-telescope/telescope-media-files.nvim' } under O.user_plugins table
2. in `lua/lv-telescope/config.lua` you can add to extensions table :

```lua
extensions = {
  -- 
  media_files = {
        -- filetypes whitelist
        -- defaults to {"png", "jpg", "mp4", "webm", "pdf"}
        filetypes = {"png", "webp", "jpg", "jpeg"},
        find_cmd = "rg" -- find command (defaults to `fd`)
      }
  },
}
```

**Comment by williamgoulois** [comment]
@ChristianChiarulli maybe we could merge extensions object in `lv-config` with the one in `lv-telescope/config.lua` because at the moment it is an override if you use `O.plugin.telescope.extensions`

**Comment by johanronkko** [comment]
Thanks for the input! Viewing images in neovim like you can in vscode would be a nice feature, but is not really something I care about. I accidentally navigated to the png file and because everything stopped working I had to restart neovim, which was quite annoying. This is of course a minor issue.

**Comment by rafamadriz** [comment]
Closing this since it's not an issue with LunarVim.

@johanronkko the best you can do for previewing images inside neovim is doing what @williamgoulois suggested.
