### ISSUE TITLE
[Feature]: Set nvim_tree_hide_dotfiles to 0 by default or let the users configure it

### ISSUE THREAD

**Issue by gikari** [ChristianChiarulli/LunarVim#843]
### Feature motivation

Since this project is meant to be used for coding, I believe it is better to let this option be off. This is because many projects have a lot of important dotfiles inside. For example (for my particular project): `.clang-format`, `.clang-tidy`, `.gitignore`, `.gitlab-ci.yml` and others. Also, VSCode and JetBrains IDEs show all hidden files and folders by default, so that's what the users will expect.

### Describe the expected solution

Turn the option off in `lv-nvimtree/init.lua`:
```lua
  g.nvim_tree_hide_dotfiles = 0
```

### Describe the alternatives you've considered

I understand, that this maybe opinionated, that's why one of the desired solutions is allowance for configuring it in `lv-config.lua` like this:
```lua
O.plugin.nvim_tree.hide_dotfiles = 0
```

**Comment by abzcoding** [comment]
There is a [PR](https://github.com/ChristianChiarulli/LunarVim/pull/769/files#diff-cfddaa3f8ed5ab885db6935e98d47ff5594f1287971d5da00e36fb3f479a16dcR24) for this

**Comment by abzcoding** [comment]
@gikari this has been added to `rolling` branch

add this to your `lv-config.lua`

```lua
O.plugin.nvimtree.hide_dotfiles = 0
```
