### ISSUE TITLE
[Feature]: customisable keymappings

### ISSUE THREAD

**Issue by Soziopath** [ChristianChiarulli/LunarVim#844]
### Feature motivation

It would be nice if you could implement customisable keymappings for dashboard and comment.
Since i'm on a qwertz keyboard its kinda awkward to be pressing "/" or ";".

Really loving Lunarvim so far.
Thanks for all your contribution.

### Describe the expected solution

I would rather be able to map comment to "-" and dashboard to ","

**Comment by AndersNS** [comment]
Should be possible to do this for you now, on rolling branch since #813 is merged

**Comment by Soziopath** [comment]
im not quite sure how to change it now. am i doing:
`O.plugin.which_key.vmappings = {
  ["-"] = { ":CommentToggle<CR>", "Comment" },
}`
in lv-config.lua now for example?

**Comment by Soziopath** [comment]
ok got it now. but i do have to place the complete mappings in lv-config.lua if i want to overwrite one specific mapping.

**Comment by Soziopath** [comment]
was kinda confusing at first but i got it now and i dont need the complete mappings in lv-config.lua. was my fault.
`O.plugin.which_key.mappings["/"] = nil
O.plugin.which_key.mappings[";"] = nil
O.plugin.which_key.mappings["-"] = { "<cmd>CommentToggle<CR>", "Comment" }
O.plugin.which_key.mappings[","] = { "<cmd>Dashboard<CR>", "Dashboard" }`
this works fine now.
much thanks
