### ISSUE TITLE
Support custom path for lv-user-config

### ISSUE THREAD

**Issue by rebuilt** [ChristianChiarulli/LunarVim#854]
Read an environment variable such as LUNARVIM_CONFIG_HOME and install user configuration to that directory.  Looking for suggestions for the name of the variable: LV_CONFIG_HOME, LV_CONFIG_PATH

**Comment by roobert** [comment]
Hey Rebuilt, you can do something like this to allow specifying a default:
```
local function lv_config_file()
    local _lv_config_file = os.getenv("LV_CONFIG_PATH")
    local path

    if _lv_config_file == nil then
        path = CONFIG_PATH .. "/lv-config.lua"
    else
        path = _lv_config_file
    end

    return path
end

LV_CONFIG_PATH = lv_config_file()
```

I prefer `PATH` over `HOME` since I think a home directory tends to imply a location that holds multiple files. It would also be great to do the above but for `LV_USER_PATH`.

**Comment by rebuilt** [comment]
lv-user-config does hold multiple files.  This is the example setup for those files.  https://github.com/rebuilt/lv-user-config/tree/master/example

**Comment by roobert** [comment]
@rebuilt in your original message you reference `LV_CONFIG` so I assumed this referenced `lv-config.lua`. If we are talking about `lv-user` then I would use the prefix `LV_USER`. Personally I still prefer `PATH` or `DIR` suffixes for this kind of thing. `HOME` I would expect to be synonymous for `CONFIG_PATH` when talking about LunarVim paths.

**Comment by roobert** [comment]
Updated snippet for `lv-user`:
```
local function lv_user_dir()
    local _lv_user_dir = os.getenv("LV_USER_DIR")
    local path

    if _lv_user_dir == nil then
        path = CONFIG_PATH .. "/lua/lv-user"
    else
        path = _lv_user_dir
    end

    return path
end

LV_USER_DIR = lv_user_dir()
```

**Comment by rebuilt** [comment]
I haven't forgotten about this.   

Now that lv-config lives in its own folder, do you still see a use case for specifying your own custom path?   

If you can still see a need for this, it should probably be in a pr.  After the `new_contract` branch gets merged, can you submit a pull request for this so Chris can decide if it should be in version 1.0 or not?  Thanks.  

If you can't see a use case for this anymore, I'll close this issue.

**Comment by roobert** [comment]
Hi @rebuilt - I think this can probably be closed, however, I think the install script needs updating to avoid overwriting `.config/lvim/lv-config.lua` if it's re-run to upgrade LunarVim.

**Comment by rebuilt** [comment]
Thanks for the reminder on the installer bug.

**Comment by rebuilt** [comment]
No longer needed now that lv-config is in it's own folder

**Comment by rebuilt** [comment]
lvim --headless +'lua require("lv-utils").generate_settings()' +qa && sort -o lv-settings.lua{,}
