### ISSUE TITLE
resize window keybinding not work on my Mac

### ISSUE THREAD

**Issue by rmGFW** [ChristianChiarulli/LunarVim#86]
nnoremap <silent> <C-Up>    :resize -2<CR>
  nnoremap <silent> <C-Down>  :resize +2<CR>
  nnoremap <silent> <C-Left>  :vertical resize -2<CR>
  nnoremap <silent> <C-Right> :vertical resize +2<CR>

all this not work on my Mac (MacBook Pro 16inch 

I press the arrow key with the Ctrl hold ,but the window size doesn't change💔 help !!!!!!!!🙏

**Comment by ChristianChiarulli** [comment]
looking into this, just noticed this

**Comment by jordisantamaria** [comment]
You have to configure terminal to accept alt key, in mac is disabled by default.
In iterm2 you configure It here, the option of Esc+.
 
![スクリーンショット 2021-03-14 14 08 11](https://user-images.githubusercontent.com/6263700/111057993-bf25ff80-84ce-11eb-9dc7-10c1e59ffa01.png)

**Comment by luxus** [comment]
Fixed since 0.41 https://github.com/ChristianChiarulli/LunarVim/pull/725

**Comment by abzcoding** [comment]
Closed #86 via #725
