### ISSUE TITLE
[Bug]: ESLint not working

### ISSUE THREAD

**Issue by williamgoulois** [ChristianChiarulli/LunarVim#860]
### Problem description

At the moment ESLint does not work on all javascript like files.

We use [ts-utils](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils) to handle the formatting but it needs [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) to be able to use ESLint.

### Quote of the Readme of ts-utils :

> Requirements
> 
> null-ls for ESLint integrations and formatting (experimental)

### Problem : null-ls is very slow, what solutions can we use ? 
- [diagnosticls-nvim](https://github.com/creativenull/diagnosticls-nvim) **lua**
Better solution IMO. Pretty easy to configure and could maybe lazy loaded only for javascript like filetypes ? A good article with config is [here](https://jose-elias-alvarez.medium.com/configuring-neovims-lsp-client-for-typescript-development-5789d58ea9c)

- [ale](https://github.com/dense-analysis/ale) **vimscript** 
Project with 11k+ stars and listed in eslint website as an integration for eslint
Quote :

> If you don't care about Language Server Protocol, ALE won't load any of the code for working with it unless needed. One of ALE's general missions is that you won't pay for the features that you don't use.

- [syntastic](https://github.com/vim-syntastic/syntastic) **vimscript** 
Project with 10k+ stars and listed in eslint website as an integration for eslint

- efm ? is it too slow compared to diagnosticls or null-ls ?

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+14-gdf33f30e8

### Relevant log output

```shell
No need for logs it worked before with efm.
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
why not efm?

**Comment by williamgoulois** [comment]
It was done before we just removed it i think

**Comment by williamgoulois** [comment]
In fact i just checked and prettier does not need to be configured in efm because we use formatter.nvim now !
I can open a PR to :
- remove prettier from efm 
- add eslint to efm (using variable O.lang.tsserver.linter)

**Comment by ChristianChiarulli** [comment]
yea, idk what we were thinking here? maybe null ls was supposed to handle it? You're PR would be appreciated.
