### ISSUE TITLE
[Bug]: Rust analyzer issues

### ISSUE THREAD

**Issue by reflog** [ChristianChiarulli/LunarVim#869]
### Problem description

1. When opening rust files 'filetype unknown' is displayed
2. 'proc macro server crashed' is displayed (see screenshot)
3. LspInfo shows odd info (see screenshot)

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### Relevant log output

```shell
lsp.log


[ ERROR ] 2021-07-11T12:20:55+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/reflog/.local/share/nvim/lspinstall/rust/rust-analyzer"	"stderr"	"::bridge::client::run_client::{{closure}}\n             at /rustc/a1411de9de38e0fed728874580218338160eb185/library/proc_macro/src/bridge/client.rs:370:9\n  49: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/a1411de9de38e0fed728874580218338160eb185/library/std/src/panic.rs:347:9\n  50: std::panicking::try::do_call\n             at /rustc/a1411de9de38e0fed728874580218338160eb185/library/std/src/panicking.rs:401:40\n  51: __rust_try\n  52: std::panicking::try\n             at /rustc/a1411de9de38e0fed728874580218338160eb185/library/std/src/panicking.rs:365:19\n  53: std::panic::catch_unwind\n             at /rustc/a1411de9de38e0fed728874580218338160eb185/library/std/src/panic.rs:434:14\n  54: proc_macro::bridge::client::run_client\n             at /rustc/a1411de9de38e0fed728874580218338160eb185/library/proc_macro/src/bridge/client.rs:369:5\n  55: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run\n             at /rustc/a1411de9de38e0fed728874580218338160eb185/library/proc_macro/src/bridge/client.rs:410:13\n  56: proc_macro_srv::proc_macro::bridge::server::run_server\n  57: proc_macro_srv::dylib::Expander::expand\n"
[ ERROR ] 2021-07-11T12:20:55+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/reflog/.local/share/nvim/lspinstall/rust/rust-analyzer"	"stderr"	"  58: proc_macro_srv::ProcMacroSrv::expand\n  59: proc_macro_srv::cli::run\n  60: rust_analyzer::main\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
[ ERROR ] 2021-07-11T12:20:55+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/reflog/.local/share/nvim/lspinstall/rust/rust-analyzer"	"stderr"	'[ERROR proc_macro_api::process] proc macro server crashed, server process state: Ok(Some(ExitStatus(ExitStatus(139)))), server request error: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }\n'
```

### Screenshots

![image](https://user-images.githubusercontent.com/109876/125189936-531c9380-e243-11eb-8437-c6531ac45c09.png)
![image](https://user-images.githubusercontent.com/109876/125189941-5adc3800-e243-11eb-94a2-0b2ff716c7fe.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Uzaaft** [comment]
What version of rust and rust-analyzer are you using?

**Comment by abzcoding** [comment]
@reflog can you test it again after pulling the latest changes?
also can you add these lines to your `lv-config.lua`:
```lua
O.lang.rust.rust_tools.active = true
```

**Comment by reflog** [comment]
@Uzaaft :
```
/home/reflog/.local/share/nvim/lspinstall/rust/rust-analyzer --version
rust-analyzer e5c1c8cf2 2021-07-05 stable
```

@abzcoding - pulled in last changes. same result: (though now instead of  'filetype unknown' I see TODO: diff parser)

![image](https://user-images.githubusercontent.com/109876/125595330-94b433ad-4a61-4b7b-8ad1-c19e9049fb28.png)

**Comment by reflog** [comment]
@abzcoding - let me know if I can provide any other info to help debug this

**Comment by abzcoding** [comment]
> @abzcoding - let me know if I can provide any other info to help debug this

Thank you, can you point me toward a sample project (that has the issue) to test it locally?

**Comment by Uzaaft** [comment]
Could you take a backup of your current config, and do a clean install of LunarVim?
After installing, can you do the following:
Run the `:LspInstall rust` command on Neovim

**Comment by Uzaaft** [comment]
I'm using LunarVim in a rust project as we speak, and I've it's working like a charm with the steps I've mentioned above.

**Comment by reflog** [comment]
@abzcoding - https://github.com/reflog/rust-crash-repro

@Uzaaft - thanks, tried that, nuked my config, created lv-config.lua with only 
```
O.lang.rust.rust_tools.active = true
```
did `LspInstall rust`


Same result:
![image](https://user-images.githubusercontent.com/109876/125598278-6e12a93a-23d6-4225-a200-dd8dda536a05.png)

**Comment by Uzaaft** [comment]
Works perfectly fine with my setup:
![image](https://user-images.githubusercontent.com/48220549/125598829-7b757a63-91ef-4498-932d-da4f870daa77.png)

**Comment by abzcoding** [comment]
> @abzcoding - https://github.com/reflog/rust-crash-repro
> 
> @Uzaaft - thanks, tried that, nuked my config, created lv-config.lua with only
> 
> ```
> O.lang.rust.rust_tools.active = true
> ```
> 
> did `LspInstall rust`
> 
> Same result:

I assume this is the expected behavior, but you're getting `proc macro server crashed` instead

![rust](https://user-images.githubusercontent.com/10992695/125598799-f75e7b3c-f688-4c4d-ae8a-4bcc2b6a39c0.png)

**Comment by Uzaaft** [comment]
@reflog Did you wipe the `../share/nvim` folder?
I'm running the 2021-07-12 version, could you see if that's the case for you as well?

**Comment by abzcoding** [comment]
@reflog [this](https://github.com/rust-analyzer/rust-analyzer/issues/8925) is probably your issue,
which is fixed [here](https://github.com/rust-analyzer/rust-analyzer/pull/9550)

**Comment by Uzaaft** [comment]
While you're at it, could you run `rustup update`?

**Comment by reflog** [comment]
@Uzaaft , I did `rustup update` and downloaded the same version of analyzer as you
`rust-analyzer fe0035888 2021-07-12 stable`

Still it crashes :(
```
 ERROR ] 2021-07-14T12:40:46+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/reflog/.local/share/nvim/lspinstall/rust/rust-analyzer"	"stderr"	'[ERROR proc_macro_api::process] proc macro server crashed, server process state: Ok(Some(ExitStatus(ExitStatus(139)))), server request error: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }\n'
```

But I don't think this is anything with LunarVim, so I think we can close this issue. Just have to wait for rust-analyzer to stabilize :(

Thanks for your help though!

**Comment by Uzaaft** [comment]
Yeah I agree. You can go ahead and close it. But I still want to figure out why it behaves different on your machine. 
Are you by any chance running Linux?

**Comment by abzcoding** [comment]
not a LV issue, probably related to [this](https://github.com/rust-analyzer/rust-analyzer/issues/8925) which is [merged](https://github.com/rust-analyzer/rust-analyzer/pull/9550) 20 hours ago

**Comment by reflog** [comment]
@Uzaaft aaaaaaaa. I am a morron. Forgot that I was on nightly :(

Switched to stable - all is great. Thanks again fellas!

**Comment by Uzaaft** [comment]
Dang it! I thought about asking that at the beginning, but I saw that rust-analyser was stable so I assumed everything was all good.
Lesson learnt: Listen to your gut
