### ISSUE TITLE
[Bug]: Prettier not working

### ISSUE THREAD

**Issue by bob3000** [ChristianChiarulli/LunarVim#871]
### Problem description

There seems to be a bug with prettier and formatter.vim
To reproduce press `<leader>lf` while editing a typescript file

### LunarVim version

rolling

### Neovim version (>= 0.5)

v0.6.0-dev+12-gf515baedc

### Relevant log output

```shell
Formatter: failed to run formatter prettier. [error] No parser and no file path given, couldn't infer a parser.
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
@bob3000 can you run `:set filetype=?` and print the output here

**Comment by williamgoulois** [comment]
Got the same error yesterday could you try PackerInstall and PackerCompile ?
Do you have global prettier installation ?

**Comment by bob3000** [comment]
@abzcoding `filetype=typescriptreact`
@williamgoulois Yes, it's a global prettier installation. Unfortunately running packer again didn't help.

I could actually narrow down the error a bit. When I open a typescript file from the command line (like `nvim myfile.ts`) the formatter actually does it's job. It does not work though, if I just enter neovim and then open a file via telescope.

**Comment by abzcoding** [comment]
> @abzcoding `filetype=typescriptreact`
> @williamgoulois Yes, it's a global prettier installation. Unfortunately running packer again didn't help.
> 
> I could actually narrow down the error a bit. When I open a typescript file from the command line (like `nvim myfile.ts`) the formatter actually does it's job. It does not work though, if I just enter neovim and then open a file via telescope.

can you run `:FormatWrite`

**Comment by abzcoding** [comment]
@bob3000 check if this fixes the issue. 
inside `lua/default-config.lua` add the `stdin = false,` line to make it look like this:
```lua
    tailwindcss = {
      active = false,
      filetypes = {
        "html",
        "css",
        "scss",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
      },
      formatter = {
        exe = "prettier",
        args = { "--stdin-filepath", vim.api.nvim_buf_get_name(0), "--single-quote" },
        stdin = false,
      },
    },
```

**Comment by bob3000** [comment]
@abzcoding Now it says 
```
Formatter: No change necessary with prettier
```

**Comment by abzcoding** [comment]
> @abzcoding Now it says
> 
> ```
> Formatter: No change necessary with prettier
> ```

that it means it fixes the issue, run the prettier from a terminal as well they should output the same thing.

**Comment by bob3000** [comment]
@abzcoding Sorry, what I wrote was not very precise. The message is shown while the file actually still needed some formatting.

**Comment by abzcoding** [comment]
> @abzcoding Sorry, what I wrote was not very precise. The message is shown while the file actually still needed some formatting.

yes I know, what I'm saying is that we run `prettier` on the file and return the output, so if it says there are no changes needed:
1. we either need to add more args to `prettier` (hence me asking you to check from terminal)
2. or create an issue for `prettier` project to fix (which means closing this issue)

**Comment by bob3000** [comment]
@abzcoding running `prettier --stdin-filepath ./src/App.tsx` on the terminal does neither format the file nor does it bring up any output.

**Comment by abzcoding** [comment]
> @abzcoding running `prettier --stdin-filepath ./src/App.tsx` on the terminal does neither format the file nor does it bring up any output.

that is good, so we need to set a different formatter for `typescriptreact` files instead of `prettier`  probably, do you have any suggestions?

**Comment by bob3000** [comment]
@abzcoding I'm actually still not convinced that we need to leave prettier behind for good. It is a very common tool and people probably want to stick to it in their projects. Maybe I can find some time later on to further dive into the problem any hopefully come up with a solution.

**Comment by abzcoding** [comment]
> @abzcoding I'm actually still not convinced that we need to leave prettier behind for good. It is a very common tool and people probably want to stick to it in their projects. Maybe I can find some time later on to further dive into the problem any hopefully come up with a solution.

I didn't mean to remove `prettier` completely, I meant for `typescriptreact` files specifically using `ESLint` instead of `prettier` for formatting. as VsCode suggests [the same](https://code.visualstudio.com/docs/languages/typescript#_typescript-extensions)

**Comment by williamgoulois** [comment]
I'm sorry @abzcoding but I think you do not understand the difference between a linter and a formatter.
ESlint needs langage server to work whereas Prettier does not. They are complementary and yes eslint can have formatting rules but prettier is way more convenient to use

This should help you understand:
https://prettier.io/docs/en/comparison.html

**Comment by Uzaaft** [comment]
@bob3000 Do you have an example tree project, including hidden files that you could post here?

**Comment by abzcoding** [comment]
> I'm sorry @abzcoding but I think you do not understand the difference between a linter and a formatter.
> ESlint needs langage server to work whereas Prettier does not. They are complementary and yes eslint can have formatting rules but prettier is way more convenient to use and people don't want to need LSP just to format files.
> 
> This should help you understand:
> https://prettier.io/docs/en/comparison.html

it is ok, I know the difference. what I'm saying is that if prettier doesn't get the job done, then we have use other stuff for example eslint + a formatted as explained [here](https://eslint.org/docs/user-guide/formatters/)

**Comment by abzcoding** [comment]
@bob3000 [this](https://stackoverflow.com/questions/61731587/prettier-doesnt-format-tsx-file) might be related

**Comment by williamgoulois** [comment]
Found the bug it is the same as this issue #867 i think.
If you open directly a javascript like file it works

**Comment by abzcoding** [comment]
> Found the bug it is the same as this issue #867 i think.
> If you open directly a javascript like file it works

already asked to bob to check it [here](https://github.com/ChristianChiarulli/LunarVim/issues/871#issuecomment-877788533)

**Comment by bob3000** [comment]
@Uzaaft you should be able to reproduce the bug when you just set up a fresh react project with `npx create-react-app myproject --template typescript`. Remember that the bug only occurs when you just open `nvim` without any file argument and then open `App.tsx` using telescope. Just mess up the indention and press `<leader>lf` and the error should happen. I just checked it again with a new project set up from scratch.

**Comment by abzcoding** [comment]
> @Uzaaft you should be able to reproduce the bug when you just set up a fresh react project with `npx create-react-app myproject --template typescript`. Remember that the bug only occurs when you just open `nvim` without any file argument and then open `App.tsx` using telescope. Just mess up the indention and press `<leader>lf` and the error should happen. I just checked it again with a new project set up from scratch.

@bob3000 that issue is fixed when we merge #879.
but the `Formatter: No change necessary with prettier` issue still remains

**Comment by williamgoulois** [comment]
> @abzcoding running `prettier --stdin-filepath ./src/App.tsx` on the terminal does neither format the file nor does it bring up any output.

To actually format a file you need to run `prettier --write ./scr/App.tsx`

**Comment by abzcoding** [comment]
@bob3000 pull the `rolling` branch and check it is fixed or not. If not, then we'll address it in tonight's stream
