### ISSUE TITLE
[Bug]: formatter.nvim doesn't run in CWD of the file being formatted.

### ISSUE THREAD

**Issue by jameswalmsley** [ChristianChiarulli/LunarVim#874]
### Problem description

I've added this PR to formatter.nvim

https://github.com/mhartington/formatter.nvim/pull/57

Tested with C/C++, and LUA

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by jameswalmsley** [comment]
Updated to a new upstream PR:
https://github.com/mhartington/formatter.nvim/pull/58

**Comment by jameswalmsley** [comment]
Now that support for cwd is merged into formatter.nvim...
#967 addresses this for c/cpp.

**Comment by ChristianChiarulli** [comment]
Can we close this?

**Comment by jameswalmsley** [comment]
Closing this now..
I've added a cpp example to the formatter.nvim readme so other languages can add support for it as required.
