### ISSUE TITLE
[Bug]: lv-config's O.user_plugins behaves erratically

### ISSUE THREAD

**Issue by gnmearacaun** [ChristianChiarulli/LunarVim#878]
### Problem description

Generally seems buggy; sometimes installing, sometimes not. Sometimes respecting `, opt = true` sometimes not. Then packer wanted to uninstall seemingly at random.

A separate issue this morning on rolling and master, I had to add `default_options` for some settings to work. Like so
```
O.default_options.timeoutlen = 250
O.default_options.wrap = true
O.default_options.linebreak = true
```

### LunarVim version

rolling

### Neovim version (>= 0.5)

v0.6.0-dev+5-g05330ba50

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
do you have an example plugin?

**Comment by williamgoulois** [comment]
@ChristianChiarulli This is because of this commit 619709eb2f0c32e0c96b1983403a6e84911c3895

**Comment by ChristianChiarulli** [comment]
@williamgoulois I don't think that should have an effect on installing, that will just notify you that there is an error in your lv-config on startup.

**Comment by williamgoulois** [comment]
you moved some options from `O` to `O.default_options` that's why everyone had to update their `lv-config` 😄

**Comment by williamgoulois** [comment]
I copied wrong commit sha in the beggining it's this one e4e8b38

**Comment by ChristianChiarulli** [comment]
ah, yes that makes more sense.

**Comment by gnmearacaun** [comment]
vimwiki is a case in point, I think I spotted that on your stream, but I don't know if you tested it there. 
```O.user_plugins = {{ "vimwiki/vimwiki" }}`  
O.user_plugins = {{ "vim-scripts/autoscroll.vim" }}
```
Both work, but without lazyloading (won't install with `, opt = true`)
Markdown-preview I've not had success with
```
O.user_plugins = {{ 'iamcco/markdown-preview.nvim', run = 'cd app && yarn install', cmd = 'MarkdownPreview', opt = true }}
```

**Comment by abzcoding** [comment]
> vimwiki is a case in point, I think I spotted that on your stream, but I don't know if you tested it there.
> `O.user_plugins = {{ "vimwiki/vimwiki" }}`
> O.user_plugins = {{ "vim-scripts/autoscroll.vim" }}
> `Both work, but without lazyloading. They won't install, with`, opt = true`As for arkdown-preview I've had no success with`
> O.user_plugins = {{ 'iamcco/markdown-preview.nvim', run = 'cd app && yarn install', cmd = 'MarkdownPreview', opt = true }}
> `

I think as long as you set an `event` for it, it should work, here is part of my own config which works:
```lua
O.user_plugins = {
  {
    "folke/tokyonight.nvim",
  },
  {
    "ray-x/lsp_signature.nvim",
    config = function()
      require("lsp_signature").on_attach()
    end,
    event = "InsertEnter",
  },
  {
    "folke/trouble.nvim",
    requires = "kyazdani42/nvim-web-devicons",
    config = function()
      require("trouble").setup()
    end,
    event = "BufRead",
  },
  {
    "simrat39/symbols-outline.nvim",
    event = "BufRead",
    opt = true,
  },
  {
    "sindrets/diffview.nvim",
    event = "BufRead",
    opt = true,
  },
  {
    "nvim-telescope/telescope-project.nvim",
    event = "BufWinEnter",
    setup = function()
      vim.cmd [[packadd telescope.nvim]]
    end,
    opt = true,
  },
}
```
as for the `O.default_options.timeoutlen = 250` and the others I've updated [Readme.md](https://github.com/ChristianChiarulli/LunarVim#configuration-file) bur you're right we might need to update the wiki and other places as well.

**Comment by abzcoding** [comment]
notice that while in `Normal` mode, 
`symols-outline.nvim` is loaded (line 5)
but `lsp_signature.nvim` is not (last line)
because `BufRead` has passed, but `InsertEnter` still hasen't been called.
![plugs](https://user-images.githubusercontent.com/10992695/125268318-d3fb8e00-e31c-11eb-8a79-9f0da538cd84.png)

**Comment by gnmearacaun** [comment]
Those work like a charm (nice list of extras). I see the (not loaded) indication for `lsp_signature.nvim is not` (line 5, not last line). Until I understand events and the autocommands better ( I see you went in depth about the MarkdownPreview plugin on the chat this morning)
```
  {
    "vimwiki/vimwiki",
    --event = "BufWinEnter",
    --opt = true,
  },
  {
    "iamcco/markdown-preview.nvim",
--    run = 'cd app && yarn install',
 --   event = "BufRead",
    cmd = 'MarkdownPreview',
    opt = true
  },
  {
    "vim-scripts/autoscroll.vim",
    event = "BufRead",
    opt = true,
  },
```

**Comment by rebuilt** [comment]
The opt keyword is redundant if you're already defining some other lazy loading strategy.  Opt on its own just tells packer to move the plugin to the opt directory and not to start it automatically.  This is useful for instance, on colorscheme plugins where you don't want it to actually load anything until you call the colorscheme command.

**Comment by gnmearacaun** [comment]
Cool, thankyou @rebuilt . @abzcoding Nice job updating Readme. I especially like the "Made with Lua" at the bottom. I have some additional settings for n00bs who are getting started.
```
-- To link your init.vim (until you find Lua replacements)
vim.cmd('source ' .. CONFIG_PATH .. '/utils/init.vim')
```
I'll make a pull request for `linebreak = true` to be added to default-config.lua. -- Don't put linebreaks in the middle of words. But for now, these are handy
```
O.default_options.wrap = true
O.default_options.linebreak = true
```
 
Under  "FEEL FREE TO CHANGE TO WHATEVER YOU WANT" you could add  "USE AUTOCOMPLETE TO EXPLORE THE OPTIONS"

Resourses: Us Matrix-client users are out in the cold this far! (Also please add a Matrix bridge to the new Discord group you posted this morning about the future of lv) 
- [Community](https://github.com/LunarVim/LunarVimCommunity)
- Matrix @Machine LunarVim
- [Odysee](https://odysee.com/@chrisatmachine:f)

**Comment by gnmearacaun** [comment]
Can I close this issue or does it prevent you from commenting?

**Comment by gnmearacaun** [comment]
One more niggle I have about the readme is the tokyonight example of an extra plugin. I gives the impression the stock color scheme might not be good enough. Now we have more examples at hand:
```
O.user_plugins = {
  {
    "ray-x/lsp_signature.nvim",
    config = function()
      require("lsp_signature").on_attach()
    end,
    event = "InsertEnter",
  },
  {
    "folke/trouble.nvim",
    requires = "kyazdani42/nvim-web-devicons",
    config = function()
      require("trouble").setup()
    end,
    event = "BufRead",
  },
  {
    "simrat39/symbols-outline.nvim",
    event = "BufRead",
    opt = true,
  },
  {
    "sindrets/diffview.nvim",
    event = "BufRead",
    opt = true,
  },
}
```

**Comment by abzcoding** [comment]
@gnmearacaun thank you, I've updated the readme based on your suggestions, feel free to close this issue.

just one thing we don't have `O.default_options.linebreak = true` atm in the config

**Comment by gnmearacaun** [comment]
Strange, the linebreak works for me. Incidentally, part what I though was erratic, was probably packer uninstalling certain packages only to reinstall them. Thanks, this has been instructive, and there are many good examples on the wiki of plugin configs.

Actually @abzcoding it looks to me as though you didn't update the readme the suggestions I was making. I can appreciate how busy you are. I will do my own pull request later.

**Comment by abzcoding** [comment]
> Strange, the linebreak setting works for me. Incidentally, part what I though was erratic, was probably just packer uninstalling certain packages only to reinstall them immediately after. Thanks, this has been instructive, and there are many good examples on the wiki of plugin configs.
> 
> Actually @abzcoding it looks to me as though you didn't update the readme with the suggestions [I was making](https://github.com/ChristianChiarulli/LunarVim/issues/878#issuecomment-878297428). I can appreciate how busy you are. I will do my own pull request later.

:facepalm: my bad, looking forward to your PR :eyes:

**Comment by gnmearacaun** [comment]
Haha, it will be my first, so I'm looking forward to it too. No worries my friend. It was written :eyes:
