### ISSUE TITLE
[Bug]: nvim-treesitter[cuda]: Error during download, please verify your internet connection

### ISSUE THREAD

**Issue by iapicca** [ChristianChiarulli/LunarVim#882]
### Problem description

I just installed `LunarVim` for the first time
and at startup I get the error in the log and in the screenshot
I tried w/ - w/o vpn , restarting my machine, same result, my connection works just fine

### LunarVim version

 LunarVim 0.4.7

### Neovim version (>= 0.5)

NVIM v0.5.0

### Relevant log output

```shell
➜  ~ echo $(nm-online) $? connection problems
Connecting............... 30s [online] 0 connection problems
```

```bash
nvim-treesitter[cuda]: Error during download, please verify your internet connection
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100   168  100   168    0     0    405      0 --:--:-- --:--:-- --:--:--   405
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file tree-sitter-cuda.tar.gz: Permission denied
^M  0  544k    0   830    0     0    920      0  0:10:06 --:--:--  0:10:06  4278
curl: (23) Failure writing output to destination
Press ENTER or type command to continue
```

```console


            .-/+oossssoo+/-.               yakforward@yoga-720 
        `:+ssssssssssssssssss+:`           ------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 80X6 Lenovo YOGA 720-13IKB 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.8.0-59-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 14 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1957 (dpkg), 16 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-7200U (4) @ 2.500GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel HD Graphics 620 
      -+sssssssssssssssssyyyssss+-         Memory: 2234MiB / 7684MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   
```
### Screenshots

![image](https://user-images.githubusercontent.com/45637986/125205795-aa932180-e28c-11eb-8bdb-3604232f307b.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
that's odd, i don't think this is a problem with lunarvim, may try asking on the treesitter github.

**Comment by luxus** [comment]
at the screenshot implies you have problems to write files that treesitter tries to download

**Comment by iapicca** [comment]
> at the screenshot implies you have problems to write files that treesitter tries to download, so the problem is not the internet connection.. it is a permission problem on the folder.. that would be a treesitter issue.

@luxus 
any suggestion on how to "chmod" the folder properly?

**Comment by luxus** [comment]
hard to say.. what OS/distro? and as chris and i told you.. maybe treesitter github is the right spot

**Comment by iapicca** [comment]
ubuntu freshly installed, details in the initial post
I opened an issue on [treesitter](https://github.com/nvim-treesitter/nvim-treesitter/issues/1560)

**Comment by abzcoding** [comment]
@iapicca do you still face this issue? Cause I think I remember it being fixed in last night's stream

**Comment by iapicca** [comment]
Yesterday was still there even after reinstalling , I'll watch the stream, do you have a timestamp?

**Comment by abzcoding** [comment]
> Yesterday was still there even after reinstalling , I'll watch the stream, do you have a timestamp?

:facepalm: my bad, I think it was another issue, so we keep this open for now

**Comment by luxus** [comment]
@iapicca can u try a clean install of lunarvim rolling branch?
this command will delete the old config folder and packer caches and install everything again with the rolling branch activated
` LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/rolling/utils/installer/install.sh) --overwrite`

**Comment by iapicca** [comment]
> LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/rolling/utils/installer/install.sh) --overwrite

@luxus 
I'm probably doing it wrong
![image](https://user-images.githubusercontent.com/45637986/126030213-f934f4f0-2fe5-4f02-9f06-9d7e40abc9b3.png)


the [treesitter issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1560#issuecomment-880057147) 
seems to identify the problem as the path provided by [install.sh](https://github.com/ChristianChiarulli/LunarVim/blob/rolling/utils/installer/install.sh)

**Comment by iapicca** [comment]
@luxus 
turns out the issue was nvim being installed with `appimage`

this fixes it

```
cd /tmp
sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl
bash < (curl -s https://raw.githubusercontent.com/ChristianChiarulli/LunarVim/rolling/utils/bin/install-latest-neovim)
curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/rolling/utils/installer/install.sh | LVBRANCH=rolling bash -s -- --overwrite
```

maybe you want to consider add a warning or stuff like that
