### ISSUE TITLE
[Feature]: Prefer goimports over gofmt

### ISSUE THREAD

**Issue by johanronkko** [ChristianChiarulli/LunarVim#884]
### Feature motivation

Most Go developers prefer to use `goimports` over `gofmt`. It's also the default Go formatter when using vscode. `goimports` does everything that `gofmt` does and more.

### Describe the expected solution

Just change `gofmt` to `goimports` in default-config.lua

**Comment by Uzaaft** [comment]
@johanronkko I don't think it should be added. The go formatter space is notoriously confusing(IMO).

I can go ahead and add an usage comment at the top of the go formatter parameter in `default-config.lua`, so that people get an idea of the possibility to change from `gofmt` to `goimports`.

**Comment by abzcoding** [comment]
> ### Feature motivation
> 
> Most Go developers prefer to use `goimports` over `gofmt`. It's also the default Go formatter when using vscode. `goimports` does everything that `gofmt` does and more.
> ### Describe the expected solution
> 
> Just change `gofmt` to `goimports` in default-config.lua
> ### Describe the alternatives you've considered
> 
> _No response_
> ### Additional context
> 
> _No response_

atm you can change it for yourself by adding this to your `lv-config.lua`:
```lua
O.lang.go.formatter.exe = "goimport"
```

**Comment by Uzaaft** [comment]
Anyways, just a sidenote: 
If we were to go with the thought process:
goimports does everything that gofmt does and more.
Then we should just use goreturns.

Formatters are a notoriously touchy and opinionated subject(just look at the python world and all the formatters there). I think it's best left to the user.

**Comment by Uzaaft** [comment]
@abzcoding I think we should create a format for the --@usage comments. 
I propose something like, an example based upon the python section of `default-config.lua`
```lua
python = {
--[[ @usage:
linter: flake8, etc... 
formatter: yapf, black, etc...
--]]
linter = "", 
isort=false, 
...

}
```
Any thoughts?

**Comment by abzcoding** [comment]
> @abzcoding I think we should create a format for the --@Usage comments.
> I propose something like, an example based upon the python section of `default-config.lua`
> 
> ```lua
> python = {
> --[[ @usage:
> linter: flake8, etc... 
> formatter: yapf, black, etc...
> --]]
> linter = "", 
> isort=false, 
> ...
> 
> }
> ```
> 
> Any thoughts?

formatter is changed, so if you want to set a custom formatter, you need to do:
```lua
O.lang.python.formatter.exe = "black"
O.lang.python.formatter.args = {"-"} -- if it needs args

O.lang.go.formatter.exe = "goimport"
```
so factor this in your usage comments, other than that it looks cool 👍

**Comment by Uzaaft** [comment]
Ah, good point.
I'll do it first thing tomorrow morning. 
Any ideas how to add this into the wiki as well? I can't figure out how to fork it...

**Comment by abzcoding** [comment]
> Ah, good point.
> I'll do it first thing tomorrow morning.
> Any ideas how to add this into the wiki as well? I can't figure out how to fork it...

you can fork the wiki using
```bash
 git clone git@github.com:ChristianChiarulli/LunarVim.wiki.git
 ```
 but sadly you can't do PR on wiki as explained [here](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github)

**Comment by abzcoding** [comment]
until we figure out `Fallback Formatters`, use this to configure it for yourself:
```lua
O.lang.go.formatter.exe = "goimport"
```

**Comment by johanronkko** [comment]
@abzcoding Thanks! I am already. Don't want to be a nitpick but don't forget the "s" at the end of "goimport" (O.lang.go.formatter.exe = "goimports"). I thought it would be a nice default, but I agree with the opinionated argument.

**Comment by abzcoding** [comment]
> @abzcoding Thanks! I am already. Don't want to be a nitpick but don't forget the "s" at the end of "goimport" (O.lang.go.formatter.exe = "goimports"). I thought it would be a nice default, but I agree with the opinionated argument.

:facepalm: oh thank you very much for mentioning that :+1:
