### ISSUE TITLE
[Bug]: No way to configure python autoformatting with LSP

### ISSUE THREAD

**Issue by eulertour** [ChristianChiarulli/LunarVim#887]
### Problem description

The arguments for black in `ftplugin/python.lua` aren't used in that file. Is this intentional and is there a way of configuring python autoformatting that I don't know about, or is this a mistake?

### LunarVim version

04f9f53

### Neovim version (>= 0.5)

0.5

### Relevant log output

```shell
N/A
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
should be an args option for O.lang.python.formatter

**Comment by abzcoding** [comment]
@eulertour 
add this to your `lv-config.lua`
```lua
O.lang.python.formatter.exe = "black"
O.lang.python.formatter.args = {"-"}
```

**Comment by eulertour** [comment]
That fixed it, it turns out I was on an older version.
