### ISSUE TITLE
[Bug]: Dart slow format

### ISSUE THREAD

**Issue by pxsanghyo** [ChristianChiarulli/LunarVim#888]
### Problem description

try formatting the following...

```dart
void main() {
  print('this is a test...',);
}
```

I swear it was faster before when each ftplugin handled autoformatting... 

### LunarVim version

latest rolling

### Neovim version (>= 0.5)

0.5

### Relevant log output

```shell
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
each ftplugin will handle formatting in the future. I'll take a look on stream later this week.

**Comment by abzcoding** [comment]
@pxsanghyo can you test it again using the `rolling` branch, it should be better now

**Comment by pxsanghyo** [comment]
@abzcoding Thanks, tried it out just now.
Honestly it feels about the same...
It takes about a second (~900ms) to format.

I swear it was instant format before which is why I created this issue.

Anyways, thanks!

**Comment by abzcoding** [comment]
> @abzcoding Thanks, tried it out just now.
> Honestly it feels about the same...
> It takes about a second (~900ms) to format.
> 
> I swear it was instant format before which is why I created this issue.
> 
> Anyways, thanks!

can you test one thing real quick
disable auto format on save by adding this to `lv-config.lua`
```lua
O.format_on_save = false
```

then run the following for formatting and check if it is faster or not
```
:lua vim.lsp.buf.formatting()
```

**Comment by pxsanghyo** [comment]
@abzcoding

With the following:
```lua
O.format_on_save = false
```

It's instantly formatting with `:lua vim.lsp.buf.formatting()`
but with `whichkey` command `LSP -> Format` it's same as before (~ 1sec to format).

**Comment by abzcoding** [comment]
@pxsanghyo thank you for testing that, yes that is a known issue we are trying to solve related to #996
