### ISSUE TITLE
[Question]: LspInstall Python not working

### ISSUE THREAD

**Issue by riegojerey** [ChristianChiarulli/LunarVim#892]
### Problem description

when i try to install python in lspInstall it just says Could not install language server for python and when i look at .local/share/nvim/lspinstall there is a folder for python but it is empty

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
> ### Problem description
> 
> when i try to install python in lspInstall it just says Could not install language server for python and when i look at .local/share/nvim/lspinstall there is a folder for python but it is empty
> ### LunarVim version
> 
> rolling
> ### Neovim version (>= 0.5)
> 
> 0.5
> ### Relevant log output
> 
> _No response_
> ### Screenshots
> 
> _No response_
> ### I have
> 
>     * [x]  Read the readme
> 
>     * [x]  Read the wiki
> 
>     * [x]  Searched for similar issues

do you have `npm` installed?
check if this command works:
```bash
npm install pyright@latest
```

**Comment by Uzaaft** [comment]
Could be that you add an space after the python word. I've experienced that before.
`LspInstall python` is the command I use. Just tested it right now, it worked for me(without using npm separately).

**Comment by riegojerey** [comment]
> do you have `npm` installed?
> check if this command works:
> 
> ```shell
> npm install pyright@latest
> ```

yup i forgot to install npm, my bad it's all good. Thank you!
