### ISSUE TITLE
[Feature]: How to mount LunarVim in docker

### ISSUE THREAD

**Issue by jicvi** [ChristianChiarulli/LunarVim#894]
### Feature motivation

For example, docker can mount vim:
ln -s /work-path/config/vim-config/usr/ubuntu/bin/vim /usr/bin/vim

ln -s /work-path/config/vim-config/vimrc.vim $HOME/.vimrc
ln -s /work-path/config/vim-config/tmux.conf $HOME/.tmux.conf

**Comment by jicvi** [comment]
This is vim in docker, sometimes vim is too stuck, I want to change to nvim
![1111111111qqqqqq20210712091643](https://user-images.githubusercontent.com/14210650/125294328-2c696600-e2f2-11eb-941c-125648a3a08d.png)

**Comment by jicvi** [comment]
Thank you

**Comment by jicvi** [comment]
@zethra  
Thank you

**Comment by zethra** [comment]
I miss-tagged the PR. It's for a different issue.
