### ISSUE TITLE
[Feature]: Add save without formatting

### ISSUE THREAD

**Issue by mvllow** [ChristianChiarulli/LunarVim#897]
### Feature motivation

The steps involved in disabling format on save is already pretty slick as `O.format_on_save` applies immediately. This could still be improved for those cases where you want format on save, except for saving a single file – whether it be a forked project or some file you simply don't want formatted.

### Describe the expected solution

With some basic testing, this function seems to do the trick:

```lua
function SaveWithoutFormatting()
    -- Temporarily disable format on save
    vim.cmd([[if exists('#autoformat#BufWritePost')
    :autocmd! autoformat
    endif]])

    -- Save file
    vim.cmd(':w')

    -- Re-enable format on save if previously enabled
    if O.format_on_save then
        require('lv-utils').define_augroups({
            autoformat = {
                {
                    'BufWritePost',
                    '*',
                    ':silent FormatWrite',
                },
            },
        })
    end
end
```

Then we could add to which-key mappings:

```lua
l = {
    ...
    F = { "<cmd>lua SaveWithoutFormatting<cr>", "Save Without Formatting" },
    ...
}
```

### Describe the alternatives you've considered

I've considered just not saving files. Who needs em' anyways

### Additional context

Pending any objections, I'm happy to make a PR soon.

**Comment by rafamadriz** [comment]
Closing in favor of #898
