### ISSUE TITLE
[Bug]: Spacegray not transparent in all places when transparent_window is enabled

### ISSUE THREAD

**Issue by gnmearacaun** [ChristianChiarulli/LunarVim#911]
### Problem description

set this in lv-config:
O.transparent_window = true
Most colorschemes are completely transparent.
Area below the status line is not transparent in spacegray.
Open nvimtree or telescope and they are not transparent, unlike other themes. 

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+5-g05330ba50

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by gnmearacaun** [comment]
I'm part way through to figuring this issue out. Once solved I think spacegray has every good a chance of winning [the competition](https://github.com/ChristianChiarulli/LunarVim/issues/957)
In the meantime, my [transparent version](https://github.com/gnmearacaun/spacegray-trans.vim) works (based on spacegray prior to when chris refactored the theme.

**Comment by Murtaza-Udaipurwala** [comment]
This is because guibg is not set to none for those highlight groups.
I have made a [PR](https://github.com/ChristianChiarulli/LunarVim/pull/990).

**Comment by gnmearacaun** [comment]
Nicely solved @Murtaza-Udaipurwala . I was attempting to do it within spacegray. This is far better as it applies to all themes. I would like to set `gray` and `comment` uniformly visible across all themes. I have tried adding these lines below yours but get an error:
```
        cmd("gray=#9a9a9a")
	cmd("let comment=#919191")
```
but just get errors. Thoughts on how to do this? Nice job with lualine and ez by the way.

**Comment by Murtaza-Udaipurwala** [comment]
@gnmearacaun here is the syntax to highlight any group
```lua
cmd("hi <GROUP> guibg=<color> guifg=<color>")
```
GROUP is the thing you want to highlight. `:hi` inside nvim to get a list of all highlight groups.

In your case the code should be
```lua
cmd('hi Comment guifg="#9a9a9a"')
```

**Comment by gnmearacaun** [comment]
Oh, very cool. Lua really does make it simple to make sweeping changes across the board.
One other thing while you're here, @Murtaza-Udaipurwala. The blank part of the tabline is not transparent. Could we get that?  
I have tried adding the following to your additions in settings, but it doesn't seem to do it
```
	cmd("au ColorScheme * hi TabLine ctermbg=none guibg=none")
```
I wonder what I'm doing wrong.
