### ISSUE TITLE
[Bug]: Galaxyline error after pulling from master - Missing variable

### ISSUE THREAD

**Issue by colutti** [ChristianChiarulli/LunarVim#926]
### Problem description

I just pulled the latest master and after opening nvim I get this error and nothing else loads:

/Users/rafaelcolucci/.config/nvim/lua/plugins.lua:150: attempt to index field 'galaxyline' (a nil value)

It seems that this variable is not declared anywhere:

![image](https://user-images.githubusercontent.com/9368892/125581250-2e42a089-6bfe-4322-8cc5-f9634e8f49ae.png)

I tried to add it to my config but since it is not globally declared I it did not work.

### LunarVim version

Master

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+1501-g9c7e04eb3

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
@colutti galaxyline is now enabled by default, you don't need to do anything with it.

also a lot of variables has been renamed, please refer to `README.md` or `utils/installer/lv-config.example.lua`
or check `lua/default-config.lua` for more info

**Comment by colutti** [comment]
@abzcoding Yes, but the plugins file is still pointing to a variable that does not exist. Look at the plugins.lua file at line 150.

**Comment by abzcoding** [comment]
> @abzcoding Yes, but the plugins file is still pointing to a variable that does not exist. Look at the plugins.lua file at line 150.

that variable  is defined inside `lua/core/status_colors.lua`

**Comment by colutti** [comment]
@abzcoding I just download the master branch and started from scratch. It does not work. Could you do the same please?

**Comment by abzcoding** [comment]
> @abzcoding I just download the master branch and started from scratch. It does not work. Could you do the same please?

on it ...

**Comment by colutti** [comment]
You cloned the rolling branch, not the master :)

**Comment by abzcoding** [comment]
> You cloned the rolling branch, not the master :)

:facepalm:  nah I just copied the wrong command here I actually used the `master` branch

**Comment by abzcoding** [comment]
![galax](https://user-images.githubusercontent.com/10992695/125592215-14257137-14cf-44b0-8fab-46725360694a.png)

**Comment by colutti** [comment]
Yes, I just did it again and it worked. Not sure what happened. Sorry

**Comment by abzcoding** [comment]
> Yes, I just did it again and it worked. Not sure what happened. Sorry

np man, sorry if we're moving too fast and breaking stuff too often :sweat_smile: 
hopefully, we can achieve a stable `1.0` release by the end of July
