### ISSUE TITLE
[Bug]: Switching files with TAB not working

### ISSUE THREAD

**Issue by colutti** [ChristianChiarulli/LunarVim#927]
### Problem description

TAB does not work because the keymaps are commented:

![image](https://user-images.githubusercontent.com/9368892/125584323-bd56027f-7e31-4037-9e70-887803924816.png)

It used to work in previous versions

### LunarVim version

Master

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+1501-g9c7e04eb3

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
> ### Problem description
> 
> TAB does not work because the keymaps are commented:
> 
> ![image](https://user-images.githubusercontent.com/9368892/125584323-bd56027f-7e31-4037-9e70-887803924816.png)
> 
> It used to work in previous versions
> ### LunarVim version
> 
> Master
> ### Neovim version (>= 0.5)
> 
> NVIM v0.6.0-dev+1501-g9c7e04eb3
> ### Relevant log output
> 
> _No response_
> ### Screenshots
> 
> _No response_
> ### I have
> 
>     * [x]  Read the readme
> 
>     * [x]  Read the wiki
> 
>     * [x]  Searched for similar issues

yes Chris has changed them to `shift+h` and `shift+l` so that we could use `tab` for autocomplete

**Comment by colutti** [comment]
@abzcoding thanks. Where is the keymap defined?

**Comment by abzcoding** [comment]
> @abzcoding thanks. Where is the keymap defined?

`lua/code///bufferline.lua`

**Comment by colutti** [comment]
@abzcoding thank you.
