### ISSUE TITLE
[Bug]: <Leader>gg not opening LazyGit

### ISSUE THREAD

**Issue by colutti** [ChristianChiarulli/LunarVim#928]
### Problem description

And it does not show on WhichKey.

### LunarVim version

Master

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+1501-g9c7e04eb3

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
add this to your `lv-config.lua` and test it again:
```lua
O.plugin.floatterm.active = true
```

**Comment by colutti** [comment]
It worked. Thanks.
