### ISSUE TITLE
set to don't use default clipboard as default?

### ISSUE THREAD

**Issue by im-AMS** [ChristianChiarulli/LunarVim#930]
### Problem description

Hi
I would want to change the default behaviour as mentioned above.
It gets annoying when what ever I delete or yank in vim, it shows up in my clipboard.

Instead I would want to map `<Leader>y` to copy to system clipboard and `<Leader>v` to paste from system clipboard.

**What have I tried**
- `vim.api.nvim_set_keymap('','<Leader>y', '"+y',{})`
    This doesn't work at all
- I tried commenting out `opt.clipboard = O.clipboard` from settings.lua,  and remapping the same way as above, it doesn't work

### LunarVim version

Latest stable

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+43-g02bf251bb

### I have

- [x] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
for changing the clipboard behavior add this to your `lv-config.lua` and change it to whatever you like:
```lua
O.default_options.clipboard = "unnamedplus" -- this is the current default, change it
```

**Comment by im-AMS** [comment]
Hey I was on Branch Stable, But i did reinstall to rolling.
The <Leader>y works, but the regular yanks(like yy, or dd) still end up at my system clipboard, which I don't want.
How do I change that?
I want to store in system clipboard ONLY if i use `<Leader>y` or `<Leader>p`

**Comment by abzcoding** [comment]
> Hey I was on Branch Stable, But i did reinstall to rolling.
> The y works, but the regular yanks(like yy, or dd) still end up at my system clipboard, which I don't want.
> How do I change that?
> I want to store in system clipboard ONLY if i use `<Leader>y` or `<Leader>p`

the same config should exactly do that :thinking: maybe try setting the clipboard = "" instead of "unnamed"

**Comment by im-AMS** [comment]
That almost works!!
<Leader>y does not use system clipboard in VISUAL mode, i.e, when I select with visual mode and press <leader>y it doesn't place in system clipboard.

**Comment by abzcoding** [comment]
> That almost works!!
> y does not use system clipboard in VISUAL mode, i.e, when I select with visual mode and press y it doesn't place in system clipboard.

we can fix that as well :sweat_smile:  add these to your `lv-config.lua`:
```lua
vim.api.nvim_set_keymap("v", "<leader>y", '"+y', {noremap = true, silent = true})
vim.api.nvim_set_keymap("v", "<leader>p", '"+p', {noremap = true, silent = true})
```

**Comment by im-AMS** [comment]
that doesn't seem to work 😅

**Comment by abzcoding** [comment]
can you test those changes on rolling or master, a lot of stuff has changed since then
feel free to reopen the issue if is still exists

**Comment by im-AMS** [comment]
How do I set **unnamed** for clipboard options. Im not able to figure out.

**Comment by abzcoding** [comment]
> How do I set **unnamed** for clipboard options. Im not able to figure out.
add this to your `~/.config/lvim/lv-config.lua`

```lua
vim.opt.clipboard="unnamed"
```

**Comment by im-AMS** [comment]
Nope, It doesn't seem to work. 
Here is what I tried
- tried `vim.opt.clipboard="unnamed"` It still uses system clipboard
- tried `vim.opt.clipboard=""` It dosen't use system clipboard. Hence I tried mapping
```
vim.api.nvim_set_keymap("v", "<leader>y", '"+y', {noremap = true, silent = true})
vim.api.nvim_set_keymap("v", "<leader>p", '"+p', {noremap = true, silent = true})

vim.api.nvim_set_keymap("n", "<leader>y", '"+y', {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<leader>p", '"+p', {noremap = true, silent = true})
```
It doesn't paste to system clipboard if I use the remaping shown above.

But if I do `:nnoremap <Leader>y "+y` and `:vnoremap <Leader>y "+y` it works UNTIL i dont close it(which is obvious)

**Comment by abzcoding** [comment]
> Nope, It doesn't seem to work.
> Here is what I tried
> 
>     * tried `vim.opt.clipboard="unnamed"` It still uses system clipboard
> 
>     * tried `vim.opt.clipboard=""` It dosen't use system clipboard. Hence I tried mapping
> 
> 
> ```
> vim.api.nvim_set_keymap("v", "<leader>y", '"+y', {noremap = true, silent = true})
> vim.api.nvim_set_keymap("v", "<leader>p", '"+p', {noremap = true, silent = true})
> 
> vim.api.nvim_set_keymap("n", "<leader>y", '"+y', {noremap = true, silent = true})
> vim.api.nvim_set_keymap("n", "<leader>p", '"+p', {noremap = true, silent = true})
> ```
> 
> It doesn't paste to system clipboard if I use the remaping shown above.
> 
> But if I do `:nnoremap <Leader>y "+y` and `:vnoremap <Leader>y "+y` it works UNTIL i dont close it(which is obvious)

`<leader>p` is used inside LV (for showing packer stuff) that is probably why

**Comment by abzcoding** [comment]
also i just checked the `vim.opt.clipboard="unnamed"` and it works just fine
what os/terminal are you using?

**Comment by im-AMS** [comment]
> <leader>p is used inside LV (for showing packer stuff) that is probably why

Ok I dint see that, but `<Leader>y` dosen't work either.

**Comment by im-AMS** [comment]
>also i just checked the vim.opt.clipboard="unnamed" and it works just fine
what os/terminal are you using?

Im on macos 11.5 M1 mac Air, iTerm2 Build 3.4.3

**Comment by abzcoding** [comment]
well i'm gonna reopen this issue in hope that someone might suggest a fix for you

**Comment by tuxflo** [comment]
So you want to yank a visual selection to the sytem clipboard using `<leader>y`? Then you'll need to setup a `vmapping`. My config looks like this:
```
vim.opt.clipboard = ""

lvim.builtin.which_key.mappings.y = { '"+y', "Yank to clipboard" }
lvim.builtin.which_key.mappings.p = { '"+p', "paste from clipboard" }
lvim.builtin.which_key.mappings.P = { '"+P', "Paste from clipboard" }
lvim.builtin.which_key.mappings.y = {
    y = {
      '"+yy', "Yank line to clipboard" }
    }
lvim.builtin.which_key.vmappings.y = {
 '"+y', "Yank to clipboard"
}
lvim.builtin.which_key.vmappings.p = {
 '"+p', "Paste from clipboard"
}
```
As you can see, I'm using the leader key to tell the yank/paste commands to use the system clipboard.

**Comment by im-AMS** [comment]
Works like a charm!! Thanks!
