### ISSUE TITLE
[Bug]: Python isort does not run

### ISSUE THREAD

**Issue by arxra** [ChristianChiarulli/LunarVim#933]
### Problem description

Setting `O.lang.python.isort = true` does not run isort when the file is formatted.
Running `isort pythonfile.py` does format the file with isort as intended with the settings in `~/.isort.cfg` 

### LunarVim version

Rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+f515baedc Build type: Release LuaJIT 2.1.0-beta3 Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210705-3553-jwh497/build/config -I/tmp/neovim-20210705-3553-jwh497/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210705-3553-jwh497/build/src/nvim/auto -I/tmp/neovim-20210705-3553-jwh497/build/include Compiled by aron@Arons-MacBook-Pro.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-f515bae/share/nvim"  Run :checkhealth for more info

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by shauryagoel0** [comment]
isort does not work for me too. Also, gruvbox is not working saying gruvbox not found. My neovim version is v0.6.0-dev.

**Comment by arxra** [comment]
@shauryagoel0 gruvbox not found sounds a lot like you're not installing gruvbox in your lv-config.lua

**Comment by shauryagoel0** [comment]
@arxra  I only set O.colorscheme = "gruvbox" in the base lv-config.lua. Do we need to install it separately? Isn't it installed automatically by default via nvcode-color-schemes.vim?

**Comment by arxra** [comment]
`nvcode-color-schemes.vim` is no longer installed by default, so if you want gruvbox you need to install it in you `lv-config.lua` under `O.user_plugins` as `ChristianChiarulli/nvcode-color-schemes.vim` (see readme for exact formattin), but please do not hijack a public issue about something that is unrelated

**Comment by rebuilt** [comment]
What's the output of :LspInfo

**Comment by arxra** [comment]
```
Configured servers: lua, efm, dockerfile, yaml, json, java, python, latex, pyright, rust, typescript
Neovim logs at: /home/jarhb/.cache/nvim/lsp.log

2 client(s) attached to this buffer: efm, pyright

  Client: efm (id 1)
  	root:      /home/jarhb/Documents/pythonpg/wattah
  	filetypes: python
  	cmd:       /home/jarhb/.local/share/nvim/lspinstall/efm/efm-langserver
  	


  Client: pyright (id 2)
  	root:      /home/jarhb/Documents/pythonpg/wattah
  	filetypes: python
  	cmd:       /home/jarhb/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	


2 active client(s): 

  Client: efm (id 1)
  	root:      /home/jarhb/Documents/pythonpg/wattah
  	filetypes: python
  	cmd:       /home/jarhb/.local/share/nvim/lspinstall/efm/efm-langserver
  	


  Client: pyright (id 2)
  	root:      /home/jarhb/Documents/pythonpg/wattah
  	filetypes: python
  	cmd:       /home/jarhb/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	


Clients that match the filetype python:

Config: lua
	filetype: No filetypes defined, please define filetypes in setup().
  
  Config: efm
  	cmd:               /home/jarhb/.local/share/nvim/lspinstall/efm/efm-langserver
  	cmd is executable: True
  	identified root:   /home/jarhb/Documents/pythonpg/wattah
  	custom handlers:   

Config: dockerfile
	filetype: No filetypes defined, please define filetypes in setup().

Config: yaml
	filetype: No filetypes defined, please define filetypes in setup().

Config: json
	filetype: No filetypes defined, please define filetypes in setup().

Config: java
	filetype: No filetypes defined, please define filetypes in setup().

Config: python
	filetype: No filetypes defined, please define filetypes in setup().

Config: latex
	filetype: No filetypes defined, please define filetypes in setup().
  
  Config: pyright
  	cmd:               /home/jarhb/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	cmd is executable: True
  	identified root:   /home/jarhb/Documents/pythonpg/wattah
  	custom handlers:   textDocument/publishDiagnostics

Config: rust
	filetype: No filetypes defined, please define filetypes in setup().

Config: typescript
	filetype: No filetypes defined, please define filetypes in setup().
```

**Comment by arxra** [comment]
From https://gitlab.com/arxra/wattah/-/blob/master/main.py , the imports after formatting and pushing are 
```
from gpiozero import LED, MCP3002, Button
from aiohttp import web
import yaml
```
and if you run isort outside of neovim (lunarvim?)
```
import yaml
from aiohttp import web
from gpiozero import LED
from gpiozero import MCP3002
from gpiozero import Button
```
which is what I would expect.

**Comment by rebuilt** [comment]
Formatting and linting stuff seems to be changing really quickly.   I'm not sure it's working right now.

In the meantime use this command to run isort on the file within neovim.  

```
:!isort %
```

**Comment by abzcoding** [comment]
@arxra at the moment formatting is done via `formatter.nvim` using `yapf` so the `efm` stuff is probably not fully functional right now, however, we're trying to re-structure the formatters so stay tuned :)

**Comment by arxra** [comment]
@abzcoding Sounds good to me! Lets keep this as a reminder/tracker then, since the option is in the README/example configuration (Maybe change that in the readme while this is a known issue?)

**Comment by ChristianChiarulli** [comment]
can we add isort to the list of active formatters?

**Comment by abzcoding** [comment]
> can we add isort to the list of active formatters?

sadly no: [Available Linters](https://github.com/mfussenegger/nvim-lint#available-linters)

**Comment by Tastyep** [comment]
> > can we add isort to the list of active formatters?
> 
> sadly no: [Available Linters](https://github.com/mfussenegger/nvim-lint#available-linters)

Why not, isort is a formatter, not a linter.

**Comment by abzcoding** [comment]
> > > can we add isort to the list of active formatters?
> > 
> > 
> > sadly no: [Available Linters](https://github.com/mfussenegger/nvim-lint#available-linters)
> 
> Why not, isort is a formatter, not a linter.

🤦 you are right

**Comment by Tastyep** [comment]
FYI I'm working on it already, I have a few ideas I want to try.

**Comment by vlcinsky** [comment]
[null-ls.nvim has support for isort](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting.lua#L42)

**Comment by arxra** [comment]
The issue with that would still be to run multiple formatters, as most often you want both black and isort, [which null-ls does not support yet](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/56). If I just wanted to have it format with isort I'd bind the above `:!isort %` to some key and have it done.

**Comment by rebuilt** [comment]
You can run multiple language servers but it gets kind of annoying because it asks you to chose which server you want to run.  But if you want to try it out add this to your lv-config to install efm

```
local efm = "/home/" .. USER .. "/.local/share/nvim/lspinstall/efm/efm-langserver"
print(efm)
require("lspconfig").efm.setup({
	-- cmd = { "efm-langserver" },
	cmd = { efm },
	init_options = { documentFormatting = true },
	filetypes = { "python" },
	settings = {
		rootMarkers = { ".git/" },
		languages = {
			python = {
				{ formatCommand = "isort --quiet -", formatStdin = true },
			},
		},
	},
})
```

You'll need to `:LspInstall efm`  or `go get github.com/mattn/efm-langserver`.  Then make sure the efm-langserver cmd points to the right location.  
It's tricky to set up sometimes.  There are numerous issues with people having trouble setting it up.  That's the reason we switched.

**Comment by ChristianChiarulli** [comment]
closing because this isn't a bug, when null-ls supports multiple formatters we will implement this feature.

**Comment by vlcinsky** [comment]
For me it works now with both `isort` and `black` being configured as python formatters in my (lv-)config.lua:

```lua
lvim.lang.python.formatters = {
  {
    exe = "isort",
    args = {"--profile", "black"}
  },
  {
    exe = "black",
    args = {}
  }
}
```
I plan to create PR with these settings being default ones for Python.
