### ISSUE TITLE
[Bug]: vim.cmd not respected in lv-config.lua

### ISSUE THREAD

**Issue by JakobMielke** [ChristianChiarulli/LunarVim#936]
### Problem description

I was trying to set some ```set```'s and ```let```'s with ```vim.cmd``` like this:
```lua
vim.cmd("set noexpandtab")
vim.cmd("set nospell")
vim.cmd("let g:vim_markdown_folding_disabled = 1")
vim.cmd("let g:vim_markdown_math = 1")
vim.cmd("let g:vim_markdown_frontmatter = 1")
vim.cmd("let g:vim_markdown_toml_frontmatter = 1")
vim.cmd("let g:vim_markdown_json_frontmatter = 1")
vim.cmd("let g:vim_markdown_strikethrough = 1")
vim.cmd("let g:vim_markdown_new_list_item_indent = 2")
vim.cmd("let g:vim_markdown_no_extensions_in_markdown = 1")
vim.cmd("let g:tex_conceal = ''")
```
however they seem to be ignored when opening a new instance of nvim ( Checked by running ```:set expandtab?```and ```set spell?``` , respectively).

### LunarVim version

0.4.8

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
settings.lua gets called after lv-config.lua.  So one of the problems is that settings will be overwritten by the defaults defined in default-config.lua

You can use the following format to set options defined in O.default_options  (~/.config/nvim/lua/default-config.lua)

```
O.default_options.expandtab = false
```

Are the other options being set correctly?

```
 g:vim_markdown...
```

**Comment by JakobMielke** [comment]
> Are the other options being set correctly? 

As far as I can tell they are (via ```:echo [option]```)

**Comment by abzcoding** [comment]
> > Are the other options being set correctly?
> 
> As far as I can tell they are (via `:echo [option]`)

for the `let g` stuff use this syntax:
```lua
vim.g.tokyonight_style = "night"
```

also put those `vim.cmd("set sth")` inside `~/.confg/nvim/lv-config.lua`

**Comment by abzcoding** [comment]
> > for the let g stuff use this syntax inside of lv-config.lua > instead:
> > ```lua
> > vim.g.tokyonight_style = "night"
> > ```
> 
> Thanks for that tip, however this is all in `~/.config/nvim/lv-config.lua`

instead of 
```vim
vim.cmd("set noexpandtab")
vim.cmd("set nospell")
```
use 
```lua
O.default_options.expandtab = false
O.default_options.spell = false
```

**Comment by JakobMielke** [comment]
Thanks for your help, however ``` O.default_options.spell = false ``` does not disable spellcheck.

**Comment by abzcoding** [comment]
> Thanks for your help, however `O.default_options.spell = false` does not disable spellcheck.

are you facing this issue in a markdown file or all filetypes?
cause inside `lua/lv-utils/init.lua` we have this:
```lua
  _markdown = {
    { "FileType", "markdown", "setlocal wrap" },
    { "FileType", "markdown", "setlocal spell" },
  },

```

**Comment by JakobMielke** [comment]
Thanks for your comment @abzcoding, I should have checked the filetype of my markdown file, because vim-pandoc set the filetype to pandoc

**Comment by abzcoding** [comment]
I am closing the issue, feel free to reopen it in case you had any other questions related to `vim.cmd` in `lv-config.lua`
