### ISSUE TITLE
[Feature]: How to quickly open file sibling which is out of current nvimtree root

### ISSUE THREAD

**Issue by vlcinsky** [ChristianChiarulli/LunarVim#946]
### Feature motivation

cd to `~/.config/nvim` and use nevim to open `lv-config`

Use `:e ~/.bashrc` to open it

Try to open `~/.aliases` (which happens tto be sibling of currently open file)

## Using nvim_tree
Using `<space>e` open nvim_tree, go up two directories and find there the `.aliases file`

This requires at least 5 keystrokes to get to the user home dir.

## Using `:Explore`
(assuming `netrw` is not intentionally disabled) call `:Ex` what opens netrw listing of user home directory (using the directory where is current file open).

This takes 4 keystrokes to get to the user home dir listing.

## Using `tpope/vim-vinegar`
Press `-` and have the netrw listing of user home directory open.

This takes 1 keystroke to get to the user home dir listing.

### Describe the expected solution

Do not disable `netrw` (and whatever other builtin plugin needed to run Explore command)

Allow to install `tpope/vim-vinegar` plugin (either as standard LunarVim part or as user defined).

### Describe the alternatives you've considered

I was researching nvim_tree to see, if there is some simple option to open the tree where the current file resides when the file is out of current nvim_tree root. I did not find an option.

### Additional context

I understand, disabling some builtin plugins speeds up start up time.

But for day to day work, speed at opening sibling file is more important as it happens more often.

**Comment by abzcoding** [comment]
if you want that plugin, simply add the following to your `lv-config.lua`
```lua
O.user_plugins = {
{"tpope/vim-vinegar"},
}
```
for more info check out the [wiki](https://github.com/ChristianChiarulli/LunarVim/wiki/Example-plugin-configurations)

**Comment by vlcinsky** [comment]
@abzcoding I have it already as you propose.

Anyway, as the `vim-vinegar` is using `netrw#Explore` function to show directory listing, it does not work currently.

I get an error `E117: Unknown function: netrw#Explore`

**Comment by abzcoding** [comment]
> @abzcoding I have it already as you propose.
> 
> Anyway, as the `vim-vinegar` is using `netrw#Explore` function to show directory listing, it does not work currently.
> 
> I get an error `E117: Unknown function: netrw#Explore`

added the pr for it, that way you can disable only what you want: 
```lua
-- lv-config.lua

O.disabled_built_ins = {
--    "netrw",
--    "netrwPlugin",
--    "netrwSettings",
--    "netrwFileHandlers",
    "gzip",
    "zip",
    "zipPlugin",
    "tar",
    "tarPlugin", -- 'man',
    "getscript",
    "getscriptPlugin",
    "vimball",
    "vimballPlugin",
    "2html_plugin",
    "logipat",
    "rrhelper",
    "spellfile_plugin",
    -- 'matchit', 'matchparen', 'shada_plugin',
  },

```

**Comment by vlcinsky** [comment]
@abzcoding thanks for the PR.

Anyway, there is still an issue with nvim_tree, I had to modify `lua/core/nvimtree.lua` with:

```lua
  g.nvim_tree_disable_netrw = 0
  g.nvim_tree_hijack_netrw = 0
```
otherwise the problem was still present.

The question is weather these values shall be constant or they shall be configurable via user options.

**Comment by abzcoding** [comment]
> ```lua
>   g.nvim_tree_disable_netrw = 0
>   g.nvim_tree_hijack_netrw = 0
> ```

there is a [PR](https://github.com/ChristianChiarulli/LunarVim/pull/769) for making nvim-tree user configurable

**Comment by vlcinsky** [comment]
@ChristianChiarulli @abzcoding can we reopen this issue?

Managing disabled plugins works great, but we are still missing user control of `vim.g.nvim_tree_disable_netrw`.

Existing [default-config.lua](https://github.com/ChristianChiarulli/LunarVim/blob/ddb627d004d1f6c3bbd593a381ed93bbe54a24fd/lua/default-config.lua#L100) allows to set `O.nvim_tree_disable_netrw` but this is actually never used.

Better option would be to proceed with PR #764 as it gives much better control of nvim_tree options.

**Comment by abzcoding** [comment]
> @ChristianChiarulli @abzcoding can we reopen this issue?
> 
> Managing disabled plugins works great, but we are still missing user control of `vim.g.nvim_tree_disable_netrw`.
> 
> Existing [default-config.lua](https://github.com/ChristianChiarulli/LunarVim/blob/ddb627d004d1f6c3bbd593a381ed93bbe54a24fd/lua/default-config.lua#L100) allows to set `O.nvim_tree_disable_netrw` but this is actually never used.
> 
> Better option would be to proceed with PR #764 as it gives much better control of nvim_tree options.

add this to `lv-config.lua`
```lua
O.plugin.nvimtree.disable_netrw = false -- or sth
```

**Comment by vlcinsky** [comment]
For `rolling` branch I can confirm, existing `lv-config.lua` allows to control required nvim_tree options needed to allow vim-vinegar to work:

Following hints from https://github.com/ChristianChiarulli/LunarVim/pull/769#issuecomment-881862932 I added to my `lv-config.lua` lines:

```lua
O.plugin.nvimtree.disable_netrw = 0
O.plugin.nvimtree.hijack_netrw = 0
```
and now it works.

All changes in my `lv-config.lua` needed to make vim-vinegar working are as follows:

```lua
O.plugin.nvimtree.disable_netrw = 0
O.plugin.nvimtree.hijack_netrw = 0

O.disabled_built_ins = {
	-- "netrw",
	-- "netrwPlugin",
	-- "netrwSettings",
	-- "netrwFileHandlers",
	"gzip",
	"zip",
	"zipPlugin",
	"tar",
	"tarPlugin", -- 'man',
	"getscript",
	"getscriptPlugin",
	"vimball",
	"vimballPlugin",
	"2html_plugin",
	"logipat",
	"rrhelper",
	"spellfile_plugin",
	-- 'matchit', 'matchparen', 'shada_plugin',
}

-- Additional Plugins
O.user_plugins = {
	{ "tpope/vim-vinegar" },
}
```

Great.
