### ISSUE TITLE
[Bug]: 404: Not Found on the curl command added recently to the readme

### ISSUE THREAD

**Issue by shinze** [ChristianChiarulli/LunarVim#950]
### Problem description

Tried to update with what is written on the readme, used 

```
curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/rolling/utils/installer/install.sh| LVBRANCH=rolling bash -s -- --overwrite
```

Had a `404: Not Found` response.

### LunarVim version

Latest

### Neovim version (>= 0.5)

v0.6.0-dev+28-g1c4168928

### Screenshots

<img width="685" alt="image" src="https://user-images.githubusercontent.com/218396/125705048-cc8f5d17-db3c-4cce-9239-dc2865456653.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
@shinze please remove the extra `\` near the `|`, that is not in the command

**Comment by shinze** [comment]
> @shinze please remove the extra `\` near the `|`, that is not in the command

It’s in the command when I use the 'copy' widget Github offers on that code block.

**Comment by Tastyep** [comment]
> > @shinze please remove the extra `\` near the `|`, that is not in the command
> 
> It’s in the command when I use the 'copy' widget Github offers on that code block.

That's surprising because when I try it I don't have it and the [raw](https://raw.githubusercontent.com/ChristianChiarulli/LunarVim/rolling/README.md) version doesn't contain it either

**Comment by abzcoding** [comment]
@shinze that is a known mac + zsh [issue](https://stackoverflow.com/questions/25614613/how-to-disable-zsh-substitution-autocomplete-with-url-and-backslashes#25622864) **not a LunarVim issue**.
Basically, when you copy things to mac terminal , the pipes get escaped with `\`
