### ISSUE TITLE
[Feature]: REPL

### ISSUE THREAD

**Issue by eo1989** [ChristianChiarulli/LunarVim#956]
### Feature motivation

Frustrated with the lack of REPL support in lunar vim. There are plenty of great vim-REPL plugins one could use; Zepl.nvim, Iron.nvim, conjure, vim-slime/neoterm/insert-your-terminal-plugin{already using one}-here.

**Comment by MatthiasX86** [comment]
I second this

**Comment by sethigeet** [comment]
This is a very simple plugin and does not require much configuration. Also not all languages support a REPL and not everyone uses it. It would be bloat for a lot of people!
Whoever wants it could just add it as a custom plugin very easily

**Comment by rebuilt** [comment]
Thanks for the suggestion.  All of us, even the core devs, install plugins we like separately.  It's easy to install on your own.  At the moment the project is focused on these things:  https://github.com/ChristianChiarulli/LunarVim#project-goals.  If you'd like to provide sample configurations for any of those solutions, I can add them to the wiki.
