### ISSUE TITLE
[Feature]: Keybindings rant and other annoyances

### ISSUE THREAD

**Issue by Araly** [ChristianChiarulli/LunarVim#960]
### Feature motivation

Hi, I've been using LunarVim for work for a while now, and I tried following the development of it, tried to understand the configuration files and how things work, and I've lately been bringing up issues I had with it to the Discord. From there I was told to post an issue about all that. I'll try to bring here all the little things I could find. I understand that things are moving a lot and that there is an effort to try to stabilize the base we have before. Sorry for the rant-like post, I was told one big post would be better than lots of tiny ones.

---

### Configuration files

We have a keybindings file, and also a whichkey file. So I've been editing those to comment out problematic lines and add my own, but I was then told that it would be better to do everything in the lv-config.lua file. I saw that there are some examples of how to do that, but it's still a lot easier to just edit those files directly. It would be a lot nicer though to be able to have user config only in one file (a bit like spacemacs does it) for sure.

### Keybind-ception

The keybindings file has a lot of keybinds that are set as binding keys to other keybinds. It's very confusing and feels like a mess. For example, if I want to have Ctrl+Left (I use a weird keyboard layout, so HJKL makes no sense to me) mapped to "go to the left window", the way it's set up now is that you would map "Ctrl+Left" to a keybind that already exists and happens to move the focus to the left window ("Ctrl+W, +h" I believe, or "C-w h"). I would expect to be able to just map "Ctrl+Left" to "nvim.focus.move_to_left_window" or something.

Binding keys to other keybinds looks horrible, it's very difficult to read and you have to learn keybinds you're not going to use. It makes adding keybinds difficult too, and creates dependencies between the keybinds. I had an issue for example where a keybind I wasn't using was causing issues with another seemingly unrelated keybind because they were colliding or something, I'm not even sure what was happening myself (Ctrl+Backspace would move the cursor to the left window when in insert because of this following line that I had to comment out in the keymappings.lua file)
```lua
vim.api.nvim_set_keymap("i", "<C-h>", "<C-\\><C-N><C-w>h", { silent = true, noremap = true })
```
Seriously just look at that keybind, why does it look more like a carbon chain representation in chemistry than code ? There's no comments around that line either, just "Terminal window navigation". I'm not sure how neovim works, and maybe that's the only way to write those keybinds. If that's the case, having a comment explaining what the keybinds do and why would be a great improvement at least. Even just so that if they are not discoverable through whichkey, they are at least searchable in the repo. Even now I have no idea what that keybind does, or any of the ones that have for only comment "I hate escape". I like escape, should I comment those keybinds out too ?

### Whichkey is more than a gimmick

whichkey makes keybindings discoverable. This is what made me jump in spacemacs a couple years ago, and it's what made me jump into LunarVim. I can just press Space, and see everything I can do. I can look around, press keys, see what happens. I don't need to learn keybinds when I can just press Space to find what I need, and memorize that with repetition. I would really love it if more stuff was in whichkey, or even if everything was in whichkey.

Of course you can still discover keybinds via other means. For example, when you press "g", you'll see all the other things you can do, and that's great. But you still have to know to use "g" in the first place. Same for "Ctrl+w". As long as we don't have too many of those, they could just be brought up in the Readme, or be in a comment in the lv-config.lua file or some other place that would be easily findable when someone is looking for keybindings that might exist.

But there are still things I don't understand at all. Hovering over a word in code is quite important, at least to me, so I had mapped it to "Space+." (Space, and then the dot), as that's very accessible to me. The keybind was then moved to "Space+L+H" (Space, then L, then H), which makes a lot of sense, as it's discoverable in the "What is my code doing ?" section of the whichkey. Now, it's been mapped by default to "Shift+k" and I can't understand why, it feels very unintuitive and arbitrary. Maybe people find "Shift+k" to be easy access, and it could be left as a duplicate keybind for comfort, but I really don't think Hovering over a work in code, which seems like quite the important keybind, should be hidden away in an obscure keybind, outside of the whichkey discoverability.

### ~~In~~sane Telescope defaults

Maybe that title is a bit harsh, but I find it fun. On a non keybind matter, I've seen other weird defaults, for example on the current (as I'm writing) master, Telescope is set up to show paths as "shorten", which makes the paths show only the first letter of folders (for example /l/l/init.lua). This might be a cool minimalist option people like, but I don't see how that can be a default, the relative path behavior telescope has when you don't have any option set up is a lot saner. Especially in LunarVim where all folders start with "lv-...", I can only see the "shorten" path be relevant for quite small screens in small projects.

I know that we are waiting for the "smart" option to appear in the Telescope plugin, but in the meantime, please get rid of the "shorten" default. The last activity on that "smart" option's PR in Telescope is from June, so we might not get that option for a while. #812 

I think we should really think about what the defaults of LunarVim are, and not just settle on someone's neat happy options, but think about what's better for the majority of people that won't change the config too much.

---

Let me know if this doesn't really belong here in this format, and maybe I can try to split it up in several different issues about the different things I bring up here, but I do think all of these are related to one another, and it goes beyond than just a bunch of individual issues.

### Describe the expected solution

I'm not sure what could be done to make LunarVim more coherent, intuitive, consistent, and sane. The Discord has been a great help even if it feels as disorganized as this repo. It's not necessarily a bad thing and it could be interesting to see all the things that get added or get tweaked, but I do think LunarVim would benefit from a solid base to work on. I know there's efforts on that so I'm very interested in seeing where we go.

### Describe the alternatives you've considered

I'm not really interested in other editors for now, I'd really like to see LunarVim work well and succeed. I might be able to try to submit some PR for things I think should be changed as I slowly get familiar with neovim and lua, but as things are changing often it's difficult to know where help would be interesting.

**Comment by rebuilt** [comment]
I'll work on overrideable configurations for the core plugins

**Comment by rebuilt** [comment]
I won't do anything about the keybindings for the moment.

**Comment by Araly** [comment]
for the keybindings if I have some time I could look into them. adding comments to explain what they do would be nice, but maybe I can find a better way to write them that doesn't make them rely on other keybinds.

I could also look into making stuff more discoverable (at least the ones I know) but that would mean changing them, which is always a subjective thing.

for example to be able to use C-w for deleting the previous word I would need to unmap the window management part of it. I could see it live pretty well at Space-w, but that's currently bound to saving the buffer to the file. or I could find what C-w calls by default to be able to bind another key for "delete the previous word" (like Ctrl-Backspace).

**Comment by rebuilt** [comment]
The code that sets the keybindings needs to be extracted from the table of keybindings.  Then you need to pass either the default table or the user keybind table to create the keybindings.  I have a rough outline of how that should look, but it needs a little more thought, so I'm just going to start with the configs for now.

**Comment by kylo252** [comment]
Most of what your complaints require adding some QoL utility functions, which we need to come up with.
However, check my comment here about modifying which-key bindings:

https://github.com/ChristianChiarulli/LunarVim/pull/973#issuecomment-880749128

That doesn't exactly solve all the problems, but I'll try to post any useful tips I can think of.

**Comment by abzcoding** [comment]
Merged
