### ISSUE TITLE
[Bug]: Go to references window doesn't show the references when the cursor is on them

### ISSUE THREAD

**Issue by Araly** [ChristianChiarulli/LunarVim#961]
### Problem description

1. have a go project (or maybe some other kind of project)
2. write a function
3. call that function from another place or file in that same project
4. press g+r to go to references
5. see the references window appear with two lines, one for where you define that function, one for where you call it
6. move cursor up and down the references list
7. see that it fails to do anything
8. press enter on a reference
9. see that it opens up the relevant file at the relevant line in the current buffer window tab thing.

I would expect the references list to behave like it used to do. When I move up and down the list, it shows up the relevant file and the relevant line, without moving me out of the references list window.

### LunarVim version

master as of how it was the 12th of July

### Neovim version (>= 0.5)

NVIM v0.5.0-dev+1471-g7d8202087 Build type: Release LuaJIT 2.1.0-beta3

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
like with bqf?

**Comment by eo1989** [comment]
Check out "any jump" or "goto-preview" plugins. With this obsession the devs have over 2-3 milliseconds of load time they've removed a lot of good functionality. Just keep a list of your own plugins you want to use and add them after they get a stable build, or fork the project and develop your own branch.

**Comment by Araly** [comment]
> like with bqf?

I have no idea, I'm new to neovim, I don't know what other plugins exist. If I remember correctly, the behavior I'm expecting is something we had in lunarvim a few weeks ago. I think the keybind called a function you could call from the : prompt, like :LspReferences or :LspDefinition. I remember also having bound a key to :LspFormating 

I went to my old config and I found the plugin that was used was LspSaga.

> Check out "any jump" or "goto-preview" plugins. With this obsession the devs have over 2-3 milliseconds of load time they've removed a lot of good functionality. Just keep a list of your own plugins you want to use and add them after they get a stable build, or fork the project and develop your own branch.

"any jump" looks very cool, I'll check out that
