### ISSUE TITLE
[Bug]: Can't run the rust LSP server

### ISSUE THREAD

**Issue by Cthutu** [ChristianChiarulli/LunarVim#972]
### Problem description

Hi tried:

1) `:LspInstall` then \<TAB> did not produce any list on my Linux OS.
2) `:LspInstall rust` did something and I also think it downloaded `rust-analyzer`
3) Opened a .rs file, screen says LSP Inactive
4) Trie `LspInfo` and it says `No filetypes defined, please define filetypes in setup().`

At this point I am stuck.  What is `setup()`?  Which file is that in?  Perhaps the error message should contain that info.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

No idea how to find out.  Latest on git today.

### Neovim version (>= 0.5)

0.6

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
@Cthutu can you test the following scenario:

```bash
cd /tmp
git@github.com:ProgrammingRust/examples.git
cd examples/ascii
nvim src/lib.rs
```
and let me know if the `:LspInfo` command works or not.

**Comment by Cthutu** [comment]
Thanks for responding.

I get the same error about no filetypes defined.

**Comment by Cthutu** [comment]
![image](https://user-images.githubusercontent.com/348614/125832249-e25c3ab1-e2d3-4ced-b718-241b5e7e81b4.png)

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/125832641-d8741f01-f29f-420c-9499-f8101f623241.png)

![image](https://user-images.githubusercontent.com/29136904/125832679-dbb56a06-df2c-4e2d-932f-06647c57720e.png)

rust analyzer is what works for me.

**Comment by ChristianChiarulli** [comment]
you have no root detected, thats your problem

**Comment by Cthutu** [comment]
What does that mean?

**Comment by ChristianChiarulli** [comment]
https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#rust_analyzer

hmm it doesn't seem to pick up on that. could you post project structure?

**Comment by abzcoding** [comment]
@Cthutu 
in the mean time test adding
```lua
O.lang.rust.rust_tools.active = true
```
to your `lv-config.lua` and see if that helps with anything

**Comment by Cthutu** [comment]
> https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#rust_analyzer
> 
> hmm it doesn't seem to pick up on that. could you post project structure?

My structure is a basic hello world structure.  A `Cargo.toml` and a `src/main.rs`.  Nothing special.

**Comment by Cthutu** [comment]
The last screenshot I did was on the ascii examples that another poster suggested.  On my very simple hello world structure: 
![image](https://user-images.githubusercontent.com/348614/125833542-95e72c9a-405c-4745-9a21-ad1c65dd4e47.png)

The edit to `lv-config.lua` didn't seem to help.

**Comment by abzcoding** [comment]
> The last screenshot I did was on the ascii examples that another poster suggested. On my very simple hello world structure:
> ![image](https://user-images.githubusercontent.com/348614/125833542-95e72c9a-405c-4745-9a21-ad1c65dd4e47.png)
> 
> The edit to `lv-config.lua` didn't seem to help.

can you provide your `~/.cache/nvim/lsp.log`

**Comment by Cthutu** [comment]
I did lose syntax highlighting.

```
[ START ] 2021-07-15T13:11:06+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:11:13+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:11:29+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:12:33+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:12:41+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:12:54+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:14:18+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:14:56+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:15:11+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:15:23+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:21:43+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:30:48+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:39:42+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:40:38+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:41:40+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:43:48+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:46:42+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:47:20+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:48:09+0100 ] LSP logging initiated
[ START ] 2021-07-15T14:01:12+0100 ] LSP logging initiated
[ START ] 2021-07-15T13:56:23+0100 ] LSP logging initiated
[ START ] 2021-07-15T14:05:43+0100 ] LSP logging initiated
[ START ] 2021-07-15T14:10:55+0100 ] LSP logging initiated
[ START ] 2021-07-15T14:11:09+0100 ] LSP logging initiated
[ START ] 2021-07-15T14:11:12+0100 ] LSP logging initiated
[ START ] 2021-07-15T14:13:40+0100 ] LSP logging initiated
[ START ] 2021-07-15T14:14:06+0100 ] LSP logging initiated
[ START ] 2021-07-15T16:43:55+0100 ] LSP logging initiated
[ START ] 2021-07-15T18:34:38+0100 ] LSP logging initiated
[ START ] 2021-07-15T18:44:06+0100 ] LSP logging initiated
[ START ] 2021-07-15T18:45:05+0100 ] LSP logging initiated
[ START ] 2021-07-15T18:45:27+0100 ] LSP logging initiated
[ START ] 2021-07-15T18:47:59+0100 ] LSP logging initiated
[ START ] 2021-07-15T18:49:03+0100 ] LSP logging initiated
```

**Comment by abzcoding** [comment]
can you run a `:PackerSync` just to be sure

**Comment by Cthutu** [comment]
Promising:
![image](https://user-images.githubusercontent.com/348614/125834345-3b659519-0668-4b83-b12a-3da72e32b02d.png)

It works!!!  It seems that you are required to run that command on my system.  For you information, I built neovim from source code and then immediately installed Lunarvim.

**Comment by Cthutu** [comment]
Thanks for your help.  This issue is closed.

**Comment by Cthutu** [comment]
For future reference, how do you get the current version of Lunarvim?  Perhaps this should be on the splash screen?

**Comment by abzcoding** [comment]
> For future reference, how do you get the current version of Lunarvim? Perhaps this should be on the splash screen?

yeah atm we're trying to fix bugs and freeze plugins so that we can have a stable version, if we accomplish that, the next step would be documentation and video series to help users tune LunarVim to their workflow
