### ISSUE TITLE
[Bug]: go to definition across files.

### ISSUE THREAD

**Issue by ivano9** [ChristianChiarulli/LunarVim#975]
### Problem description

On erlang proyect not working g-d for jump to a definition to another file
1. Define a function
2. Call the function in another file
3. put the cursor over function called
4. press g-d

Result: no jump to definition.
Expected: open the file and put the cursor over definition function

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

0.4.8

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+27-g27118c6eb

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
does erlang lsp support this?

**Comment by ivano9** [comment]
yes, before update lunarvim was working.

**Comment by ChristianChiarulli** [comment]
ok I'll take a closer look

**Comment by reflog** [comment]
same with clojure. lsp is working, but 'gd' doesn't.

**Comment by ChristianChiarulli** [comment]
I don't think erlang was implemented for some reason, must have gotten lost in the refactor, it is on rolling now.

**Comment by ChristianChiarulli** [comment]
I'll look into clojure as well

**Comment by ChristianChiarulli** [comment]
clojure is now on rolling

**Comment by reflog** [comment]
@ChristianChiarulli - thanks, works great!

**Comment by ivano9** [comment]
thanks, now works!
