### ISSUE TITLE
[Feature]: Smarter explorer use

### ISSUE THREAD

**Issue by Cthutu** [ChristianChiarulli/LunarVim#980]
### Feature motivation

I want to switch to nvimtree with a keypress, but current SPC+e, will only toggle.  This means that when I am editing a file and I want to go over to nvimtree, I have to press SPC+e twice.

### Describe the expected solution

Perhaps SPC+e should do different things depending on context:

1) If the user is on nvimtree, it closes
2) If nvimtree is not visible, it opens
3) If the user is on a different window, it switches to nvimtree.

**Comment by ChristianChiarulli** [comment]
Is this not the current behavior?

**Comment by Uzaaft** [comment]
I use Ctrl+H/L to jump between an editor and nvimtree if it's open.

**Comment by Cthutu** [comment]
> Is this not the current behavior?

Not quite.  SPC+e will just toggle the visibility of the nvimtree.

**Comment by Cthutu** [comment]
> I use Ctrl+H/L to jump between an editor and nvimtree if it's open. This works out of the box for me.

That's great if you have just one window open.  Using the nvimtree is so common that I would prefer the declarative approach to it (press 1 key to go straight there), rather than the imperative approach (press 1 or more keys depending on how many windows you have and how they are set up).

**Comment by williamgoulois** [comment]
> That's great if you have just one window open. Using the nvimtree is so common that I would prefer the declarative approach to it (press 1 key to go straight there), rather than the imperative approach (press 1 or more keys depending on how many windows you have and how they are set up).

Yeah but this means that when you open a file from nvimtree and need to close the tree you have to press 2 times (one to focus nvimtree and the other one to close it)
And by the way i doubt you would have more that 2 vertical editors opened :)

**Comment by Cthutu** [comment]
I have an ultrawide monitor 😃

**Comment by Uzaaft** [comment]
I have an ultrawide monitor myself, and I have never had the need to use more than 2 editors.
Just shows that how we use LunarVim varies a lot.
The LunarVim project tries to provide sane defaults to neovim. IMHO I think that the current defaults are good. @ChristianChiarulli  Any thoughts? 
Also, I looked at the NvimTree code. Seems to me that they do not provide a way to jump from an editor to an explorer if the explorer is open. I imagine that it might be possible to code a solution that implements what you are describing, but I believe that it would require quite some time to implement.

**Comment by williamgoulois** [comment]
> Also, I looked at the NvimTree code. Seems to me that they do not provide a way to jump from an editor to an explorer if the explorer is open.

We could use `NvimTreeFindFile` command to focus nvimtree.

> I have an ultrawide monitor 😃

### Solution proposed

Ok i understand better now ! It may be possible to make this behavior customizable with two behaviors : `focus` or `toggle`.
- focus: If focus is on buffer we call `NvimTreeFindFile` else we call `NvimTreeClose`
- toggle: we always call `NvimTreeToggle`

what do you think of this @Cthutu ?

**Comment by Cthutu** [comment]
Yes, that seems fine for people who still like the current behaviour.  And
for people like me who prefer a more declarative approach can switch to the
other mode.

**Comment by Cthutu** [comment]
Also, in the new behaviour, if the nvimtree window isn't showing, of course NvimTreeToggle is good too.

**Comment by williamgoulois** [comment]
Ok i found what i need to implement it, will do in a few days when i have time !
Need to update my own ocnfig after breaking change of lvim before

**Comment by williamgoulois** [comment]
I implemented the behavior @Cthutu @ChristianChiarulli the PR #1074 is opened 😃
