### ISSUE TITLE
[Bug]: Error using the command installer

### ISSUE THREAD

**Issue by ivano9** [ChristianChiarulli/LunarVim#981]
### Problem description

Just run the installer command, master branch.

On Ubuntu 21.04

### LunarVim version

0.4.8

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+27-g27118c6eb

### Screenshots

![image](https://user-images.githubusercontent.com/43305758/125852776-ed4b02ad-0346-4ccf-966b-af87bf89e235.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by luxus** [comment]
I can confirm the error

**Comment by nerdthatnoonelikes** [comment]
I can confirm the error as well. 
![image](https://user-images.githubusercontent.com/33642056/125871443-a994b9e3-6d72-4f58-92cf-4cb2f4d1aa83.png)

**Comment by etrigan63** [comment]
Confirm as well.

**Comment by abzcoding** [comment]
can you guys check if it is fixed or not 🥺

**Comment by abzcoding** [comment]
tested both `master` and `rolling` locally, it should be fixed now, feel free to reopen if it happened again
