### ISSUE TITLE
[Bug]: Error while pressing tab

### ISSUE THREAD

**Issue by ivano9** [ChristianChiarulli/LunarVim#993]
### Problem description

On branch rolling
When want switch tabs files pressing Tab show that error (image attached).

### LunarVim version

0.4.8

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+27-g27118c6eb

### Screenshots

![image](https://user-images.githubusercontent.com/43305758/125971873-1cc7d68b-df55-44dd-a8ef-9dd3db45dad8.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
What filetype are you editing? 

```
:set filetype?
```

What's the output of 

```
:LspInfo
```

**Comment by abzcoding** [comment]
@ivano9 

the tab is for auto-completion, and your LSP doesn't support signature help for the thing under your cursor, hence the error


use `shift+h` and `shift-l` for tab switching

**Comment by vlcinsky** [comment]
I got confused too with Tab not switching tabs:

https://github.com/ChristianChiarulli/LunarVim/blob/ddb627d004d1f6c3bbd593a381ed93bbe54a24fd/utils/lv-vscode/init.vim#L83-L84 defines such key mapping, but it apparently does not work (something else is probably overriding the keymap)

The lines are likely to be removed as `shift+h` and `shift-l` seems to be working well.

**Comment by abzcoding** [comment]
> I got confused too with Tab not switching tabs:
> 
> https://github.com/ChristianChiarulli/LunarVim/blob/ddb627d004d1f6c3bbd593a381ed93bbe54a24fd/utils/lv-vscode/init.vim#L83-L84
> defines such key mapping, but it apparently does not work (something else is probably overriding the keymap)
> 
> The lines are likely to be removed as `shift+h` and `shift-l` seems to be working well.

This is where the replacement happens 

https://github.com/ChristianChiarulli/LunarVim/blob/ddb627d004d1f6c3bbd593a381ed93bbe54a24fd/lua/core/compe.lua#L84-L87

**Comment by ChristianChiarulli** [comment]
> I got confused too with Tab not switching tabs:
> 
> https://github.com/ChristianChiarulli/LunarVim/blob/ddb627d004d1f6c3bbd593a381ed93bbe54a24fd/utils/lv-vscode/init.vim#L83-L84
> 
> defines such key mapping, but it apparently does not work (something else is probably overriding the keymap)
> The lines are likely to be removed as `shift+h` and `shift-l` seems to be working well.

this is the vscode config, rolling is testing out using tab as signature help, (I'm also thinking of <leader><tab> as tabnew). shift+h and shift+l are way better to move between tabs, shift<tab>  is not ergonomic at all.
