### ISSUE TITLE
[Bug]: packer.nvim Error in coroutine

### ISSUE THREAD

**Issue by antlis** [ChristianChiarulli/LunarVim#994]
### Problem description

1. Run install script 
`bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/master/utils/installer/install.sh)`

### LunarVim version

LunarVim 0.4.8

### Neovim version (>= 0.5)

NVIM v0.5.0-dev

### Screenshots

![Screenshot from 2021-07-16 21-46-10](https://user-images.githubusercontent.com/4791958/125981649-34862aa9-9bb1-4b8f-8cba-32309bc86203.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by antlis** [comment]
I've found a similar, closed issue https://github.com/ChristianChiarulli/LunarVim/issues/981

But I am experiencing the problem anyway

**Comment by abzcoding** [comment]
> I've found a similar, closed issue #981
> 
> Only I am still experiencing the problem anyway

can you run `nvim -v`

**Comment by antlis** [comment]
@abzcoding 

![Screenshot from 2021-07-17 02-25-34](https://user-images.githubusercontent.com/4791958/126010064-f621cf43-85af-4f9c-a4bd-a1922c5daf52.png)

**Comment by luxus** [comment]
for me the issue is fixed since @abzcoding tried to fixed it.. 
```bash
❯ LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/lunarvim/rolling/utils/installer/install.sh) --overwrite
Installing LunarVim
!!Warning!! -> Removing all nvim related config because of the --overwrite flag
pip installed, moving on...
node installed, moving on...
pynvim installed, moving on...
Cloning into '/Users/luxus/.local/share/nvim/site/pack/packer/start/packer.nvim'...
remote: Enumerating objects: 2379, done.
remote: Counting objects: 100% (683/683), done.
remote: Compressing objects: 100% (198/198), done.
remote: Total 2379 (delta 538), reused 587 (delta 480), pack-reused 1696
Receiving objects: 100% (2379/2379), 743.43 KiB | 5.90 MiB/s, done.
Resolving deltas: 100% (1337/1337), done.
Cloning LunarVim configuration
Cloning into '/Users/luxus/.config/nvim'...
remote: Enumerating objects: 7681, done.
remote: Counting objects: 100% (1284/1284), done.
remote: Compressing objects: 100% (513/513), done.
remote: Total 7681 (delta 819), reused 1125 (delta 743), pack-reused 6397
Receiving objects: 100% (7681/7681), 10.27 MiB | 15.63 MiB/s, done.
Resolving deltas: 100% (4560/4560), done.

Compile Complete
I recommend you also install and activate a font from here: https://github.com/ryanoasis/nerd-fonts

~ took 6s
```

**Comment by antlis** [comment]
Setting `rolling` did not help.

![Screenshot from 2021-07-17 02-53-00](https://user-images.githubusercontent.com/4791958/126012714-7dc38c87-c2d2-4347-9609-3bd31293192c.png)

@luxus  Are you suggesting installing stable `nvim`?

**Comment by antlis** [comment]
I am not sure how to install stable `nvim` on ubuntu, without building it from sources. It works with `0.6.0-dev` tho, after I updated it.

So I guess the issue can be closed.

![Screenshot from 2021-07-17 03-21-44](https://user-images.githubusercontent.com/4791958/126013925-84691334-217f-44b7-b1ba-a66deea73106.png)

**Comment by luxus** [comment]
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
